module ALPHA2.PlanHolParser where

import ALPHA2.Ast
import ALPHA2.Grammar
import ALPHA2.Header
import ALPHA2.PlanHolLexer
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

-- the following codes are generated by PGS.

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()

runAladdinParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runAladdinParser = fmap (getEither getQuery (getSequence getDecl)) . runLALR1 theLALR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] = (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[16]] = RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[18]] = RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] = RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[17, 16]] = RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[17]] = (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise = RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[16]] = RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[19, 18]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[19]] = (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[19, 20]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[20]] = (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise = RTyVar (loc_1) (contents_1)
    getTypeRep2 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise = RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[18]] = RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] = RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 3]] = RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep0 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1 _1)) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] = (getTermRep1 _1)
    getTermRep1 :: ParsingTree -> (TermRep)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 5]] = RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1 _1)) (getTermRep2 _3)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] = (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 5]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep3 _1)) (getTermRep2 _3)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] = (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 7]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep3 _1)) (getTermRep4 _3)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] = (getTermRep4 _1)
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 7]] = RApp (getSLoc (getTermRep5 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getTermRep4 _3)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = (getTermRep5 _1)
    getTermRep5 :: ParsingTree -> (TermRep)
    getTermRep5 (PTBranch _ [PTLeaf (T_pi loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] = RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_pi)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [PTLeaf (T_sigma loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] = RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_sigma)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_is loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_is)) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_eq) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_le loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_le) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_lt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_lt) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_ge loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_ge) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_gt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_gt) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = (getTermRep6 _1)
    getTermRep6 :: ParsingTree -> (TermRep)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_plus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 10]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep7 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_plus) (getTermRep6 _1)) (getTermRep7 _3)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_minus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 10]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep7 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_minus) (getTermRep6 _1)) (getTermRep7 _3)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] = (getTermRep7 _1)
    getTermRep7 :: ParsingTree -> (TermRep)
    getTermRep7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_star loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep7 _1) <> getSLoc (getTermRep8 _3)) (RApp (getSLoc (getTermRep7 _1) <> (loc_2)) (RCon (loc_2) DC_mul) (getTermRep7 _1)) (getTermRep8 _3)
    getTermRep7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_slash loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep7 _1) <> getSLoc (getTermRep8 _3)) (RApp (getSLoc (getTermRep7 _1) <> (loc_2)) (RCon (loc_2) DC_div) (getTermRep7 _1)) (getTermRep8 _3)
    getTermRep7 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[11]] = (getTermRep8 _1)
    getTermRep8 :: ParsingTree -> (TermRep)
    getTermRep8 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[11, 12]] = RApp (getSLoc (getTermRep8 _1) <> getSLoc (getTermRep9 _2)) (getTermRep8 _1) (getTermRep9 _2)
    getTermRep8 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] = (getTermRep9 _1)
    getTermRep8 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_largeid loc_2 contents_2), PTLeaf (T_bslash loc_3), _4@(PTBranch guard4 _)])
        | [guard1, guard4] `elem` [[12, 3]] = RApp (getSLoc (getTermRep9 _1) <> getSLoc (getTermRep0 _4)) (getTermRep9 _1) (RAbs ((loc_2) <> getSLoc (getTermRep0 _4)) (contents_2) (getTermRep0 _4))
    getTermRep8 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise = RCon (loc_1) DC_Succ
    getTermRep9 :: ParsingTree -> (TermRep)
    getTermRep9 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] = RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep9 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_cut)
    getTermRep9 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_true)
    getTermRep9 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_fail)
    getTermRep9 (PTBranch _ [PTLeaf (T_debug loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_debug)
    getTermRep9 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise = RCon (loc_1) (DC_Named (contents_1))
    getTermRep9 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise = RVar (loc_1) (contents_1)
    getTermRep9 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise = mkNatLit (loc_1) (contents_1)
    getTermRep9 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise = mkStrLit (loc_1) (contents_1)
    getTermRep9 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise = mkChrLit (loc_1) (contents_1)
    getTermRep9 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise = RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep9 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[13]] = RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise = []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[15, 14]] = (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] = Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[14]] = Right (getRight _1)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = RApp (getSLoc (getTermRep5 _1)) (RApp (getSLoc (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Cons) (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 13]] = RApp (getSLoc (getTermRep5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getListBody _3)
    toTerminal :: (Token) -> TSym
    toTerminal (T_dot loc) = 1
    toTerminal (T_arrow loc) = 2
    toTerminal (T_lparen loc) = 3
    toTerminal (T_rparen loc) = 4
    toTerminal (T_lbracket loc) = 5
    toTerminal (T_rbracket loc) = 6
    toTerminal (T_quest loc) = 7
    toTerminal (T_if loc) = 8
    toTerminal (T_comma loc) = 9
    toTerminal (T_semicolon loc) = 10
    toTerminal (T_fatarrow loc) = 11
    toTerminal (T_pi loc) = 12
    toTerminal (T_sigma loc) = 13
    toTerminal (T_succ loc) = 14
    toTerminal (T_eq loc) = 15
    toTerminal (T_le loc) = 16
    toTerminal (T_lt loc) = 17
    toTerminal (T_ge loc) = 18
    toTerminal (T_gt loc) = 19
    toTerminal (T_plus loc) = 20
    toTerminal (T_minus loc) = 21
    toTerminal (T_star loc) = 22
    toTerminal (T_slash loc) = 23
    toTerminal (T_cut loc) = 24
    toTerminal (T_true loc) = 25
    toTerminal (T_fail loc) = 26
    toTerminal (T_is loc) = 27
    toTerminal (T_debug loc) = 28
    toTerminal (T_bslash loc) = 29
    toTerminal (T_cons loc) = 30
    toTerminal (T_kind loc) = 31
    toTerminal (T_type loc) = 32
    toTerminal (T_smallid loc contents) = 33
    toTerminal (T_largeid loc contents) = 34
    toTerminal (T_nat_lit loc contents) = 35
    toTerminal (T_chr_lit loc contents) = 36
    toTerminal (T_str_lit loc contents) = 37
    runLALR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLALR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLALR1Parser :: LR1Parser
    theLALR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (14, [])), ((0, 3), Shift 22), ((0, 5), Shift 21), ((0, 7), Shift 25), ((0, 12), Shift 24), ((0, 13), Shift 26), ((0, 14), Shift 29), ((0, 24), Shift 16), ((0, 25), Shift 30), ((0, 26), Shift 18), ((0, 28), Shift 17), ((0, 31), Shift 19), ((0, 32), Shift 31), ((0, 33), Shift 27), ((0, 34), Shift 20), ((0, 35), Shift 23), ((0, 36), Shift 15), ((0, 37), Shift 28)
            , ((1, 0), Reduce (14, [])), ((1, 3), Shift 22), ((1, 5), Shift 21), ((1, 12), Shift 24), ((1, 13), Shift 26), ((1, 14), Shift 29), ((1, 24), Shift 16), ((1, 25), Shift 30), ((1, 26), Shift 18), ((1, 28), Shift 17), ((1, 31), Shift 19), ((1, 32), Shift 31), ((1, 33), Shift 27), ((1, 34), Shift 20), ((1, 35), Shift 23), ((1, 36), Shift 15), ((1, 37), Shift 28)
            , ((2, 0), Reduce (1, [NS 2]))
            , ((3, 1), Shift 33)
            , ((4, 1), Reduce (3, [NS 4])), ((4, 3), Reduce (3, [NS 4])), ((4, 4), Reduce (3, [NS 4])), ((4, 5), Reduce (3, [NS 4])), ((4, 6), Reduce (3, [NS 4])), ((4, 8), Reduce (3, [NS 4])), ((4, 9), Reduce (3, [NS 4])), ((4, 10), Reduce (3, [NS 4])), ((4, 11), Reduce (3, [NS 4])), ((4, 15), Reduce (3, [NS 4])), ((4, 16), Reduce (3, [NS 4])), ((4, 17), Reduce (3, [NS 4])), ((4, 18), Reduce (3, [NS 4])), ((4, 19), Reduce (3, [NS 4])), ((4, 20), Reduce (3, [NS 4])), ((4, 21), Reduce (3, [NS 4])), ((4, 22), Reduce (3, [NS 4])), ((4, 23), Reduce (3, [NS 4])), ((4, 24), Reduce (3, [NS 4])), ((4, 25), Reduce (3, [NS 4])), ((4, 26), Reduce (3, [NS 4])), ((4, 27), Reduce (3, [NS 4])), ((4, 28), Reduce (3, [NS 4])), ((4, 30), Reduce (3, [NS 4])), ((4, 33), Reduce (3, [NS 4])), ((4, 34), Reduce (3, [NS 4])), ((4, 35), Reduce (3, [NS 4])), ((4, 36), Reduce (3, [NS 4])), ((4, 37), Reduce (3, [NS 4]))
            , ((5, 1), Reduce (4, [NS 5])), ((5, 4), Reduce (4, [NS 5])), ((5, 8), Reduce (4, [NS 5])), ((5, 10), Reduce (4, [NS 5]))
            , ((6, 1), Reduce (5, [NS 6])), ((6, 4), Reduce (5, [NS 6])), ((6, 8), Reduce (5, [NS 6])), ((6, 9), Shift 45), ((6, 10), Reduce (5, [NS 6])), ((6, 11), Shift 46)
            , ((7, 1), Reduce (6, [NS 7])), ((7, 4), Reduce (6, [NS 7])), ((7, 8), Reduce (6, [NS 7])), ((7, 9), Reduce (6, [NS 7])), ((7, 10), Reduce (6, [NS 7])), ((7, 11), Reduce (6, [NS 7]))
            , ((8, 1), Reduce (7, [NS 8])), ((8, 4), Reduce (7, [NS 8])), ((8, 8), Reduce (7, [NS 8])), ((8, 9), Reduce (7, [NS 8])), ((8, 10), Reduce (7, [NS 8])), ((8, 11), Reduce (7, [NS 8])), ((8, 30), Shift 47)
            , ((9, 1), Reduce (8, [NS 9])), ((9, 4), Reduce (8, [NS 9])), ((9, 6), Reduce (8, [NS 9])), ((9, 8), Reduce (8, [NS 9])), ((9, 9), Reduce (8, [NS 9])), ((9, 10), Reduce (8, [NS 9])), ((9, 11), Reduce (8, [NS 9])), ((9, 15), Shift 50), ((9, 16), Shift 54), ((9, 17), Shift 55), ((9, 18), Shift 51), ((9, 19), Shift 52), ((9, 20), Shift 57), ((9, 21), Shift 56), ((9, 27), Shift 53), ((9, 30), Reduce (8, [NS 9]))
            , ((10, 1), Reduce (9, [NS 10])), ((10, 4), Reduce (9, [NS 10])), ((10, 6), Reduce (9, [NS 10])), ((10, 8), Reduce (9, [NS 10])), ((10, 9), Reduce (9, [NS 10])), ((10, 10), Reduce (9, [NS 10])), ((10, 11), Reduce (9, [NS 10])), ((10, 15), Reduce (9, [NS 10])), ((10, 16), Reduce (9, [NS 10])), ((10, 17), Reduce (9, [NS 10])), ((10, 18), Reduce (9, [NS 10])), ((10, 19), Reduce (9, [NS 10])), ((10, 20), Reduce (9, [NS 10])), ((10, 21), Reduce (9, [NS 10])), ((10, 22), Shift 59), ((10, 23), Shift 58), ((10, 27), Reduce (9, [NS 10])), ((10, 30), Reduce (9, [NS 10]))
            , ((11, 1), Reduce (10, [NS 11])), ((11, 3), Shift 22), ((11, 4), Reduce (10, [NS 11])), ((11, 5), Shift 21), ((11, 6), Reduce (10, [NS 11])), ((11, 8), Reduce (10, [NS 11])), ((11, 9), Reduce (10, [NS 11])), ((11, 10), Reduce (10, [NS 11])), ((11, 11), Reduce (10, [NS 11])), ((11, 15), Reduce (10, [NS 11])), ((11, 16), Reduce (10, [NS 11])), ((11, 17), Reduce (10, [NS 11])), ((11, 18), Reduce (10, [NS 11])), ((11, 19), Reduce (10, [NS 11])), ((11, 20), Reduce (10, [NS 11])), ((11, 21), Reduce (10, [NS 11])), ((11, 22), Reduce (10, [NS 11])), ((11, 23), Reduce (10, [NS 11])), ((11, 24), Shift 16), ((11, 25), Shift 30), ((11, 26), Shift 18), ((11, 27), Reduce (10, [NS 11])), ((11, 28), Shift 17), ((11, 30), Reduce (10, [NS 11])), ((11, 33), Shift 27), ((11, 34), Shift 38), ((11, 35), Shift 23), ((11, 36), Shift 15), ((11, 37), Shift 28)
            , ((12, 1), Reduce (11, [NS 12])), ((12, 3), Reduce (11, [NS 12])), ((12, 4), Reduce (11, [NS 12])), ((12, 5), Reduce (11, [NS 12])), ((12, 6), Reduce (11, [NS 12])), ((12, 8), Reduce (11, [NS 12])), ((12, 9), Reduce (11, [NS 12])), ((12, 10), Reduce (11, [NS 12])), ((12, 11), Reduce (11, [NS 12])), ((12, 15), Reduce (11, [NS 12])), ((12, 16), Reduce (11, [NS 12])), ((12, 17), Reduce (11, [NS 12])), ((12, 18), Reduce (11, [NS 12])), ((12, 19), Reduce (11, [NS 12])), ((12, 20), Reduce (11, [NS 12])), ((12, 21), Reduce (11, [NS 12])), ((12, 22), Reduce (11, [NS 12])), ((12, 23), Reduce (11, [NS 12])), ((12, 24), Reduce (11, [NS 12])), ((12, 25), Reduce (11, [NS 12])), ((12, 26), Reduce (11, [NS 12])), ((12, 27), Reduce (11, [NS 12])), ((12, 28), Reduce (11, [NS 12])), ((12, 30), Reduce (11, [NS 12])), ((12, 33), Reduce (11, [NS 12])), ((12, 34), Reduce (11, [NS 12])), ((12, 35), Reduce (11, [NS 12])), ((12, 36), Reduce (11, [NS 12])), ((12, 37), Reduce (11, [NS 12]))
            , ((13, 0), Reduce (1, [NS 14]))
            , ((14, 0), Accept)
            , ((15, 1), Reduce (12, [TS 36])), ((15, 3), Reduce (12, [TS 36])), ((15, 4), Reduce (12, [TS 36])), ((15, 5), Reduce (12, [TS 36])), ((15, 6), Reduce (12, [TS 36])), ((15, 8), Reduce (12, [TS 36])), ((15, 9), Reduce (12, [TS 36])), ((15, 10), Reduce (12, [TS 36])), ((15, 11), Reduce (12, [TS 36])), ((15, 15), Reduce (12, [TS 36])), ((15, 16), Reduce (12, [TS 36])), ((15, 17), Reduce (12, [TS 36])), ((15, 18), Reduce (12, [TS 36])), ((15, 19), Reduce (12, [TS 36])), ((15, 20), Reduce (12, [TS 36])), ((15, 21), Reduce (12, [TS 36])), ((15, 22), Reduce (12, [TS 36])), ((15, 23), Reduce (12, [TS 36])), ((15, 24), Reduce (12, [TS 36])), ((15, 25), Reduce (12, [TS 36])), ((15, 26), Reduce (12, [TS 36])), ((15, 27), Reduce (12, [TS 36])), ((15, 28), Reduce (12, [TS 36])), ((15, 30), Reduce (12, [TS 36])), ((15, 33), Reduce (12, [TS 36])), ((15, 34), Reduce (12, [TS 36])), ((15, 35), Reduce (12, [TS 36])), ((15, 36), Reduce (12, [TS 36])), ((15, 37), Reduce (12, [TS 36]))
            , ((16, 1), Reduce (12, [TS 24])), ((16, 3), Reduce (12, [TS 24])), ((16, 4), Reduce (12, [TS 24])), ((16, 5), Reduce (12, [TS 24])), ((16, 6), Reduce (12, [TS 24])), ((16, 8), Reduce (12, [TS 24])), ((16, 9), Reduce (12, [TS 24])), ((16, 10), Reduce (12, [TS 24])), ((16, 11), Reduce (12, [TS 24])), ((16, 15), Reduce (12, [TS 24])), ((16, 16), Reduce (12, [TS 24])), ((16, 17), Reduce (12, [TS 24])), ((16, 18), Reduce (12, [TS 24])), ((16, 19), Reduce (12, [TS 24])), ((16, 20), Reduce (12, [TS 24])), ((16, 21), Reduce (12, [TS 24])), ((16, 22), Reduce (12, [TS 24])), ((16, 23), Reduce (12, [TS 24])), ((16, 24), Reduce (12, [TS 24])), ((16, 25), Reduce (12, [TS 24])), ((16, 26), Reduce (12, [TS 24])), ((16, 27), Reduce (12, [TS 24])), ((16, 28), Reduce (12, [TS 24])), ((16, 30), Reduce (12, [TS 24])), ((16, 33), Reduce (12, [TS 24])), ((16, 34), Reduce (12, [TS 24])), ((16, 35), Reduce (12, [TS 24])), ((16, 36), Reduce (12, [TS 24])), ((16, 37), Reduce (12, [TS 24]))
            , ((17, 1), Reduce (12, [TS 28])), ((17, 3), Reduce (12, [TS 28])), ((17, 4), Reduce (12, [TS 28])), ((17, 5), Reduce (12, [TS 28])), ((17, 6), Reduce (12, [TS 28])), ((17, 8), Reduce (12, [TS 28])), ((17, 9), Reduce (12, [TS 28])), ((17, 10), Reduce (12, [TS 28])), ((17, 11), Reduce (12, [TS 28])), ((17, 15), Reduce (12, [TS 28])), ((17, 16), Reduce (12, [TS 28])), ((17, 17), Reduce (12, [TS 28])), ((17, 18), Reduce (12, [TS 28])), ((17, 19), Reduce (12, [TS 28])), ((17, 20), Reduce (12, [TS 28])), ((17, 21), Reduce (12, [TS 28])), ((17, 22), Reduce (12, [TS 28])), ((17, 23), Reduce (12, [TS 28])), ((17, 24), Reduce (12, [TS 28])), ((17, 25), Reduce (12, [TS 28])), ((17, 26), Reduce (12, [TS 28])), ((17, 27), Reduce (12, [TS 28])), ((17, 28), Reduce (12, [TS 28])), ((17, 30), Reduce (12, [TS 28])), ((17, 33), Reduce (12, [TS 28])), ((17, 34), Reduce (12, [TS 28])), ((17, 35), Reduce (12, [TS 28])), ((17, 36), Reduce (12, [TS 28])), ((17, 37), Reduce (12, [TS 28]))
            , ((18, 1), Reduce (12, [TS 26])), ((18, 3), Reduce (12, [TS 26])), ((18, 4), Reduce (12, [TS 26])), ((18, 5), Reduce (12, [TS 26])), ((18, 6), Reduce (12, [TS 26])), ((18, 8), Reduce (12, [TS 26])), ((18, 9), Reduce (12, [TS 26])), ((18, 10), Reduce (12, [TS 26])), ((18, 11), Reduce (12, [TS 26])), ((18, 15), Reduce (12, [TS 26])), ((18, 16), Reduce (12, [TS 26])), ((18, 17), Reduce (12, [TS 26])), ((18, 18), Reduce (12, [TS 26])), ((18, 19), Reduce (12, [TS 26])), ((18, 20), Reduce (12, [TS 26])), ((18, 21), Reduce (12, [TS 26])), ((18, 22), Reduce (12, [TS 26])), ((18, 23), Reduce (12, [TS 26])), ((18, 24), Reduce (12, [TS 26])), ((18, 25), Reduce (12, [TS 26])), ((18, 26), Reduce (12, [TS 26])), ((18, 27), Reduce (12, [TS 26])), ((18, 28), Reduce (12, [TS 26])), ((18, 30), Reduce (12, [TS 26])), ((18, 33), Reduce (12, [TS 26])), ((18, 34), Reduce (12, [TS 26])), ((18, 35), Reduce (12, [TS 26])), ((18, 36), Reduce (12, [TS 26])), ((18, 37), Reduce (12, [TS 26]))
            , ((19, 33), Shift 34)
            , ((20, 1), Reduce (12, [TS 34])), ((20, 3), Reduce (12, [TS 34])), ((20, 4), Reduce (12, [TS 34])), ((20, 5), Reduce (12, [TS 34])), ((20, 8), Reduce (12, [TS 34])), ((20, 9), Reduce (12, [TS 34])), ((20, 10), Reduce (12, [TS 34])), ((20, 11), Reduce (12, [TS 34])), ((20, 15), Reduce (12, [TS 34])), ((20, 16), Reduce (12, [TS 34])), ((20, 17), Reduce (12, [TS 34])), ((20, 18), Reduce (12, [TS 34])), ((20, 19), Reduce (12, [TS 34])), ((20, 20), Reduce (12, [TS 34])), ((20, 21), Reduce (12, [TS 34])), ((20, 22), Reduce (12, [TS 34])), ((20, 23), Reduce (12, [TS 34])), ((20, 24), Reduce (12, [TS 34])), ((20, 25), Reduce (12, [TS 34])), ((20, 26), Reduce (12, [TS 34])), ((20, 27), Reduce (12, [TS 34])), ((20, 28), Reduce (12, [TS 34])), ((20, 29), Shift 44), ((20, 30), Reduce (12, [TS 34])), ((20, 33), Reduce (12, [TS 34])), ((20, 34), Reduce (12, [TS 34])), ((20, 35), Reduce (12, [TS 34])), ((20, 36), Reduce (12, [TS 34])), ((20, 37), Reduce (12, [TS 34]))
            , ((21, 3), Shift 22), ((21, 5), Shift 21), ((21, 6), Shift 39), ((21, 12), Shift 24), ((21, 13), Shift 26), ((21, 14), Shift 29), ((21, 24), Shift 16), ((21, 25), Shift 30), ((21, 26), Shift 18), ((21, 28), Shift 17), ((21, 33), Shift 27), ((21, 34), Shift 38), ((21, 35), Shift 23), ((21, 36), Shift 15), ((21, 37), Shift 28)
            , ((22, 3), Shift 22), ((22, 5), Shift 21), ((22, 12), Shift 24), ((22, 13), Shift 26), ((22, 14), Shift 29), ((22, 24), Shift 16), ((22, 25), Shift 30), ((22, 26), Shift 18), ((22, 28), Shift 17), ((22, 33), Shift 27), ((22, 34), Shift 20), ((22, 35), Shift 23), ((22, 36), Shift 15), ((22, 37), Shift 28)
            , ((23, 1), Reduce (12, [TS 35])), ((23, 3), Reduce (12, [TS 35])), ((23, 4), Reduce (12, [TS 35])), ((23, 5), Reduce (12, [TS 35])), ((23, 6), Reduce (12, [TS 35])), ((23, 8), Reduce (12, [TS 35])), ((23, 9), Reduce (12, [TS 35])), ((23, 10), Reduce (12, [TS 35])), ((23, 11), Reduce (12, [TS 35])), ((23, 15), Reduce (12, [TS 35])), ((23, 16), Reduce (12, [TS 35])), ((23, 17), Reduce (12, [TS 35])), ((23, 18), Reduce (12, [TS 35])), ((23, 19), Reduce (12, [TS 35])), ((23, 20), Reduce (12, [TS 35])), ((23, 21), Reduce (12, [TS 35])), ((23, 22), Reduce (12, [TS 35])), ((23, 23), Reduce (12, [TS 35])), ((23, 24), Reduce (12, [TS 35])), ((23, 25), Reduce (12, [TS 35])), ((23, 26), Reduce (12, [TS 35])), ((23, 27), Reduce (12, [TS 35])), ((23, 28), Reduce (12, [TS 35])), ((23, 30), Reduce (12, [TS 35])), ((23, 33), Reduce (12, [TS 35])), ((23, 34), Reduce (12, [TS 35])), ((23, 35), Reduce (12, [TS 35])), ((23, 36), Reduce (12, [TS 35])), ((23, 37), Reduce (12, [TS 35]))
            , ((24, 3), Shift 22), ((24, 5), Shift 21), ((24, 12), Shift 24), ((24, 13), Shift 26), ((24, 14), Shift 29), ((24, 24), Shift 16), ((24, 25), Shift 30), ((24, 26), Shift 18), ((24, 28), Shift 17), ((24, 33), Shift 27), ((24, 34), Shift 38), ((24, 35), Shift 23), ((24, 36), Shift 15), ((24, 37), Shift 28)
            , ((25, 3), Shift 22), ((25, 5), Shift 21), ((25, 12), Shift 24), ((25, 13), Shift 26), ((25, 14), Shift 29), ((25, 24), Shift 16), ((25, 25), Shift 30), ((25, 26), Shift 18), ((25, 28), Shift 17), ((25, 33), Shift 27), ((25, 34), Shift 20), ((25, 35), Shift 23), ((25, 36), Shift 15), ((25, 37), Shift 28)
            , ((26, 3), Shift 22), ((26, 5), Shift 21), ((26, 12), Shift 24), ((26, 13), Shift 26), ((26, 14), Shift 29), ((26, 24), Shift 16), ((26, 25), Shift 30), ((26, 26), Shift 18), ((26, 28), Shift 17), ((26, 33), Shift 27), ((26, 34), Shift 38), ((26, 35), Shift 23), ((26, 36), Shift 15), ((26, 37), Shift 28)
            , ((27, 1), Reduce (12, [TS 33])), ((27, 3), Reduce (12, [TS 33])), ((27, 4), Reduce (12, [TS 33])), ((27, 5), Reduce (12, [TS 33])), ((27, 6), Reduce (12, [TS 33])), ((27, 8), Reduce (12, [TS 33])), ((27, 9), Reduce (12, [TS 33])), ((27, 10), Reduce (12, [TS 33])), ((27, 11), Reduce (12, [TS 33])), ((27, 15), Reduce (12, [TS 33])), ((27, 16), Reduce (12, [TS 33])), ((27, 17), Reduce (12, [TS 33])), ((27, 18), Reduce (12, [TS 33])), ((27, 19), Reduce (12, [TS 33])), ((27, 20), Reduce (12, [TS 33])), ((27, 21), Reduce (12, [TS 33])), ((27, 22), Reduce (12, [TS 33])), ((27, 23), Reduce (12, [TS 33])), ((27, 24), Reduce (12, [TS 33])), ((27, 25), Reduce (12, [TS 33])), ((27, 26), Reduce (12, [TS 33])), ((27, 27), Reduce (12, [TS 33])), ((27, 28), Reduce (12, [TS 33])), ((27, 30), Reduce (12, [TS 33])), ((27, 33), Reduce (12, [TS 33])), ((27, 34), Reduce (12, [TS 33])), ((27, 35), Reduce (12, [TS 33])), ((27, 36), Reduce (12, [TS 33])), ((27, 37), Reduce (12, [TS 33]))
            , ((28, 1), Reduce (12, [TS 37])), ((28, 3), Reduce (12, [TS 37])), ((28, 4), Reduce (12, [TS 37])), ((28, 5), Reduce (12, [TS 37])), ((28, 6), Reduce (12, [TS 37])), ((28, 8), Reduce (12, [TS 37])), ((28, 9), Reduce (12, [TS 37])), ((28, 10), Reduce (12, [TS 37])), ((28, 11), Reduce (12, [TS 37])), ((28, 15), Reduce (12, [TS 37])), ((28, 16), Reduce (12, [TS 37])), ((28, 17), Reduce (12, [TS 37])), ((28, 18), Reduce (12, [TS 37])), ((28, 19), Reduce (12, [TS 37])), ((28, 20), Reduce (12, [TS 37])), ((28, 21), Reduce (12, [TS 37])), ((28, 22), Reduce (12, [TS 37])), ((28, 23), Reduce (12, [TS 37])), ((28, 24), Reduce (12, [TS 37])), ((28, 25), Reduce (12, [TS 37])), ((28, 26), Reduce (12, [TS 37])), ((28, 27), Reduce (12, [TS 37])), ((28, 28), Reduce (12, [TS 37])), ((28, 30), Reduce (12, [TS 37])), ((28, 33), Reduce (12, [TS 37])), ((28, 34), Reduce (12, [TS 37])), ((28, 35), Reduce (12, [TS 37])), ((28, 36), Reduce (12, [TS 37])), ((28, 37), Reduce (12, [TS 37]))
            , ((29, 1), Reduce (11, [TS 14])), ((29, 3), Reduce (11, [TS 14])), ((29, 4), Reduce (11, [TS 14])), ((29, 5), Reduce (11, [TS 14])), ((29, 6), Reduce (11, [TS 14])), ((29, 8), Reduce (11, [TS 14])), ((29, 9), Reduce (11, [TS 14])), ((29, 10), Reduce (11, [TS 14])), ((29, 11), Reduce (11, [TS 14])), ((29, 15), Reduce (11, [TS 14])), ((29, 16), Reduce (11, [TS 14])), ((29, 17), Reduce (11, [TS 14])), ((29, 18), Reduce (11, [TS 14])), ((29, 19), Reduce (11, [TS 14])), ((29, 20), Reduce (11, [TS 14])), ((29, 21), Reduce (11, [TS 14])), ((29, 22), Reduce (11, [TS 14])), ((29, 23), Reduce (11, [TS 14])), ((29, 24), Reduce (11, [TS 14])), ((29, 25), Reduce (11, [TS 14])), ((29, 26), Reduce (11, [TS 14])), ((29, 27), Reduce (11, [TS 14])), ((29, 28), Reduce (11, [TS 14])), ((29, 30), Reduce (11, [TS 14])), ((29, 33), Reduce (11, [TS 14])), ((29, 34), Reduce (11, [TS 14])), ((29, 35), Reduce (11, [TS 14])), ((29, 36), Reduce (11, [TS 14])), ((29, 37), Reduce (11, [TS 14]))
            , ((30, 1), Reduce (12, [TS 25])), ((30, 3), Reduce (12, [TS 25])), ((30, 4), Reduce (12, [TS 25])), ((30, 5), Reduce (12, [TS 25])), ((30, 6), Reduce (12, [TS 25])), ((30, 8), Reduce (12, [TS 25])), ((30, 9), Reduce (12, [TS 25])), ((30, 10), Reduce (12, [TS 25])), ((30, 11), Reduce (12, [TS 25])), ((30, 15), Reduce (12, [TS 25])), ((30, 16), Reduce (12, [TS 25])), ((30, 17), Reduce (12, [TS 25])), ((30, 18), Reduce (12, [TS 25])), ((30, 19), Reduce (12, [TS 25])), ((30, 20), Reduce (12, [TS 25])), ((30, 21), Reduce (12, [TS 25])), ((30, 22), Reduce (12, [TS 25])), ((30, 23), Reduce (12, [TS 25])), ((30, 24), Reduce (12, [TS 25])), ((30, 25), Reduce (12, [TS 25])), ((30, 26), Reduce (12, [TS 25])), ((30, 27), Reduce (12, [TS 25])), ((30, 28), Reduce (12, [TS 25])), ((30, 30), Reduce (12, [TS 25])), ((30, 33), Reduce (12, [TS 25])), ((30, 34), Reduce (12, [TS 25])), ((30, 35), Reduce (12, [TS 25])), ((30, 36), Reduce (12, [TS 25])), ((30, 37), Reduce (12, [TS 25]))
            , ((31, 33), Shift 35)
            , ((32, 0), Reduce (14, [NS 15, NS 14]))
            , ((33, 0), Reduce (15, [NS 3, TS 1])), ((33, 3), Reduce (15, [NS 3, TS 1])), ((33, 5), Reduce (15, [NS 3, TS 1])), ((33, 12), Reduce (15, [NS 3, TS 1])), ((33, 13), Reduce (15, [NS 3, TS 1])), ((33, 14), Reduce (15, [NS 3, TS 1])), ((33, 24), Reduce (15, [NS 3, TS 1])), ((33, 25), Reduce (15, [NS 3, TS 1])), ((33, 26), Reduce (15, [NS 3, TS 1])), ((33, 28), Reduce (15, [NS 3, TS 1])), ((33, 31), Reduce (15, [NS 3, TS 1])), ((33, 32), Reduce (15, [NS 3, TS 1])), ((33, 33), Reduce (15, [NS 3, TS 1])), ((33, 34), Reduce (15, [NS 3, TS 1])), ((33, 35), Reduce (15, [NS 3, TS 1])), ((33, 36), Reduce (15, [NS 3, TS 1])), ((33, 37), Reduce (15, [NS 3, TS 1]))
            , ((34, 3), Shift 64), ((34, 32), Shift 65)
            , ((35, 3), Shift 70), ((35, 33), Shift 71), ((35, 34), Shift 69)
            , ((36, 6), Shift 91)
            , ((37, 6), Reduce (13, [NS 8])), ((37, 9), Shift 72)
            , ((38, 1), Reduce (12, [TS 34])), ((38, 3), Reduce (12, [TS 34])), ((38, 4), Reduce (12, [TS 34])), ((38, 5), Reduce (12, [TS 34])), ((38, 6), Reduce (12, [TS 34])), ((38, 8), Reduce (12, [TS 34])), ((38, 9), Reduce (12, [TS 34])), ((38, 10), Reduce (12, [TS 34])), ((38, 11), Reduce (12, [TS 34])), ((38, 15), Reduce (12, [TS 34])), ((38, 16), Reduce (12, [TS 34])), ((38, 17), Reduce (12, [TS 34])), ((38, 18), Reduce (12, [TS 34])), ((38, 19), Reduce (12, [TS 34])), ((38, 20), Reduce (12, [TS 34])), ((38, 21), Reduce (12, [TS 34])), ((38, 22), Reduce (12, [TS 34])), ((38, 23), Reduce (12, [TS 34])), ((38, 24), Reduce (12, [TS 34])), ((38, 25), Reduce (12, [TS 34])), ((38, 26), Reduce (12, [TS 34])), ((38, 27), Reduce (12, [TS 34])), ((38, 28), Reduce (12, [TS 34])), ((38, 30), Reduce (12, [TS 34])), ((38, 33), Reduce (12, [TS 34])), ((38, 34), Reduce (12, [TS 34])), ((38, 35), Reduce (12, [TS 34])), ((38, 36), Reduce (12, [TS 34])), ((38, 37), Reduce (12, [TS 34]))
            , ((39, 1), Reduce (12, [TS 5, TS 6])), ((39, 3), Reduce (12, [TS 5, TS 6])), ((39, 4), Reduce (12, [TS 5, TS 6])), ((39, 5), Reduce (12, [TS 5, TS 6])), ((39, 6), Reduce (12, [TS 5, TS 6])), ((39, 8), Reduce (12, [TS 5, TS 6])), ((39, 9), Reduce (12, [TS 5, TS 6])), ((39, 10), Reduce (12, [TS 5, TS 6])), ((39, 11), Reduce (12, [TS 5, TS 6])), ((39, 15), Reduce (12, [TS 5, TS 6])), ((39, 16), Reduce (12, [TS 5, TS 6])), ((39, 17), Reduce (12, [TS 5, TS 6])), ((39, 18), Reduce (12, [TS 5, TS 6])), ((39, 19), Reduce (12, [TS 5, TS 6])), ((39, 20), Reduce (12, [TS 5, TS 6])), ((39, 21), Reduce (12, [TS 5, TS 6])), ((39, 22), Reduce (12, [TS 5, TS 6])), ((39, 23), Reduce (12, [TS 5, TS 6])), ((39, 24), Reduce (12, [TS 5, TS 6])), ((39, 25), Reduce (12, [TS 5, TS 6])), ((39, 26), Reduce (12, [TS 5, TS 6])), ((39, 27), Reduce (12, [TS 5, TS 6])), ((39, 28), Reduce (12, [TS 5, TS 6])), ((39, 30), Reduce (12, [TS 5, TS 6])), ((39, 33), Reduce (12, [TS 5, TS 6])), ((39, 34), Reduce (12, [TS 5, TS 6])), ((39, 35), Reduce (12, [TS 5, TS 6])), ((39, 36), Reduce (12, [TS 5, TS 6])), ((39, 37), Reduce (12, [TS 5, TS 6]))
            , ((40, 1), Shift 73)
            , ((41, 4), Shift 92)
            , ((42, 3), Shift 22), ((42, 5), Shift 21), ((42, 12), Shift 24), ((42, 13), Shift 26), ((42, 14), Shift 29), ((42, 24), Shift 16), ((42, 25), Shift 30), ((42, 26), Shift 18), ((42, 28), Shift 17), ((42, 33), Shift 27), ((42, 34), Shift 20), ((42, 35), Shift 23), ((42, 36), Shift 15), ((42, 37), Shift 28)
            , ((43, 3), Shift 22), ((43, 5), Shift 21), ((43, 12), Shift 24), ((43, 13), Shift 26), ((43, 14), Shift 29), ((43, 24), Shift 16), ((43, 25), Shift 30), ((43, 26), Shift 18), ((43, 28), Shift 17), ((43, 33), Shift 27), ((43, 34), Shift 38), ((43, 35), Shift 23), ((43, 36), Shift 15), ((43, 37), Shift 28)
            , ((44, 3), Shift 22), ((44, 5), Shift 21), ((44, 12), Shift 24), ((44, 13), Shift 26), ((44, 14), Shift 29), ((44, 24), Shift 16), ((44, 25), Shift 30), ((44, 26), Shift 18), ((44, 28), Shift 17), ((44, 33), Shift 27), ((44, 34), Shift 20), ((44, 35), Shift 23), ((44, 36), Shift 15), ((44, 37), Shift 28)
            , ((45, 3), Shift 22), ((45, 5), Shift 21), ((45, 12), Shift 24), ((45, 13), Shift 26), ((45, 14), Shift 29), ((45, 24), Shift 16), ((45, 25), Shift 30), ((45, 26), Shift 18), ((45, 28), Shift 17), ((45, 33), Shift 27), ((45, 34), Shift 38), ((45, 35), Shift 23), ((45, 36), Shift 15), ((45, 37), Shift 28)
            , ((46, 3), Shift 22), ((46, 5), Shift 21), ((46, 12), Shift 24), ((46, 13), Shift 26), ((46, 14), Shift 29), ((46, 24), Shift 16), ((46, 25), Shift 30), ((46, 26), Shift 18), ((46, 28), Shift 17), ((46, 33), Shift 27), ((46, 34), Shift 38), ((46, 35), Shift 23), ((46, 36), Shift 15), ((46, 37), Shift 28)
            , ((47, 3), Shift 22), ((47, 5), Shift 21), ((47, 12), Shift 24), ((47, 13), Shift 26), ((47, 14), Shift 29), ((47, 24), Shift 16), ((47, 25), Shift 30), ((47, 26), Shift 18), ((47, 28), Shift 17), ((47, 33), Shift 27), ((47, 34), Shift 38), ((47, 35), Shift 23), ((47, 36), Shift 15), ((47, 37), Shift 28)
            , ((48, 1), Reduce (8, [TS 12, NS 8])), ((48, 4), Reduce (8, [TS 12, NS 8])), ((48, 6), Reduce (8, [TS 12, NS 8])), ((48, 8), Reduce (8, [TS 12, NS 8])), ((48, 9), Reduce (8, [TS 12, NS 8])), ((48, 10), Reduce (8, [TS 12, NS 8])), ((48, 11), Reduce (8, [TS 12, NS 8])), ((48, 30), Reduce (8, [TS 12, NS 8]))
            , ((49, 1), Reduce (8, [TS 13, NS 8])), ((49, 4), Reduce (8, [TS 13, NS 8])), ((49, 6), Reduce (8, [TS 13, NS 8])), ((49, 8), Reduce (8, [TS 13, NS 8])), ((49, 9), Reduce (8, [TS 13, NS 8])), ((49, 10), Reduce (8, [TS 13, NS 8])), ((49, 11), Reduce (8, [TS 13, NS 8])), ((49, 30), Reduce (8, [TS 13, NS 8]))
            , ((50, 3), Shift 22), ((50, 5), Shift 21), ((50, 14), Shift 29), ((50, 24), Shift 16), ((50, 25), Shift 30), ((50, 26), Shift 18), ((50, 28), Shift 17), ((50, 33), Shift 27), ((50, 34), Shift 38), ((50, 35), Shift 23), ((50, 36), Shift 15), ((50, 37), Shift 28)
            , ((51, 3), Shift 22), ((51, 5), Shift 21), ((51, 14), Shift 29), ((51, 24), Shift 16), ((51, 25), Shift 30), ((51, 26), Shift 18), ((51, 28), Shift 17), ((51, 33), Shift 27), ((51, 34), Shift 38), ((51, 35), Shift 23), ((51, 36), Shift 15), ((51, 37), Shift 28)
            , ((52, 3), Shift 22), ((52, 5), Shift 21), ((52, 14), Shift 29), ((52, 24), Shift 16), ((52, 25), Shift 30), ((52, 26), Shift 18), ((52, 28), Shift 17), ((52, 33), Shift 27), ((52, 34), Shift 38), ((52, 35), Shift 23), ((52, 36), Shift 15), ((52, 37), Shift 28)
            , ((53, 3), Shift 22), ((53, 5), Shift 21), ((53, 14), Shift 29), ((53, 24), Shift 16), ((53, 25), Shift 30), ((53, 26), Shift 18), ((53, 28), Shift 17), ((53, 33), Shift 27), ((53, 34), Shift 38), ((53, 35), Shift 23), ((53, 36), Shift 15), ((53, 37), Shift 28)
            , ((54, 3), Shift 22), ((54, 5), Shift 21), ((54, 14), Shift 29), ((54, 24), Shift 16), ((54, 25), Shift 30), ((54, 26), Shift 18), ((54, 28), Shift 17), ((54, 33), Shift 27), ((54, 34), Shift 38), ((54, 35), Shift 23), ((54, 36), Shift 15), ((54, 37), Shift 28)
            , ((55, 3), Shift 22), ((55, 5), Shift 21), ((55, 14), Shift 29), ((55, 24), Shift 16), ((55, 25), Shift 30), ((55, 26), Shift 18), ((55, 28), Shift 17), ((55, 33), Shift 27), ((55, 34), Shift 38), ((55, 35), Shift 23), ((55, 36), Shift 15), ((55, 37), Shift 28)
            , ((56, 3), Shift 22), ((56, 5), Shift 21), ((56, 14), Shift 29), ((56, 24), Shift 16), ((56, 25), Shift 30), ((56, 26), Shift 18), ((56, 28), Shift 17), ((56, 33), Shift 27), ((56, 34), Shift 38), ((56, 35), Shift 23), ((56, 36), Shift 15), ((56, 37), Shift 28)
            , ((57, 3), Shift 22), ((57, 5), Shift 21), ((57, 14), Shift 29), ((57, 24), Shift 16), ((57, 25), Shift 30), ((57, 26), Shift 18), ((57, 28), Shift 17), ((57, 33), Shift 27), ((57, 34), Shift 38), ((57, 35), Shift 23), ((57, 36), Shift 15), ((57, 37), Shift 28)
            , ((58, 3), Shift 22), ((58, 5), Shift 21), ((58, 14), Shift 29), ((58, 24), Shift 16), ((58, 25), Shift 30), ((58, 26), Shift 18), ((58, 28), Shift 17), ((58, 33), Shift 27), ((58, 34), Shift 38), ((58, 35), Shift 23), ((58, 36), Shift 15), ((58, 37), Shift 28)
            , ((59, 3), Shift 22), ((59, 5), Shift 21), ((59, 14), Shift 29), ((59, 24), Shift 16), ((59, 25), Shift 30), ((59, 26), Shift 18), ((59, 28), Shift 17), ((59, 33), Shift 27), ((59, 34), Shift 38), ((59, 35), Shift 23), ((59, 36), Shift 15), ((59, 37), Shift 28)
            , ((60, 1), Reduce (11, [NS 11, NS 12])), ((60, 3), Reduce (11, [NS 11, NS 12])), ((60, 4), Reduce (11, [NS 11, NS 12])), ((60, 5), Reduce (11, [NS 11, NS 12])), ((60, 6), Reduce (11, [NS 11, NS 12])), ((60, 8), Reduce (11, [NS 11, NS 12])), ((60, 9), Reduce (11, [NS 11, NS 12])), ((60, 10), Reduce (11, [NS 11, NS 12])), ((60, 11), Reduce (11, [NS 11, NS 12])), ((60, 15), Reduce (11, [NS 11, NS 12])), ((60, 16), Reduce (11, [NS 11, NS 12])), ((60, 17), Reduce (11, [NS 11, NS 12])), ((60, 18), Reduce (11, [NS 11, NS 12])), ((60, 19), Reduce (11, [NS 11, NS 12])), ((60, 20), Reduce (11, [NS 11, NS 12])), ((60, 21), Reduce (11, [NS 11, NS 12])), ((60, 22), Reduce (11, [NS 11, NS 12])), ((60, 23), Reduce (11, [NS 11, NS 12])), ((60, 24), Reduce (11, [NS 11, NS 12])), ((60, 25), Reduce (11, [NS 11, NS 12])), ((60, 26), Reduce (11, [NS 11, NS 12])), ((60, 27), Reduce (11, [NS 11, NS 12])), ((60, 28), Reduce (11, [NS 11, NS 12])), ((60, 30), Reduce (11, [NS 11, NS 12])), ((60, 33), Reduce (11, [NS 11, NS 12])), ((60, 34), Reduce (11, [NS 11, NS 12])), ((60, 35), Reduce (11, [NS 11, NS 12])), ((60, 36), Reduce (11, [NS 11, NS 12])), ((60, 37), Reduce (11, [NS 11, NS 12]))
            , ((61, 29), Shift 90)
            , ((62, 1), Shift 93)
            , ((63, 1), Reduce (16, [NS 17])), ((63, 2), Shift 96), ((63, 4), Reduce (16, [NS 17]))
            , ((64, 3), Shift 64), ((64, 32), Shift 65)
            , ((65, 1), Reduce (17, [TS 32])), ((65, 2), Reduce (17, [TS 32])), ((65, 4), Reduce (17, [TS 32]))
            , ((66, 1), Shift 94)
            , ((67, 1), Reduce (18, [NS 19])), ((67, 2), Shift 101), ((67, 3), Shift 70), ((67, 4), Reduce (18, [NS 19])), ((67, 33), Shift 71), ((67, 34), Shift 69)
            , ((68, 1), Reduce (19, [NS 20])), ((68, 2), Reduce (19, [NS 20])), ((68, 3), Reduce (19, [NS 20])), ((68, 4), Reduce (19, [NS 20])), ((68, 33), Reduce (19, [NS 20])), ((68, 34), Reduce (19, [NS 20]))
            , ((69, 1), Reduce (20, [TS 34])), ((69, 2), Reduce (20, [TS 34])), ((69, 3), Reduce (20, [TS 34])), ((69, 4), Reduce (20, [TS 34])), ((69, 33), Reduce (20, [TS 34])), ((69, 34), Reduce (20, [TS 34]))
            , ((70, 3), Shift 70), ((70, 33), Shift 71), ((70, 34), Shift 69)
            , ((71, 1), Reduce (20, [TS 33])), ((71, 2), Reduce (20, [TS 33])), ((71, 3), Reduce (20, [TS 33])), ((71, 4), Reduce (20, [TS 33])), ((71, 33), Reduce (20, [TS 33])), ((71, 34), Reduce (20, [TS 33]))
            , ((72, 3), Shift 22), ((72, 5), Shift 21), ((72, 12), Shift 24), ((72, 13), Shift 26), ((72, 14), Shift 29), ((72, 24), Shift 16), ((72, 25), Shift 30), ((72, 26), Shift 18), ((72, 28), Shift 17), ((72, 33), Shift 27), ((72, 34), Shift 38), ((72, 35), Shift 23), ((72, 36), Shift 15), ((72, 37), Shift 28)
            , ((73, 0), Reduce (2, [TS 7, NS 3, TS 1]))
            , ((74, 1), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 3), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 4), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 5), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 6), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 8), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 9), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 10), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 11), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 15), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 16), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 17), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 18), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 19), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 20), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 21), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 22), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 23), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 24), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 25), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 26), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 27), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 28), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 30), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 33), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 34), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 35), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 36), Reduce (3, [NS 4, TS 8, NS 3])), ((74, 37), Reduce (3, [NS 4, TS 8, NS 3]))
            , ((75, 1), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 3), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 4), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 5), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 6), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 8), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 9), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 10), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 11), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 15), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 16), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 17), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 18), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 19), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 20), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 21), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 22), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 23), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 24), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 25), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 26), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 27), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 28), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 30), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 33), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 34), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 35), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 36), Reduce (3, [TS 34, TS 29, NS 3])), ((75, 37), Reduce (3, [TS 34, TS 29, NS 3]))
            , ((76, 1), Reduce (4, [NS 4, TS 10, NS 5])), ((76, 4), Reduce (4, [NS 4, TS 10, NS 5])), ((76, 8), Reduce (4, [NS 4, TS 10, NS 5])), ((76, 10), Reduce (4, [NS 4, TS 10, NS 5]))
            , ((77, 1), Reduce (5, [NS 6, TS 11, NS 5])), ((77, 4), Reduce (5, [NS 6, TS 11, NS 5])), ((77, 8), Reduce (5, [NS 6, TS 11, NS 5])), ((77, 10), Reduce (5, [NS 6, TS 11, NS 5]))
            , ((78, 1), Reduce (6, [NS 6, TS 9, NS 7])), ((78, 4), Reduce (6, [NS 6, TS 9, NS 7])), ((78, 8), Reduce (6, [NS 6, TS 9, NS 7])), ((78, 9), Reduce (6, [NS 6, TS 9, NS 7])), ((78, 10), Reduce (6, [NS 6, TS 9, NS 7])), ((78, 11), Reduce (6, [NS 6, TS 9, NS 7]))
            , ((79, 1), Reduce (7, [NS 8, TS 30, NS 7])), ((79, 4), Reduce (7, [NS 8, TS 30, NS 7])), ((79, 8), Reduce (7, [NS 8, TS 30, NS 7])), ((79, 9), Reduce (7, [NS 8, TS 30, NS 7])), ((79, 10), Reduce (7, [NS 8, TS 30, NS 7])), ((79, 11), Reduce (7, [NS 8, TS 30, NS 7]))
            , ((80, 1), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 4), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 6), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 8), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 9), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 10), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 11), Reduce (8, [NS 9, TS 15, NS 9])), ((80, 20), Shift 57), ((80, 21), Shift 56), ((80, 30), Reduce (8, [NS 9, TS 15, NS 9]))
            , ((81, 1), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 4), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 6), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 8), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 9), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 10), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 11), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 20), Shift 57), ((81, 21), Shift 56), ((81, 30), Reduce (8, [NS 9, TS 18, NS 9]))
            , ((82, 1), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 4), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 6), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 8), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 9), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 10), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 11), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 20), Shift 57), ((82, 21), Shift 56), ((82, 30), Reduce (8, [NS 9, TS 19, NS 9]))
            , ((83, 1), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 4), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 6), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 8), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 9), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 10), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 11), Reduce (8, [NS 9, TS 27, NS 9])), ((83, 20), Shift 57), ((83, 21), Shift 56), ((83, 30), Reduce (8, [NS 9, TS 27, NS 9]))
            , ((84, 1), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 4), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 6), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 8), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 9), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 10), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 11), Reduce (8, [NS 9, TS 16, NS 9])), ((84, 20), Shift 57), ((84, 21), Shift 56), ((84, 30), Reduce (8, [NS 9, TS 16, NS 9]))
            , ((85, 1), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 4), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 6), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 8), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 9), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 10), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 11), Reduce (8, [NS 9, TS 17, NS 9])), ((85, 20), Shift 57), ((85, 21), Shift 56), ((85, 30), Reduce (8, [NS 9, TS 17, NS 9]))
            , ((86, 1), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 4), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 6), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 8), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 9), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 10), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 11), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 15), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 16), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 17), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 18), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 19), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 20), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 21), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 22), Shift 59), ((86, 23), Shift 58), ((86, 27), Reduce (9, [NS 9, TS 21, NS 10])), ((86, 30), Reduce (9, [NS 9, TS 21, NS 10]))
            , ((87, 1), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 4), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 6), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 8), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 9), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 10), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 11), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 15), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 16), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 17), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 18), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 19), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 20), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 21), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 22), Shift 59), ((87, 23), Shift 58), ((87, 27), Reduce (9, [NS 9, TS 20, NS 10])), ((87, 30), Reduce (9, [NS 9, TS 20, NS 10]))
            , ((88, 1), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 3), Shift 22), ((88, 4), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 5), Shift 21), ((88, 6), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 8), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 9), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 10), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 11), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 15), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 16), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 17), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 18), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 19), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 20), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 21), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 22), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 23), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 24), Shift 16), ((88, 25), Shift 30), ((88, 26), Shift 18), ((88, 27), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 28), Shift 17), ((88, 30), Reduce (10, [NS 10, TS 23, NS 11])), ((88, 33), Shift 27), ((88, 34), Shift 38), ((88, 35), Shift 23), ((88, 36), Shift 15), ((88, 37), Shift 28)
            , ((89, 1), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 3), Shift 22), ((89, 4), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 5), Shift 21), ((89, 6), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 8), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 9), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 10), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 11), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 15), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 16), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 17), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 18), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 19), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 20), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 21), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 22), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 23), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 24), Shift 16), ((89, 25), Shift 30), ((89, 26), Shift 18), ((89, 27), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 28), Shift 17), ((89, 30), Reduce (10, [NS 10, TS 22, NS 11])), ((89, 33), Shift 27), ((89, 34), Shift 38), ((89, 35), Shift 23), ((89, 36), Shift 15), ((89, 37), Shift 28)
            , ((90, 3), Shift 22), ((90, 5), Shift 21), ((90, 12), Shift 24), ((90, 13), Shift 26), ((90, 14), Shift 29), ((90, 24), Shift 16), ((90, 25), Shift 30), ((90, 26), Shift 18), ((90, 28), Shift 17), ((90, 33), Shift 27), ((90, 34), Shift 20), ((90, 35), Shift 23), ((90, 36), Shift 15), ((90, 37), Shift 28)
            , ((91, 1), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 3), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 4), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 5), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 6), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 8), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 9), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 10), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 11), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 15), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 16), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 17), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 18), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 19), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 20), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 21), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 22), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 23), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 24), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 25), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 26), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 27), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 28), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 30), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 33), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 34), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 35), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 36), Reduce (12, [TS 5, NS 13, TS 6])), ((91, 37), Reduce (12, [TS 5, NS 13, TS 6]))
            , ((92, 1), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 3), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 4), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 5), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 6), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 8), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 9), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 10), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 11), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 15), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 16), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 17), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 18), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 19), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 20), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 21), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 22), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 23), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 24), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 25), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 26), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 27), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 28), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 30), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 33), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 34), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 35), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 36), Reduce (12, [TS 3, NS 3, TS 4])), ((92, 37), Reduce (12, [TS 3, NS 3, TS 4]))
            , ((93, 0), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 3), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 5), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 12), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 13), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 14), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 24), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 25), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 26), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 28), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 31), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 32), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 33), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 34), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 35), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 36), Reduce (15, [TS 31, TS 33, NS 16, TS 1])), ((93, 37), Reduce (15, [TS 31, TS 33, NS 16, TS 1]))
            , ((94, 0), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 3), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 5), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 12), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 13), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 14), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 24), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 25), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 26), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 28), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 31), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 32), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 33), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 34), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 35), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 36), Reduce (15, [TS 32, TS 33, NS 18, TS 1])), ((94, 37), Reduce (15, [TS 32, TS 33, NS 18, TS 1]))
            , ((95, 4), Shift 103)
            , ((96, 3), Shift 64), ((96, 32), Shift 65)
            , ((97, 6), Reduce (13, [NS 8, TS 9, NS 13]))
            , ((98, 1), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 3), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 4), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 5), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 6), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 8), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 9), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 10), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 11), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 15), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 16), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 17), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 18), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 19), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 20), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 21), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 22), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 23), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 24), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 25), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 26), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 27), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 28), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 30), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 33), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 34), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 35), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 36), Reduce (11, [NS 12, TS 34, TS 29, NS 3])), ((98, 37), Reduce (11, [NS 12, TS 34, TS 29, NS 3]))
            , ((99, 4), Shift 105)
            , ((100, 1), Reduce (19, [NS 19, NS 20])), ((100, 2), Reduce (19, [NS 19, NS 20])), ((100, 3), Reduce (19, [NS 19, NS 20])), ((100, 4), Reduce (19, [NS 19, NS 20])), ((100, 33), Reduce (19, [NS 19, NS 20])), ((100, 34), Reduce (19, [NS 19, NS 20]))
            , ((101, 3), Shift 70), ((101, 33), Shift 71), ((101, 34), Shift 69)
            , ((102, 1), Reduce (16, [NS 17, TS 2, NS 16])), ((102, 4), Reduce (16, [NS 17, TS 2, NS 16]))
            , ((103, 1), Reduce (17, [TS 3, NS 16, TS 4])), ((103, 2), Reduce (17, [TS 3, NS 16, TS 4])), ((103, 4), Reduce (17, [TS 3, NS 16, TS 4]))
            , ((104, 1), Reduce (18, [NS 19, TS 2, NS 18])), ((104, 4), Reduce (18, [NS 19, TS 2, NS 18]))
            , ((105, 1), Reduce (20, [TS 3, NS 18, TS 4])), ((105, 2), Reduce (20, [TS 3, NS 18, TS 4])), ((105, 3), Reduce (20, [TS 3, NS 18, TS 4])), ((105, 4), Reduce (20, [TS 3, NS 18, TS 4])), ((105, 33), Reduce (20, [TS 3, NS 18, TS 4])), ((105, 34), Reduce (20, [TS 3, NS 18, TS 4]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 14), ((0, 2), 2), ((0, 3), 3), ((0, 4), 4), ((0, 5), 5), ((0, 6), 6), ((0, 7), 7), ((0, 8), 8), ((0, 9), 9), ((0, 10), 10), ((0, 11), 11), ((0, 12), 12), ((0, 14), 13), ((0, 15), 1)
            , ((1, 3), 3), ((1, 4), 4), ((1, 5), 5), ((1, 6), 6), ((1, 7), 7), ((1, 8), 8), ((1, 9), 9), ((1, 10), 10), ((1, 11), 11), ((1, 12), 12), ((1, 14), 32), ((1, 15), 1)
            , ((11, 12), 60)
            , ((21, 8), 37), ((21, 9), 9), ((21, 10), 10), ((21, 11), 11), ((21, 12), 12), ((21, 13), 36)
            , ((22, 3), 41), ((22, 4), 4), ((22, 5), 5), ((22, 6), 6), ((22, 7), 7), ((22, 8), 8), ((22, 9), 9), ((22, 10), 10), ((22, 11), 11), ((22, 12), 12)
            , ((24, 8), 48), ((24, 9), 9), ((24, 10), 10), ((24, 11), 11), ((24, 12), 12)
            , ((25, 3), 40), ((25, 4), 4), ((25, 5), 5), ((25, 6), 6), ((25, 7), 7), ((25, 8), 8), ((25, 9), 9), ((25, 10), 10), ((25, 11), 11), ((25, 12), 12)
            , ((26, 8), 49), ((26, 9), 9), ((26, 10), 10), ((26, 11), 11), ((26, 12), 12)
            , ((34, 16), 62), ((34, 17), 63)
            , ((35, 18), 66), ((35, 19), 67), ((35, 20), 68)
            , ((42, 3), 74), ((42, 4), 4), ((42, 5), 5), ((42, 6), 6), ((42, 7), 7), ((42, 8), 8), ((42, 9), 9), ((42, 10), 10), ((42, 11), 11), ((42, 12), 12)
            , ((43, 5), 76), ((43, 6), 6), ((43, 7), 7), ((43, 8), 8), ((43, 9), 9), ((43, 10), 10), ((43, 11), 11), ((43, 12), 12)
            , ((44, 3), 75), ((44, 4), 4), ((44, 5), 5), ((44, 6), 6), ((44, 7), 7), ((44, 8), 8), ((44, 9), 9), ((44, 10), 10), ((44, 11), 11), ((44, 12), 12)
            , ((45, 7), 78), ((45, 8), 8), ((45, 9), 9), ((45, 10), 10), ((45, 11), 11), ((45, 12), 12)
            , ((46, 5), 77), ((46, 6), 6), ((46, 7), 7), ((46, 8), 8), ((46, 9), 9), ((46, 10), 10), ((46, 11), 11), ((46, 12), 12)
            , ((47, 7), 79), ((47, 8), 8), ((47, 9), 9), ((47, 10), 10), ((47, 11), 11), ((47, 12), 12)
            , ((50, 9), 80), ((50, 10), 10), ((50, 11), 11), ((50, 12), 12)
            , ((51, 9), 81), ((51, 10), 10), ((51, 11), 11), ((51, 12), 12)
            , ((52, 9), 82), ((52, 10), 10), ((52, 11), 11), ((52, 12), 12)
            , ((53, 9), 83), ((53, 10), 10), ((53, 11), 11), ((53, 12), 12)
            , ((54, 9), 84), ((54, 10), 10), ((54, 11), 11), ((54, 12), 12)
            , ((55, 9), 85), ((55, 10), 10), ((55, 11), 11), ((55, 12), 12)
            , ((56, 10), 86), ((56, 11), 11), ((56, 12), 12)
            , ((57, 10), 87), ((57, 11), 11), ((57, 12), 12)
            , ((58, 11), 88), ((58, 12), 12)
            , ((59, 11), 89), ((59, 12), 12)
            , ((64, 16), 95), ((64, 17), 63)
            , ((67, 20), 100)
            , ((70, 18), 99), ((70, 19), 67), ((70, 20), 68)
            , ((72, 8), 37), ((72, 9), 9), ((72, 10), 10), ((72, 11), 11), ((72, 12), 12), ((72, 13), 97)
            , ((88, 12), 60)
            , ((89, 12), 60)
            , ((90, 3), 98), ((90, 4), 4), ((90, 5), 5), ((90, 6), 6), ((90, 7), 7), ((90, 8), 8), ((90, 9), 9), ((90, 10), 10), ((90, 11), 11), ((90, 12), 12)
            , ((96, 16), 102), ((96, 17), 63)
            , ((101, 18), 104), ((101, 19), 67), ((101, 20), 68)
            ]
        }

