name: ppap
version: 1.0.0
synopsis: Projects Pouring All Power
description: The collection of my Haskell projects including a lexer generator, a parser generator, and an interpreter of (a dialect of) λProlog.
homepage: https://github.com/KiJeong-Lim/ppap
license: BSD3
license-file: LICENSE
author: 林 起靖
maintainer: gijungdduk@naver.com
copyright: 2021-2026, Kijeong Lim
build-type: Simple
cabal-version: 2.0
extra-source-files:
  doc/HolBETA.txt
  test/SmokeMain.hs
  test/smoke.sh
  test/audit_module/*.hol
  test/audit_module/*.input.txt
  test/audit_module/*.expected.txt
  test/audit_module/*.hs
  test/audit_module/*.sh
  test/audit_runtime/*.hol
  test/audit_runtime/*.input.txt
  test/audit_runtime/*.expected.txt
  test/audit_runtime/*.hs
  test/audit_runtime/*.sh
  test/cut/*.hol
  test/cut/*.input.txt
  test/cut/*.expected.txt
  test/debug/*.hol
  test/debug/*.input.txt
  test/debug/*.expected.txt
  test/example/*.hol
  test/example/*.input.txt
  test/example/*.expected.txt
  test/fibonacci/*.hol
  test/fibonacci/*.input.txt
  test/fibonacci/*.expected.txt
  test/io/*.hol
  test/io/*.input.txt
  test/io/*.expected.txt
  test/kind/*.hol
  test/kind/*.input.txt
  test/kind/*.expected.txt
  test/module/*.hol
  test/module/*.input.txt
  test/module/*.expected.txt
  test/multi_head/*.hol
  test/multi_head/*.input.txt
  test/multi_head/*.expected.txt
  test/notation/*.hol
  test/notation/*.input.txt
  test/notation/*.expected.txt
  test/presburger/*.hol
  test/presburger/*.input.txt
  test/presburger/*.expected.txt
  test/sloc/*.hol
  test/sloc/*.input.txt
  test/sloc/*.expected.txt
  test/sloc/*.hs
  test/sloc/*.sh
  test/symbolic/*.hol
  test/symbolic/*.input.txt
  test/symbolic/*.expected.txt
  test/typecheck/*.hol
  test/typecheck/*.input.txt
  test/typecheck/*.expected.txt
  test/typecheck/*.hs
  test/typecheck/*.sh

executable ppap
  hs-source-dirs: src
  default-language: Haskell2010
  main-is: Main.hs
  ghc-options: -O2 -funbox-strict-fields -fspec-constr -fexpose-all-unfoldings -fspecialise-aggressively
  build-depends: base >= 4.7 && < 5, array >= 0.5, containers >= 0.6, transformers >= 0.5, pretty-terminal >= 0.1, QuickCheck >= 2.13, checkers >= 0.5, directory >= 1.3, vector >= 0.12, math-functions >= 0.3, extra >= 1.7, filepath >= 1.5, process >= 1.0, random >= 1.0
  other-modules:
    ALPHA1.Header
    ALPHA1.PlanHolLexer
    ALPHA1.PlanHolParser
    ALPHA1.Constant
    ALPHA1.Desugarer
    ALPHA1.TypeChecker
    ALPHA1.TermNode
    ALPHA1.HOPU
    ALPHA1.Runtime
    ALPHA1.Compiler
    ALPHA1.Main
    Calc.ControlSystem.Diagram.Solver
    Calc.ControlSystem.Export
    Calc.ControlSystem.Test
    Calc.ControlSystem.Util
    Calc.Presburger.Internal
    Calc.Presburger.Test
    Calc.Runtime.Executor
    Calc.Tools.Fuzzy
    Calc.Tools.FuzzyExample1
    Calc.Main
    Hol.ALPHA2.Header
    Hol.ALPHA2.PlanHolLexer
    Hol.ALPHA2.PlanHolParser
    Hol.ALPHA2.Constant
    Hol.ALPHA2.Desugarer
    Hol.ALPHA2.TypeChecker
    Hol.ALPHA2.TermNode
    Hol.ALPHA2.HOPU
    Hol.ALPHA2.Runtime
    Hol.ALPHA2.Compiler
    Hol.ALPHA2.Main
    Hol.BETA.Arith
    Hol.BETA.Compiler
    Hol.BETA.Constant
    Hol.BETA.Debugger
    Hol.BETA.Desugarer
    Hol.BETA.Diagnostic
    Hol.BETA.FixityResolver
    Hol.BETA.Header
    Hol.BETA.HOPU
    Hol.BETA.Main
    Hol.BETA.ModuleLoader
    Hol.BETA.Notation
    Hol.BETA.PlanHolLexer
    Hol.BETA.PlanHolParser
    Hol.BETA.Runtime
    Hol.BETA.TermNode
    Hol.BETA.TypeChecker
    Hol.V1.Main
    Hol.Main
    IsabelleHol.Dependecies
    Json.JsonAst
    Json.JsonLexer
    Json.JsonParser
    Json.JsonTest
    Json.JsonViewer
    LGS.Alpha1
    LGS.Alpha2
    LGS.Main
    PGS.Alpha1
    PGS.LALR
    PGS.Main
    TEST.Main
    X.Machine
    Y.Text.Ppr.Viewer
    Y.Text.Ppr
    Y.Base
    Z.Algo.Function
    Z.Algo.Sorting
    Z.Math.V1.Internal
    Z.Math.Classes
    Z.Math.V1
    Z.Math.Z2
    Z.System.File
    Z.System.Machine
    Z.System.Path
    Z.System.Shelly
    Z.System.Util
    Z.Text.Doc.Internal
    Z.Text.Doc.Test
    Z.Text.PC.Base
    Z.Text.PC.Internal
    Z.Text.PC.Test
    Z.Text.Doc
    Z.Text.PC
    Z.Text.PM
    Z.Algorithms
    Z.Doc
    Z.OldPC
    Z.PC
    Z.System
    Z.Utils
  include-dirs:
    src/X
  includes:
    machine.h
  c-sources:
    src/X/machine.c

test-suite hol-beta-smoke
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: SmokeMain.hs
  default-language: Haskell2010
  build-depends: base >= 4.7 && < 5, directory >= 1.3, filepath >= 1.4, process >= 1.0
  build-tool-depends: ppap:ppap
