module Hol.BETA1.PlanHolParser where

import Hol.BETA1.Header
import Hol.BETA1.PlanHolLexer
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

-- the following codes are generated by PGS.

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()

runHolParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runHolParser = fmap (getEither getQuery (getSequence getDecl)) . runLALR1 theLALR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] = (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[20]] = RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[22]] = RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_infixl loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixL (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infixr loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixR (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infix loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixN (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_prefix loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_Prefix (contents_2) (contents_3)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] = RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[21, 20]] = RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[21]] = (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise = RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[20]] = RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[23, 22]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[23]] = (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[23, 24]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[24]] = (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = if head (contents_1) `elem` ['A' .. 'Z'] then RTyVar (loc_1) (contents_1) else RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[22]] = RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_id loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] = RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] = (getTermRep1L0 _1)
    getTermRep1L0 :: ParsingTree -> (TermRep)
    getTermRep1L0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[5, 5]] = RApp (getSLoc (getTermRep1L1 _1) <> getSLoc (getTermRep1L1 _3)) (RApp (getSLoc (getTermRep1L1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1L1 _1)) (getTermRep1L1 _3)
    getTermRep1L0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] = (getTermRep1L1 _1)
    getTermRep1L1 :: ParsingTree -> (TermRep)
    getTermRep1L1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[5, 6]] = RApp (getSLoc (getTermRep1L1 _1) <> getSLoc (getTermRep1L2 _3)) (RApp (getSLoc (getTermRep1L1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1L1 _1)) (getTermRep1L2 _3)
    getTermRep1L1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] = (getTermRep1L2 _1)
    getTermRep1L2 :: ParsingTree -> (TermRep)
    getTermRep1L2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[7, 6]] = RApp (getSLoc (getTermRep1L3 _1) <> getSLoc (getTermRep1L2 _3)) (RApp (getSLoc (getTermRep1L3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep1L3 _1)) (getTermRep1L2 _3)
    getTermRep1L2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] = (getTermRep1L3 _1)
    getTermRep1L3 :: ParsingTree -> (TermRep)
    getTermRep1L3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[7, 8]] = RApp (getSLoc (getTermRep1L3 _1) <> getSLoc (getTermRep1L4 _3)) (RApp (getSLoc (getTermRep1L3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep1L3 _1)) (getTermRep1L4 _3)
    getTermRep1L3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = (getTermRep1L4 _1)
    getTermRep1L4 :: ParsingTree -> (TermRep)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_is loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_is)) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_eq) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_le loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_le) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_lt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_lt) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_ge loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_ge) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_gt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_gt) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = (getTermRep1L5 _1)
    getTermRep1L5 :: ParsingTree -> (TermRep)
    getTermRep1L5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 9]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep1L6 _1)) (getTermRep1L5 _3)
    getTermRep1L5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] = (getTermRep1L6 _1)
    getTermRep1L6 :: ParsingTree -> (TermRep)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_plus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L7 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_plus) (getTermRep1L6 _1)) (getTermRep1L7 _3)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_minus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L7 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_minus) (getTermRep1L6 _1)) (getTermRep1L7 _3)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[11]] = (getTermRep1L7 _1)
    getTermRep1L7 :: ParsingTree -> (TermRep)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_star loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[11, 12]] = RApp (getSLoc (getTermRep1L7 _1) <> getSLoc (getTermRep1L8 _3)) (RApp (getSLoc (getTermRep1L7 _1) <> (loc_2)) (RCon (loc_2) DC_mul) (getTermRep1L7 _1)) (getTermRep1L8 _3)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_slash loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[11, 12]] = RApp (getSLoc (getTermRep1L7 _1) <> getSLoc (getTermRep1L8 _3)) (RApp (getSLoc (getTermRep1L7 _1) <> (loc_2)) (RCon (loc_2) DC_div) (getTermRep1L7 _1)) (getTermRep1L8 _3)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] = (getTermRep1L8 _1)
    getTermRep1L8 :: ParsingTree -> (TermRep)
    getTermRep1L8 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[13]] = (getTermRep1L9 _1)
    getTermRep1L9 :: ParsingTree -> (TermRep)
    getTermRep1L9 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[14]] = (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_bslash loc_3), _4@(PTBranch guard4 _)])
        | [guard1, guard4] `elem` [[15, 3]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep0 _4)) (getTermRep3 _1) (RAbs ((loc_2) <> getSLoc (getTermRep0 _4)) (contents_2) (getTermRep0 _4))
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[15]] = (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[15, 16]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _2)) (getTermRep3 _1) (getTermRep4 _2)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[16]] = (getTermRep4 _1)
    getTermRep3 (PTBranch _ [PTLeaf (T_pi loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_pi)
    getTermRep3 (PTBranch _ [PTLeaf (T_sigma loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_sigma)
    getTermRep3 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise = RCon (loc_1) DC_Succ
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] = RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep4 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_cut)
    getTermRep4 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_true)
    getTermRep4 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_fail)
    getTermRep4 (PTBranch _ [PTLeaf (T_debug loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_debug)
    getTermRep4 (PTBranch _ [PTLeaf (T_wildcard loc_1)])
        | otherwise = R_wc (loc_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = if head (contents_1) `elem` ['A' .. 'Z'] then RVar (loc_1) (contents_1) else RCon (loc_1) (DC_Named (contents_1))
    getTermRep4 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise = mkNatLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise = mkStrLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise = mkChrLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise = RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep4 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[17]] = RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = RApp (getSLoc (getTermRep1L5 _1)) (RApp (getSLoc (getTermRep1L5 _1)) (RCon (getSLoc (getTermRep1L5 _1)) DC_Cons) (getTermRep1L5 _1)) (RCon (getSLoc (getTermRep1L5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 17]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep1L5 _1)) (getListBody _3)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise = []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[19, 18]] = (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] = Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[18]] = Right (getRight _1)
    toTerminal :: (Token) -> TSym
    toTerminal (T_wildcard loc) = 1
    toTerminal (T_dot loc) = 2
    toTerminal (T_arrow loc) = 3
    toTerminal (T_lparen loc) = 4
    toTerminal (T_rparen loc) = 5
    toTerminal (T_lbracket loc) = 6
    toTerminal (T_rbracket loc) = 7
    toTerminal (T_quest loc) = 8
    toTerminal (T_pi loc) = 9
    toTerminal (T_sigma loc) = 10
    toTerminal (T_succ loc) = 11
    toTerminal (T_bslash loc) = 12
    toTerminal (T_if loc) = 13
    toTerminal (T_semicolon loc) = 14
    toTerminal (T_fatarrow loc) = 15
    toTerminal (T_comma loc) = 16
    toTerminal (T_eq loc) = 17
    toTerminal (T_le loc) = 18
    toTerminal (T_lt loc) = 19
    toTerminal (T_ge loc) = 20
    toTerminal (T_gt loc) = 21
    toTerminal (T_is loc) = 22
    toTerminal (T_cons loc) = 23
    toTerminal (T_plus loc) = 24
    toTerminal (T_minus loc) = 25
    toTerminal (T_star loc) = 26
    toTerminal (T_slash loc) = 27
    toTerminal (T_cut loc) = 28
    toTerminal (T_true loc) = 29
    toTerminal (T_fail loc) = 30
    toTerminal (T_debug loc) = 31
    toTerminal (T_kind loc) = 32
    toTerminal (T_type loc) = 33
    toTerminal (T_infixl loc) = 34
    toTerminal (T_infixr loc) = 35
    toTerminal (T_infix loc) = 36
    toTerminal (T_prefix loc) = 37
    toTerminal (T_abbrev loc) = 38
    toTerminal (T_notation loc) = 39
    toTerminal (T_id loc contents) = 40
    toTerminal (T_nat_lit loc contents) = 41
    toTerminal (T_chr_lit loc contents) = 42
    toTerminal (T_str_lit loc contents) = 43
    runLALR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLALR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLALR1Parser :: LR1Parser
    theLALR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (18, [])), ((0, 1), Shift 39), ((0, 4), Shift 29), ((0, 6), Shift 28), ((0, 8), Shift 33), ((0, 9), Shift 31), ((0, 10), Shift 34), ((0, 11), Shift 36), ((0, 28), Shift 20), ((0, 29), Shift 37), ((0, 30), Shift 22), ((0, 31), Shift 21), ((0, 32), Shift 27), ((0, 33), Shift 38), ((0, 34), Shift 25), ((0, 35), Shift 26), ((0, 36), Shift 24), ((0, 37), Shift 32), ((0, 40), Shift 23), ((0, 41), Shift 30), ((0, 42), Shift 19), ((0, 43), Shift 35)
            , ((1, 0), Reduce (18, [])), ((1, 1), Shift 39), ((1, 4), Shift 29), ((1, 6), Shift 28), ((1, 9), Shift 31), ((1, 10), Shift 34), ((1, 11), Shift 36), ((1, 28), Shift 20), ((1, 29), Shift 37), ((1, 30), Shift 22), ((1, 31), Shift 21), ((1, 32), Shift 27), ((1, 33), Shift 38), ((1, 34), Shift 25), ((1, 35), Shift 26), ((1, 36), Shift 24), ((1, 37), Shift 32), ((1, 40), Shift 23), ((1, 41), Shift 30), ((1, 42), Shift 19), ((1, 43), Shift 35)
            , ((2, 0), Reduce (1, [NS 2]))
            , ((3, 2), Shift 41)
            , ((4, 2), Reduce (3, [NS 4])), ((4, 5), Reduce (3, [NS 4])), ((4, 7), Reduce (3, [NS 4])), ((4, 13), Reduce (3, [NS 4])), ((4, 14), Reduce (3, [NS 4])), ((4, 15), Reduce (3, [NS 4])), ((4, 16), Reduce (3, [NS 4])), ((4, 17), Reduce (3, [NS 4])), ((4, 18), Reduce (3, [NS 4])), ((4, 19), Reduce (3, [NS 4])), ((4, 20), Reduce (3, [NS 4])), ((4, 21), Reduce (3, [NS 4])), ((4, 22), Reduce (3, [NS 4])), ((4, 23), Reduce (3, [NS 4])), ((4, 24), Reduce (3, [NS 4])), ((4, 25), Reduce (3, [NS 4])), ((4, 26), Reduce (3, [NS 4])), ((4, 27), Reduce (3, [NS 4]))
            , ((5, 2), Reduce (4, [NS 5])), ((5, 5), Reduce (4, [NS 5])), ((5, 7), Reduce (4, [NS 5])), ((5, 13), Shift 42), ((5, 14), Shift 43), ((5, 15), Reduce (4, [NS 5])), ((5, 16), Reduce (4, [NS 5])), ((5, 17), Reduce (4, [NS 5])), ((5, 18), Reduce (4, [NS 5])), ((5, 19), Reduce (4, [NS 5])), ((5, 20), Reduce (4, [NS 5])), ((5, 21), Reduce (4, [NS 5])), ((5, 22), Reduce (4, [NS 5])), ((5, 23), Reduce (4, [NS 5])), ((5, 24), Reduce (4, [NS 5])), ((5, 25), Reduce (4, [NS 5])), ((5, 26), Reduce (4, [NS 5])), ((5, 27), Reduce (4, [NS 5]))
            , ((6, 2), Reduce (5, [NS 6])), ((6, 5), Reduce (5, [NS 6])), ((6, 7), Reduce (5, [NS 6])), ((6, 13), Reduce (5, [NS 6])), ((6, 14), Reduce (5, [NS 6])), ((6, 15), Reduce (5, [NS 6])), ((6, 16), Reduce (5, [NS 6])), ((6, 17), Reduce (5, [NS 6])), ((6, 18), Reduce (5, [NS 6])), ((6, 19), Reduce (5, [NS 6])), ((6, 20), Reduce (5, [NS 6])), ((6, 21), Reduce (5, [NS 6])), ((6, 22), Reduce (5, [NS 6])), ((6, 23), Reduce (5, [NS 6])), ((6, 24), Reduce (5, [NS 6])), ((6, 25), Reduce (5, [NS 6])), ((6, 26), Reduce (5, [NS 6])), ((6, 27), Reduce (5, [NS 6]))
            , ((7, 2), Reduce (6, [NS 7])), ((7, 5), Reduce (6, [NS 7])), ((7, 7), Reduce (6, [NS 7])), ((7, 13), Reduce (6, [NS 7])), ((7, 14), Reduce (6, [NS 7])), ((7, 15), Shift 45), ((7, 16), Shift 44), ((7, 17), Reduce (6, [NS 7])), ((7, 18), Reduce (6, [NS 7])), ((7, 19), Reduce (6, [NS 7])), ((7, 20), Reduce (6, [NS 7])), ((7, 21), Reduce (6, [NS 7])), ((7, 22), Reduce (6, [NS 7])), ((7, 23), Reduce (6, [NS 7])), ((7, 24), Reduce (6, [NS 7])), ((7, 25), Reduce (6, [NS 7])), ((7, 26), Reduce (6, [NS 7])), ((7, 27), Reduce (6, [NS 7]))
            , ((8, 2), Reduce (7, [NS 8])), ((8, 5), Reduce (7, [NS 8])), ((8, 7), Reduce (7, [NS 8])), ((8, 13), Reduce (7, [NS 8])), ((8, 14), Reduce (7, [NS 8])), ((8, 15), Reduce (7, [NS 8])), ((8, 16), Reduce (7, [NS 8])), ((8, 17), Reduce (7, [NS 8])), ((8, 18), Reduce (7, [NS 8])), ((8, 19), Reduce (7, [NS 8])), ((8, 20), Reduce (7, [NS 8])), ((8, 21), Reduce (7, [NS 8])), ((8, 22), Reduce (7, [NS 8])), ((8, 23), Reduce (7, [NS 8])), ((8, 24), Reduce (7, [NS 8])), ((8, 25), Reduce (7, [NS 8])), ((8, 26), Reduce (7, [NS 8])), ((8, 27), Reduce (7, [NS 8]))
            , ((9, 2), Reduce (8, [NS 9])), ((9, 5), Reduce (8, [NS 9])), ((9, 7), Reduce (8, [NS 9])), ((9, 13), Reduce (8, [NS 9])), ((9, 14), Reduce (8, [NS 9])), ((9, 15), Reduce (8, [NS 9])), ((9, 16), Reduce (8, [NS 9])), ((9, 17), Shift 46), ((9, 18), Shift 50), ((9, 19), Shift 51), ((9, 20), Shift 47), ((9, 21), Shift 48), ((9, 22), Shift 49), ((9, 23), Reduce (8, [NS 9])), ((9, 24), Reduce (8, [NS 9])), ((9, 25), Reduce (8, [NS 9])), ((9, 26), Reduce (8, [NS 9])), ((9, 27), Reduce (8, [NS 9]))
            , ((10, 2), Reduce (9, [NS 10])), ((10, 5), Reduce (9, [NS 10])), ((10, 7), Reduce (9, [NS 10])), ((10, 13), Reduce (9, [NS 10])), ((10, 14), Reduce (9, [NS 10])), ((10, 15), Reduce (9, [NS 10])), ((10, 16), Reduce (9, [NS 10])), ((10, 17), Reduce (9, [NS 10])), ((10, 18), Reduce (9, [NS 10])), ((10, 19), Reduce (9, [NS 10])), ((10, 20), Reduce (9, [NS 10])), ((10, 21), Reduce (9, [NS 10])), ((10, 22), Reduce (9, [NS 10])), ((10, 23), Shift 52), ((10, 24), Shift 54), ((10, 25), Shift 53), ((10, 26), Reduce (9, [NS 10])), ((10, 27), Reduce (9, [NS 10]))
            , ((11, 2), Reduce (10, [NS 11])), ((11, 5), Reduce (10, [NS 11])), ((11, 7), Reduce (10, [NS 11])), ((11, 13), Reduce (10, [NS 11])), ((11, 14), Reduce (10, [NS 11])), ((11, 15), Reduce (10, [NS 11])), ((11, 16), Reduce (10, [NS 11])), ((11, 17), Reduce (10, [NS 11])), ((11, 18), Reduce (10, [NS 11])), ((11, 19), Reduce (10, [NS 11])), ((11, 20), Reduce (10, [NS 11])), ((11, 21), Reduce (10, [NS 11])), ((11, 22), Reduce (10, [NS 11])), ((11, 23), Reduce (10, [NS 11])), ((11, 24), Reduce (10, [NS 11])), ((11, 25), Reduce (10, [NS 11])), ((11, 26), Shift 56), ((11, 27), Shift 55)
            , ((12, 2), Reduce (11, [NS 12])), ((12, 5), Reduce (11, [NS 12])), ((12, 7), Reduce (11, [NS 12])), ((12, 13), Reduce (11, [NS 12])), ((12, 14), Reduce (11, [NS 12])), ((12, 15), Reduce (11, [NS 12])), ((12, 16), Reduce (11, [NS 12])), ((12, 17), Reduce (11, [NS 12])), ((12, 18), Reduce (11, [NS 12])), ((12, 19), Reduce (11, [NS 12])), ((12, 20), Reduce (11, [NS 12])), ((12, 21), Reduce (11, [NS 12])), ((12, 22), Reduce (11, [NS 12])), ((12, 23), Reduce (11, [NS 12])), ((12, 24), Reduce (11, [NS 12])), ((12, 25), Reduce (11, [NS 12])), ((12, 26), Reduce (11, [NS 12])), ((12, 27), Reduce (11, [NS 12]))
            , ((13, 2), Reduce (12, [NS 13])), ((13, 5), Reduce (12, [NS 13])), ((13, 7), Reduce (12, [NS 13])), ((13, 13), Reduce (12, [NS 13])), ((13, 14), Reduce (12, [NS 13])), ((13, 15), Reduce (12, [NS 13])), ((13, 16), Reduce (12, [NS 13])), ((13, 17), Reduce (12, [NS 13])), ((13, 18), Reduce (12, [NS 13])), ((13, 19), Reduce (12, [NS 13])), ((13, 20), Reduce (12, [NS 13])), ((13, 21), Reduce (12, [NS 13])), ((13, 22), Reduce (12, [NS 13])), ((13, 23), Reduce (12, [NS 13])), ((13, 24), Reduce (12, [NS 13])), ((13, 25), Reduce (12, [NS 13])), ((13, 26), Reduce (12, [NS 13])), ((13, 27), Reduce (12, [NS 13]))
            , ((14, 2), Reduce (13, [NS 14])), ((14, 5), Reduce (13, [NS 14])), ((14, 7), Reduce (13, [NS 14])), ((14, 13), Reduce (13, [NS 14])), ((14, 14), Reduce (13, [NS 14])), ((14, 15), Reduce (13, [NS 14])), ((14, 16), Reduce (13, [NS 14])), ((14, 17), Reduce (13, [NS 14])), ((14, 18), Reduce (13, [NS 14])), ((14, 19), Reduce (13, [NS 14])), ((14, 20), Reduce (13, [NS 14])), ((14, 21), Reduce (13, [NS 14])), ((14, 22), Reduce (13, [NS 14])), ((14, 23), Reduce (13, [NS 14])), ((14, 24), Reduce (13, [NS 14])), ((14, 25), Reduce (13, [NS 14])), ((14, 26), Reduce (13, [NS 14])), ((14, 27), Reduce (13, [NS 14]))
            , ((15, 1), Shift 39), ((15, 2), Reduce (14, [NS 15])), ((15, 4), Shift 29), ((15, 5), Reduce (14, [NS 15])), ((15, 6), Shift 28), ((15, 7), Reduce (14, [NS 15])), ((15, 13), Reduce (14, [NS 15])), ((15, 14), Reduce (14, [NS 15])), ((15, 15), Reduce (14, [NS 15])), ((15, 16), Reduce (14, [NS 15])), ((15, 17), Reduce (14, [NS 15])), ((15, 18), Reduce (14, [NS 15])), ((15, 19), Reduce (14, [NS 15])), ((15, 20), Reduce (14, [NS 15])), ((15, 21), Reduce (14, [NS 15])), ((15, 22), Reduce (14, [NS 15])), ((15, 23), Reduce (14, [NS 15])), ((15, 24), Reduce (14, [NS 15])), ((15, 25), Reduce (14, [NS 15])), ((15, 26), Reduce (14, [NS 15])), ((15, 27), Reduce (14, [NS 15])), ((15, 28), Shift 20), ((15, 29), Shift 37), ((15, 30), Shift 22), ((15, 31), Shift 21), ((15, 40), Shift 58), ((15, 41), Shift 30), ((15, 42), Shift 19), ((15, 43), Shift 35)
            , ((16, 1), Reduce (15, [NS 16])), ((16, 2), Reduce (15, [NS 16])), ((16, 4), Reduce (15, [NS 16])), ((16, 5), Reduce (15, [NS 16])), ((16, 6), Reduce (15, [NS 16])), ((16, 7), Reduce (15, [NS 16])), ((16, 13), Reduce (15, [NS 16])), ((16, 14), Reduce (15, [NS 16])), ((16, 15), Reduce (15, [NS 16])), ((16, 16), Reduce (15, [NS 16])), ((16, 17), Reduce (15, [NS 16])), ((16, 18), Reduce (15, [NS 16])), ((16, 19), Reduce (15, [NS 16])), ((16, 20), Reduce (15, [NS 16])), ((16, 21), Reduce (15, [NS 16])), ((16, 22), Reduce (15, [NS 16])), ((16, 23), Reduce (15, [NS 16])), ((16, 24), Reduce (15, [NS 16])), ((16, 25), Reduce (15, [NS 16])), ((16, 26), Reduce (15, [NS 16])), ((16, 27), Reduce (15, [NS 16])), ((16, 28), Reduce (15, [NS 16])), ((16, 29), Reduce (15, [NS 16])), ((16, 30), Reduce (15, [NS 16])), ((16, 31), Reduce (15, [NS 16])), ((16, 40), Reduce (15, [NS 16])), ((16, 41), Reduce (15, [NS 16])), ((16, 42), Reduce (15, [NS 16])), ((16, 43), Reduce (15, [NS 16]))
            , ((17, 0), Reduce (1, [NS 18]))
            , ((18, 0), Accept)
            , ((19, 1), Reduce (16, [TS 42])), ((19, 2), Reduce (16, [TS 42])), ((19, 4), Reduce (16, [TS 42])), ((19, 5), Reduce (16, [TS 42])), ((19, 6), Reduce (16, [TS 42])), ((19, 7), Reduce (16, [TS 42])), ((19, 13), Reduce (16, [TS 42])), ((19, 14), Reduce (16, [TS 42])), ((19, 15), Reduce (16, [TS 42])), ((19, 16), Reduce (16, [TS 42])), ((19, 17), Reduce (16, [TS 42])), ((19, 18), Reduce (16, [TS 42])), ((19, 19), Reduce (16, [TS 42])), ((19, 20), Reduce (16, [TS 42])), ((19, 21), Reduce (16, [TS 42])), ((19, 22), Reduce (16, [TS 42])), ((19, 23), Reduce (16, [TS 42])), ((19, 24), Reduce (16, [TS 42])), ((19, 25), Reduce (16, [TS 42])), ((19, 26), Reduce (16, [TS 42])), ((19, 27), Reduce (16, [TS 42])), ((19, 28), Reduce (16, [TS 42])), ((19, 29), Reduce (16, [TS 42])), ((19, 30), Reduce (16, [TS 42])), ((19, 31), Reduce (16, [TS 42])), ((19, 40), Reduce (16, [TS 42])), ((19, 41), Reduce (16, [TS 42])), ((19, 42), Reduce (16, [TS 42])), ((19, 43), Reduce (16, [TS 42]))
            , ((20, 1), Reduce (16, [TS 28])), ((20, 2), Reduce (16, [TS 28])), ((20, 4), Reduce (16, [TS 28])), ((20, 5), Reduce (16, [TS 28])), ((20, 6), Reduce (16, [TS 28])), ((20, 7), Reduce (16, [TS 28])), ((20, 13), Reduce (16, [TS 28])), ((20, 14), Reduce (16, [TS 28])), ((20, 15), Reduce (16, [TS 28])), ((20, 16), Reduce (16, [TS 28])), ((20, 17), Reduce (16, [TS 28])), ((20, 18), Reduce (16, [TS 28])), ((20, 19), Reduce (16, [TS 28])), ((20, 20), Reduce (16, [TS 28])), ((20, 21), Reduce (16, [TS 28])), ((20, 22), Reduce (16, [TS 28])), ((20, 23), Reduce (16, [TS 28])), ((20, 24), Reduce (16, [TS 28])), ((20, 25), Reduce (16, [TS 28])), ((20, 26), Reduce (16, [TS 28])), ((20, 27), Reduce (16, [TS 28])), ((20, 28), Reduce (16, [TS 28])), ((20, 29), Reduce (16, [TS 28])), ((20, 30), Reduce (16, [TS 28])), ((20, 31), Reduce (16, [TS 28])), ((20, 40), Reduce (16, [TS 28])), ((20, 41), Reduce (16, [TS 28])), ((20, 42), Reduce (16, [TS 28])), ((20, 43), Reduce (16, [TS 28]))
            , ((21, 1), Reduce (16, [TS 31])), ((21, 2), Reduce (16, [TS 31])), ((21, 4), Reduce (16, [TS 31])), ((21, 5), Reduce (16, [TS 31])), ((21, 6), Reduce (16, [TS 31])), ((21, 7), Reduce (16, [TS 31])), ((21, 13), Reduce (16, [TS 31])), ((21, 14), Reduce (16, [TS 31])), ((21, 15), Reduce (16, [TS 31])), ((21, 16), Reduce (16, [TS 31])), ((21, 17), Reduce (16, [TS 31])), ((21, 18), Reduce (16, [TS 31])), ((21, 19), Reduce (16, [TS 31])), ((21, 20), Reduce (16, [TS 31])), ((21, 21), Reduce (16, [TS 31])), ((21, 22), Reduce (16, [TS 31])), ((21, 23), Reduce (16, [TS 31])), ((21, 24), Reduce (16, [TS 31])), ((21, 25), Reduce (16, [TS 31])), ((21, 26), Reduce (16, [TS 31])), ((21, 27), Reduce (16, [TS 31])), ((21, 28), Reduce (16, [TS 31])), ((21, 29), Reduce (16, [TS 31])), ((21, 30), Reduce (16, [TS 31])), ((21, 31), Reduce (16, [TS 31])), ((21, 40), Reduce (16, [TS 31])), ((21, 41), Reduce (16, [TS 31])), ((21, 42), Reduce (16, [TS 31])), ((21, 43), Reduce (16, [TS 31]))
            , ((22, 1), Reduce (16, [TS 30])), ((22, 2), Reduce (16, [TS 30])), ((22, 4), Reduce (16, [TS 30])), ((22, 5), Reduce (16, [TS 30])), ((22, 6), Reduce (16, [TS 30])), ((22, 7), Reduce (16, [TS 30])), ((22, 13), Reduce (16, [TS 30])), ((22, 14), Reduce (16, [TS 30])), ((22, 15), Reduce (16, [TS 30])), ((22, 16), Reduce (16, [TS 30])), ((22, 17), Reduce (16, [TS 30])), ((22, 18), Reduce (16, [TS 30])), ((22, 19), Reduce (16, [TS 30])), ((22, 20), Reduce (16, [TS 30])), ((22, 21), Reduce (16, [TS 30])), ((22, 22), Reduce (16, [TS 30])), ((22, 23), Reduce (16, [TS 30])), ((22, 24), Reduce (16, [TS 30])), ((22, 25), Reduce (16, [TS 30])), ((22, 26), Reduce (16, [TS 30])), ((22, 27), Reduce (16, [TS 30])), ((22, 28), Reduce (16, [TS 30])), ((22, 29), Reduce (16, [TS 30])), ((22, 30), Reduce (16, [TS 30])), ((22, 31), Reduce (16, [TS 30])), ((22, 40), Reduce (16, [TS 30])), ((22, 41), Reduce (16, [TS 30])), ((22, 42), Reduce (16, [TS 30])), ((22, 43), Reduce (16, [TS 30]))
            , ((23, 1), Reduce (16, [TS 40])), ((23, 2), Reduce (16, [TS 40])), ((23, 4), Reduce (16, [TS 40])), ((23, 5), Reduce (16, [TS 40])), ((23, 6), Reduce (16, [TS 40])), ((23, 7), Reduce (16, [TS 40])), ((23, 12), Shift 60), ((23, 13), Reduce (16, [TS 40])), ((23, 14), Reduce (16, [TS 40])), ((23, 15), Reduce (16, [TS 40])), ((23, 16), Reduce (16, [TS 40])), ((23, 17), Reduce (16, [TS 40])), ((23, 18), Reduce (16, [TS 40])), ((23, 19), Reduce (16, [TS 40])), ((23, 20), Reduce (16, [TS 40])), ((23, 21), Reduce (16, [TS 40])), ((23, 22), Reduce (16, [TS 40])), ((23, 23), Reduce (16, [TS 40])), ((23, 24), Reduce (16, [TS 40])), ((23, 25), Reduce (16, [TS 40])), ((23, 26), Reduce (16, [TS 40])), ((23, 27), Reduce (16, [TS 40])), ((23, 28), Reduce (16, [TS 40])), ((23, 29), Reduce (16, [TS 40])), ((23, 30), Reduce (16, [TS 40])), ((23, 31), Reduce (16, [TS 40])), ((23, 40), Reduce (16, [TS 40])), ((23, 41), Reduce (16, [TS 40])), ((23, 42), Reduce (16, [TS 40])), ((23, 43), Reduce (16, [TS 40]))
            , ((24, 40), Shift 61)
            , ((25, 40), Shift 62)
            , ((26, 40), Shift 63)
            , ((27, 40), Shift 64)
            , ((28, 1), Shift 39), ((28, 4), Shift 29), ((28, 6), Shift 28), ((28, 7), Shift 68), ((28, 9), Shift 31), ((28, 10), Shift 34), ((28, 11), Shift 36), ((28, 28), Shift 20), ((28, 29), Shift 37), ((28, 30), Shift 22), ((28, 31), Shift 21), ((28, 40), Shift 67), ((28, 41), Shift 30), ((28, 42), Shift 19), ((28, 43), Shift 35)
            , ((29, 1), Shift 39), ((29, 4), Shift 29), ((29, 6), Shift 28), ((29, 9), Shift 31), ((29, 10), Shift 34), ((29, 11), Shift 36), ((29, 28), Shift 20), ((29, 29), Shift 37), ((29, 30), Shift 22), ((29, 31), Shift 21), ((29, 40), Shift 23), ((29, 41), Shift 30), ((29, 42), Shift 19), ((29, 43), Shift 35)
            , ((30, 1), Reduce (16, [TS 41])), ((30, 2), Reduce (16, [TS 41])), ((30, 4), Reduce (16, [TS 41])), ((30, 5), Reduce (16, [TS 41])), ((30, 6), Reduce (16, [TS 41])), ((30, 7), Reduce (16, [TS 41])), ((30, 13), Reduce (16, [TS 41])), ((30, 14), Reduce (16, [TS 41])), ((30, 15), Reduce (16, [TS 41])), ((30, 16), Reduce (16, [TS 41])), ((30, 17), Reduce (16, [TS 41])), ((30, 18), Reduce (16, [TS 41])), ((30, 19), Reduce (16, [TS 41])), ((30, 20), Reduce (16, [TS 41])), ((30, 21), Reduce (16, [TS 41])), ((30, 22), Reduce (16, [TS 41])), ((30, 23), Reduce (16, [TS 41])), ((30, 24), Reduce (16, [TS 41])), ((30, 25), Reduce (16, [TS 41])), ((30, 26), Reduce (16, [TS 41])), ((30, 27), Reduce (16, [TS 41])), ((30, 28), Reduce (16, [TS 41])), ((30, 29), Reduce (16, [TS 41])), ((30, 30), Reduce (16, [TS 41])), ((30, 31), Reduce (16, [TS 41])), ((30, 40), Reduce (16, [TS 41])), ((30, 41), Reduce (16, [TS 41])), ((30, 42), Reduce (16, [TS 41])), ((30, 43), Reduce (16, [TS 41]))
            , ((31, 1), Reduce (15, [TS 9])), ((31, 2), Reduce (15, [TS 9])), ((31, 4), Reduce (15, [TS 9])), ((31, 5), Reduce (15, [TS 9])), ((31, 6), Reduce (15, [TS 9])), ((31, 7), Reduce (15, [TS 9])), ((31, 13), Reduce (15, [TS 9])), ((31, 14), Reduce (15, [TS 9])), ((31, 15), Reduce (15, [TS 9])), ((31, 16), Reduce (15, [TS 9])), ((31, 17), Reduce (15, [TS 9])), ((31, 18), Reduce (15, [TS 9])), ((31, 19), Reduce (15, [TS 9])), ((31, 20), Reduce (15, [TS 9])), ((31, 21), Reduce (15, [TS 9])), ((31, 22), Reduce (15, [TS 9])), ((31, 23), Reduce (15, [TS 9])), ((31, 24), Reduce (15, [TS 9])), ((31, 25), Reduce (15, [TS 9])), ((31, 26), Reduce (15, [TS 9])), ((31, 27), Reduce (15, [TS 9])), ((31, 28), Reduce (15, [TS 9])), ((31, 29), Reduce (15, [TS 9])), ((31, 30), Reduce (15, [TS 9])), ((31, 31), Reduce (15, [TS 9])), ((31, 40), Reduce (15, [TS 9])), ((31, 41), Reduce (15, [TS 9])), ((31, 42), Reduce (15, [TS 9])), ((31, 43), Reduce (15, [TS 9]))
            , ((32, 40), Shift 70)
            , ((33, 1), Shift 39), ((33, 4), Shift 29), ((33, 6), Shift 28), ((33, 9), Shift 31), ((33, 10), Shift 34), ((33, 11), Shift 36), ((33, 28), Shift 20), ((33, 29), Shift 37), ((33, 30), Shift 22), ((33, 31), Shift 21), ((33, 40), Shift 23), ((33, 41), Shift 30), ((33, 42), Shift 19), ((33, 43), Shift 35)
            , ((34, 1), Reduce (15, [TS 10])), ((34, 2), Reduce (15, [TS 10])), ((34, 4), Reduce (15, [TS 10])), ((34, 5), Reduce (15, [TS 10])), ((34, 6), Reduce (15, [TS 10])), ((34, 7), Reduce (15, [TS 10])), ((34, 13), Reduce (15, [TS 10])), ((34, 14), Reduce (15, [TS 10])), ((34, 15), Reduce (15, [TS 10])), ((34, 16), Reduce (15, [TS 10])), ((34, 17), Reduce (15, [TS 10])), ((34, 18), Reduce (15, [TS 10])), ((34, 19), Reduce (15, [TS 10])), ((34, 20), Reduce (15, [TS 10])), ((34, 21), Reduce (15, [TS 10])), ((34, 22), Reduce (15, [TS 10])), ((34, 23), Reduce (15, [TS 10])), ((34, 24), Reduce (15, [TS 10])), ((34, 25), Reduce (15, [TS 10])), ((34, 26), Reduce (15, [TS 10])), ((34, 27), Reduce (15, [TS 10])), ((34, 28), Reduce (15, [TS 10])), ((34, 29), Reduce (15, [TS 10])), ((34, 30), Reduce (15, [TS 10])), ((34, 31), Reduce (15, [TS 10])), ((34, 40), Reduce (15, [TS 10])), ((34, 41), Reduce (15, [TS 10])), ((34, 42), Reduce (15, [TS 10])), ((34, 43), Reduce (15, [TS 10]))
            , ((35, 1), Reduce (16, [TS 43])), ((35, 2), Reduce (16, [TS 43])), ((35, 4), Reduce (16, [TS 43])), ((35, 5), Reduce (16, [TS 43])), ((35, 6), Reduce (16, [TS 43])), ((35, 7), Reduce (16, [TS 43])), ((35, 13), Reduce (16, [TS 43])), ((35, 14), Reduce (16, [TS 43])), ((35, 15), Reduce (16, [TS 43])), ((35, 16), Reduce (16, [TS 43])), ((35, 17), Reduce (16, [TS 43])), ((35, 18), Reduce (16, [TS 43])), ((35, 19), Reduce (16, [TS 43])), ((35, 20), Reduce (16, [TS 43])), ((35, 21), Reduce (16, [TS 43])), ((35, 22), Reduce (16, [TS 43])), ((35, 23), Reduce (16, [TS 43])), ((35, 24), Reduce (16, [TS 43])), ((35, 25), Reduce (16, [TS 43])), ((35, 26), Reduce (16, [TS 43])), ((35, 27), Reduce (16, [TS 43])), ((35, 28), Reduce (16, [TS 43])), ((35, 29), Reduce (16, [TS 43])), ((35, 30), Reduce (16, [TS 43])), ((35, 31), Reduce (16, [TS 43])), ((35, 40), Reduce (16, [TS 43])), ((35, 41), Reduce (16, [TS 43])), ((35, 42), Reduce (16, [TS 43])), ((35, 43), Reduce (16, [TS 43]))
            , ((36, 1), Reduce (15, [TS 11])), ((36, 2), Reduce (15, [TS 11])), ((36, 4), Reduce (15, [TS 11])), ((36, 5), Reduce (15, [TS 11])), ((36, 6), Reduce (15, [TS 11])), ((36, 7), Reduce (15, [TS 11])), ((36, 13), Reduce (15, [TS 11])), ((36, 14), Reduce (15, [TS 11])), ((36, 15), Reduce (15, [TS 11])), ((36, 16), Reduce (15, [TS 11])), ((36, 17), Reduce (15, [TS 11])), ((36, 18), Reduce (15, [TS 11])), ((36, 19), Reduce (15, [TS 11])), ((36, 20), Reduce (15, [TS 11])), ((36, 21), Reduce (15, [TS 11])), ((36, 22), Reduce (15, [TS 11])), ((36, 23), Reduce (15, [TS 11])), ((36, 24), Reduce (15, [TS 11])), ((36, 25), Reduce (15, [TS 11])), ((36, 26), Reduce (15, [TS 11])), ((36, 27), Reduce (15, [TS 11])), ((36, 28), Reduce (15, [TS 11])), ((36, 29), Reduce (15, [TS 11])), ((36, 30), Reduce (15, [TS 11])), ((36, 31), Reduce (15, [TS 11])), ((36, 40), Reduce (15, [TS 11])), ((36, 41), Reduce (15, [TS 11])), ((36, 42), Reduce (15, [TS 11])), ((36, 43), Reduce (15, [TS 11]))
            , ((37, 1), Reduce (16, [TS 29])), ((37, 2), Reduce (16, [TS 29])), ((37, 4), Reduce (16, [TS 29])), ((37, 5), Reduce (16, [TS 29])), ((37, 6), Reduce (16, [TS 29])), ((37, 7), Reduce (16, [TS 29])), ((37, 13), Reduce (16, [TS 29])), ((37, 14), Reduce (16, [TS 29])), ((37, 15), Reduce (16, [TS 29])), ((37, 16), Reduce (16, [TS 29])), ((37, 17), Reduce (16, [TS 29])), ((37, 18), Reduce (16, [TS 29])), ((37, 19), Reduce (16, [TS 29])), ((37, 20), Reduce (16, [TS 29])), ((37, 21), Reduce (16, [TS 29])), ((37, 22), Reduce (16, [TS 29])), ((37, 23), Reduce (16, [TS 29])), ((37, 24), Reduce (16, [TS 29])), ((37, 25), Reduce (16, [TS 29])), ((37, 26), Reduce (16, [TS 29])), ((37, 27), Reduce (16, [TS 29])), ((37, 28), Reduce (16, [TS 29])), ((37, 29), Reduce (16, [TS 29])), ((37, 30), Reduce (16, [TS 29])), ((37, 31), Reduce (16, [TS 29])), ((37, 40), Reduce (16, [TS 29])), ((37, 41), Reduce (16, [TS 29])), ((37, 42), Reduce (16, [TS 29])), ((37, 43), Reduce (16, [TS 29]))
            , ((38, 40), Shift 72)
            , ((39, 1), Reduce (16, [TS 1])), ((39, 2), Reduce (16, [TS 1])), ((39, 4), Reduce (16, [TS 1])), ((39, 5), Reduce (16, [TS 1])), ((39, 6), Reduce (16, [TS 1])), ((39, 7), Reduce (16, [TS 1])), ((39, 13), Reduce (16, [TS 1])), ((39, 14), Reduce (16, [TS 1])), ((39, 15), Reduce (16, [TS 1])), ((39, 16), Reduce (16, [TS 1])), ((39, 17), Reduce (16, [TS 1])), ((39, 18), Reduce (16, [TS 1])), ((39, 19), Reduce (16, [TS 1])), ((39, 20), Reduce (16, [TS 1])), ((39, 21), Reduce (16, [TS 1])), ((39, 22), Reduce (16, [TS 1])), ((39, 23), Reduce (16, [TS 1])), ((39, 24), Reduce (16, [TS 1])), ((39, 25), Reduce (16, [TS 1])), ((39, 26), Reduce (16, [TS 1])), ((39, 27), Reduce (16, [TS 1])), ((39, 28), Reduce (16, [TS 1])), ((39, 29), Reduce (16, [TS 1])), ((39, 30), Reduce (16, [TS 1])), ((39, 31), Reduce (16, [TS 1])), ((39, 40), Reduce (16, [TS 1])), ((39, 41), Reduce (16, [TS 1])), ((39, 42), Reduce (16, [TS 1])), ((39, 43), Reduce (16, [TS 1]))
            , ((40, 0), Reduce (18, [NS 19, NS 18]))
            , ((41, 0), Reduce (19, [NS 3, TS 2])), ((41, 1), Reduce (19, [NS 3, TS 2])), ((41, 4), Reduce (19, [NS 3, TS 2])), ((41, 6), Reduce (19, [NS 3, TS 2])), ((41, 9), Reduce (19, [NS 3, TS 2])), ((41, 10), Reduce (19, [NS 3, TS 2])), ((41, 11), Reduce (19, [NS 3, TS 2])), ((41, 28), Reduce (19, [NS 3, TS 2])), ((41, 29), Reduce (19, [NS 3, TS 2])), ((41, 30), Reduce (19, [NS 3, TS 2])), ((41, 31), Reduce (19, [NS 3, TS 2])), ((41, 32), Reduce (19, [NS 3, TS 2])), ((41, 33), Reduce (19, [NS 3, TS 2])), ((41, 34), Reduce (19, [NS 3, TS 2])), ((41, 35), Reduce (19, [NS 3, TS 2])), ((41, 36), Reduce (19, [NS 3, TS 2])), ((41, 37), Reduce (19, [NS 3, TS 2])), ((41, 40), Reduce (19, [NS 3, TS 2])), ((41, 41), Reduce (19, [NS 3, TS 2])), ((41, 42), Reduce (19, [NS 3, TS 2])), ((41, 43), Reduce (19, [NS 3, TS 2]))
            , ((42, 1), Shift 39), ((42, 4), Shift 29), ((42, 6), Shift 28), ((42, 9), Shift 31), ((42, 10), Shift 34), ((42, 11), Shift 36), ((42, 28), Shift 20), ((42, 29), Shift 37), ((42, 30), Shift 22), ((42, 31), Shift 21), ((42, 40), Shift 67), ((42, 41), Shift 30), ((42, 42), Shift 19), ((42, 43), Shift 35)
            , ((43, 1), Shift 39), ((43, 4), Shift 29), ((43, 6), Shift 28), ((43, 9), Shift 31), ((43, 10), Shift 34), ((43, 11), Shift 36), ((43, 28), Shift 20), ((43, 29), Shift 37), ((43, 30), Shift 22), ((43, 31), Shift 21), ((43, 40), Shift 67), ((43, 41), Shift 30), ((43, 42), Shift 19), ((43, 43), Shift 35)
            , ((44, 1), Shift 39), ((44, 4), Shift 29), ((44, 6), Shift 28), ((44, 9), Shift 31), ((44, 10), Shift 34), ((44, 11), Shift 36), ((44, 28), Shift 20), ((44, 29), Shift 37), ((44, 30), Shift 22), ((44, 31), Shift 21), ((44, 40), Shift 67), ((44, 41), Shift 30), ((44, 42), Shift 19), ((44, 43), Shift 35)
            , ((45, 1), Shift 39), ((45, 4), Shift 29), ((45, 6), Shift 28), ((45, 9), Shift 31), ((45, 10), Shift 34), ((45, 11), Shift 36), ((45, 28), Shift 20), ((45, 29), Shift 37), ((45, 30), Shift 22), ((45, 31), Shift 21), ((45, 40), Shift 67), ((45, 41), Shift 30), ((45, 42), Shift 19), ((45, 43), Shift 35)
            , ((46, 1), Shift 39), ((46, 4), Shift 29), ((46, 6), Shift 28), ((46, 9), Shift 31), ((46, 10), Shift 34), ((46, 11), Shift 36), ((46, 28), Shift 20), ((46, 29), Shift 37), ((46, 30), Shift 22), ((46, 31), Shift 21), ((46, 40), Shift 67), ((46, 41), Shift 30), ((46, 42), Shift 19), ((46, 43), Shift 35)
            , ((47, 1), Shift 39), ((47, 4), Shift 29), ((47, 6), Shift 28), ((47, 9), Shift 31), ((47, 10), Shift 34), ((47, 11), Shift 36), ((47, 28), Shift 20), ((47, 29), Shift 37), ((47, 30), Shift 22), ((47, 31), Shift 21), ((47, 40), Shift 67), ((47, 41), Shift 30), ((47, 42), Shift 19), ((47, 43), Shift 35)
            , ((48, 1), Shift 39), ((48, 4), Shift 29), ((48, 6), Shift 28), ((48, 9), Shift 31), ((48, 10), Shift 34), ((48, 11), Shift 36), ((48, 28), Shift 20), ((48, 29), Shift 37), ((48, 30), Shift 22), ((48, 31), Shift 21), ((48, 40), Shift 67), ((48, 41), Shift 30), ((48, 42), Shift 19), ((48, 43), Shift 35)
            , ((49, 1), Shift 39), ((49, 4), Shift 29), ((49, 6), Shift 28), ((49, 9), Shift 31), ((49, 10), Shift 34), ((49, 11), Shift 36), ((49, 28), Shift 20), ((49, 29), Shift 37), ((49, 30), Shift 22), ((49, 31), Shift 21), ((49, 40), Shift 67), ((49, 41), Shift 30), ((49, 42), Shift 19), ((49, 43), Shift 35)
            , ((50, 1), Shift 39), ((50, 4), Shift 29), ((50, 6), Shift 28), ((50, 9), Shift 31), ((50, 10), Shift 34), ((50, 11), Shift 36), ((50, 28), Shift 20), ((50, 29), Shift 37), ((50, 30), Shift 22), ((50, 31), Shift 21), ((50, 40), Shift 67), ((50, 41), Shift 30), ((50, 42), Shift 19), ((50, 43), Shift 35)
            , ((51, 1), Shift 39), ((51, 4), Shift 29), ((51, 6), Shift 28), ((51, 9), Shift 31), ((51, 10), Shift 34), ((51, 11), Shift 36), ((51, 28), Shift 20), ((51, 29), Shift 37), ((51, 30), Shift 22), ((51, 31), Shift 21), ((51, 40), Shift 67), ((51, 41), Shift 30), ((51, 42), Shift 19), ((51, 43), Shift 35)
            , ((52, 1), Shift 39), ((52, 4), Shift 29), ((52, 6), Shift 28), ((52, 9), Shift 31), ((52, 10), Shift 34), ((52, 11), Shift 36), ((52, 28), Shift 20), ((52, 29), Shift 37), ((52, 30), Shift 22), ((52, 31), Shift 21), ((52, 40), Shift 67), ((52, 41), Shift 30), ((52, 42), Shift 19), ((52, 43), Shift 35)
            , ((53, 1), Shift 39), ((53, 4), Shift 29), ((53, 6), Shift 28), ((53, 9), Shift 31), ((53, 10), Shift 34), ((53, 11), Shift 36), ((53, 28), Shift 20), ((53, 29), Shift 37), ((53, 30), Shift 22), ((53, 31), Shift 21), ((53, 40), Shift 67), ((53, 41), Shift 30), ((53, 42), Shift 19), ((53, 43), Shift 35)
            , ((54, 1), Shift 39), ((54, 4), Shift 29), ((54, 6), Shift 28), ((54, 9), Shift 31), ((54, 10), Shift 34), ((54, 11), Shift 36), ((54, 28), Shift 20), ((54, 29), Shift 37), ((54, 30), Shift 22), ((54, 31), Shift 21), ((54, 40), Shift 67), ((54, 41), Shift 30), ((54, 42), Shift 19), ((54, 43), Shift 35)
            , ((55, 1), Shift 39), ((55, 4), Shift 29), ((55, 6), Shift 28), ((55, 9), Shift 31), ((55, 10), Shift 34), ((55, 11), Shift 36), ((55, 28), Shift 20), ((55, 29), Shift 37), ((55, 30), Shift 22), ((55, 31), Shift 21), ((55, 40), Shift 67), ((55, 41), Shift 30), ((55, 42), Shift 19), ((55, 43), Shift 35)
            , ((56, 1), Shift 39), ((56, 4), Shift 29), ((56, 6), Shift 28), ((56, 9), Shift 31), ((56, 10), Shift 34), ((56, 11), Shift 36), ((56, 28), Shift 20), ((56, 29), Shift 37), ((56, 30), Shift 22), ((56, 31), Shift 21), ((56, 40), Shift 67), ((56, 41), Shift 30), ((56, 42), Shift 19), ((56, 43), Shift 35)
            , ((57, 1), Reduce (15, [NS 15, NS 16])), ((57, 2), Reduce (15, [NS 15, NS 16])), ((57, 4), Reduce (15, [NS 15, NS 16])), ((57, 5), Reduce (15, [NS 15, NS 16])), ((57, 6), Reduce (15, [NS 15, NS 16])), ((57, 7), Reduce (15, [NS 15, NS 16])), ((57, 13), Reduce (15, [NS 15, NS 16])), ((57, 14), Reduce (15, [NS 15, NS 16])), ((57, 15), Reduce (15, [NS 15, NS 16])), ((57, 16), Reduce (15, [NS 15, NS 16])), ((57, 17), Reduce (15, [NS 15, NS 16])), ((57, 18), Reduce (15, [NS 15, NS 16])), ((57, 19), Reduce (15, [NS 15, NS 16])), ((57, 20), Reduce (15, [NS 15, NS 16])), ((57, 21), Reduce (15, [NS 15, NS 16])), ((57, 22), Reduce (15, [NS 15, NS 16])), ((57, 23), Reduce (15, [NS 15, NS 16])), ((57, 24), Reduce (15, [NS 15, NS 16])), ((57, 25), Reduce (15, [NS 15, NS 16])), ((57, 26), Reduce (15, [NS 15, NS 16])), ((57, 27), Reduce (15, [NS 15, NS 16])), ((57, 28), Reduce (15, [NS 15, NS 16])), ((57, 29), Reduce (15, [NS 15, NS 16])), ((57, 30), Reduce (15, [NS 15, NS 16])), ((57, 31), Reduce (15, [NS 15, NS 16])), ((57, 40), Reduce (15, [NS 15, NS 16])), ((57, 41), Reduce (15, [NS 15, NS 16])), ((57, 42), Reduce (15, [NS 15, NS 16])), ((57, 43), Reduce (15, [NS 15, NS 16]))
            , ((58, 1), Reduce (16, [TS 40])), ((58, 2), Reduce (16, [TS 40])), ((58, 4), Reduce (16, [TS 40])), ((58, 5), Reduce (16, [TS 40])), ((58, 6), Reduce (16, [TS 40])), ((58, 7), Reduce (16, [TS 40])), ((58, 12), Shift 88), ((58, 13), Reduce (16, [TS 40])), ((58, 14), Reduce (16, [TS 40])), ((58, 15), Reduce (16, [TS 40])), ((58, 16), Reduce (16, [TS 40])), ((58, 17), Reduce (16, [TS 40])), ((58, 18), Reduce (16, [TS 40])), ((58, 19), Reduce (16, [TS 40])), ((58, 20), Reduce (16, [TS 40])), ((58, 21), Reduce (16, [TS 40])), ((58, 22), Reduce (16, [TS 40])), ((58, 23), Reduce (16, [TS 40])), ((58, 24), Reduce (16, [TS 40])), ((58, 25), Reduce (16, [TS 40])), ((58, 26), Reduce (16, [TS 40])), ((58, 27), Reduce (16, [TS 40])), ((58, 28), Reduce (16, [TS 40])), ((58, 29), Reduce (16, [TS 40])), ((58, 30), Reduce (16, [TS 40])), ((58, 31), Reduce (16, [TS 40])), ((58, 40), Reduce (16, [TS 40])), ((58, 41), Reduce (16, [TS 40])), ((58, 42), Reduce (16, [TS 40])), ((58, 43), Reduce (16, [TS 40]))
            , ((60, 1), Shift 39), ((60, 4), Shift 29), ((60, 6), Shift 28), ((60, 9), Shift 31), ((60, 10), Shift 34), ((60, 11), Shift 36), ((60, 28), Shift 20), ((60, 29), Shift 37), ((60, 30), Shift 22), ((60, 31), Shift 21), ((60, 40), Shift 23), ((60, 41), Shift 30), ((60, 42), Shift 19), ((60, 43), Shift 35)
            , ((61, 41), Shift 90)
            , ((62, 41), Shift 91)
            , ((63, 41), Shift 92)
            , ((64, 4), Shift 95), ((64, 33), Shift 96)
            , ((65, 7), Shift 97)
            , ((66, 7), Reduce (17, [NS 9])), ((66, 16), Shift 98)
            , ((67, 1), Reduce (16, [TS 40])), ((67, 2), Reduce (16, [TS 40])), ((67, 4), Reduce (16, [TS 40])), ((67, 5), Reduce (16, [TS 40])), ((67, 6), Reduce (16, [TS 40])), ((67, 7), Reduce (16, [TS 40])), ((67, 13), Reduce (16, [TS 40])), ((67, 14), Reduce (16, [TS 40])), ((67, 15), Reduce (16, [TS 40])), ((67, 16), Reduce (16, [TS 40])), ((67, 17), Reduce (16, [TS 40])), ((67, 18), Reduce (16, [TS 40])), ((67, 19), Reduce (16, [TS 40])), ((67, 20), Reduce (16, [TS 40])), ((67, 21), Reduce (16, [TS 40])), ((67, 22), Reduce (16, [TS 40])), ((67, 23), Reduce (16, [TS 40])), ((67, 24), Reduce (16, [TS 40])), ((67, 25), Reduce (16, [TS 40])), ((67, 26), Reduce (16, [TS 40])), ((67, 27), Reduce (16, [TS 40])), ((67, 28), Reduce (16, [TS 40])), ((67, 29), Reduce (16, [TS 40])), ((67, 30), Reduce (16, [TS 40])), ((67, 31), Reduce (16, [TS 40])), ((67, 40), Reduce (16, [TS 40])), ((67, 41), Reduce (16, [TS 40])), ((67, 42), Reduce (16, [TS 40])), ((67, 43), Reduce (16, [TS 40]))
            , ((68, 1), Reduce (16, [TS 6, TS 7])), ((68, 2), Reduce (16, [TS 6, TS 7])), ((68, 4), Reduce (16, [TS 6, TS 7])), ((68, 5), Reduce (16, [TS 6, TS 7])), ((68, 6), Reduce (16, [TS 6, TS 7])), ((68, 7), Reduce (16, [TS 6, TS 7])), ((68, 13), Reduce (16, [TS 6, TS 7])), ((68, 14), Reduce (16, [TS 6, TS 7])), ((68, 15), Reduce (16, [TS 6, TS 7])), ((68, 16), Reduce (16, [TS 6, TS 7])), ((68, 17), Reduce (16, [TS 6, TS 7])), ((68, 18), Reduce (16, [TS 6, TS 7])), ((68, 19), Reduce (16, [TS 6, TS 7])), ((68, 20), Reduce (16, [TS 6, TS 7])), ((68, 21), Reduce (16, [TS 6, TS 7])), ((68, 22), Reduce (16, [TS 6, TS 7])), ((68, 23), Reduce (16, [TS 6, TS 7])), ((68, 24), Reduce (16, [TS 6, TS 7])), ((68, 25), Reduce (16, [TS 6, TS 7])), ((68, 26), Reduce (16, [TS 6, TS 7])), ((68, 27), Reduce (16, [TS 6, TS 7])), ((68, 28), Reduce (16, [TS 6, TS 7])), ((68, 29), Reduce (16, [TS 6, TS 7])), ((68, 30), Reduce (16, [TS 6, TS 7])), ((68, 31), Reduce (16, [TS 6, TS 7])), ((68, 40), Reduce (16, [TS 6, TS 7])), ((68, 41), Reduce (16, [TS 6, TS 7])), ((68, 42), Reduce (16, [TS 6, TS 7])), ((68, 43), Reduce (16, [TS 6, TS 7]))
            , ((69, 5), Shift 99)
            , ((70, 41), Shift 100)
            , ((71, 2), Shift 101)
            , ((72, 4), Shift 106), ((72, 40), Shift 105)
            , ((73, 2), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 5), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 7), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 13), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 14), Shift 43), ((73, 15), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 16), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 17), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 18), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 19), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 20), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 21), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 22), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 23), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 24), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 25), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 26), Reduce (4, [NS 5, TS 13, NS 5])), ((73, 27), Reduce (4, [NS 5, TS 13, NS 5]))
            , ((74, 2), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 5), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 7), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 13), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 14), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 15), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 16), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 17), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 18), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 19), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 20), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 21), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 22), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 23), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 24), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 25), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 26), Reduce (5, [NS 5, TS 14, NS 6])), ((74, 27), Reduce (5, [NS 5, TS 14, NS 6]))
            , ((75, 2), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 5), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 7), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 13), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 14), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 15), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 16), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 17), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 18), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 19), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 20), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 21), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 22), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 23), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 24), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 25), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 26), Reduce (7, [NS 7, TS 16, NS 8])), ((75, 27), Reduce (7, [NS 7, TS 16, NS 8]))
            , ((76, 2), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 5), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 7), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 13), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 14), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 15), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 16), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 17), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 18), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 19), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 20), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 21), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 22), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 23), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 24), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 25), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 26), Reduce (6, [NS 7, TS 15, NS 6])), ((76, 27), Reduce (6, [NS 7, TS 15, NS 6]))
            , ((77, 2), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 5), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 7), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 13), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 14), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 15), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 16), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 17), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 18), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 19), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 20), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 21), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 22), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 23), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 24), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 25), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 26), Reduce (8, [NS 9, TS 17, NS 9])), ((77, 27), Reduce (8, [NS 9, TS 17, NS 9]))
            , ((78, 2), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 5), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 7), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 13), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 14), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 15), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 16), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 17), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 18), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 19), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 20), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 21), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 22), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 23), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 24), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 25), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 26), Reduce (8, [NS 9, TS 20, NS 9])), ((78, 27), Reduce (8, [NS 9, TS 20, NS 9]))
            , ((79, 2), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 5), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 7), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 13), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 14), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 15), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 16), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 17), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 18), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 19), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 20), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 21), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 22), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 23), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 24), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 25), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 26), Reduce (8, [NS 9, TS 21, NS 9])), ((79, 27), Reduce (8, [NS 9, TS 21, NS 9]))
            , ((80, 2), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 5), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 7), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 13), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 14), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 15), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 16), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 17), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 18), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 19), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 20), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 21), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 22), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 23), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 24), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 25), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 26), Reduce (8, [NS 9, TS 22, NS 9])), ((80, 27), Reduce (8, [NS 9, TS 22, NS 9]))
            , ((81, 2), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 5), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 7), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 13), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 14), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 15), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 16), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 17), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 18), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 19), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 20), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 21), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 22), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 23), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 24), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 25), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 26), Reduce (8, [NS 9, TS 18, NS 9])), ((81, 27), Reduce (8, [NS 9, TS 18, NS 9]))
            , ((82, 2), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 5), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 7), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 13), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 14), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 15), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 16), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 17), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 18), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 19), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 20), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 21), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 22), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 23), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 24), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 25), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 26), Reduce (8, [NS 9, TS 19, NS 9])), ((82, 27), Reduce (8, [NS 9, TS 19, NS 9]))
            , ((83, 2), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 5), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 7), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 13), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 14), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 15), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 16), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 17), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 18), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 19), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 20), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 21), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 22), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 23), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 24), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 25), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 26), Reduce (9, [NS 10, TS 23, NS 9])), ((83, 27), Reduce (9, [NS 10, TS 23, NS 9]))
            , ((84, 2), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 5), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 7), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 13), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 14), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 15), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 16), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 17), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 18), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 19), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 20), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 21), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 22), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 23), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 24), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 25), Reduce (10, [NS 10, TS 25, NS 11])), ((84, 26), Shift 56), ((84, 27), Shift 55)
            , ((85, 2), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 5), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 7), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 13), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 14), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 15), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 16), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 17), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 18), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 19), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 20), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 21), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 22), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 23), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 24), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 25), Reduce (10, [NS 10, TS 24, NS 11])), ((85, 26), Shift 56), ((85, 27), Shift 55)
            , ((86, 2), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 5), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 7), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 13), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 14), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 15), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 16), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 17), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 18), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 19), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 20), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 21), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 22), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 23), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 24), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 25), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 26), Reduce (11, [NS 11, TS 27, NS 12])), ((86, 27), Reduce (11, [NS 11, TS 27, NS 12]))
            , ((87, 2), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 5), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 7), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 13), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 14), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 15), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 16), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 17), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 18), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 19), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 20), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 21), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 22), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 23), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 24), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 25), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 26), Reduce (11, [NS 11, TS 26, NS 12])), ((87, 27), Reduce (11, [NS 11, TS 26, NS 12]))
            , ((88, 1), Shift 39), ((88, 4), Shift 29), ((88, 6), Shift 28), ((88, 9), Shift 31), ((88, 10), Shift 34), ((88, 11), Shift 36), ((88, 28), Shift 20), ((88, 29), Shift 37), ((88, 30), Shift 22), ((88, 31), Shift 21), ((88, 40), Shift 23), ((88, 41), Shift 30), ((88, 42), Shift 19), ((88, 43), Shift 35)
            , ((89, 2), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 5), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 7), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 13), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 14), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 15), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 16), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 17), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 18), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 19), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 20), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 21), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 22), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 23), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 24), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 25), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 26), Reduce (3, [TS 40, TS 12, NS 3])), ((89, 27), Reduce (3, [TS 40, TS 12, NS 3]))
            , ((90, 2), Shift 108)
            , ((91, 2), Shift 109)
            , ((92, 2), Shift 110)
            , ((93, 2), Shift 111)
            , ((94, 2), Reduce (20, [NS 21])), ((94, 3), Shift 112), ((94, 5), Reduce (20, [NS 21]))
            , ((95, 4), Shift 95), ((95, 33), Shift 96)
            , ((96, 2), Reduce (21, [TS 33])), ((96, 3), Reduce (21, [TS 33])), ((96, 5), Reduce (21, [TS 33]))
            , ((97, 1), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 2), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 4), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 5), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 6), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 7), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 13), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 14), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 15), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 16), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 17), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 18), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 19), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 20), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 21), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 22), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 23), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 24), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 25), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 26), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 27), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 28), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 29), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 30), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 31), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 40), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 41), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 42), Reduce (16, [TS 6, NS 17, TS 7])), ((97, 43), Reduce (16, [TS 6, NS 17, TS 7]))
            , ((98, 1), Shift 39), ((98, 4), Shift 29), ((98, 6), Shift 28), ((98, 9), Shift 31), ((98, 10), Shift 34), ((98, 11), Shift 36), ((98, 28), Shift 20), ((98, 29), Shift 37), ((98, 30), Shift 22), ((98, 31), Shift 21), ((98, 40), Shift 67), ((98, 41), Shift 30), ((98, 42), Shift 19), ((98, 43), Shift 35)
            , ((99, 1), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 2), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 4), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 5), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 6), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 7), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 13), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 14), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 15), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 16), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 17), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 18), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 19), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 20), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 21), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 22), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 23), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 24), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 25), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 26), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 27), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 28), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 29), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 30), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 31), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 40), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 41), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 42), Reduce (16, [TS 4, NS 3, TS 5])), ((99, 43), Reduce (16, [TS 4, NS 3, TS 5]))
            , ((100, 2), Shift 115)
            , ((101, 0), Reduce (2, [TS 8, NS 3, TS 2]))
            , ((102, 2), Shift 116)
            , ((103, 2), Reduce (22, [NS 23])), ((103, 3), Shift 118), ((103, 4), Shift 106), ((103, 5), Reduce (22, [NS 23])), ((103, 40), Shift 105)
            , ((104, 2), Reduce (23, [NS 24])), ((104, 3), Reduce (23, [NS 24])), ((104, 4), Reduce (23, [NS 24])), ((104, 5), Reduce (23, [NS 24])), ((104, 40), Reduce (23, [NS 24]))
            , ((105, 2), Reduce (24, [TS 40])), ((105, 3), Reduce (24, [TS 40])), ((105, 4), Reduce (24, [TS 40])), ((105, 5), Reduce (24, [TS 40])), ((105, 40), Reduce (24, [TS 40]))
            , ((106, 4), Shift 106), ((106, 40), Shift 105)
            , ((107, 2), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 5), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 7), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 13), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 14), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 15), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 16), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 17), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 18), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 19), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 20), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 21), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 22), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 23), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 24), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 25), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 26), Reduce (14, [NS 15, TS 40, TS 12, NS 3])), ((107, 27), Reduce (14, [NS 15, TS 40, TS 12, NS 3]))
            , ((108, 0), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 1), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 4), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 6), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 9), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 10), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 11), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 28), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 29), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 30), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 31), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 32), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 33), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 34), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 35), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 36), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 37), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 40), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 41), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 42), Reduce (19, [TS 36, TS 40, TS 41, TS 2])), ((108, 43), Reduce (19, [TS 36, TS 40, TS 41, TS 2]))
            , ((109, 0), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 1), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 4), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 6), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 9), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 10), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 11), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 28), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 29), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 30), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 31), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 32), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 33), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 34), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 35), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 36), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 37), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 40), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 41), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 42), Reduce (19, [TS 34, TS 40, TS 41, TS 2])), ((109, 43), Reduce (19, [TS 34, TS 40, TS 41, TS 2]))
            , ((110, 0), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 1), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 4), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 6), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 9), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 10), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 11), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 28), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 29), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 30), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 31), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 32), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 33), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 34), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 35), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 36), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 37), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 40), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 41), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 42), Reduce (19, [TS 35, TS 40, TS 41, TS 2])), ((110, 43), Reduce (19, [TS 35, TS 40, TS 41, TS 2]))
            , ((111, 0), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 1), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 4), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 6), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 9), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 10), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 11), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 28), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 29), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 30), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 31), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 32), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 33), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 34), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 35), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 36), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 37), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 40), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 41), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 42), Reduce (19, [TS 32, TS 40, NS 20, TS 2])), ((111, 43), Reduce (19, [TS 32, TS 40, NS 20, TS 2]))
            , ((112, 4), Shift 95), ((112, 33), Shift 96)
            , ((113, 5), Shift 121)
            , ((114, 7), Reduce (17, [NS 9, TS 16, NS 17]))
            , ((115, 0), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 1), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 4), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 6), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 9), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 10), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 11), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 28), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 29), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 30), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 31), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 32), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 33), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 34), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 35), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 36), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 37), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 40), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 41), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 42), Reduce (19, [TS 37, TS 40, TS 41, TS 2])), ((115, 43), Reduce (19, [TS 37, TS 40, TS 41, TS 2]))
            , ((116, 0), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 1), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 4), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 6), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 9), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 10), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 11), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 28), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 29), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 30), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 31), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 32), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 33), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 34), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 35), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 36), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 37), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 40), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 41), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 42), Reduce (19, [TS 33, TS 40, NS 22, TS 2])), ((116, 43), Reduce (19, [TS 33, TS 40, NS 22, TS 2]))
            , ((117, 2), Reduce (23, [NS 23, NS 24])), ((117, 3), Reduce (23, [NS 23, NS 24])), ((117, 4), Reduce (23, [NS 23, NS 24])), ((117, 5), Reduce (23, [NS 23, NS 24])), ((117, 40), Reduce (23, [NS 23, NS 24]))
            , ((118, 4), Shift 106), ((118, 40), Shift 105)
            , ((119, 5), Shift 123)
            , ((120, 2), Reduce (20, [NS 21, TS 3, NS 20])), ((120, 5), Reduce (20, [NS 21, TS 3, NS 20]))
            , ((121, 2), Reduce (21, [TS 4, NS 20, TS 5])), ((121, 3), Reduce (21, [TS 4, NS 20, TS 5])), ((121, 5), Reduce (21, [TS 4, NS 20, TS 5]))
            , ((122, 2), Reduce (22, [NS 23, TS 3, NS 22])), ((122, 5), Reduce (22, [NS 23, TS 3, NS 22]))
            , ((123, 2), Reduce (24, [TS 4, NS 22, TS 5])), ((123, 3), Reduce (24, [TS 4, NS 22, TS 5])), ((123, 4), Reduce (24, [TS 4, NS 22, TS 5])), ((123, 5), Reduce (24, [TS 4, NS 22, TS 5])), ((123, 40), Reduce (24, [TS 4, NS 22, TS 5]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 18), ((0, 2), 2), ((0, 3), 3), ((0, 4), 4), ((0, 5), 5), ((0, 6), 6), ((0, 7), 7), ((0, 8), 8), ((0, 9), 9), ((0, 10), 10), ((0, 11), 11), ((0, 12), 12), ((0, 13), 13), ((0, 14), 14), ((0, 15), 15), ((0, 16), 16), ((0, 18), 17), ((0, 19), 1)
            , ((1, 3), 3), ((1, 4), 4), ((1, 5), 5), ((1, 6), 6), ((1, 7), 7), ((1, 8), 8), ((1, 9), 9), ((1, 10), 10), ((1, 11), 11), ((1, 12), 12), ((1, 13), 13), ((1, 14), 14), ((1, 15), 15), ((1, 16), 16), ((1, 18), 40), ((1, 19), 1)
            , ((15, 16), 57)
            , ((28, 9), 66), ((28, 10), 10), ((28, 11), 11), ((28, 12), 12), ((28, 13), 13), ((28, 14), 14), ((28, 15), 15), ((28, 16), 16), ((28, 17), 65)
            , ((29, 3), 69), ((29, 4), 4), ((29, 5), 5), ((29, 6), 6), ((29, 7), 7), ((29, 8), 8), ((29, 9), 9), ((29, 10), 10), ((29, 11), 11), ((29, 12), 12), ((29, 13), 13), ((29, 14), 14), ((29, 15), 15), ((29, 16), 16)
            , ((33, 3), 71), ((33, 4), 4), ((33, 5), 5), ((33, 6), 6), ((33, 7), 7), ((33, 8), 8), ((33, 9), 9), ((33, 10), 10), ((33, 11), 11), ((33, 12), 12), ((33, 13), 13), ((33, 14), 14), ((33, 15), 15), ((33, 16), 16)
            , ((42, 5), 73), ((42, 6), 6), ((42, 7), 7), ((42, 8), 8), ((42, 9), 9), ((42, 10), 10), ((42, 11), 11), ((42, 12), 12), ((42, 13), 13), ((42, 14), 14), ((42, 15), 15), ((42, 16), 16)
            , ((43, 6), 74), ((43, 7), 7), ((43, 8), 8), ((43, 9), 9), ((43, 10), 10), ((43, 11), 11), ((43, 12), 12), ((43, 13), 13), ((43, 14), 14), ((43, 15), 15), ((43, 16), 16)
            , ((44, 8), 75), ((44, 9), 9), ((44, 10), 10), ((44, 11), 11), ((44, 12), 12), ((44, 13), 13), ((44, 14), 14), ((44, 15), 15), ((44, 16), 16)
            , ((45, 6), 76), ((45, 7), 7), ((45, 8), 8), ((45, 9), 9), ((45, 10), 10), ((45, 11), 11), ((45, 12), 12), ((45, 13), 13), ((45, 14), 14), ((45, 15), 15), ((45, 16), 16)
            , ((46, 9), 77), ((46, 10), 10), ((46, 11), 11), ((46, 12), 12), ((46, 13), 13), ((46, 14), 14), ((46, 15), 15), ((46, 16), 16)
            , ((47, 9), 78), ((47, 10), 10), ((47, 11), 11), ((47, 12), 12), ((47, 13), 13), ((47, 14), 14), ((47, 15), 15), ((47, 16), 16)
            , ((48, 9), 79), ((48, 10), 10), ((48, 11), 11), ((48, 12), 12), ((48, 13), 13), ((48, 14), 14), ((48, 15), 15), ((48, 16), 16)
            , ((49, 9), 80), ((49, 10), 10), ((49, 11), 11), ((49, 12), 12), ((49, 13), 13), ((49, 14), 14), ((49, 15), 15), ((49, 16), 16)
            , ((50, 9), 81), ((50, 10), 10), ((50, 11), 11), ((50, 12), 12), ((50, 13), 13), ((50, 14), 14), ((50, 15), 15), ((50, 16), 16)
            , ((51, 9), 82), ((51, 10), 10), ((51, 11), 11), ((51, 12), 12), ((51, 13), 13), ((51, 14), 14), ((51, 15), 15), ((51, 16), 16)
            , ((52, 9), 83), ((52, 10), 10), ((52, 11), 11), ((52, 12), 12), ((52, 13), 13), ((52, 14), 14), ((52, 15), 15), ((52, 16), 16)
            , ((53, 11), 84), ((53, 12), 12), ((53, 13), 13), ((53, 14), 14), ((53, 15), 15), ((53, 16), 16)
            , ((54, 11), 85), ((54, 12), 12), ((54, 13), 13), ((54, 14), 14), ((54, 15), 15), ((54, 16), 16)
            , ((55, 12), 86), ((55, 13), 13), ((55, 14), 14), ((55, 15), 15), ((55, 16), 16)
            , ((56, 12), 87), ((56, 13), 13), ((56, 14), 14), ((56, 15), 15), ((56, 16), 16)
            , ((60, 3), 89), ((60, 4), 4), ((60, 5), 5), ((60, 6), 6), ((60, 7), 7), ((60, 8), 8), ((60, 9), 9), ((60, 10), 10), ((60, 11), 11), ((60, 12), 12), ((60, 13), 13), ((60, 14), 14), ((60, 15), 15), ((60, 16), 16)
            , ((64, 20), 93), ((64, 21), 94)
            , ((72, 22), 102), ((72, 23), 103), ((72, 24), 104)
            , ((88, 3), 107), ((88, 4), 4), ((88, 5), 5), ((88, 6), 6), ((88, 7), 7), ((88, 8), 8), ((88, 9), 9), ((88, 10), 10), ((88, 11), 11), ((88, 12), 12), ((88, 13), 13), ((88, 14), 14), ((88, 15), 15), ((88, 16), 16)
            , ((95, 20), 113), ((95, 21), 94)
            , ((98, 9), 66), ((98, 10), 10), ((98, 11), 11), ((98, 12), 12), ((98, 13), 13), ((98, 14), 14), ((98, 15), 15), ((98, 16), 16), ((98, 17), 114)
            , ((103, 24), 117)
            , ((106, 22), 119), ((106, 23), 103), ((106, 24), 104)
            , ((112, 20), 120), ((112, 21), 94)
            , ((118, 22), 122), ((118, 23), 103), ((118, 24), 104)
            ]
        }
