module Json.JsonLexer where
import Data.Ratio
import qualified Control.Monad.Trans.State.Strict as XState
import qualified Data.Functor.Identity as XIdentity
import qualified Data.Map.Strict as XMap
import qualified Data.Set as XSet

data JsonToken loc
    = T_lbrace loc
    | T_rbrace loc
    | T_lbracket loc
    | T_rbracket loc
    | T_comma loc
    | T_semicolon loc
    | T_true loc
    | T_false loc
    | T_null loc
    | T_string loc String
    | T_integer loc String
    | T_fraction loc String
    | T_exponent loc String
    deriving (Eq, Show)
instance Functor (JsonToken) where
    fmap f (T_lbrace loc) = T_lbrace (f loc)
    fmap f (T_rbrace loc) = T_rbrace (f loc)
    fmap f (T_lbracket loc) = T_lbracket (f loc)
    fmap f (T_rbracket loc) = T_rbracket (f loc)
    fmap f (T_comma loc) = T_comma (f loc)
    fmap f (T_semicolon loc) = T_semicolon (f loc)
    fmap f (T_true loc) = T_true (f loc)
    fmap f (T_false loc) = T_false (f loc)
    fmap f (T_null loc) = T_null (f loc)
    fmap f (T_string loc str) = T_string (f loc) str
    fmap f (T_integer loc n) = T_integer (f loc) n
    fmap f (T_fraction loc q) = T_fraction (f loc) q
    fmap f (T_exponent loc x) = T_exponent (f loc) x
getLoc :: JsonToken a -> a
getLoc (T_lbrace loc) = loc
getLoc (T_rbrace loc) = loc
getLoc (T_lbracket loc) = loc
getLoc (T_rbracket loc) = loc
getLoc (T_comma loc) = loc
getLoc (T_semicolon loc) = loc
getLoc (T_true loc) = loc
getLoc (T_false loc) = loc
getLoc (T_null loc) = loc
getLoc (T_string loc str) = loc
getLoc (T_integer loc n) = loc
getLoc (T_fraction loc q) = loc
getLoc (T_exponent loc x) = loc

-- the following codes are generated by LGS.

data DFA
    = DFA
        { getInitialQOfDFA :: Int
        , getFinalQsOfDFA :: XMap.Map Int Int
        , getTransitionsOfDFA :: XMap.Map (Int, Maybe Char) Int
        }
    deriving ()

jsonlexer :: String -> Either (Int, Int) [JsonToken (Int, Int)]
jsonlexer = jsonlexer_this . addLoc 1 1 where
    theDFA :: DFA
    theDFA = DFA
        { getInitialQOfDFA = 21
        , getFinalQsOfDFA = XMap.fromAscList [(22, 1), (23, 2), (24, 3), (25, 4), (26, 5), (27, 6), (28, 7), (29, 8), (30, 9), (31, 10), (32, 11), (33, 11), (34, 12), (35, 13), (36, 14)]
        , getTransitionsOfDFA = XMap.fromList 
            [ ((0, Just '"'), 13), ((0, Just '/'), 13), ((0, Just '\\'), 13), ((0, Just 'b'), 13), ((0, Just 'f'), 13), ((0, Just 'n'), 13), ((0, Just 'r'), 13), ((0, Just 't'), 13), ((0, Just 'u'), 4)
            , ((1, Just '0'), 13), ((1, Just '1'), 13), ((1, Just '2'), 13), ((1, Just '3'), 13), ((1, Just '4'), 13), ((1, Just '5'), 13), ((1, Just '6'), 13), ((1, Just '7'), 13), ((1, Just '8'), 13), ((1, Just '9'), 13), ((1, Just 'A'), 13), ((1, Just 'B'), 13), ((1, Just 'C'), 13), ((1, Just 'D'), 13), ((1, Just 'E'), 13), ((1, Just 'F'), 13), ((1, Just 'a'), 13), ((1, Just 'b'), 13), ((1, Just 'c'), 13), ((1, Just 'd'), 13), ((1, Just 'e'), 13), ((1, Just 'f'), 13)
            , ((2, Just '0'), 1), ((2, Just '1'), 1), ((2, Just '2'), 1), ((2, Just '3'), 1), ((2, Just '4'), 1), ((2, Just '5'), 1), ((2, Just '6'), 1), ((2, Just '7'), 1), ((2, Just '8'), 1), ((2, Just '9'), 1), ((2, Just 'A'), 1), ((2, Just 'B'), 1), ((2, Just 'C'), 1), ((2, Just 'D'), 1), ((2, Just 'E'), 1), ((2, Just 'F'), 1), ((2, Just 'a'), 1), ((2, Just 'b'), 1), ((2, Just 'c'), 1), ((2, Just 'd'), 1), ((2, Just 'e'), 1), ((2, Just 'f'), 1)
            , ((3, Just '0'), 2), ((3, Just '1'), 2), ((3, Just '2'), 2), ((3, Just '3'), 2), ((3, Just '4'), 2), ((3, Just '5'), 2), ((3, Just '6'), 2), ((3, Just '7'), 2), ((3, Just '8'), 2), ((3, Just '9'), 2), ((3, Just 'A'), 2), ((3, Just 'B'), 2), ((3, Just 'C'), 2), ((3, Just 'D'), 2), ((3, Just 'E'), 2), ((3, Just 'F'), 2), ((3, Just 'a'), 2), ((3, Just 'b'), 2), ((3, Just 'c'), 2), ((3, Just 'd'), 2), ((3, Just 'e'), 2), ((3, Just 'f'), 2)
            , ((4, Just '0'), 3), ((4, Just '1'), 3), ((4, Just '2'), 3), ((4, Just '3'), 3), ((4, Just '4'), 3), ((4, Just '5'), 3), ((4, Just '6'), 3), ((4, Just '7'), 3), ((4, Just '8'), 3), ((4, Just '9'), 3), ((4, Just 'A'), 3), ((4, Just 'B'), 3), ((4, Just 'C'), 3), ((4, Just 'D'), 3), ((4, Just 'E'), 3), ((4, Just 'F'), 3), ((4, Just 'a'), 3), ((4, Just 'b'), 3), ((4, Just 'c'), 3), ((4, Just 'd'), 3), ((4, Just 'e'), 3), ((4, Just 'f'), 3)
            , ((5, Just 'u'), 18)
            , ((6, Just 's'), 19)
            , ((7, Just 'l'), 6)
            , ((8, Just 'a'), 7)
            , ((9, Just 'r'), 5)
            , ((10, Just 'l'), 20)
            , ((11, Just 'u'), 10)
            , ((13, Just '\n'), 13), ((13, Just ' '), 13), ((13, Just '"'), 31), ((13, Just '+'), 13), ((13, Just ','), 13), ((13, Just '-'), 13), ((13, Just '.'), 13), ((13, Just '/'), 13), ((13, Just '0'), 13), ((13, Just '1'), 13), ((13, Just '2'), 13), ((13, Just '3'), 13), ((13, Just '4'), 13), ((13, Just '5'), 13), ((13, Just '6'), 13), ((13, Just '7'), 13), ((13, Just '8'), 13), ((13, Just '9'), 13), ((13, Just ':'), 13), ((13, Just 'A'), 13), ((13, Just 'B'), 13), ((13, Just 'C'), 13), ((13, Just 'D'), 13), ((13, Just 'E'), 13), ((13, Just 'F'), 13), ((13, Just '['), 13), ((13, Just '\\'), 0), ((13, Just ']'), 13), ((13, Just 'a'), 13), ((13, Just 'b'), 13), ((13, Just 'c'), 13), ((13, Just 'd'), 13), ((13, Just 'e'), 13), ((13, Just 'f'), 13), ((13, Just 'l'), 13), ((13, Just 'n'), 13), ((13, Just 'r'), 13), ((13, Just 's'), 13), ((13, Just 't'), 13), ((13, Just 'u'), 13), ((13, Just '{'), 13), ((13, Just '}'), 13), ((13, Nothing), 13)
            , ((14, Just '0'), 32), ((14, Just '1'), 33), ((14, Just '2'), 33), ((14, Just '3'), 33), ((14, Just '4'), 33), ((14, Just '5'), 33), ((14, Just '6'), 33), ((14, Just '7'), 33), ((14, Just '8'), 33), ((14, Just '9'), 33)
            , ((15, Just '+'), 17), ((15, Just '-'), 17), ((15, Just '0'), 35), ((15, Just '1'), 35), ((15, Just '2'), 35), ((15, Just '3'), 35), ((15, Just '4'), 35), ((15, Just '5'), 35), ((15, Just '6'), 35), ((15, Just '7'), 35), ((15, Just '8'), 35), ((15, Just '9'), 35)
            , ((16, Just '0'), 34), ((16, Just '1'), 34), ((16, Just '2'), 34), ((16, Just '3'), 34), ((16, Just '4'), 34), ((16, Just '5'), 34), ((16, Just '6'), 34), ((16, Just '7'), 34), ((16, Just '8'), 34), ((16, Just '9'), 34)
            , ((17, Just '0'), 35), ((17, Just '1'), 35), ((17, Just '2'), 35), ((17, Just '3'), 35), ((17, Just '4'), 35), ((17, Just '5'), 35), ((17, Just '6'), 35), ((17, Just '7'), 35), ((17, Just '8'), 35), ((17, Just '9'), 35)
            , ((18, Just 'e'), 28)
            , ((19, Just 'e'), 29)
            , ((20, Just 'l'), 30)
            , ((21, Just '\n'), 36), ((21, Just ' '), 36), ((21, Just '"'), 13), ((21, Just ','), 26), ((21, Just '-'), 14), ((21, Just '0'), 32), ((21, Just '1'), 33), ((21, Just '2'), 33), ((21, Just '3'), 33), ((21, Just '4'), 33), ((21, Just '5'), 33), ((21, Just '6'), 33), ((21, Just '7'), 33), ((21, Just '8'), 33), ((21, Just '9'), 33), ((21, Just ':'), 27), ((21, Just '['), 24), ((21, Just ']'), 25), ((21, Just 'f'), 8), ((21, Just 'n'), 11), ((21, Just 't'), 9), ((21, Just '{'), 22), ((21, Just '}'), 23)
            , ((32, Just '.'), 16)
            , ((33, Just '.'), 16), ((33, Just '0'), 33), ((33, Just '1'), 33), ((33, Just '2'), 33), ((33, Just '3'), 33), ((33, Just '4'), 33), ((33, Just '5'), 33), ((33, Just '6'), 33), ((33, Just '7'), 33), ((33, Just '8'), 33), ((33, Just '9'), 33)
            , ((34, Just '0'), 34), ((34, Just '1'), 34), ((34, Just '2'), 34), ((34, Just '3'), 34), ((34, Just '4'), 34), ((34, Just '5'), 34), ((34, Just '6'), 34), ((34, Just '7'), 34), ((34, Just '8'), 34), ((34, Just '9'), 34), ((34, Just 'E'), 15), ((34, Just 'e'), 15)
            , ((35, Just '0'), 35), ((35, Just '1'), 35), ((35, Just '2'), 35), ((35, Just '3'), 35), ((35, Just '4'), 35), ((35, Just '5'), 35), ((35, Just '6'), 35), ((35, Just '7'), 35), ((35, Just '8'), 35), ((35, Just '9'), 35)
            , ((36, Just '\n'), 36), ((36, Just ' '), 36)
            ]
        }
    theAlphabet :: XSet.Set Char
    theAlphabet = XSet.fromAscList "\n \"+,-./0123456789:ABCDEF[\\]abcdeflnrstu{}"
    runDFA :: DFA -> [((Int, Int), Char)] -> Either (Int, Int) ((Maybe Int, [((Int, Int), Char)]), [((Int, Int), Char)])
    runDFA (DFA q0 qfs deltas) = Right . XIdentity.runIdentity . runFast where
        classify :: Char -> Maybe Char
        classify ch = if ch `XSet.member` theAlphabet then Just ch else Nothing
        loop1 :: Int -> [((Int, Int), Char)] -> [((Int, Int), Char)] -> XState.StateT (Maybe Int, [((Int, Int), Char)]) XIdentity.Identity [((Int, Int), Char)]
        loop1 q buffer [] = return buffer
        loop1 q buffer (ch : str) = do
            (latest, accepted) <- XState.get
            case XMap.lookup (q, classify (snd ch)) deltas of
                Nothing -> return (buffer ++ [ch] ++ str)
                Just p -> case XMap.lookup p qfs of
                    Nothing -> loop1 p (buffer ++ [ch]) str
                    latest' -> do
                        XState.put (latest', accepted ++ buffer ++ [ch])
                        loop1 p [] str
        runFast :: [((Int, Int), Char)] -> XIdentity.Identity ((Maybe Int, [((Int, Int), Char)]), [((Int, Int), Char)])
        runFast input = do
            (rest, (latest, accepted)) <- XState.runStateT (loop1 q0 [] input) (Nothing, [])
            return ((latest, accepted), rest)
    addLoc :: Int -> Int -> String -> [((Int, Int), Char)]
    addLoc _ _ [] = []
    addLoc row col (ch : chs) = if ch == '\n' then ((row, col), ch) : addLoc (row + 1) 1 chs else ((row, col), ch) : addLoc row (col + 1) chs
    jsonlexer_this :: [((Int, Int), Char)] -> Either (Int, Int) [JsonToken (Int, Int)]
    jsonlexer_this [] = return []
    jsonlexer_this str0 = do
        let return_one my_token = return [my_token]
        dfa_output <- runDFA theDFA str0
        (str1, piece) <- case dfa_output of
            ((_, []), _) -> Left (fst (head str0))
            ((Just label, accepted), rest) -> return (rest, ((label, map snd accepted), (fst (head accepted), fst (head (reverse accepted)))))
            _ -> Left (fst (head str0))
        tokens1 <- case piece of
            ((1, this), ((row1, col1), (row2, col2))) -> return_one (T_lbrace (row1, col1))
            ((2, this), ((row1, col1), (row2, col2))) -> return_one (T_rbrace (row1, col1))
            ((3, this), ((row1, col1), (row2, col2))) -> return_one (T_lbracket (row1, col1))
            ((4, this), ((row1, col1), (row2, col2))) -> return_one (T_rbracket (row1, col1))
            ((5, this), ((row1, col1), (row2, col2))) -> return_one (T_comma (row1, col1))
            ((6, this), ((row1, col1), (row2, col2))) -> return_one (T_semicolon (row1, col1))
            ((7, this), ((row1, col1), (row2, col2))) -> return_one (T_true (row1, col1))
            ((8, this), ((row1, col1), (row2, col2))) -> return_one (T_false (row1, col1))
            ((9, this), ((row1, col1), (row2, col2))) -> return_one (T_null (row1, col1))
            ((10, this), ((row1, col1), (row2, col2))) -> return_one (T_string (row1, col1) (this))
            ((11, this), ((row1, col1), (row2, col2))) -> return_one (T_integer (row1, col1) (this))
            ((12, this), ((row1, col1), (row2, col2))) -> return_one (T_fraction (row1, col1) (this))
            ((13, this), ((row1, col1), (row2, col2))) -> return_one (T_exponent (row1, col1) (this))
            ((14, this), ((row1, col1), (row2, col2))) -> return []
        tokens2 <- jsonlexer_this str1
        return (tokens1 ++ tokens2)
