module Aladdin.Front.Analyzer.Parser where

import Aladdin.Front.Analyzer.Grammar
import Aladdin.Front.Header
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

-- the following codes are generated by PGS.

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()

runAladdinParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runAladdinParser = fmap (getEither getQuery (getSequence getDecl)) . runLALR1 theLALR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] = (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[14]] = RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[16]] = RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] = RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[15, 14]] = RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[15]] = (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise = RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[14]] = RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[17, 16]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[17]] = (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[17, 18]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[18]] = (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise = RTyVar (loc_1) (contents_1)
    getTypeRep2 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise = RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[16]] = RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] = RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 3]] = RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep0 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1 _1)) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] = (getTermRep1 _1)
    getTermRep1 :: ParsingTree -> (TermRep)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 5]] = RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1 _1)) (getTermRep2 _3)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] = (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 5]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep3 _1)) (getTermRep2 _3)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] = (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 7]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep3 _1)) (getTermRep4 _3)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] = (getTermRep4 _1)
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 7]] = RApp (getSLoc (getTermRep5 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getTermRep4 _3)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = (getTermRep5 _1)
    getTermRep5 :: ParsingTree -> (TermRep)
    getTermRep5 (PTBranch _ [PTLeaf (T_pi loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] = RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_pi)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [PTLeaf (T_sigma loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] = RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_sigma)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_Eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep6 _3)) (RApp (getSLoc (getTermRep6 _1) <> (loc_2)) (RCon (loc_2) DC_Eq) (getTermRep6 _1)) (getTermRep6 _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = (getTermRep6 _1)
    getTermRep6 :: ParsingTree -> (TermRep)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[9, 10]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep7 _2)) (getTermRep6 _1) (getTermRep7 _2)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] = (getTermRep7 _1)
    getTermRep6 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise = RCon (loc_1) DC_Succ
    getTermRep7 :: ParsingTree -> (TermRep)
    getTermRep7 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] = RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep7 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_cut)
    getTermRep7 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_true)
    getTermRep7 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_fail)
    getTermRep7 (PTBranch _ [PTLeaf (T_debug loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_debug)
    getTermRep7 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise = RCon (loc_1) (DC_Named (contents_1))
    getTermRep7 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise = RVar (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise = mkNatLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise = mkStrLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise = mkChrLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise = RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep7 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[11]] = RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise = []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[13, 12]] = (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] = Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] = Right (getRight _1)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = RApp (getSLoc (getTermRep5 _1)) (RApp (getSLoc (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Cons) (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 11]] = RApp (getSLoc (getTermRep5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getListBody _3)
    toTerminal :: (Token) -> TSym
    toTerminal (T_dot loc) = 1
    toTerminal (T_arrow loc) = 2
    toTerminal (T_lparen loc) = 3
    toTerminal (T_rparen loc) = 4
    toTerminal (T_lbracket loc) = 5
    toTerminal (T_rbracket loc) = 6
    toTerminal (T_quest loc) = 7
    toTerminal (T_if loc) = 8
    toTerminal (T_comma loc) = 9
    toTerminal (T_semicolon loc) = 10
    toTerminal (T_fatarrow loc) = 11
    toTerminal (T_pi loc) = 12
    toTerminal (T_sigma loc) = 13
    toTerminal (T_succ loc) = 14
    toTerminal (T_Eq loc) = 15
    toTerminal (T_cut loc) = 16
    toTerminal (T_true loc) = 17
    toTerminal (T_fail loc) = 18
    toTerminal (T_debug loc) = 19
    toTerminal (T_bslash loc) = 20
    toTerminal (T_cons loc) = 21
    toTerminal (T_kind loc) = 22
    toTerminal (T_type loc) = 23
    toTerminal (T_smallid loc contents) = 24
    toTerminal (T_largeid loc contents) = 25
    toTerminal (T_nat_lit loc contents) = 26
    toTerminal (T_chr_lit loc contents) = 27
    toTerminal (T_str_lit loc contents) = 28
    runLALR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLALR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLALR1Parser :: LR1Parser
    theLALR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (12, [])), ((0, 3), Shift 20), ((0, 5), Shift 19), ((0, 7), Shift 23), ((0, 12), Shift 22), ((0, 13), Shift 24), ((0, 14), Shift 27), ((0, 16), Shift 14), ((0, 17), Shift 28), ((0, 18), Shift 16), ((0, 19), Shift 15), ((0, 22), Shift 17), ((0, 23), Shift 29), ((0, 24), Shift 25), ((0, 25), Shift 18), ((0, 26), Shift 21), ((0, 27), Shift 13), ((0, 28), Shift 26)
            , ((1, 0), Reduce (12, [])), ((1, 3), Shift 20), ((1, 5), Shift 19), ((1, 12), Shift 22), ((1, 13), Shift 24), ((1, 14), Shift 27), ((1, 16), Shift 14), ((1, 17), Shift 28), ((1, 18), Shift 16), ((1, 19), Shift 15), ((1, 22), Shift 17), ((1, 23), Shift 29), ((1, 24), Shift 25), ((1, 25), Shift 18), ((1, 26), Shift 21), ((1, 27), Shift 13), ((1, 28), Shift 26)
            , ((2, 0), Reduce (1, [NS 2]))
            , ((3, 1), Shift 31)
            , ((4, 1), Reduce (3, [NS 4])), ((4, 4), Reduce (3, [NS 4])), ((4, 8), Shift 40), ((4, 10), Shift 41)
            , ((5, 1), Reduce (4, [NS 5])), ((5, 4), Reduce (4, [NS 5])), ((5, 8), Reduce (4, [NS 5])), ((5, 10), Reduce (4, [NS 5]))
            , ((6, 1), Reduce (5, [NS 6])), ((6, 4), Reduce (5, [NS 6])), ((6, 8), Reduce (5, [NS 6])), ((6, 9), Shift 43), ((6, 10), Reduce (5, [NS 6])), ((6, 11), Shift 44)
            , ((7, 1), Reduce (6, [NS 7])), ((7, 4), Reduce (6, [NS 7])), ((7, 8), Reduce (6, [NS 7])), ((7, 9), Reduce (6, [NS 7])), ((7, 10), Reduce (6, [NS 7])), ((7, 11), Reduce (6, [NS 7]))
            , ((8, 1), Reduce (7, [NS 8])), ((8, 4), Reduce (7, [NS 8])), ((8, 8), Reduce (7, [NS 8])), ((8, 9), Reduce (7, [NS 8])), ((8, 10), Reduce (7, [NS 8])), ((8, 11), Reduce (7, [NS 8])), ((8, 21), Shift 45)
            , ((9, 1), Reduce (8, [NS 9])), ((9, 3), Shift 20), ((9, 4), Reduce (8, [NS 9])), ((9, 5), Shift 19), ((9, 6), Reduce (8, [NS 9])), ((9, 8), Reduce (8, [NS 9])), ((9, 9), Reduce (8, [NS 9])), ((9, 10), Reduce (8, [NS 9])), ((9, 11), Reduce (8, [NS 9])), ((9, 15), Shift 49), ((9, 16), Shift 14), ((9, 17), Shift 28), ((9, 18), Shift 16), ((9, 19), Shift 15), ((9, 21), Reduce (8, [NS 9])), ((9, 24), Shift 25), ((9, 25), Shift 36), ((9, 26), Shift 21), ((9, 27), Shift 13), ((9, 28), Shift 26)
            , ((10, 1), Reduce (9, [NS 10])), ((10, 3), Reduce (9, [NS 10])), ((10, 4), Reduce (9, [NS 10])), ((10, 5), Reduce (9, [NS 10])), ((10, 6), Reduce (9, [NS 10])), ((10, 8), Reduce (9, [NS 10])), ((10, 9), Reduce (9, [NS 10])), ((10, 10), Reduce (9, [NS 10])), ((10, 11), Reduce (9, [NS 10])), ((10, 15), Reduce (9, [NS 10])), ((10, 16), Reduce (9, [NS 10])), ((10, 17), Reduce (9, [NS 10])), ((10, 18), Reduce (9, [NS 10])), ((10, 19), Reduce (9, [NS 10])), ((10, 21), Reduce (9, [NS 10])), ((10, 24), Reduce (9, [NS 10])), ((10, 25), Reduce (9, [NS 10])), ((10, 26), Reduce (9, [NS 10])), ((10, 27), Reduce (9, [NS 10])), ((10, 28), Reduce (9, [NS 10]))
            , ((11, 0), Reduce (1, [NS 12]))
            , ((12, 0), Accept)
            , ((13, 1), Reduce (10, [TS 27])), ((13, 3), Reduce (10, [TS 27])), ((13, 4), Reduce (10, [TS 27])), ((13, 5), Reduce (10, [TS 27])), ((13, 6), Reduce (10, [TS 27])), ((13, 8), Reduce (10, [TS 27])), ((13, 9), Reduce (10, [TS 27])), ((13, 10), Reduce (10, [TS 27])), ((13, 11), Reduce (10, [TS 27])), ((13, 15), Reduce (10, [TS 27])), ((13, 16), Reduce (10, [TS 27])), ((13, 17), Reduce (10, [TS 27])), ((13, 18), Reduce (10, [TS 27])), ((13, 19), Reduce (10, [TS 27])), ((13, 21), Reduce (10, [TS 27])), ((13, 24), Reduce (10, [TS 27])), ((13, 25), Reduce (10, [TS 27])), ((13, 26), Reduce (10, [TS 27])), ((13, 27), Reduce (10, [TS 27])), ((13, 28), Reduce (10, [TS 27]))
            , ((14, 1), Reduce (10, [TS 16])), ((14, 3), Reduce (10, [TS 16])), ((14, 4), Reduce (10, [TS 16])), ((14, 5), Reduce (10, [TS 16])), ((14, 6), Reduce (10, [TS 16])), ((14, 8), Reduce (10, [TS 16])), ((14, 9), Reduce (10, [TS 16])), ((14, 10), Reduce (10, [TS 16])), ((14, 11), Reduce (10, [TS 16])), ((14, 15), Reduce (10, [TS 16])), ((14, 16), Reduce (10, [TS 16])), ((14, 17), Reduce (10, [TS 16])), ((14, 18), Reduce (10, [TS 16])), ((14, 19), Reduce (10, [TS 16])), ((14, 21), Reduce (10, [TS 16])), ((14, 24), Reduce (10, [TS 16])), ((14, 25), Reduce (10, [TS 16])), ((14, 26), Reduce (10, [TS 16])), ((14, 27), Reduce (10, [TS 16])), ((14, 28), Reduce (10, [TS 16]))
            , ((15, 1), Reduce (10, [TS 19])), ((15, 3), Reduce (10, [TS 19])), ((15, 4), Reduce (10, [TS 19])), ((15, 5), Reduce (10, [TS 19])), ((15, 6), Reduce (10, [TS 19])), ((15, 8), Reduce (10, [TS 19])), ((15, 9), Reduce (10, [TS 19])), ((15, 10), Reduce (10, [TS 19])), ((15, 11), Reduce (10, [TS 19])), ((15, 15), Reduce (10, [TS 19])), ((15, 16), Reduce (10, [TS 19])), ((15, 17), Reduce (10, [TS 19])), ((15, 18), Reduce (10, [TS 19])), ((15, 19), Reduce (10, [TS 19])), ((15, 21), Reduce (10, [TS 19])), ((15, 24), Reduce (10, [TS 19])), ((15, 25), Reduce (10, [TS 19])), ((15, 26), Reduce (10, [TS 19])), ((15, 27), Reduce (10, [TS 19])), ((15, 28), Reduce (10, [TS 19]))
            , ((16, 1), Reduce (10, [TS 18])), ((16, 3), Reduce (10, [TS 18])), ((16, 4), Reduce (10, [TS 18])), ((16, 5), Reduce (10, [TS 18])), ((16, 6), Reduce (10, [TS 18])), ((16, 8), Reduce (10, [TS 18])), ((16, 9), Reduce (10, [TS 18])), ((16, 10), Reduce (10, [TS 18])), ((16, 11), Reduce (10, [TS 18])), ((16, 15), Reduce (10, [TS 18])), ((16, 16), Reduce (10, [TS 18])), ((16, 17), Reduce (10, [TS 18])), ((16, 18), Reduce (10, [TS 18])), ((16, 19), Reduce (10, [TS 18])), ((16, 21), Reduce (10, [TS 18])), ((16, 24), Reduce (10, [TS 18])), ((16, 25), Reduce (10, [TS 18])), ((16, 26), Reduce (10, [TS 18])), ((16, 27), Reduce (10, [TS 18])), ((16, 28), Reduce (10, [TS 18]))
            , ((17, 24), Shift 32)
            , ((18, 1), Reduce (10, [TS 25])), ((18, 3), Reduce (10, [TS 25])), ((18, 4), Reduce (10, [TS 25])), ((18, 5), Reduce (10, [TS 25])), ((18, 8), Reduce (10, [TS 25])), ((18, 9), Reduce (10, [TS 25])), ((18, 10), Reduce (10, [TS 25])), ((18, 11), Reduce (10, [TS 25])), ((18, 15), Reduce (10, [TS 25])), ((18, 16), Reduce (10, [TS 25])), ((18, 17), Reduce (10, [TS 25])), ((18, 18), Reduce (10, [TS 25])), ((18, 19), Reduce (10, [TS 25])), ((18, 20), Shift 42), ((18, 21), Reduce (10, [TS 25])), ((18, 24), Reduce (10, [TS 25])), ((18, 25), Reduce (10, [TS 25])), ((18, 26), Reduce (10, [TS 25])), ((18, 27), Reduce (10, [TS 25])), ((18, 28), Reduce (10, [TS 25]))
            , ((19, 3), Shift 20), ((19, 5), Shift 19), ((19, 6), Shift 37), ((19, 12), Shift 22), ((19, 13), Shift 24), ((19, 14), Shift 27), ((19, 16), Shift 14), ((19, 17), Shift 28), ((19, 18), Shift 16), ((19, 19), Shift 15), ((19, 24), Shift 25), ((19, 25), Shift 36), ((19, 26), Shift 21), ((19, 27), Shift 13), ((19, 28), Shift 26)
            , ((20, 3), Shift 20), ((20, 5), Shift 19), ((20, 12), Shift 22), ((20, 13), Shift 24), ((20, 14), Shift 27), ((20, 16), Shift 14), ((20, 17), Shift 28), ((20, 18), Shift 16), ((20, 19), Shift 15), ((20, 24), Shift 25), ((20, 25), Shift 18), ((20, 26), Shift 21), ((20, 27), Shift 13), ((20, 28), Shift 26)
            , ((21, 1), Reduce (10, [TS 26])), ((21, 3), Reduce (10, [TS 26])), ((21, 4), Reduce (10, [TS 26])), ((21, 5), Reduce (10, [TS 26])), ((21, 6), Reduce (10, [TS 26])), ((21, 8), Reduce (10, [TS 26])), ((21, 9), Reduce (10, [TS 26])), ((21, 10), Reduce (10, [TS 26])), ((21, 11), Reduce (10, [TS 26])), ((21, 15), Reduce (10, [TS 26])), ((21, 16), Reduce (10, [TS 26])), ((21, 17), Reduce (10, [TS 26])), ((21, 18), Reduce (10, [TS 26])), ((21, 19), Reduce (10, [TS 26])), ((21, 21), Reduce (10, [TS 26])), ((21, 24), Reduce (10, [TS 26])), ((21, 25), Reduce (10, [TS 26])), ((21, 26), Reduce (10, [TS 26])), ((21, 27), Reduce (10, [TS 26])), ((21, 28), Reduce (10, [TS 26]))
            , ((22, 3), Shift 20), ((22, 5), Shift 19), ((22, 12), Shift 22), ((22, 13), Shift 24), ((22, 14), Shift 27), ((22, 16), Shift 14), ((22, 17), Shift 28), ((22, 18), Shift 16), ((22, 19), Shift 15), ((22, 24), Shift 25), ((22, 25), Shift 36), ((22, 26), Shift 21), ((22, 27), Shift 13), ((22, 28), Shift 26)
            , ((23, 3), Shift 20), ((23, 5), Shift 19), ((23, 12), Shift 22), ((23, 13), Shift 24), ((23, 14), Shift 27), ((23, 16), Shift 14), ((23, 17), Shift 28), ((23, 18), Shift 16), ((23, 19), Shift 15), ((23, 24), Shift 25), ((23, 25), Shift 18), ((23, 26), Shift 21), ((23, 27), Shift 13), ((23, 28), Shift 26)
            , ((24, 3), Shift 20), ((24, 5), Shift 19), ((24, 12), Shift 22), ((24, 13), Shift 24), ((24, 14), Shift 27), ((24, 16), Shift 14), ((24, 17), Shift 28), ((24, 18), Shift 16), ((24, 19), Shift 15), ((24, 24), Shift 25), ((24, 25), Shift 36), ((24, 26), Shift 21), ((24, 27), Shift 13), ((24, 28), Shift 26)
            , ((25, 1), Reduce (10, [TS 24])), ((25, 3), Reduce (10, [TS 24])), ((25, 4), Reduce (10, [TS 24])), ((25, 5), Reduce (10, [TS 24])), ((25, 6), Reduce (10, [TS 24])), ((25, 8), Reduce (10, [TS 24])), ((25, 9), Reduce (10, [TS 24])), ((25, 10), Reduce (10, [TS 24])), ((25, 11), Reduce (10, [TS 24])), ((25, 15), Reduce (10, [TS 24])), ((25, 16), Reduce (10, [TS 24])), ((25, 17), Reduce (10, [TS 24])), ((25, 18), Reduce (10, [TS 24])), ((25, 19), Reduce (10, [TS 24])), ((25, 21), Reduce (10, [TS 24])), ((25, 24), Reduce (10, [TS 24])), ((25, 25), Reduce (10, [TS 24])), ((25, 26), Reduce (10, [TS 24])), ((25, 27), Reduce (10, [TS 24])), ((25, 28), Reduce (10, [TS 24]))
            , ((26, 1), Reduce (10, [TS 28])), ((26, 3), Reduce (10, [TS 28])), ((26, 4), Reduce (10, [TS 28])), ((26, 5), Reduce (10, [TS 28])), ((26, 6), Reduce (10, [TS 28])), ((26, 8), Reduce (10, [TS 28])), ((26, 9), Reduce (10, [TS 28])), ((26, 10), Reduce (10, [TS 28])), ((26, 11), Reduce (10, [TS 28])), ((26, 15), Reduce (10, [TS 28])), ((26, 16), Reduce (10, [TS 28])), ((26, 17), Reduce (10, [TS 28])), ((26, 18), Reduce (10, [TS 28])), ((26, 19), Reduce (10, [TS 28])), ((26, 21), Reduce (10, [TS 28])), ((26, 24), Reduce (10, [TS 28])), ((26, 25), Reduce (10, [TS 28])), ((26, 26), Reduce (10, [TS 28])), ((26, 27), Reduce (10, [TS 28])), ((26, 28), Reduce (10, [TS 28]))
            , ((27, 1), Reduce (9, [TS 14])), ((27, 3), Reduce (9, [TS 14])), ((27, 4), Reduce (9, [TS 14])), ((27, 5), Reduce (9, [TS 14])), ((27, 6), Reduce (9, [TS 14])), ((27, 8), Reduce (9, [TS 14])), ((27, 9), Reduce (9, [TS 14])), ((27, 10), Reduce (9, [TS 14])), ((27, 11), Reduce (9, [TS 14])), ((27, 15), Reduce (9, [TS 14])), ((27, 16), Reduce (9, [TS 14])), ((27, 17), Reduce (9, [TS 14])), ((27, 18), Reduce (9, [TS 14])), ((27, 19), Reduce (9, [TS 14])), ((27, 21), Reduce (9, [TS 14])), ((27, 24), Reduce (9, [TS 14])), ((27, 25), Reduce (9, [TS 14])), ((27, 26), Reduce (9, [TS 14])), ((27, 27), Reduce (9, [TS 14])), ((27, 28), Reduce (9, [TS 14]))
            , ((28, 1), Reduce (10, [TS 17])), ((28, 3), Reduce (10, [TS 17])), ((28, 4), Reduce (10, [TS 17])), ((28, 5), Reduce (10, [TS 17])), ((28, 6), Reduce (10, [TS 17])), ((28, 8), Reduce (10, [TS 17])), ((28, 9), Reduce (10, [TS 17])), ((28, 10), Reduce (10, [TS 17])), ((28, 11), Reduce (10, [TS 17])), ((28, 15), Reduce (10, [TS 17])), ((28, 16), Reduce (10, [TS 17])), ((28, 17), Reduce (10, [TS 17])), ((28, 18), Reduce (10, [TS 17])), ((28, 19), Reduce (10, [TS 17])), ((28, 21), Reduce (10, [TS 17])), ((28, 24), Reduce (10, [TS 17])), ((28, 25), Reduce (10, [TS 17])), ((28, 26), Reduce (10, [TS 17])), ((28, 27), Reduce (10, [TS 17])), ((28, 28), Reduce (10, [TS 17]))
            , ((29, 24), Shift 33)
            , ((30, 0), Reduce (12, [NS 13, NS 12]))
            , ((31, 0), Reduce (13, [NS 3, TS 1])), ((31, 3), Reduce (13, [NS 3, TS 1])), ((31, 5), Reduce (13, [NS 3, TS 1])), ((31, 12), Reduce (13, [NS 3, TS 1])), ((31, 13), Reduce (13, [NS 3, TS 1])), ((31, 14), Reduce (13, [NS 3, TS 1])), ((31, 16), Reduce (13, [NS 3, TS 1])), ((31, 17), Reduce (13, [NS 3, TS 1])), ((31, 18), Reduce (13, [NS 3, TS 1])), ((31, 19), Reduce (13, [NS 3, TS 1])), ((31, 22), Reduce (13, [NS 3, TS 1])), ((31, 23), Reduce (13, [NS 3, TS 1])), ((31, 24), Reduce (13, [NS 3, TS 1])), ((31, 25), Reduce (13, [NS 3, TS 1])), ((31, 26), Reduce (13, [NS 3, TS 1])), ((31, 27), Reduce (13, [NS 3, TS 1])), ((31, 28), Reduce (13, [NS 3, TS 1]))
            , ((32, 3), Shift 52), ((32, 23), Shift 53)
            , ((33, 3), Shift 58), ((33, 24), Shift 59), ((33, 25), Shift 57)
            , ((34, 6), Shift 69)
            , ((35, 6), Reduce (11, [NS 8])), ((35, 9), Shift 60)
            , ((36, 1), Reduce (10, [TS 25])), ((36, 3), Reduce (10, [TS 25])), ((36, 4), Reduce (10, [TS 25])), ((36, 5), Reduce (10, [TS 25])), ((36, 6), Reduce (10, [TS 25])), ((36, 8), Reduce (10, [TS 25])), ((36, 9), Reduce (10, [TS 25])), ((36, 10), Reduce (10, [TS 25])), ((36, 11), Reduce (10, [TS 25])), ((36, 15), Reduce (10, [TS 25])), ((36, 16), Reduce (10, [TS 25])), ((36, 17), Reduce (10, [TS 25])), ((36, 18), Reduce (10, [TS 25])), ((36, 19), Reduce (10, [TS 25])), ((36, 21), Reduce (10, [TS 25])), ((36, 24), Reduce (10, [TS 25])), ((36, 25), Reduce (10, [TS 25])), ((36, 26), Reduce (10, [TS 25])), ((36, 27), Reduce (10, [TS 25])), ((36, 28), Reduce (10, [TS 25]))
            , ((37, 1), Reduce (10, [TS 5, TS 6])), ((37, 3), Reduce (10, [TS 5, TS 6])), ((37, 4), Reduce (10, [TS 5, TS 6])), ((37, 5), Reduce (10, [TS 5, TS 6])), ((37, 6), Reduce (10, [TS 5, TS 6])), ((37, 8), Reduce (10, [TS 5, TS 6])), ((37, 9), Reduce (10, [TS 5, TS 6])), ((37, 10), Reduce (10, [TS 5, TS 6])), ((37, 11), Reduce (10, [TS 5, TS 6])), ((37, 15), Reduce (10, [TS 5, TS 6])), ((37, 16), Reduce (10, [TS 5, TS 6])), ((37, 17), Reduce (10, [TS 5, TS 6])), ((37, 18), Reduce (10, [TS 5, TS 6])), ((37, 19), Reduce (10, [TS 5, TS 6])), ((37, 21), Reduce (10, [TS 5, TS 6])), ((37, 24), Reduce (10, [TS 5, TS 6])), ((37, 25), Reduce (10, [TS 5, TS 6])), ((37, 26), Reduce (10, [TS 5, TS 6])), ((37, 27), Reduce (10, [TS 5, TS 6])), ((37, 28), Reduce (10, [TS 5, TS 6]))
            , ((38, 1), Shift 61)
            , ((39, 4), Shift 70)
            , ((40, 3), Shift 20), ((40, 5), Shift 19), ((40, 12), Shift 22), ((40, 13), Shift 24), ((40, 14), Shift 27), ((40, 16), Shift 14), ((40, 17), Shift 28), ((40, 18), Shift 16), ((40, 19), Shift 15), ((40, 24), Shift 25), ((40, 25), Shift 18), ((40, 26), Shift 21), ((40, 27), Shift 13), ((40, 28), Shift 26)
            , ((41, 3), Shift 20), ((41, 5), Shift 19), ((41, 12), Shift 22), ((41, 13), Shift 24), ((41, 14), Shift 27), ((41, 16), Shift 14), ((41, 17), Shift 28), ((41, 18), Shift 16), ((41, 19), Shift 15), ((41, 24), Shift 25), ((41, 25), Shift 36), ((41, 26), Shift 21), ((41, 27), Shift 13), ((41, 28), Shift 26)
            , ((42, 3), Shift 20), ((42, 5), Shift 19), ((42, 12), Shift 22), ((42, 13), Shift 24), ((42, 14), Shift 27), ((42, 16), Shift 14), ((42, 17), Shift 28), ((42, 18), Shift 16), ((42, 19), Shift 15), ((42, 24), Shift 25), ((42, 25), Shift 18), ((42, 26), Shift 21), ((42, 27), Shift 13), ((42, 28), Shift 26)
            , ((43, 3), Shift 20), ((43, 5), Shift 19), ((43, 12), Shift 22), ((43, 13), Shift 24), ((43, 14), Shift 27), ((43, 16), Shift 14), ((43, 17), Shift 28), ((43, 18), Shift 16), ((43, 19), Shift 15), ((43, 24), Shift 25), ((43, 25), Shift 36), ((43, 26), Shift 21), ((43, 27), Shift 13), ((43, 28), Shift 26)
            , ((44, 3), Shift 20), ((44, 5), Shift 19), ((44, 12), Shift 22), ((44, 13), Shift 24), ((44, 14), Shift 27), ((44, 16), Shift 14), ((44, 17), Shift 28), ((44, 18), Shift 16), ((44, 19), Shift 15), ((44, 24), Shift 25), ((44, 25), Shift 36), ((44, 26), Shift 21), ((44, 27), Shift 13), ((44, 28), Shift 26)
            , ((45, 3), Shift 20), ((45, 5), Shift 19), ((45, 12), Shift 22), ((45, 13), Shift 24), ((45, 14), Shift 27), ((45, 16), Shift 14), ((45, 17), Shift 28), ((45, 18), Shift 16), ((45, 19), Shift 15), ((45, 24), Shift 25), ((45, 25), Shift 36), ((45, 26), Shift 21), ((45, 27), Shift 13), ((45, 28), Shift 26)
            , ((46, 1), Reduce (8, [TS 12, NS 8])), ((46, 4), Reduce (8, [TS 12, NS 8])), ((46, 6), Reduce (8, [TS 12, NS 8])), ((46, 8), Reduce (8, [TS 12, NS 8])), ((46, 9), Reduce (8, [TS 12, NS 8])), ((46, 10), Reduce (8, [TS 12, NS 8])), ((46, 11), Reduce (8, [TS 12, NS 8])), ((46, 21), Reduce (8, [TS 12, NS 8]))
            , ((47, 1), Reduce (8, [TS 13, NS 8])), ((47, 4), Reduce (8, [TS 13, NS 8])), ((47, 6), Reduce (8, [TS 13, NS 8])), ((47, 8), Reduce (8, [TS 13, NS 8])), ((47, 9), Reduce (8, [TS 13, NS 8])), ((47, 10), Reduce (8, [TS 13, NS 8])), ((47, 11), Reduce (8, [TS 13, NS 8])), ((47, 21), Reduce (8, [TS 13, NS 8]))
            , ((48, 1), Reduce (9, [NS 9, NS 10])), ((48, 3), Reduce (9, [NS 9, NS 10])), ((48, 4), Reduce (9, [NS 9, NS 10])), ((48, 5), Reduce (9, [NS 9, NS 10])), ((48, 6), Reduce (9, [NS 9, NS 10])), ((48, 8), Reduce (9, [NS 9, NS 10])), ((48, 9), Reduce (9, [NS 9, NS 10])), ((48, 10), Reduce (9, [NS 9, NS 10])), ((48, 11), Reduce (9, [NS 9, NS 10])), ((48, 15), Reduce (9, [NS 9, NS 10])), ((48, 16), Reduce (9, [NS 9, NS 10])), ((48, 17), Reduce (9, [NS 9, NS 10])), ((48, 18), Reduce (9, [NS 9, NS 10])), ((48, 19), Reduce (9, [NS 9, NS 10])), ((48, 21), Reduce (9, [NS 9, NS 10])), ((48, 24), Reduce (9, [NS 9, NS 10])), ((48, 25), Reduce (9, [NS 9, NS 10])), ((48, 26), Reduce (9, [NS 9, NS 10])), ((48, 27), Reduce (9, [NS 9, NS 10])), ((48, 28), Reduce (9, [NS 9, NS 10]))
            , ((49, 3), Shift 20), ((49, 5), Shift 19), ((49, 14), Shift 27), ((49, 16), Shift 14), ((49, 17), Shift 28), ((49, 18), Shift 16), ((49, 19), Shift 15), ((49, 24), Shift 25), ((49, 25), Shift 36), ((49, 26), Shift 21), ((49, 27), Shift 13), ((49, 28), Shift 26)
            , ((50, 1), Shift 71)
            , ((51, 1), Reduce (14, [NS 15])), ((51, 2), Shift 74), ((51, 4), Reduce (14, [NS 15]))
            , ((52, 3), Shift 52), ((52, 23), Shift 53)
            , ((53, 1), Reduce (15, [TS 23])), ((53, 2), Reduce (15, [TS 23])), ((53, 4), Reduce (15, [TS 23]))
            , ((54, 1), Shift 72)
            , ((55, 1), Reduce (16, [NS 17])), ((55, 2), Shift 78), ((55, 3), Shift 58), ((55, 4), Reduce (16, [NS 17])), ((55, 24), Shift 59), ((55, 25), Shift 57)
            , ((56, 1), Reduce (17, [NS 18])), ((56, 2), Reduce (17, [NS 18])), ((56, 3), Reduce (17, [NS 18])), ((56, 4), Reduce (17, [NS 18])), ((56, 24), Reduce (17, [NS 18])), ((56, 25), Reduce (17, [NS 18]))
            , ((57, 1), Reduce (18, [TS 25])), ((57, 2), Reduce (18, [TS 25])), ((57, 3), Reduce (18, [TS 25])), ((57, 4), Reduce (18, [TS 25])), ((57, 24), Reduce (18, [TS 25])), ((57, 25), Reduce (18, [TS 25]))
            , ((58, 3), Shift 58), ((58, 24), Shift 59), ((58, 25), Shift 57)
            , ((59, 1), Reduce (18, [TS 24])), ((59, 2), Reduce (18, [TS 24])), ((59, 3), Reduce (18, [TS 24])), ((59, 4), Reduce (18, [TS 24])), ((59, 24), Reduce (18, [TS 24])), ((59, 25), Reduce (18, [TS 24]))
            , ((60, 3), Shift 20), ((60, 5), Shift 19), ((60, 12), Shift 22), ((60, 13), Shift 24), ((60, 14), Shift 27), ((60, 16), Shift 14), ((60, 17), Shift 28), ((60, 18), Shift 16), ((60, 19), Shift 15), ((60, 24), Shift 25), ((60, 25), Shift 36), ((60, 26), Shift 21), ((60, 27), Shift 13), ((60, 28), Shift 26)
            , ((61, 0), Reduce (2, [TS 7, NS 3, TS 1]))
            , ((62, 1), Reduce (3, [NS 4, TS 8, NS 3])), ((62, 4), Reduce (3, [NS 4, TS 8, NS 3]))
            , ((63, 1), Reduce (3, [TS 25, TS 20, NS 3])), ((63, 4), Reduce (3, [TS 25, TS 20, NS 3]))
            , ((64, 1), Reduce (4, [NS 4, TS 10, NS 5])), ((64, 4), Reduce (4, [NS 4, TS 10, NS 5])), ((64, 8), Reduce (4, [NS 4, TS 10, NS 5])), ((64, 10), Reduce (4, [NS 4, TS 10, NS 5]))
            , ((65, 1), Reduce (5, [NS 6, TS 11, NS 5])), ((65, 4), Reduce (5, [NS 6, TS 11, NS 5])), ((65, 8), Reduce (5, [NS 6, TS 11, NS 5])), ((65, 10), Reduce (5, [NS 6, TS 11, NS 5]))
            , ((66, 1), Reduce (6, [NS 6, TS 9, NS 7])), ((66, 4), Reduce (6, [NS 6, TS 9, NS 7])), ((66, 8), Reduce (6, [NS 6, TS 9, NS 7])), ((66, 9), Reduce (6, [NS 6, TS 9, NS 7])), ((66, 10), Reduce (6, [NS 6, TS 9, NS 7])), ((66, 11), Reduce (6, [NS 6, TS 9, NS 7]))
            , ((67, 1), Reduce (7, [NS 8, TS 21, NS 7])), ((67, 4), Reduce (7, [NS 8, TS 21, NS 7])), ((67, 8), Reduce (7, [NS 8, TS 21, NS 7])), ((67, 9), Reduce (7, [NS 8, TS 21, NS 7])), ((67, 10), Reduce (7, [NS 8, TS 21, NS 7])), ((67, 11), Reduce (7, [NS 8, TS 21, NS 7]))
            , ((68, 1), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 3), Shift 20), ((68, 4), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 5), Shift 19), ((68, 6), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 8), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 9), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 10), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 11), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 16), Shift 14), ((68, 17), Shift 28), ((68, 18), Shift 16), ((68, 19), Shift 15), ((68, 21), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 24), Shift 25), ((68, 25), Shift 36), ((68, 26), Shift 21), ((68, 27), Shift 13), ((68, 28), Shift 26)
            , ((69, 1), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 3), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 4), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 5), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 6), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 8), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 9), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 10), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 11), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 15), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 16), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 17), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 18), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 19), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 21), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 24), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 25), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 26), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 27), Reduce (10, [TS 5, NS 11, TS 6])), ((69, 28), Reduce (10, [TS 5, NS 11, TS 6]))
            , ((70, 1), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 3), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 4), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 5), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 6), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 8), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 9), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 10), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 11), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 15), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 16), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 17), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 18), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 19), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 21), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 24), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 25), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 26), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 27), Reduce (10, [TS 3, NS 3, TS 4])), ((70, 28), Reduce (10, [TS 3, NS 3, TS 4]))
            , ((71, 0), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 3), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 5), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 12), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 13), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 14), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 16), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 17), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 18), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 19), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 22), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 23), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 24), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 25), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 26), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 27), Reduce (13, [TS 22, TS 24, NS 14, TS 1])), ((71, 28), Reduce (13, [TS 22, TS 24, NS 14, TS 1]))
            , ((72, 0), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 3), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 5), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 12), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 13), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 14), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 16), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 17), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 18), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 19), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 22), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 23), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 24), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 25), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 26), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 27), Reduce (13, [TS 23, TS 24, NS 16, TS 1])), ((72, 28), Reduce (13, [TS 23, TS 24, NS 16, TS 1]))
            , ((73, 4), Shift 80)
            , ((74, 3), Shift 52), ((74, 23), Shift 53)
            , ((75, 6), Reduce (11, [NS 8, TS 9, NS 11]))
            , ((76, 4), Shift 82)
            , ((77, 1), Reduce (17, [NS 17, NS 18])), ((77, 2), Reduce (17, [NS 17, NS 18])), ((77, 3), Reduce (17, [NS 17, NS 18])), ((77, 4), Reduce (17, [NS 17, NS 18])), ((77, 24), Reduce (17, [NS 17, NS 18])), ((77, 25), Reduce (17, [NS 17, NS 18]))
            , ((78, 3), Shift 58), ((78, 24), Shift 59), ((78, 25), Shift 57)
            , ((79, 1), Reduce (14, [NS 15, TS 2, NS 14])), ((79, 4), Reduce (14, [NS 15, TS 2, NS 14]))
            , ((80, 1), Reduce (15, [TS 3, NS 14, TS 4])), ((80, 2), Reduce (15, [TS 3, NS 14, TS 4])), ((80, 4), Reduce (15, [TS 3, NS 14, TS 4]))
            , ((81, 1), Reduce (16, [NS 17, TS 2, NS 16])), ((81, 4), Reduce (16, [NS 17, TS 2, NS 16]))
            , ((82, 1), Reduce (18, [TS 3, NS 16, TS 4])), ((82, 2), Reduce (18, [TS 3, NS 16, TS 4])), ((82, 3), Reduce (18, [TS 3, NS 16, TS 4])), ((82, 4), Reduce (18, [TS 3, NS 16, TS 4])), ((82, 24), Reduce (18, [TS 3, NS 16, TS 4])), ((82, 25), Reduce (18, [TS 3, NS 16, TS 4]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 12), ((0, 2), 2), ((0, 3), 3), ((0, 4), 4), ((0, 5), 5), ((0, 6), 6), ((0, 7), 7), ((0, 8), 8), ((0, 9), 9), ((0, 10), 10), ((0, 12), 11), ((0, 13), 1)
            , ((1, 3), 3), ((1, 4), 4), ((1, 5), 5), ((1, 6), 6), ((1, 7), 7), ((1, 8), 8), ((1, 9), 9), ((1, 10), 10), ((1, 12), 30), ((1, 13), 1)
            , ((9, 10), 48)
            , ((19, 8), 35), ((19, 9), 9), ((19, 10), 10), ((19, 11), 34)
            , ((20, 3), 39), ((20, 4), 4), ((20, 5), 5), ((20, 6), 6), ((20, 7), 7), ((20, 8), 8), ((20, 9), 9), ((20, 10), 10)
            , ((22, 8), 46), ((22, 9), 9), ((22, 10), 10)
            , ((23, 3), 38), ((23, 4), 4), ((23, 5), 5), ((23, 6), 6), ((23, 7), 7), ((23, 8), 8), ((23, 9), 9), ((23, 10), 10)
            , ((24, 8), 47), ((24, 9), 9), ((24, 10), 10)
            , ((32, 14), 50), ((32, 15), 51)
            , ((33, 16), 54), ((33, 17), 55), ((33, 18), 56)
            , ((40, 3), 62), ((40, 4), 4), ((40, 5), 5), ((40, 6), 6), ((40, 7), 7), ((40, 8), 8), ((40, 9), 9), ((40, 10), 10)
            , ((41, 5), 64), ((41, 6), 6), ((41, 7), 7), ((41, 8), 8), ((41, 9), 9), ((41, 10), 10)
            , ((42, 3), 63), ((42, 4), 4), ((42, 5), 5), ((42, 6), 6), ((42, 7), 7), ((42, 8), 8), ((42, 9), 9), ((42, 10), 10)
            , ((43, 7), 66), ((43, 8), 8), ((43, 9), 9), ((43, 10), 10)
            , ((44, 5), 65), ((44, 6), 6), ((44, 7), 7), ((44, 8), 8), ((44, 9), 9), ((44, 10), 10)
            , ((45, 7), 67), ((45, 8), 8), ((45, 9), 9), ((45, 10), 10)
            , ((49, 9), 68), ((49, 10), 10)
            , ((52, 14), 73), ((52, 15), 51)
            , ((55, 18), 77)
            , ((58, 16), 76), ((58, 17), 55), ((58, 18), 56)
            , ((60, 8), 35), ((60, 9), 9), ((60, 10), 10), ((60, 11), 75)
            , ((68, 10), 48)
            , ((74, 14), 79), ((74, 15), 51)
            , ((78, 16), 81), ((78, 17), 55), ((78, 18), 56)
            ]
        }

{- The canonical collection of LR(0) items is:
getParserSInfo :: ParserS -> ParserSInfo
getParserSInfo 0 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= . <TermRep0> `dot'"
        , "<Decl> ::= . `kind' `smallid' <KindRep0> `dot'"
        , "<Decl> ::= . `type' `smallid' <TypeRep0> `dot'"
        , "<Query> ::= . `quest' <TermRep0> `dot'"
        , "<TermRep0> ::= . <TermRep1>"
        , "<TermRep0> ::= . <TermRep1> `if' <TermRep0>"
        , "<TermRep0> ::= . `largeid' `bslash' <TermRep0>"
        , "<TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>"
        , "<TermRep1> ::= . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        , "<\\ACCEPT> ::= . <Either Query (Sequence Decl)> `\\$'"
        , "<Sequence Decl> ::= ."
        , "<Sequence Decl> ::= . <Decl> <Sequence Decl>"
        , "<Either Query (Sequence Decl)> ::= . <Query>"
        , "<Either Query (Sequence Decl)> ::= . <Sequence Decl>"
        ]
    , myNexts = 
        [ "<Decl> +-> 1"
        , "<Query> +-> 2"
        , "<TermRep0> +-> 3"
        , "<TermRep1> +-> 4"
        , "<TermRep2> +-> 5"
        , "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "<Sequence Decl> +-> 11"
        , "<Either Query (Sequence Decl)> +-> 12"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`kind' +-> 17"
        , "`largeid' +-> 18"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`quest' +-> 23"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`type' +-> 29"
        ]
    }
getParserSInfo 1 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= . <TermRep0> `dot'"
        , "<Decl> ::= . `kind' `smallid' <KindRep0> `dot'"
        , "<Decl> ::= . `type' `smallid' <TypeRep0> `dot'"
        , "<TermRep0> ::= . <TermRep1>"
        , "<TermRep0> ::= . <TermRep1> `if' <TermRep0>"
        , "<TermRep0> ::= . `largeid' `bslash' <TermRep0>"
        , "<TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>"
        , "<TermRep1> ::= . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        , "<Sequence Decl> ::= ."
        , "<Sequence Decl> ::= . <Decl> <Sequence Decl>"
        , "<Sequence Decl> ::= <Decl> . <Sequence Decl>"
        ]
    , myNexts = 
        [ "<Decl> +-> 1"
        , "<TermRep0> +-> 3"
        , "<TermRep1> +-> 4"
        , "<TermRep2> +-> 5"
        , "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`kind' +-> 17"
        , "`largeid' +-> 18"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`type' +-> 29"
        , "<Sequence Decl> +-> 30"
        ]
    }
getParserSInfo 2 = ParserSInfo
    { myItems = 
        [ "<Either Query (Sequence Decl)> ::= <Query> ."
        ]
    , myNexts = []
    }
getParserSInfo 3 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= <TermRep0> . `dot'"
        ]
    , myNexts = 
        [ "`dot' +-> 31"
        ]
    }
getParserSInfo 4 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= <TermRep1> ."
        , "<TermRep0> ::= <TermRep1> . `if' <TermRep0>"
        , "<TermRep1> ::= <TermRep1> . `semicolon' <TermRep2>"
        ]
    , myNexts = 
        [ "`if' +-> 40"
        , "`semicolon' +-> 41"
        ]
    }
getParserSInfo 5 = ParserSInfo
    { myItems = 
        [ "<TermRep1> ::= <TermRep2> ."
        ]
    , myNexts = []
    }
getParserSInfo 6 = ParserSInfo
    { myItems = 
        [ "<TermRep2> ::= <TermRep3> ."
        , "<TermRep2> ::= <TermRep3> . `fatarrow' <TermRep2>"
        , "<TermRep3> ::= <TermRep3> . `comma' <TermRep4>"
        ]
    , myNexts = 
        [ "`comma' +-> 43"
        , "`fatarrow' +-> 44"
        ]
    }
getParserSInfo 7 = ParserSInfo
    { myItems = 
        [ "<TermRep3> ::= <TermRep4> ."
        ]
    , myNexts = []
    }
getParserSInfo 8 = ParserSInfo
    { myItems = 
        [ "<TermRep4> ::= <TermRep5> ."
        , "<TermRep4> ::= <TermRep5> . `cons' <TermRep4>"
        ]
    , myNexts = 
        [ "`cons' +-> 45"
        ]
    }
getParserSInfo 9 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= <TermRep6> ."
        , "<TermRep5> ::= <TermRep6> . `eq' <TermRep6>"
        , "<TermRep6> ::= <TermRep6> . <TermRep7>"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep7> +-> 48"
        , "`eq' +-> 49"
        ]
    }
getParserSInfo 10 = ParserSInfo
    { myItems = 
        [ "<TermRep6> ::= <TermRep7> ."
        ]
    , myNexts = []
    }
getParserSInfo 11 = ParserSInfo
    { myItems = 
        [ "<Either Query (Sequence Decl)> ::= <Sequence Decl> ."
        ]
    , myNexts = []
    }
getParserSInfo 12 = ParserSInfo
    { myItems = 
        [ "<\\ACCEPT> ::= <Either Query (Sequence Decl)> . `\\$'"
        ]
    , myNexts = []
    }
getParserSInfo 13 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `chrlit' ."
        ]
    , myNexts = []
    }
getParserSInfo 14 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `cut' ."
        ]
    , myNexts = []
    }
getParserSInfo 15 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `debug' ."
        ]
    , myNexts = []
    }
getParserSInfo 16 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `fail' ."
        ]
    , myNexts = []
    }
getParserSInfo 17 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `kind' . `smallid' <KindRep0> `dot'"
        ]
    , myNexts = 
        [ "`smallid' +-> 32"
        ]
    }
getParserSInfo 18 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= `largeid' . `bslash' <TermRep0>"
        , "<TermRep7> ::= `largeid' ."
        ]
    , myNexts = 
        [ "`bslash' +-> 42"
        ]
    }
getParserSInfo 19 = ParserSInfo
    { myItems = 
        [ "<ListBody> ::= . <TermRep5>"
        , "<ListBody> ::= . <TermRep5> `comma' <ListBody>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        , "<TermRep7> ::= `lbracket' . <ListBody> `rbracket'"
        , "<TermRep7> ::= `lbracket' . `rbracket'"
        ]
    , myNexts = 
        [ "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "<ListBody> +-> 34"
        , "<TermRep5> +-> 35"
        , "`largeid' +-> 36"
        , "`rbracket' +-> 37"
        ]
    }
getParserSInfo 20 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= . <TermRep1>"
        , "<TermRep0> ::= . <TermRep1> `if' <TermRep0>"
        , "<TermRep0> ::= . `largeid' `bslash' <TermRep0>"
        , "<TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>"
        , "<TermRep1> ::= . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        , "<TermRep7> ::= `lparen' . <TermRep0> `rparen'"
        ]
    , myNexts = 
        [ "<TermRep1> +-> 4"
        , "<TermRep2> +-> 5"
        , "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`largeid' +-> 18"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "<TermRep0> +-> 39"
        ]
    }
getParserSInfo 21 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `natlit' ."
        ]
    , myNexts = []
    }
getParserSInfo 22 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep5> ::= `pi' . <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep5> +-> 46"
        ]
    }
getParserSInfo 23 = ParserSInfo
    { myItems = 
        [ "<Query> ::= `quest' . <TermRep0> `dot'"
        , "<TermRep0> ::= . <TermRep1>"
        , "<TermRep0> ::= . <TermRep1> `if' <TermRep0>"
        , "<TermRep0> ::= . `largeid' `bslash' <TermRep0>"
        , "<TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>"
        , "<TermRep1> ::= . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep1> +-> 4"
        , "<TermRep2> +-> 5"
        , "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`largeid' +-> 18"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "<TermRep0> +-> 38"
        ]
    }
getParserSInfo 24 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep5> ::= `sigma' . <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep5> +-> 47"
        ]
    }
getParserSInfo 25 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `smallid' ."
        ]
    , myNexts = []
    }
getParserSInfo 26 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `strlit' ."
        ]
    , myNexts = []
    }
getParserSInfo 27 = ParserSInfo
    { myItems = 
        [ "<TermRep6> ::= `succ' ."
        ]
    , myNexts = []
    }
getParserSInfo 28 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `true' ."
        ]
    , myNexts = []
    }
getParserSInfo 29 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `type' . `smallid' <TypeRep0> `dot'"
        ]
    , myNexts = 
        [ "`smallid' +-> 33"
        ]
    }
getParserSInfo 30 = ParserSInfo
    { myItems = 
        [ "<Sequence Decl> ::= <Decl> <Sequence Decl> ."
        ]
    , myNexts = []
    }
getParserSInfo 31 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= <TermRep0> `dot' ."
        ]
    , myNexts = []
    }
getParserSInfo 32 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `kind' `smallid' . <KindRep0> `dot'"
        , "<KindRep0> ::= . <KindRep1>"
        , "<KindRep0> ::= . <KindRep1> `arrow' <KindRep0>"
        , "<KindRep1> ::= . `lparen' <KindRep0> `rparen'"
        , "<KindRep1> ::= . `type'"
        ]
    , myNexts = 
        [ "<KindRep0> +-> 50"
        , "<KindRep1> +-> 51"
        , "`lparen' +-> 52"
        , "`type' +-> 53"
        ]
    }
getParserSInfo 33 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `type' `smallid' . <TypeRep0> `dot'"
        , "<TypeRep0> ::= . <TypeRep1>"
        , "<TypeRep0> ::= . <TypeRep1> `arrow' <TypeRep0>"
        , "<TypeRep1> ::= . <TypeRep1> <TypeRep2>"
        , "<TypeRep1> ::= . <TypeRep2>"
        , "<TypeRep2> ::= . `largeid'"
        , "<TypeRep2> ::= . `lparen' <TypeRep0> `rparen'"
        , "<TypeRep2> ::= . `smallid'"
        ]
    , myNexts = 
        [ "<TypeRep0> +-> 54"
        , "<TypeRep1> +-> 55"
        , "<TypeRep2> +-> 56"
        , "`largeid' +-> 57"
        , "`lparen' +-> 58"
        , "`smallid' +-> 59"
        ]
    }
getParserSInfo 34 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `lbracket' <ListBody> . `rbracket'"
        ]
    , myNexts = 
        [ "`rbracket' +-> 69"
        ]
    }
getParserSInfo 35 = ParserSInfo
    { myItems = 
        [ "<ListBody> ::= <TermRep5> ."
        , "<ListBody> ::= <TermRep5> . `comma' <ListBody>"
        ]
    , myNexts = 
        [ "`comma' +-> 60"
        ]
    }
getParserSInfo 36 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `largeid' ."
        ]
    , myNexts = []
    }
getParserSInfo 37 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `lbracket' `rbracket' ."
        ]
    , myNexts = []
    }
getParserSInfo 38 = ParserSInfo
    { myItems = 
        [ "<Query> ::= `quest' <TermRep0> . `dot'"
        ]
    , myNexts = 
        [ "`dot' +-> 61"
        ]
    }
getParserSInfo 39 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `lparen' <TermRep0> . `rparen'"
        ]
    , myNexts = 
        [ "`rparen' +-> 70"
        ]
    }
getParserSInfo 40 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= . <TermRep1>"
        , "<TermRep0> ::= . <TermRep1> `if' <TermRep0>"
        , "<TermRep0> ::= . `largeid' `bslash' <TermRep0>"
        , "<TermRep0> ::= <TermRep1> `if' . <TermRep0>"
        , "<TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>"
        , "<TermRep1> ::= . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep1> +-> 4"
        , "<TermRep2> +-> 5"
        , "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`largeid' +-> 18"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "<TermRep0> +-> 62"
        ]
    }
getParserSInfo 41 = ParserSInfo
    { myItems = 
        [ "<TermRep1> ::= <TermRep1> `semicolon' . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep2> +-> 64"
        ]
    }
getParserSInfo 42 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= . <TermRep1>"
        , "<TermRep0> ::= . <TermRep1> `if' <TermRep0>"
        , "<TermRep0> ::= . `largeid' `bslash' <TermRep0>"
        , "<TermRep0> ::= `largeid' `bslash' . <TermRep0>"
        , "<TermRep1> ::= . <TermRep1> `semicolon' <TermRep2>"
        , "<TermRep1> ::= . <TermRep2>"
        , "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep1> +-> 4"
        , "<TermRep2> +-> 5"
        , "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`largeid' +-> 18"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "<TermRep0> +-> 63"
        ]
    }
getParserSInfo 43 = ParserSInfo
    { myItems = 
        [ "<TermRep3> ::= <TermRep3> `comma' . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep4> +-> 66"
        ]
    }
getParserSInfo 44 = ParserSInfo
    { myItems = 
        [ "<TermRep2> ::= . <TermRep3>"
        , "<TermRep2> ::= . <TermRep3> `fatarrow' <TermRep2>"
        , "<TermRep2> ::= <TermRep3> `fatarrow' . <TermRep2>"
        , "<TermRep3> ::= . <TermRep3> `comma' <TermRep4>"
        , "<TermRep3> ::= . <TermRep4>"
        , "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep3> +-> 6"
        , "<TermRep4> +-> 7"
        , "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep2> +-> 65"
        ]
    }
getParserSInfo 45 = ParserSInfo
    { myItems = 
        [ "<TermRep4> ::= . <TermRep5>"
        , "<TermRep4> ::= . <TermRep5> `cons' <TermRep4>"
        , "<TermRep4> ::= <TermRep5> `cons' . <TermRep4>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep5> +-> 8"
        , "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep4> +-> 67"
        ]
    }
getParserSInfo 46 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= `pi' <TermRep5> ."
        ]
    , myNexts = []
    }
getParserSInfo 47 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= `sigma' <TermRep5> ."
        ]
    , myNexts = []
    }
getParserSInfo 48 = ParserSInfo
    { myItems = 
        [ "<TermRep6> ::= <TermRep6> <TermRep7> ."
        ]
    , myNexts = []
    }
getParserSInfo 49 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= <TermRep6> `eq' . <TermRep6>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep6> +-> 68"
        ]
    }
getParserSInfo 50 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `kind' `smallid' <KindRep0> . `dot'"
        ]
    , myNexts = 
        [ "`dot' +-> 71"
        ]
    }
getParserSInfo 51 = ParserSInfo
    { myItems = 
        [ "<KindRep0> ::= <KindRep1> ."
        , "<KindRep0> ::= <KindRep1> . `arrow' <KindRep0>"
        ]
    , myNexts = 
        [ "`arrow' +-> 74"
        ]
    }
getParserSInfo 52 = ParserSInfo
    { myItems = 
        [ "<KindRep0> ::= . <KindRep1>"
        , "<KindRep0> ::= . <KindRep1> `arrow' <KindRep0>"
        , "<KindRep1> ::= . `lparen' <KindRep0> `rparen'"
        , "<KindRep1> ::= . `type'"
        , "<KindRep1> ::= `lparen' . <KindRep0> `rparen'"
        ]
    , myNexts = 
        [ "<KindRep1> +-> 51"
        , "`lparen' +-> 52"
        , "`type' +-> 53"
        , "<KindRep0> +-> 73"
        ]
    }
getParserSInfo 53 = ParserSInfo
    { myItems = 
        [ "<KindRep1> ::= `type' ."
        ]
    , myNexts = []
    }
getParserSInfo 54 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `type' `smallid' <TypeRep0> . `dot'"
        ]
    , myNexts = 
        [ "`dot' +-> 72"
        ]
    }
getParserSInfo 55 = ParserSInfo
    { myItems = 
        [ "<TypeRep0> ::= <TypeRep1> ."
        , "<TypeRep0> ::= <TypeRep1> . `arrow' <TypeRep0>"
        , "<TypeRep1> ::= <TypeRep1> . <TypeRep2>"
        , "<TypeRep2> ::= . `largeid'"
        , "<TypeRep2> ::= . `lparen' <TypeRep0> `rparen'"
        , "<TypeRep2> ::= . `smallid'"
        ]
    , myNexts = 
        [ "`largeid' +-> 57"
        , "`lparen' +-> 58"
        , "`smallid' +-> 59"
        , "<TypeRep2> +-> 77"
        , "`arrow' +-> 78"
        ]
    }
getParserSInfo 56 = ParserSInfo
    { myItems = 
        [ "<TypeRep1> ::= <TypeRep2> ."
        ]
    , myNexts = []
    }
getParserSInfo 57 = ParserSInfo
    { myItems = 
        [ "<TypeRep2> ::= `largeid' ."
        ]
    , myNexts = []
    }
getParserSInfo 58 = ParserSInfo
    { myItems = 
        [ "<TypeRep0> ::= . <TypeRep1>"
        , "<TypeRep0> ::= . <TypeRep1> `arrow' <TypeRep0>"
        , "<TypeRep1> ::= . <TypeRep1> <TypeRep2>"
        , "<TypeRep1> ::= . <TypeRep2>"
        , "<TypeRep2> ::= . `largeid'"
        , "<TypeRep2> ::= . `lparen' <TypeRep0> `rparen'"
        , "<TypeRep2> ::= . `smallid'"
        , "<TypeRep2> ::= `lparen' . <TypeRep0> `rparen'"
        ]
    , myNexts = 
        [ "<TypeRep1> +-> 55"
        , "<TypeRep2> +-> 56"
        , "`largeid' +-> 57"
        , "`lparen' +-> 58"
        , "`smallid' +-> 59"
        , "<TypeRep0> +-> 76"
        ]
    }
getParserSInfo 59 = ParserSInfo
    { myItems = 
        [ "<TypeRep2> ::= `smallid' ."
        ]
    , myNexts = []
    }
getParserSInfo 60 = ParserSInfo
    { myItems = 
        [ "<ListBody> ::= . <TermRep5>"
        , "<ListBody> ::= . <TermRep5> `comma' <ListBody>"
        , "<ListBody> ::= <TermRep5> `comma' . <ListBody>"
        , "<TermRep5> ::= . <TermRep6>"
        , "<TermRep5> ::= . <TermRep6> `eq' <TermRep6>"
        , "<TermRep5> ::= . `pi' <TermRep5>"
        , "<TermRep5> ::= . `sigma' <TermRep5>"
        , "<TermRep6> ::= . <TermRep6> <TermRep7>"
        , "<TermRep6> ::= . <TermRep7>"
        , "<TermRep6> ::= . `succ'"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "<TermRep6> +-> 9"
        , "<TermRep7> +-> 10"
        , "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`pi' +-> 22"
        , "`sigma' +-> 24"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`succ' +-> 27"
        , "`true' +-> 28"
        , "<TermRep5> +-> 35"
        , "`largeid' +-> 36"
        , "<ListBody> +-> 75"
        ]
    }
getParserSInfo 61 = ParserSInfo
    { myItems = 
        [ "<Query> ::= `quest' <TermRep0> `dot' ."
        ]
    , myNexts = []
    }
getParserSInfo 62 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= <TermRep1> `if' <TermRep0> ."
        ]
    , myNexts = []
    }
getParserSInfo 63 = ParserSInfo
    { myItems = 
        [ "<TermRep0> ::= `largeid' `bslash' <TermRep0> ."
        ]
    , myNexts = []
    }
getParserSInfo 64 = ParserSInfo
    { myItems = 
        [ "<TermRep1> ::= <TermRep1> `semicolon' <TermRep2> ."
        ]
    , myNexts = []
    }
getParserSInfo 65 = ParserSInfo
    { myItems = 
        [ "<TermRep2> ::= <TermRep3> `fatarrow' <TermRep2> ."
        ]
    , myNexts = []
    }
getParserSInfo 66 = ParserSInfo
    { myItems = 
        [ "<TermRep3> ::= <TermRep3> `comma' <TermRep4> ."
        ]
    , myNexts = []
    }
getParserSInfo 67 = ParserSInfo
    { myItems = 
        [ "<TermRep4> ::= <TermRep5> `cons' <TermRep4> ."
        ]
    , myNexts = []
    }
getParserSInfo 68 = ParserSInfo
    { myItems = 
        [ "<TermRep5> ::= <TermRep6> `eq' <TermRep6> ."
        , "<TermRep6> ::= <TermRep6> . <TermRep7>"
        , "<TermRep7> ::= . `chrlit'"
        , "<TermRep7> ::= . `cut'"
        , "<TermRep7> ::= . `debug'"
        , "<TermRep7> ::= . `fail'"
        , "<TermRep7> ::= . `largeid'"
        , "<TermRep7> ::= . `lbracket' <ListBody> `rbracket'"
        , "<TermRep7> ::= . `lbracket' `rbracket'"
        , "<TermRep7> ::= . `lparen' <TermRep0> `rparen'"
        , "<TermRep7> ::= . `natlit'"
        , "<TermRep7> ::= . `smallid'"
        , "<TermRep7> ::= . `strlit'"
        , "<TermRep7> ::= . `true'"
        ]
    , myNexts = 
        [ "`chrlit' +-> 13"
        , "`cut' +-> 14"
        , "`debug' +-> 15"
        , "`fail' +-> 16"
        , "`lbracket' +-> 19"
        , "`lparen' +-> 20"
        , "`natlit' +-> 21"
        , "`smallid' +-> 25"
        , "`strlit' +-> 26"
        , "`true' +-> 28"
        , "`largeid' +-> 36"
        , "<TermRep7> +-> 48"
        ]
    }
getParserSInfo 69 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `lbracket' <ListBody> `rbracket' ."
        ]
    , myNexts = []
    }
getParserSInfo 70 = ParserSInfo
    { myItems = 
        [ "<TermRep7> ::= `lparen' <TermRep0> `rparen' ."
        ]
    , myNexts = []
    }
getParserSInfo 71 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `kind' `smallid' <KindRep0> `dot' ."
        ]
    , myNexts = []
    }
getParserSInfo 72 = ParserSInfo
    { myItems = 
        [ "<Decl> ::= `type' `smallid' <TypeRep0> `dot' ."
        ]
    , myNexts = []
    }
getParserSInfo 73 = ParserSInfo
    { myItems = 
        [ "<KindRep1> ::= `lparen' <KindRep0> . `rparen'"
        ]
    , myNexts = 
        [ "`rparen' +-> 80"
        ]
    }
getParserSInfo 74 = ParserSInfo
    { myItems = 
        [ "<KindRep0> ::= . <KindRep1>"
        , "<KindRep0> ::= . <KindRep1> `arrow' <KindRep0>"
        , "<KindRep0> ::= <KindRep1> `arrow' . <KindRep0>"
        , "<KindRep1> ::= . `lparen' <KindRep0> `rparen'"
        , "<KindRep1> ::= . `type'"
        ]
    , myNexts = 
        [ "<KindRep1> +-> 51"
        , "`lparen' +-> 52"
        , "`type' +-> 53"
        , "<KindRep0> +-> 79"
        ]
    }
getParserSInfo 75 = ParserSInfo
    { myItems = 
        [ "<ListBody> ::= <TermRep5> `comma' <ListBody> ."
        ]
    , myNexts = []
    }
getParserSInfo 76 = ParserSInfo
    { myItems = 
        [ "<TypeRep2> ::= `lparen' <TypeRep0> . `rparen'"
        ]
    , myNexts = 
        [ "`rparen' +-> 82"
        ]
    }
getParserSInfo 77 = ParserSInfo
    { myItems = 
        [ "<TypeRep1> ::= <TypeRep1> <TypeRep2> ."
        ]
    , myNexts = []
    }
getParserSInfo 78 = ParserSInfo
    { myItems = 
        [ "<TypeRep0> ::= . <TypeRep1>"
        , "<TypeRep0> ::= . <TypeRep1> `arrow' <TypeRep0>"
        , "<TypeRep0> ::= <TypeRep1> `arrow' . <TypeRep0>"
        , "<TypeRep1> ::= . <TypeRep1> <TypeRep2>"
        , "<TypeRep1> ::= . <TypeRep2>"
        , "<TypeRep2> ::= . `largeid'"
        , "<TypeRep2> ::= . `lparen' <TypeRep0> `rparen'"
        , "<TypeRep2> ::= . `smallid'"
        ]
    , myNexts = 
        [ "<TypeRep1> +-> 55"
        , "<TypeRep2> +-> 56"
        , "`largeid' +-> 57"
        , "`lparen' +-> 58"
        , "`smallid' +-> 59"
        , "<TypeRep0> +-> 81"
        ]
    }
getParserSInfo 79 = ParserSInfo
    { myItems = 
        [ "<KindRep0> ::= <KindRep1> `arrow' <KindRep0> ."
        ]
    , myNexts = []
    }
getParserSInfo 80 = ParserSInfo
    { myItems = 
        [ "<KindRep1> ::= `lparen' <KindRep0> `rparen' ."
        ]
    , myNexts = []
    }
getParserSInfo 81 = ParserSInfo
    { myItems = 
        [ "<TypeRep0> ::= <TypeRep1> `arrow' <TypeRep0> ."
        ]
    , myNexts = []
    }
getParserSInfo 82 = ParserSInfo
    { myItems = 
        [ "<TypeRep2> ::= `lparen' <TypeRep0> `rparen' ."
        ]
    , myNexts = []
    }
-}
