module ALPHA2.PlanHolParser where

import ALPHA2.Header
import ALPHA2.PlanHolLexer
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

-- the following codes are generated by PGS.

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()

runHolParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runHolParser = fmap (getEither getQuery (getSequence getDecl)) . runLALR1 theLALR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] = (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[20]] = RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[22]] = RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] = RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[21, 20]] = RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[21]] = (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise = RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[20]] = RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[23, 22]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[23]] = (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[23, 24]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[24]] = (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = if head (contents_1) `elem` ['A' .. 'Z'] then RTyVar (loc_1) (contents_1) else RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[22]] = RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_id loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] = RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] = (getTermRep1L0 _1)
    getTermRep1L0 :: ParsingTree -> (TermRep)
    getTermRep1L0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[5, 5]] = RApp (getSLoc (getTermRep1L1 _1) <> getSLoc (getTermRep1L1 _3)) (RApp (getSLoc (getTermRep1L1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1L1 _1)) (getTermRep1L1 _3)
    getTermRep1L0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] = (getTermRep1L1 _1)
    getTermRep1L1 :: ParsingTree -> (TermRep)
    getTermRep1L1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[5, 6]] = RApp (getSLoc (getTermRep1L1 _1) <> getSLoc (getTermRep1L2 _3)) (RApp (getSLoc (getTermRep1L1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1L1 _1)) (getTermRep1L2 _3)
    getTermRep1L1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] = (getTermRep1L2 _1)
    getTermRep1L2 :: ParsingTree -> (TermRep)
    getTermRep1L2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[7, 6]] = RApp (getSLoc (getTermRep1L3 _1) <> getSLoc (getTermRep1L2 _3)) (RApp (getSLoc (getTermRep1L3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep1L3 _1)) (getTermRep1L2 _3)
    getTermRep1L2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] = (getTermRep1L3 _1)
    getTermRep1L3 :: ParsingTree -> (TermRep)
    getTermRep1L3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[7, 8]] = RApp (getSLoc (getTermRep1L3 _1) <> getSLoc (getTermRep1L4 _3)) (RApp (getSLoc (getTermRep1L3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep1L3 _1)) (getTermRep1L4 _3)
    getTermRep1L3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = (getTermRep1L4 _1)
    getTermRep1L4 :: ParsingTree -> (TermRep)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_is loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_is)) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_eq) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_le loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_le) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_lt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_lt) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_ge loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_ge) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_gt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_gt) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = (getTermRep1L5 _1)
    getTermRep1L5 :: ParsingTree -> (TermRep)
    getTermRep1L5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 9]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep1L6 _1)) (getTermRep1L5 _3)
    getTermRep1L5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] = (getTermRep1L6 _1)
    getTermRep1L6 :: ParsingTree -> (TermRep)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_plus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L7 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_plus) (getTermRep1L6 _1)) (getTermRep1L7 _3)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_minus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L7 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_minus) (getTermRep1L6 _1)) (getTermRep1L7 _3)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[11]] = (getTermRep1L7 _1)
    getTermRep1L7 :: ParsingTree -> (TermRep)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_star loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[11, 12]] = RApp (getSLoc (getTermRep1L7 _1) <> getSLoc (getTermRep1L8 _3)) (RApp (getSLoc (getTermRep1L7 _1) <> (loc_2)) (RCon (loc_2) DC_mul) (getTermRep1L7 _1)) (getTermRep1L8 _3)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_slash loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[11, 12]] = RApp (getSLoc (getTermRep1L7 _1) <> getSLoc (getTermRep1L8 _3)) (RApp (getSLoc (getTermRep1L7 _1) <> (loc_2)) (RCon (loc_2) DC_div) (getTermRep1L7 _1)) (getTermRep1L8 _3)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] = (getTermRep1L8 _1)
    getTermRep1L8 :: ParsingTree -> (TermRep)
    getTermRep1L8 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[13]] = (getTermRep1L9 _1)
    getTermRep1L9 :: ParsingTree -> (TermRep)
    getTermRep1L9 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[14]] = (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_bslash loc_3), _4@(PTBranch guard4 _)])
        | [guard1, guard4] `elem` [[15, 3]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep0 _4)) (getTermRep3 _1) (RAbs ((loc_2) <> getSLoc (getTermRep0 _4)) (contents_2) (getTermRep0 _4))
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[15]] = (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[15, 16]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _2)) (getTermRep3 _1) (getTermRep4 _2)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[16]] = (getTermRep4 _1)
    getTermRep3 (PTBranch _ [PTLeaf (T_pi loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_pi)
    getTermRep3 (PTBranch _ [PTLeaf (T_sigma loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_sigma)
    getTermRep3 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise = RCon (loc_1) DC_Succ
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] = RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep4 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_cut)
    getTermRep4 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_true)
    getTermRep4 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_fail)
    getTermRep4 (PTBranch _ [PTLeaf (T_debug loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_debug)
    getTermRep4 (PTBranch _ [PTLeaf (T_wildcard loc_1)])
        | otherwise = R_wc (loc_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = if head (contents_1) `elem` ['A' .. 'Z'] then RVar (loc_1) (contents_1) else RCon (loc_1) (DC_Named (contents_1))
    getTermRep4 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise = mkNatLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise = mkStrLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise = mkChrLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise = RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep4 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[17]] = RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = RApp (getSLoc (getTermRep1L5 _1)) (RApp (getSLoc (getTermRep1L5 _1)) (RCon (getSLoc (getTermRep1L5 _1)) DC_Cons) (getTermRep1L5 _1)) (RCon (getSLoc (getTermRep1L5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 17]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep1L5 _1)) (getListBody _3)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise = []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[19, 18]] = (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] = Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[18]] = Right (getRight _1)
    toTerminal :: (Token) -> TSym
    toTerminal (T_wildcard loc) = 1
    toTerminal (T_dot loc) = 2
    toTerminal (T_arrow loc) = 3
    toTerminal (T_lparen loc) = 4
    toTerminal (T_rparen loc) = 5
    toTerminal (T_lbracket loc) = 6
    toTerminal (T_rbracket loc) = 7
    toTerminal (T_quest loc) = 8
    toTerminal (T_pi loc) = 9
    toTerminal (T_sigma loc) = 10
    toTerminal (T_succ loc) = 11
    toTerminal (T_bslash loc) = 12
    toTerminal (T_if loc) = 13
    toTerminal (T_semicolon loc) = 14
    toTerminal (T_fatarrow loc) = 15
    toTerminal (T_comma loc) = 16
    toTerminal (T_eq loc) = 17
    toTerminal (T_le loc) = 18
    toTerminal (T_lt loc) = 19
    toTerminal (T_ge loc) = 20
    toTerminal (T_gt loc) = 21
    toTerminal (T_is loc) = 22
    toTerminal (T_cons loc) = 23
    toTerminal (T_plus loc) = 24
    toTerminal (T_minus loc) = 25
    toTerminal (T_star loc) = 26
    toTerminal (T_slash loc) = 27
    toTerminal (T_cut loc) = 28
    toTerminal (T_true loc) = 29
    toTerminal (T_fail loc) = 30
    toTerminal (T_debug loc) = 31
    toTerminal (T_kind loc) = 32
    toTerminal (T_type loc) = 33
    toTerminal (T_id loc contents) = 34
    toTerminal (T_nat_lit loc contents) = 35
    toTerminal (T_chr_lit loc contents) = 36
    toTerminal (T_str_lit loc contents) = 37
    runLALR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLALR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLALR1Parser :: LR1Parser
    theLALR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (18, [])), ((0, 1), Shift 35), ((0, 4), Shift 26), ((0, 6), Shift 25), ((0, 8), Shift 29), ((0, 9), Shift 28), ((0, 10), Shift 30), ((0, 11), Shift 32), ((0, 28), Shift 20), ((0, 29), Shift 33), ((0, 30), Shift 22), ((0, 31), Shift 21), ((0, 32), Shift 24), ((0, 33), Shift 34), ((0, 34), Shift 23), ((0, 35), Shift 27), ((0, 36), Shift 19), ((0, 37), Shift 31)
            , ((1, 0), Reduce (18, [])), ((1, 1), Shift 35), ((1, 4), Shift 26), ((1, 6), Shift 25), ((1, 9), Shift 28), ((1, 10), Shift 30), ((1, 11), Shift 32), ((1, 28), Shift 20), ((1, 29), Shift 33), ((1, 30), Shift 22), ((1, 31), Shift 21), ((1, 32), Shift 24), ((1, 33), Shift 34), ((1, 34), Shift 23), ((1, 35), Shift 27), ((1, 36), Shift 19), ((1, 37), Shift 31)
            , ((2, 0), Reduce (1, [NS 2]))
            , ((3, 2), Shift 37)
            , ((4, 2), Reduce (3, [NS 4])), ((4, 5), Reduce (3, [NS 4])), ((4, 7), Reduce (3, [NS 4])), ((4, 13), Reduce (3, [NS 4])), ((4, 14), Reduce (3, [NS 4])), ((4, 15), Reduce (3, [NS 4])), ((4, 16), Reduce (3, [NS 4])), ((4, 17), Reduce (3, [NS 4])), ((4, 18), Reduce (3, [NS 4])), ((4, 19), Reduce (3, [NS 4])), ((4, 20), Reduce (3, [NS 4])), ((4, 21), Reduce (3, [NS 4])), ((4, 22), Reduce (3, [NS 4])), ((4, 23), Reduce (3, [NS 4])), ((4, 24), Reduce (3, [NS 4])), ((4, 25), Reduce (3, [NS 4])), ((4, 26), Reduce (3, [NS 4])), ((4, 27), Reduce (3, [NS 4]))
            , ((5, 2), Reduce (4, [NS 5])), ((5, 5), Reduce (4, [NS 5])), ((5, 7), Reduce (4, [NS 5])), ((5, 13), Shift 38), ((5, 14), Shift 39), ((5, 15), Reduce (4, [NS 5])), ((5, 16), Reduce (4, [NS 5])), ((5, 17), Reduce (4, [NS 5])), ((5, 18), Reduce (4, [NS 5])), ((5, 19), Reduce (4, [NS 5])), ((5, 20), Reduce (4, [NS 5])), ((5, 21), Reduce (4, [NS 5])), ((5, 22), Reduce (4, [NS 5])), ((5, 23), Reduce (4, [NS 5])), ((5, 24), Reduce (4, [NS 5])), ((5, 25), Reduce (4, [NS 5])), ((5, 26), Reduce (4, [NS 5])), ((5, 27), Reduce (4, [NS 5]))
            , ((6, 2), Reduce (5, [NS 6])), ((6, 5), Reduce (5, [NS 6])), ((6, 7), Reduce (5, [NS 6])), ((6, 13), Reduce (5, [NS 6])), ((6, 14), Reduce (5, [NS 6])), ((6, 15), Reduce (5, [NS 6])), ((6, 16), Reduce (5, [NS 6])), ((6, 17), Reduce (5, [NS 6])), ((6, 18), Reduce (5, [NS 6])), ((6, 19), Reduce (5, [NS 6])), ((6, 20), Reduce (5, [NS 6])), ((6, 21), Reduce (5, [NS 6])), ((6, 22), Reduce (5, [NS 6])), ((6, 23), Reduce (5, [NS 6])), ((6, 24), Reduce (5, [NS 6])), ((6, 25), Reduce (5, [NS 6])), ((6, 26), Reduce (5, [NS 6])), ((6, 27), Reduce (5, [NS 6]))
            , ((7, 2), Reduce (6, [NS 7])), ((7, 5), Reduce (6, [NS 7])), ((7, 7), Reduce (6, [NS 7])), ((7, 13), Reduce (6, [NS 7])), ((7, 14), Reduce (6, [NS 7])), ((7, 15), Shift 41), ((7, 16), Shift 40), ((7, 17), Reduce (6, [NS 7])), ((7, 18), Reduce (6, [NS 7])), ((7, 19), Reduce (6, [NS 7])), ((7, 20), Reduce (6, [NS 7])), ((7, 21), Reduce (6, [NS 7])), ((7, 22), Reduce (6, [NS 7])), ((7, 23), Reduce (6, [NS 7])), ((7, 24), Reduce (6, [NS 7])), ((7, 25), Reduce (6, [NS 7])), ((7, 26), Reduce (6, [NS 7])), ((7, 27), Reduce (6, [NS 7]))
            , ((8, 2), Reduce (7, [NS 8])), ((8, 5), Reduce (7, [NS 8])), ((8, 7), Reduce (7, [NS 8])), ((8, 13), Reduce (7, [NS 8])), ((8, 14), Reduce (7, [NS 8])), ((8, 15), Reduce (7, [NS 8])), ((8, 16), Reduce (7, [NS 8])), ((8, 17), Reduce (7, [NS 8])), ((8, 18), Reduce (7, [NS 8])), ((8, 19), Reduce (7, [NS 8])), ((8, 20), Reduce (7, [NS 8])), ((8, 21), Reduce (7, [NS 8])), ((8, 22), Reduce (7, [NS 8])), ((8, 23), Reduce (7, [NS 8])), ((8, 24), Reduce (7, [NS 8])), ((8, 25), Reduce (7, [NS 8])), ((8, 26), Reduce (7, [NS 8])), ((8, 27), Reduce (7, [NS 8]))
            , ((9, 2), Reduce (8, [NS 9])), ((9, 5), Reduce (8, [NS 9])), ((9, 7), Reduce (8, [NS 9])), ((9, 13), Reduce (8, [NS 9])), ((9, 14), Reduce (8, [NS 9])), ((9, 15), Reduce (8, [NS 9])), ((9, 16), Reduce (8, [NS 9])), ((9, 17), Shift 42), ((9, 18), Shift 46), ((9, 19), Shift 47), ((9, 20), Shift 43), ((9, 21), Shift 44), ((9, 22), Shift 45), ((9, 23), Reduce (8, [NS 9])), ((9, 24), Reduce (8, [NS 9])), ((9, 25), Reduce (8, [NS 9])), ((9, 26), Reduce (8, [NS 9])), ((9, 27), Reduce (8, [NS 9]))
            , ((10, 2), Reduce (9, [NS 10])), ((10, 5), Reduce (9, [NS 10])), ((10, 7), Reduce (9, [NS 10])), ((10, 13), Reduce (9, [NS 10])), ((10, 14), Reduce (9, [NS 10])), ((10, 15), Reduce (9, [NS 10])), ((10, 16), Reduce (9, [NS 10])), ((10, 17), Reduce (9, [NS 10])), ((10, 18), Reduce (9, [NS 10])), ((10, 19), Reduce (9, [NS 10])), ((10, 20), Reduce (9, [NS 10])), ((10, 21), Reduce (9, [NS 10])), ((10, 22), Reduce (9, [NS 10])), ((10, 23), Shift 48), ((10, 24), Shift 50), ((10, 25), Shift 49), ((10, 26), Reduce (9, [NS 10])), ((10, 27), Reduce (9, [NS 10]))
            , ((11, 2), Reduce (10, [NS 11])), ((11, 5), Reduce (10, [NS 11])), ((11, 7), Reduce (10, [NS 11])), ((11, 13), Reduce (10, [NS 11])), ((11, 14), Reduce (10, [NS 11])), ((11, 15), Reduce (10, [NS 11])), ((11, 16), Reduce (10, [NS 11])), ((11, 17), Reduce (10, [NS 11])), ((11, 18), Reduce (10, [NS 11])), ((11, 19), Reduce (10, [NS 11])), ((11, 20), Reduce (10, [NS 11])), ((11, 21), Reduce (10, [NS 11])), ((11, 22), Reduce (10, [NS 11])), ((11, 23), Reduce (10, [NS 11])), ((11, 24), Reduce (10, [NS 11])), ((11, 25), Reduce (10, [NS 11])), ((11, 26), Shift 52), ((11, 27), Shift 51)
            , ((12, 2), Reduce (11, [NS 12])), ((12, 5), Reduce (11, [NS 12])), ((12, 7), Reduce (11, [NS 12])), ((12, 13), Reduce (11, [NS 12])), ((12, 14), Reduce (11, [NS 12])), ((12, 15), Reduce (11, [NS 12])), ((12, 16), Reduce (11, [NS 12])), ((12, 17), Reduce (11, [NS 12])), ((12, 18), Reduce (11, [NS 12])), ((12, 19), Reduce (11, [NS 12])), ((12, 20), Reduce (11, [NS 12])), ((12, 21), Reduce (11, [NS 12])), ((12, 22), Reduce (11, [NS 12])), ((12, 23), Reduce (11, [NS 12])), ((12, 24), Reduce (11, [NS 12])), ((12, 25), Reduce (11, [NS 12])), ((12, 26), Reduce (11, [NS 12])), ((12, 27), Reduce (11, [NS 12]))
            , ((13, 2), Reduce (12, [NS 13])), ((13, 5), Reduce (12, [NS 13])), ((13, 7), Reduce (12, [NS 13])), ((13, 13), Reduce (12, [NS 13])), ((13, 14), Reduce (12, [NS 13])), ((13, 15), Reduce (12, [NS 13])), ((13, 16), Reduce (12, [NS 13])), ((13, 17), Reduce (12, [NS 13])), ((13, 18), Reduce (12, [NS 13])), ((13, 19), Reduce (12, [NS 13])), ((13, 20), Reduce (12, [NS 13])), ((13, 21), Reduce (12, [NS 13])), ((13, 22), Reduce (12, [NS 13])), ((13, 23), Reduce (12, [NS 13])), ((13, 24), Reduce (12, [NS 13])), ((13, 25), Reduce (12, [NS 13])), ((13, 26), Reduce (12, [NS 13])), ((13, 27), Reduce (12, [NS 13]))
            , ((14, 2), Reduce (13, [NS 14])), ((14, 5), Reduce (13, [NS 14])), ((14, 7), Reduce (13, [NS 14])), ((14, 13), Reduce (13, [NS 14])), ((14, 14), Reduce (13, [NS 14])), ((14, 15), Reduce (13, [NS 14])), ((14, 16), Reduce (13, [NS 14])), ((14, 17), Reduce (13, [NS 14])), ((14, 18), Reduce (13, [NS 14])), ((14, 19), Reduce (13, [NS 14])), ((14, 20), Reduce (13, [NS 14])), ((14, 21), Reduce (13, [NS 14])), ((14, 22), Reduce (13, [NS 14])), ((14, 23), Reduce (13, [NS 14])), ((14, 24), Reduce (13, [NS 14])), ((14, 25), Reduce (13, [NS 14])), ((14, 26), Reduce (13, [NS 14])), ((14, 27), Reduce (13, [NS 14]))
            , ((15, 1), Shift 35), ((15, 2), Reduce (14, [NS 15])), ((15, 4), Shift 26), ((15, 5), Reduce (14, [NS 15])), ((15, 6), Shift 25), ((15, 7), Reduce (14, [NS 15])), ((15, 13), Reduce (14, [NS 15])), ((15, 14), Reduce (14, [NS 15])), ((15, 15), Reduce (14, [NS 15])), ((15, 16), Reduce (14, [NS 15])), ((15, 17), Reduce (14, [NS 15])), ((15, 18), Reduce (14, [NS 15])), ((15, 19), Reduce (14, [NS 15])), ((15, 20), Reduce (14, [NS 15])), ((15, 21), Reduce (14, [NS 15])), ((15, 22), Reduce (14, [NS 15])), ((15, 23), Reduce (14, [NS 15])), ((15, 24), Reduce (14, [NS 15])), ((15, 25), Reduce (14, [NS 15])), ((15, 26), Reduce (14, [NS 15])), ((15, 27), Reduce (14, [NS 15])), ((15, 28), Shift 20), ((15, 29), Shift 33), ((15, 30), Shift 22), ((15, 31), Shift 21), ((15, 34), Shift 54), ((15, 35), Shift 27), ((15, 36), Shift 19), ((15, 37), Shift 31)
            , ((16, 1), Reduce (15, [NS 16])), ((16, 2), Reduce (15, [NS 16])), ((16, 4), Reduce (15, [NS 16])), ((16, 5), Reduce (15, [NS 16])), ((16, 6), Reduce (15, [NS 16])), ((16, 7), Reduce (15, [NS 16])), ((16, 13), Reduce (15, [NS 16])), ((16, 14), Reduce (15, [NS 16])), ((16, 15), Reduce (15, [NS 16])), ((16, 16), Reduce (15, [NS 16])), ((16, 17), Reduce (15, [NS 16])), ((16, 18), Reduce (15, [NS 16])), ((16, 19), Reduce (15, [NS 16])), ((16, 20), Reduce (15, [NS 16])), ((16, 21), Reduce (15, [NS 16])), ((16, 22), Reduce (15, [NS 16])), ((16, 23), Reduce (15, [NS 16])), ((16, 24), Reduce (15, [NS 16])), ((16, 25), Reduce (15, [NS 16])), ((16, 26), Reduce (15, [NS 16])), ((16, 27), Reduce (15, [NS 16])), ((16, 28), Reduce (15, [NS 16])), ((16, 29), Reduce (15, [NS 16])), ((16, 30), Reduce (15, [NS 16])), ((16, 31), Reduce (15, [NS 16])), ((16, 34), Reduce (15, [NS 16])), ((16, 35), Reduce (15, [NS 16])), ((16, 36), Reduce (15, [NS 16])), ((16, 37), Reduce (15, [NS 16]))
            , ((17, 0), Reduce (1, [NS 18]))
            , ((18, 0), Accept)
            , ((19, 1), Reduce (16, [TS 36])), ((19, 2), Reduce (16, [TS 36])), ((19, 4), Reduce (16, [TS 36])), ((19, 5), Reduce (16, [TS 36])), ((19, 6), Reduce (16, [TS 36])), ((19, 7), Reduce (16, [TS 36])), ((19, 13), Reduce (16, [TS 36])), ((19, 14), Reduce (16, [TS 36])), ((19, 15), Reduce (16, [TS 36])), ((19, 16), Reduce (16, [TS 36])), ((19, 17), Reduce (16, [TS 36])), ((19, 18), Reduce (16, [TS 36])), ((19, 19), Reduce (16, [TS 36])), ((19, 20), Reduce (16, [TS 36])), ((19, 21), Reduce (16, [TS 36])), ((19, 22), Reduce (16, [TS 36])), ((19, 23), Reduce (16, [TS 36])), ((19, 24), Reduce (16, [TS 36])), ((19, 25), Reduce (16, [TS 36])), ((19, 26), Reduce (16, [TS 36])), ((19, 27), Reduce (16, [TS 36])), ((19, 28), Reduce (16, [TS 36])), ((19, 29), Reduce (16, [TS 36])), ((19, 30), Reduce (16, [TS 36])), ((19, 31), Reduce (16, [TS 36])), ((19, 34), Reduce (16, [TS 36])), ((19, 35), Reduce (16, [TS 36])), ((19, 36), Reduce (16, [TS 36])), ((19, 37), Reduce (16, [TS 36]))
            , ((20, 1), Reduce (16, [TS 28])), ((20, 2), Reduce (16, [TS 28])), ((20, 4), Reduce (16, [TS 28])), ((20, 5), Reduce (16, [TS 28])), ((20, 6), Reduce (16, [TS 28])), ((20, 7), Reduce (16, [TS 28])), ((20, 13), Reduce (16, [TS 28])), ((20, 14), Reduce (16, [TS 28])), ((20, 15), Reduce (16, [TS 28])), ((20, 16), Reduce (16, [TS 28])), ((20, 17), Reduce (16, [TS 28])), ((20, 18), Reduce (16, [TS 28])), ((20, 19), Reduce (16, [TS 28])), ((20, 20), Reduce (16, [TS 28])), ((20, 21), Reduce (16, [TS 28])), ((20, 22), Reduce (16, [TS 28])), ((20, 23), Reduce (16, [TS 28])), ((20, 24), Reduce (16, [TS 28])), ((20, 25), Reduce (16, [TS 28])), ((20, 26), Reduce (16, [TS 28])), ((20, 27), Reduce (16, [TS 28])), ((20, 28), Reduce (16, [TS 28])), ((20, 29), Reduce (16, [TS 28])), ((20, 30), Reduce (16, [TS 28])), ((20, 31), Reduce (16, [TS 28])), ((20, 34), Reduce (16, [TS 28])), ((20, 35), Reduce (16, [TS 28])), ((20, 36), Reduce (16, [TS 28])), ((20, 37), Reduce (16, [TS 28]))
            , ((21, 1), Reduce (16, [TS 31])), ((21, 2), Reduce (16, [TS 31])), ((21, 4), Reduce (16, [TS 31])), ((21, 5), Reduce (16, [TS 31])), ((21, 6), Reduce (16, [TS 31])), ((21, 7), Reduce (16, [TS 31])), ((21, 13), Reduce (16, [TS 31])), ((21, 14), Reduce (16, [TS 31])), ((21, 15), Reduce (16, [TS 31])), ((21, 16), Reduce (16, [TS 31])), ((21, 17), Reduce (16, [TS 31])), ((21, 18), Reduce (16, [TS 31])), ((21, 19), Reduce (16, [TS 31])), ((21, 20), Reduce (16, [TS 31])), ((21, 21), Reduce (16, [TS 31])), ((21, 22), Reduce (16, [TS 31])), ((21, 23), Reduce (16, [TS 31])), ((21, 24), Reduce (16, [TS 31])), ((21, 25), Reduce (16, [TS 31])), ((21, 26), Reduce (16, [TS 31])), ((21, 27), Reduce (16, [TS 31])), ((21, 28), Reduce (16, [TS 31])), ((21, 29), Reduce (16, [TS 31])), ((21, 30), Reduce (16, [TS 31])), ((21, 31), Reduce (16, [TS 31])), ((21, 34), Reduce (16, [TS 31])), ((21, 35), Reduce (16, [TS 31])), ((21, 36), Reduce (16, [TS 31])), ((21, 37), Reduce (16, [TS 31]))
            , ((22, 1), Reduce (16, [TS 30])), ((22, 2), Reduce (16, [TS 30])), ((22, 4), Reduce (16, [TS 30])), ((22, 5), Reduce (16, [TS 30])), ((22, 6), Reduce (16, [TS 30])), ((22, 7), Reduce (16, [TS 30])), ((22, 13), Reduce (16, [TS 30])), ((22, 14), Reduce (16, [TS 30])), ((22, 15), Reduce (16, [TS 30])), ((22, 16), Reduce (16, [TS 30])), ((22, 17), Reduce (16, [TS 30])), ((22, 18), Reduce (16, [TS 30])), ((22, 19), Reduce (16, [TS 30])), ((22, 20), Reduce (16, [TS 30])), ((22, 21), Reduce (16, [TS 30])), ((22, 22), Reduce (16, [TS 30])), ((22, 23), Reduce (16, [TS 30])), ((22, 24), Reduce (16, [TS 30])), ((22, 25), Reduce (16, [TS 30])), ((22, 26), Reduce (16, [TS 30])), ((22, 27), Reduce (16, [TS 30])), ((22, 28), Reduce (16, [TS 30])), ((22, 29), Reduce (16, [TS 30])), ((22, 30), Reduce (16, [TS 30])), ((22, 31), Reduce (16, [TS 30])), ((22, 34), Reduce (16, [TS 30])), ((22, 35), Reduce (16, [TS 30])), ((22, 36), Reduce (16, [TS 30])), ((22, 37), Reduce (16, [TS 30]))
            , ((23, 1), Reduce (16, [TS 34])), ((23, 2), Reduce (16, [TS 34])), ((23, 4), Reduce (16, [TS 34])), ((23, 5), Reduce (16, [TS 34])), ((23, 6), Reduce (16, [TS 34])), ((23, 7), Reduce (16, [TS 34])), ((23, 12), Shift 56), ((23, 13), Reduce (16, [TS 34])), ((23, 14), Reduce (16, [TS 34])), ((23, 15), Reduce (16, [TS 34])), ((23, 16), Reduce (16, [TS 34])), ((23, 17), Reduce (16, [TS 34])), ((23, 18), Reduce (16, [TS 34])), ((23, 19), Reduce (16, [TS 34])), ((23, 20), Reduce (16, [TS 34])), ((23, 21), Reduce (16, [TS 34])), ((23, 22), Reduce (16, [TS 34])), ((23, 23), Reduce (16, [TS 34])), ((23, 24), Reduce (16, [TS 34])), ((23, 25), Reduce (16, [TS 34])), ((23, 26), Reduce (16, [TS 34])), ((23, 27), Reduce (16, [TS 34])), ((23, 28), Reduce (16, [TS 34])), ((23, 29), Reduce (16, [TS 34])), ((23, 30), Reduce (16, [TS 34])), ((23, 31), Reduce (16, [TS 34])), ((23, 34), Reduce (16, [TS 34])), ((23, 35), Reduce (16, [TS 34])), ((23, 36), Reduce (16, [TS 34])), ((23, 37), Reduce (16, [TS 34]))
            , ((24, 34), Shift 57)
            , ((25, 1), Shift 35), ((25, 4), Shift 26), ((25, 6), Shift 25), ((25, 7), Shift 61), ((25, 9), Shift 28), ((25, 10), Shift 30), ((25, 11), Shift 32), ((25, 28), Shift 20), ((25, 29), Shift 33), ((25, 30), Shift 22), ((25, 31), Shift 21), ((25, 34), Shift 60), ((25, 35), Shift 27), ((25, 36), Shift 19), ((25, 37), Shift 31)
            , ((26, 1), Shift 35), ((26, 4), Shift 26), ((26, 6), Shift 25), ((26, 9), Shift 28), ((26, 10), Shift 30), ((26, 11), Shift 32), ((26, 28), Shift 20), ((26, 29), Shift 33), ((26, 30), Shift 22), ((26, 31), Shift 21), ((26, 34), Shift 23), ((26, 35), Shift 27), ((26, 36), Shift 19), ((26, 37), Shift 31)
            , ((27, 1), Reduce (16, [TS 35])), ((27, 2), Reduce (16, [TS 35])), ((27, 4), Reduce (16, [TS 35])), ((27, 5), Reduce (16, [TS 35])), ((27, 6), Reduce (16, [TS 35])), ((27, 7), Reduce (16, [TS 35])), ((27, 13), Reduce (16, [TS 35])), ((27, 14), Reduce (16, [TS 35])), ((27, 15), Reduce (16, [TS 35])), ((27, 16), Reduce (16, [TS 35])), ((27, 17), Reduce (16, [TS 35])), ((27, 18), Reduce (16, [TS 35])), ((27, 19), Reduce (16, [TS 35])), ((27, 20), Reduce (16, [TS 35])), ((27, 21), Reduce (16, [TS 35])), ((27, 22), Reduce (16, [TS 35])), ((27, 23), Reduce (16, [TS 35])), ((27, 24), Reduce (16, [TS 35])), ((27, 25), Reduce (16, [TS 35])), ((27, 26), Reduce (16, [TS 35])), ((27, 27), Reduce (16, [TS 35])), ((27, 28), Reduce (16, [TS 35])), ((27, 29), Reduce (16, [TS 35])), ((27, 30), Reduce (16, [TS 35])), ((27, 31), Reduce (16, [TS 35])), ((27, 34), Reduce (16, [TS 35])), ((27, 35), Reduce (16, [TS 35])), ((27, 36), Reduce (16, [TS 35])), ((27, 37), Reduce (16, [TS 35]))
            , ((28, 1), Reduce (15, [TS 9])), ((28, 2), Reduce (15, [TS 9])), ((28, 4), Reduce (15, [TS 9])), ((28, 5), Reduce (15, [TS 9])), ((28, 6), Reduce (15, [TS 9])), ((28, 7), Reduce (15, [TS 9])), ((28, 13), Reduce (15, [TS 9])), ((28, 14), Reduce (15, [TS 9])), ((28, 15), Reduce (15, [TS 9])), ((28, 16), Reduce (15, [TS 9])), ((28, 17), Reduce (15, [TS 9])), ((28, 18), Reduce (15, [TS 9])), ((28, 19), Reduce (15, [TS 9])), ((28, 20), Reduce (15, [TS 9])), ((28, 21), Reduce (15, [TS 9])), ((28, 22), Reduce (15, [TS 9])), ((28, 23), Reduce (15, [TS 9])), ((28, 24), Reduce (15, [TS 9])), ((28, 25), Reduce (15, [TS 9])), ((28, 26), Reduce (15, [TS 9])), ((28, 27), Reduce (15, [TS 9])), ((28, 28), Reduce (15, [TS 9])), ((28, 29), Reduce (15, [TS 9])), ((28, 30), Reduce (15, [TS 9])), ((28, 31), Reduce (15, [TS 9])), ((28, 34), Reduce (15, [TS 9])), ((28, 35), Reduce (15, [TS 9])), ((28, 36), Reduce (15, [TS 9])), ((28, 37), Reduce (15, [TS 9]))
            , ((29, 1), Shift 35), ((29, 4), Shift 26), ((29, 6), Shift 25), ((29, 9), Shift 28), ((29, 10), Shift 30), ((29, 11), Shift 32), ((29, 28), Shift 20), ((29, 29), Shift 33), ((29, 30), Shift 22), ((29, 31), Shift 21), ((29, 34), Shift 23), ((29, 35), Shift 27), ((29, 36), Shift 19), ((29, 37), Shift 31)
            , ((30, 1), Reduce (15, [TS 10])), ((30, 2), Reduce (15, [TS 10])), ((30, 4), Reduce (15, [TS 10])), ((30, 5), Reduce (15, [TS 10])), ((30, 6), Reduce (15, [TS 10])), ((30, 7), Reduce (15, [TS 10])), ((30, 13), Reduce (15, [TS 10])), ((30, 14), Reduce (15, [TS 10])), ((30, 15), Reduce (15, [TS 10])), ((30, 16), Reduce (15, [TS 10])), ((30, 17), Reduce (15, [TS 10])), ((30, 18), Reduce (15, [TS 10])), ((30, 19), Reduce (15, [TS 10])), ((30, 20), Reduce (15, [TS 10])), ((30, 21), Reduce (15, [TS 10])), ((30, 22), Reduce (15, [TS 10])), ((30, 23), Reduce (15, [TS 10])), ((30, 24), Reduce (15, [TS 10])), ((30, 25), Reduce (15, [TS 10])), ((30, 26), Reduce (15, [TS 10])), ((30, 27), Reduce (15, [TS 10])), ((30, 28), Reduce (15, [TS 10])), ((30, 29), Reduce (15, [TS 10])), ((30, 30), Reduce (15, [TS 10])), ((30, 31), Reduce (15, [TS 10])), ((30, 34), Reduce (15, [TS 10])), ((30, 35), Reduce (15, [TS 10])), ((30, 36), Reduce (15, [TS 10])), ((30, 37), Reduce (15, [TS 10]))
            , ((31, 1), Reduce (16, [TS 37])), ((31, 2), Reduce (16, [TS 37])), ((31, 4), Reduce (16, [TS 37])), ((31, 5), Reduce (16, [TS 37])), ((31, 6), Reduce (16, [TS 37])), ((31, 7), Reduce (16, [TS 37])), ((31, 13), Reduce (16, [TS 37])), ((31, 14), Reduce (16, [TS 37])), ((31, 15), Reduce (16, [TS 37])), ((31, 16), Reduce (16, [TS 37])), ((31, 17), Reduce (16, [TS 37])), ((31, 18), Reduce (16, [TS 37])), ((31, 19), Reduce (16, [TS 37])), ((31, 20), Reduce (16, [TS 37])), ((31, 21), Reduce (16, [TS 37])), ((31, 22), Reduce (16, [TS 37])), ((31, 23), Reduce (16, [TS 37])), ((31, 24), Reduce (16, [TS 37])), ((31, 25), Reduce (16, [TS 37])), ((31, 26), Reduce (16, [TS 37])), ((31, 27), Reduce (16, [TS 37])), ((31, 28), Reduce (16, [TS 37])), ((31, 29), Reduce (16, [TS 37])), ((31, 30), Reduce (16, [TS 37])), ((31, 31), Reduce (16, [TS 37])), ((31, 34), Reduce (16, [TS 37])), ((31, 35), Reduce (16, [TS 37])), ((31, 36), Reduce (16, [TS 37])), ((31, 37), Reduce (16, [TS 37]))
            , ((32, 1), Reduce (15, [TS 11])), ((32, 2), Reduce (15, [TS 11])), ((32, 4), Reduce (15, [TS 11])), ((32, 5), Reduce (15, [TS 11])), ((32, 6), Reduce (15, [TS 11])), ((32, 7), Reduce (15, [TS 11])), ((32, 13), Reduce (15, [TS 11])), ((32, 14), Reduce (15, [TS 11])), ((32, 15), Reduce (15, [TS 11])), ((32, 16), Reduce (15, [TS 11])), ((32, 17), Reduce (15, [TS 11])), ((32, 18), Reduce (15, [TS 11])), ((32, 19), Reduce (15, [TS 11])), ((32, 20), Reduce (15, [TS 11])), ((32, 21), Reduce (15, [TS 11])), ((32, 22), Reduce (15, [TS 11])), ((32, 23), Reduce (15, [TS 11])), ((32, 24), Reduce (15, [TS 11])), ((32, 25), Reduce (15, [TS 11])), ((32, 26), Reduce (15, [TS 11])), ((32, 27), Reduce (15, [TS 11])), ((32, 28), Reduce (15, [TS 11])), ((32, 29), Reduce (15, [TS 11])), ((32, 30), Reduce (15, [TS 11])), ((32, 31), Reduce (15, [TS 11])), ((32, 34), Reduce (15, [TS 11])), ((32, 35), Reduce (15, [TS 11])), ((32, 36), Reduce (15, [TS 11])), ((32, 37), Reduce (15, [TS 11]))
            , ((33, 1), Reduce (16, [TS 29])), ((33, 2), Reduce (16, [TS 29])), ((33, 4), Reduce (16, [TS 29])), ((33, 5), Reduce (16, [TS 29])), ((33, 6), Reduce (16, [TS 29])), ((33, 7), Reduce (16, [TS 29])), ((33, 13), Reduce (16, [TS 29])), ((33, 14), Reduce (16, [TS 29])), ((33, 15), Reduce (16, [TS 29])), ((33, 16), Reduce (16, [TS 29])), ((33, 17), Reduce (16, [TS 29])), ((33, 18), Reduce (16, [TS 29])), ((33, 19), Reduce (16, [TS 29])), ((33, 20), Reduce (16, [TS 29])), ((33, 21), Reduce (16, [TS 29])), ((33, 22), Reduce (16, [TS 29])), ((33, 23), Reduce (16, [TS 29])), ((33, 24), Reduce (16, [TS 29])), ((33, 25), Reduce (16, [TS 29])), ((33, 26), Reduce (16, [TS 29])), ((33, 27), Reduce (16, [TS 29])), ((33, 28), Reduce (16, [TS 29])), ((33, 29), Reduce (16, [TS 29])), ((33, 30), Reduce (16, [TS 29])), ((33, 31), Reduce (16, [TS 29])), ((33, 34), Reduce (16, [TS 29])), ((33, 35), Reduce (16, [TS 29])), ((33, 36), Reduce (16, [TS 29])), ((33, 37), Reduce (16, [TS 29]))
            , ((34, 34), Shift 64)
            , ((35, 1), Reduce (16, [TS 1])), ((35, 2), Reduce (16, [TS 1])), ((35, 4), Reduce (16, [TS 1])), ((35, 5), Reduce (16, [TS 1])), ((35, 6), Reduce (16, [TS 1])), ((35, 7), Reduce (16, [TS 1])), ((35, 13), Reduce (16, [TS 1])), ((35, 14), Reduce (16, [TS 1])), ((35, 15), Reduce (16, [TS 1])), ((35, 16), Reduce (16, [TS 1])), ((35, 17), Reduce (16, [TS 1])), ((35, 18), Reduce (16, [TS 1])), ((35, 19), Reduce (16, [TS 1])), ((35, 20), Reduce (16, [TS 1])), ((35, 21), Reduce (16, [TS 1])), ((35, 22), Reduce (16, [TS 1])), ((35, 23), Reduce (16, [TS 1])), ((35, 24), Reduce (16, [TS 1])), ((35, 25), Reduce (16, [TS 1])), ((35, 26), Reduce (16, [TS 1])), ((35, 27), Reduce (16, [TS 1])), ((35, 28), Reduce (16, [TS 1])), ((35, 29), Reduce (16, [TS 1])), ((35, 30), Reduce (16, [TS 1])), ((35, 31), Reduce (16, [TS 1])), ((35, 34), Reduce (16, [TS 1])), ((35, 35), Reduce (16, [TS 1])), ((35, 36), Reduce (16, [TS 1])), ((35, 37), Reduce (16, [TS 1]))
            , ((36, 0), Reduce (18, [NS 19, NS 18]))
            , ((37, 0), Reduce (19, [NS 3, TS 2])), ((37, 1), Reduce (19, [NS 3, TS 2])), ((37, 4), Reduce (19, [NS 3, TS 2])), ((37, 6), Reduce (19, [NS 3, TS 2])), ((37, 9), Reduce (19, [NS 3, TS 2])), ((37, 10), Reduce (19, [NS 3, TS 2])), ((37, 11), Reduce (19, [NS 3, TS 2])), ((37, 28), Reduce (19, [NS 3, TS 2])), ((37, 29), Reduce (19, [NS 3, TS 2])), ((37, 30), Reduce (19, [NS 3, TS 2])), ((37, 31), Reduce (19, [NS 3, TS 2])), ((37, 32), Reduce (19, [NS 3, TS 2])), ((37, 33), Reduce (19, [NS 3, TS 2])), ((37, 34), Reduce (19, [NS 3, TS 2])), ((37, 35), Reduce (19, [NS 3, TS 2])), ((37, 36), Reduce (19, [NS 3, TS 2])), ((37, 37), Reduce (19, [NS 3, TS 2]))
            , ((38, 1), Shift 35), ((38, 4), Shift 26), ((38, 6), Shift 25), ((38, 9), Shift 28), ((38, 10), Shift 30), ((38, 11), Shift 32), ((38, 28), Shift 20), ((38, 29), Shift 33), ((38, 30), Shift 22), ((38, 31), Shift 21), ((38, 34), Shift 60), ((38, 35), Shift 27), ((38, 36), Shift 19), ((38, 37), Shift 31)
            , ((39, 1), Shift 35), ((39, 4), Shift 26), ((39, 6), Shift 25), ((39, 9), Shift 28), ((39, 10), Shift 30), ((39, 11), Shift 32), ((39, 28), Shift 20), ((39, 29), Shift 33), ((39, 30), Shift 22), ((39, 31), Shift 21), ((39, 34), Shift 60), ((39, 35), Shift 27), ((39, 36), Shift 19), ((39, 37), Shift 31)
            , ((40, 1), Shift 35), ((40, 4), Shift 26), ((40, 6), Shift 25), ((40, 9), Shift 28), ((40, 10), Shift 30), ((40, 11), Shift 32), ((40, 28), Shift 20), ((40, 29), Shift 33), ((40, 30), Shift 22), ((40, 31), Shift 21), ((40, 34), Shift 60), ((40, 35), Shift 27), ((40, 36), Shift 19), ((40, 37), Shift 31)
            , ((41, 1), Shift 35), ((41, 4), Shift 26), ((41, 6), Shift 25), ((41, 9), Shift 28), ((41, 10), Shift 30), ((41, 11), Shift 32), ((41, 28), Shift 20), ((41, 29), Shift 33), ((41, 30), Shift 22), ((41, 31), Shift 21), ((41, 34), Shift 60), ((41, 35), Shift 27), ((41, 36), Shift 19), ((41, 37), Shift 31)
            , ((42, 1), Shift 35), ((42, 4), Shift 26), ((42, 6), Shift 25), ((42, 9), Shift 28), ((42, 10), Shift 30), ((42, 11), Shift 32), ((42, 28), Shift 20), ((42, 29), Shift 33), ((42, 30), Shift 22), ((42, 31), Shift 21), ((42, 34), Shift 60), ((42, 35), Shift 27), ((42, 36), Shift 19), ((42, 37), Shift 31)
            , ((43, 1), Shift 35), ((43, 4), Shift 26), ((43, 6), Shift 25), ((43, 9), Shift 28), ((43, 10), Shift 30), ((43, 11), Shift 32), ((43, 28), Shift 20), ((43, 29), Shift 33), ((43, 30), Shift 22), ((43, 31), Shift 21), ((43, 34), Shift 60), ((43, 35), Shift 27), ((43, 36), Shift 19), ((43, 37), Shift 31)
            , ((44, 1), Shift 35), ((44, 4), Shift 26), ((44, 6), Shift 25), ((44, 9), Shift 28), ((44, 10), Shift 30), ((44, 11), Shift 32), ((44, 28), Shift 20), ((44, 29), Shift 33), ((44, 30), Shift 22), ((44, 31), Shift 21), ((44, 34), Shift 60), ((44, 35), Shift 27), ((44, 36), Shift 19), ((44, 37), Shift 31)
            , ((45, 1), Shift 35), ((45, 4), Shift 26), ((45, 6), Shift 25), ((45, 9), Shift 28), ((45, 10), Shift 30), ((45, 11), Shift 32), ((45, 28), Shift 20), ((45, 29), Shift 33), ((45, 30), Shift 22), ((45, 31), Shift 21), ((45, 34), Shift 60), ((45, 35), Shift 27), ((45, 36), Shift 19), ((45, 37), Shift 31)
            , ((46, 1), Shift 35), ((46, 4), Shift 26), ((46, 6), Shift 25), ((46, 9), Shift 28), ((46, 10), Shift 30), ((46, 11), Shift 32), ((46, 28), Shift 20), ((46, 29), Shift 33), ((46, 30), Shift 22), ((46, 31), Shift 21), ((46, 34), Shift 60), ((46, 35), Shift 27), ((46, 36), Shift 19), ((46, 37), Shift 31)
            , ((47, 1), Shift 35), ((47, 4), Shift 26), ((47, 6), Shift 25), ((47, 9), Shift 28), ((47, 10), Shift 30), ((47, 11), Shift 32), ((47, 28), Shift 20), ((47, 29), Shift 33), ((47, 30), Shift 22), ((47, 31), Shift 21), ((47, 34), Shift 60), ((47, 35), Shift 27), ((47, 36), Shift 19), ((47, 37), Shift 31)
            , ((48, 1), Shift 35), ((48, 4), Shift 26), ((48, 6), Shift 25), ((48, 9), Shift 28), ((48, 10), Shift 30), ((48, 11), Shift 32), ((48, 28), Shift 20), ((48, 29), Shift 33), ((48, 30), Shift 22), ((48, 31), Shift 21), ((48, 34), Shift 60), ((48, 35), Shift 27), ((48, 36), Shift 19), ((48, 37), Shift 31)
            , ((49, 1), Shift 35), ((49, 4), Shift 26), ((49, 6), Shift 25), ((49, 9), Shift 28), ((49, 10), Shift 30), ((49, 11), Shift 32), ((49, 28), Shift 20), ((49, 29), Shift 33), ((49, 30), Shift 22), ((49, 31), Shift 21), ((49, 34), Shift 60), ((49, 35), Shift 27), ((49, 36), Shift 19), ((49, 37), Shift 31)
            , ((50, 1), Shift 35), ((50, 4), Shift 26), ((50, 6), Shift 25), ((50, 9), Shift 28), ((50, 10), Shift 30), ((50, 11), Shift 32), ((50, 28), Shift 20), ((50, 29), Shift 33), ((50, 30), Shift 22), ((50, 31), Shift 21), ((50, 34), Shift 60), ((50, 35), Shift 27), ((50, 36), Shift 19), ((50, 37), Shift 31)
            , ((51, 1), Shift 35), ((51, 4), Shift 26), ((51, 6), Shift 25), ((51, 9), Shift 28), ((51, 10), Shift 30), ((51, 11), Shift 32), ((51, 28), Shift 20), ((51, 29), Shift 33), ((51, 30), Shift 22), ((51, 31), Shift 21), ((51, 34), Shift 60), ((51, 35), Shift 27), ((51, 36), Shift 19), ((51, 37), Shift 31)
            , ((52, 1), Shift 35), ((52, 4), Shift 26), ((52, 6), Shift 25), ((52, 9), Shift 28), ((52, 10), Shift 30), ((52, 11), Shift 32), ((52, 28), Shift 20), ((52, 29), Shift 33), ((52, 30), Shift 22), ((52, 31), Shift 21), ((52, 34), Shift 60), ((52, 35), Shift 27), ((52, 36), Shift 19), ((52, 37), Shift 31)
            , ((53, 1), Reduce (15, [NS 15, NS 16])), ((53, 2), Reduce (15, [NS 15, NS 16])), ((53, 4), Reduce (15, [NS 15, NS 16])), ((53, 5), Reduce (15, [NS 15, NS 16])), ((53, 6), Reduce (15, [NS 15, NS 16])), ((53, 7), Reduce (15, [NS 15, NS 16])), ((53, 13), Reduce (15, [NS 15, NS 16])), ((53, 14), Reduce (15, [NS 15, NS 16])), ((53, 15), Reduce (15, [NS 15, NS 16])), ((53, 16), Reduce (15, [NS 15, NS 16])), ((53, 17), Reduce (15, [NS 15, NS 16])), ((53, 18), Reduce (15, [NS 15, NS 16])), ((53, 19), Reduce (15, [NS 15, NS 16])), ((53, 20), Reduce (15, [NS 15, NS 16])), ((53, 21), Reduce (15, [NS 15, NS 16])), ((53, 22), Reduce (15, [NS 15, NS 16])), ((53, 23), Reduce (15, [NS 15, NS 16])), ((53, 24), Reduce (15, [NS 15, NS 16])), ((53, 25), Reduce (15, [NS 15, NS 16])), ((53, 26), Reduce (15, [NS 15, NS 16])), ((53, 27), Reduce (15, [NS 15, NS 16])), ((53, 28), Reduce (15, [NS 15, NS 16])), ((53, 29), Reduce (15, [NS 15, NS 16])), ((53, 30), Reduce (15, [NS 15, NS 16])), ((53, 31), Reduce (15, [NS 15, NS 16])), ((53, 34), Reduce (15, [NS 15, NS 16])), ((53, 35), Reduce (15, [NS 15, NS 16])), ((53, 36), Reduce (15, [NS 15, NS 16])), ((53, 37), Reduce (15, [NS 15, NS 16]))
            , ((54, 1), Reduce (16, [TS 34])), ((54, 2), Reduce (16, [TS 34])), ((54, 4), Reduce (16, [TS 34])), ((54, 5), Reduce (16, [TS 34])), ((54, 6), Reduce (16, [TS 34])), ((54, 7), Reduce (16, [TS 34])), ((54, 12), Shift 80), ((54, 13), Reduce (16, [TS 34])), ((54, 14), Reduce (16, [TS 34])), ((54, 15), Reduce (16, [TS 34])), ((54, 16), Reduce (16, [TS 34])), ((54, 17), Reduce (16, [TS 34])), ((54, 18), Reduce (16, [TS 34])), ((54, 19), Reduce (16, [TS 34])), ((54, 20), Reduce (16, [TS 34])), ((54, 21), Reduce (16, [TS 34])), ((54, 22), Reduce (16, [TS 34])), ((54, 23), Reduce (16, [TS 34])), ((54, 24), Reduce (16, [TS 34])), ((54, 25), Reduce (16, [TS 34])), ((54, 26), Reduce (16, [TS 34])), ((54, 27), Reduce (16, [TS 34])), ((54, 28), Reduce (16, [TS 34])), ((54, 29), Reduce (16, [TS 34])), ((54, 30), Reduce (16, [TS 34])), ((54, 31), Reduce (16, [TS 34])), ((54, 34), Reduce (16, [TS 34])), ((54, 35), Reduce (16, [TS 34])), ((54, 36), Reduce (16, [TS 34])), ((54, 37), Reduce (16, [TS 34]))
            , ((56, 1), Shift 35), ((56, 4), Shift 26), ((56, 6), Shift 25), ((56, 9), Shift 28), ((56, 10), Shift 30), ((56, 11), Shift 32), ((56, 28), Shift 20), ((56, 29), Shift 33), ((56, 30), Shift 22), ((56, 31), Shift 21), ((56, 34), Shift 23), ((56, 35), Shift 27), ((56, 36), Shift 19), ((56, 37), Shift 31)
            , ((57, 4), Shift 84), ((57, 33), Shift 85)
            , ((58, 7), Shift 86)
            , ((59, 7), Reduce (17, [NS 9])), ((59, 16), Shift 87)
            , ((60, 1), Reduce (16, [TS 34])), ((60, 2), Reduce (16, [TS 34])), ((60, 4), Reduce (16, [TS 34])), ((60, 5), Reduce (16, [TS 34])), ((60, 6), Reduce (16, [TS 34])), ((60, 7), Reduce (16, [TS 34])), ((60, 13), Reduce (16, [TS 34])), ((60, 14), Reduce (16, [TS 34])), ((60, 15), Reduce (16, [TS 34])), ((60, 16), Reduce (16, [TS 34])), ((60, 17), Reduce (16, [TS 34])), ((60, 18), Reduce (16, [TS 34])), ((60, 19), Reduce (16, [TS 34])), ((60, 20), Reduce (16, [TS 34])), ((60, 21), Reduce (16, [TS 34])), ((60, 22), Reduce (16, [TS 34])), ((60, 23), Reduce (16, [TS 34])), ((60, 24), Reduce (16, [TS 34])), ((60, 25), Reduce (16, [TS 34])), ((60, 26), Reduce (16, [TS 34])), ((60, 27), Reduce (16, [TS 34])), ((60, 28), Reduce (16, [TS 34])), ((60, 29), Reduce (16, [TS 34])), ((60, 30), Reduce (16, [TS 34])), ((60, 31), Reduce (16, [TS 34])), ((60, 34), Reduce (16, [TS 34])), ((60, 35), Reduce (16, [TS 34])), ((60, 36), Reduce (16, [TS 34])), ((60, 37), Reduce (16, [TS 34]))
            , ((61, 1), Reduce (16, [TS 6, TS 7])), ((61, 2), Reduce (16, [TS 6, TS 7])), ((61, 4), Reduce (16, [TS 6, TS 7])), ((61, 5), Reduce (16, [TS 6, TS 7])), ((61, 6), Reduce (16, [TS 6, TS 7])), ((61, 7), Reduce (16, [TS 6, TS 7])), ((61, 13), Reduce (16, [TS 6, TS 7])), ((61, 14), Reduce (16, [TS 6, TS 7])), ((61, 15), Reduce (16, [TS 6, TS 7])), ((61, 16), Reduce (16, [TS 6, TS 7])), ((61, 17), Reduce (16, [TS 6, TS 7])), ((61, 18), Reduce (16, [TS 6, TS 7])), ((61, 19), Reduce (16, [TS 6, TS 7])), ((61, 20), Reduce (16, [TS 6, TS 7])), ((61, 21), Reduce (16, [TS 6, TS 7])), ((61, 22), Reduce (16, [TS 6, TS 7])), ((61, 23), Reduce (16, [TS 6, TS 7])), ((61, 24), Reduce (16, [TS 6, TS 7])), ((61, 25), Reduce (16, [TS 6, TS 7])), ((61, 26), Reduce (16, [TS 6, TS 7])), ((61, 27), Reduce (16, [TS 6, TS 7])), ((61, 28), Reduce (16, [TS 6, TS 7])), ((61, 29), Reduce (16, [TS 6, TS 7])), ((61, 30), Reduce (16, [TS 6, TS 7])), ((61, 31), Reduce (16, [TS 6, TS 7])), ((61, 34), Reduce (16, [TS 6, TS 7])), ((61, 35), Reduce (16, [TS 6, TS 7])), ((61, 36), Reduce (16, [TS 6, TS 7])), ((61, 37), Reduce (16, [TS 6, TS 7]))
            , ((62, 5), Shift 88)
            , ((63, 2), Shift 89)
            , ((64, 4), Shift 94), ((64, 34), Shift 93)
            , ((65, 2), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 5), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 7), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 13), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 14), Shift 39), ((65, 15), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 16), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 17), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 18), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 19), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 20), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 21), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 22), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 23), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 24), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 25), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 26), Reduce (4, [NS 5, TS 13, NS 5])), ((65, 27), Reduce (4, [NS 5, TS 13, NS 5]))
            , ((66, 2), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 5), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 7), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 13), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 14), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 15), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 16), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 17), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 18), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 19), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 20), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 21), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 22), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 23), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 24), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 25), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 26), Reduce (5, [NS 5, TS 14, NS 6])), ((66, 27), Reduce (5, [NS 5, TS 14, NS 6]))
            , ((67, 2), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 5), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 7), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 13), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 14), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 15), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 16), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 17), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 18), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 19), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 20), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 21), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 22), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 23), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 24), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 25), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 26), Reduce (7, [NS 7, TS 16, NS 8])), ((67, 27), Reduce (7, [NS 7, TS 16, NS 8]))
            , ((68, 2), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 5), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 7), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 13), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 14), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 15), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 16), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 17), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 18), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 19), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 20), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 21), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 22), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 23), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 24), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 25), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 26), Reduce (6, [NS 7, TS 15, NS 6])), ((68, 27), Reduce (6, [NS 7, TS 15, NS 6]))
            , ((69, 2), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 5), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 7), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 13), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 14), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 15), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 16), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 17), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 18), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 19), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 20), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 21), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 22), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 23), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 24), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 25), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 26), Reduce (8, [NS 9, TS 17, NS 9])), ((69, 27), Reduce (8, [NS 9, TS 17, NS 9]))
            , ((70, 2), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 5), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 7), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 13), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 14), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 15), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 16), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 17), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 18), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 19), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 20), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 21), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 22), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 23), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 24), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 25), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 26), Reduce (8, [NS 9, TS 20, NS 9])), ((70, 27), Reduce (8, [NS 9, TS 20, NS 9]))
            , ((71, 2), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 5), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 7), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 13), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 14), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 15), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 16), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 17), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 18), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 19), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 20), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 21), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 22), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 23), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 24), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 25), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 26), Reduce (8, [NS 9, TS 21, NS 9])), ((71, 27), Reduce (8, [NS 9, TS 21, NS 9]))
            , ((72, 2), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 5), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 7), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 13), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 14), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 15), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 16), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 17), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 18), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 19), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 20), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 21), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 22), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 23), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 24), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 25), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 26), Reduce (8, [NS 9, TS 22, NS 9])), ((72, 27), Reduce (8, [NS 9, TS 22, NS 9]))
            , ((73, 2), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 5), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 7), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 13), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 14), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 15), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 16), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 17), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 18), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 19), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 20), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 21), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 22), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 23), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 24), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 25), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 26), Reduce (8, [NS 9, TS 18, NS 9])), ((73, 27), Reduce (8, [NS 9, TS 18, NS 9]))
            , ((74, 2), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 5), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 7), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 13), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 14), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 15), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 16), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 17), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 18), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 19), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 20), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 21), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 22), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 23), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 24), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 25), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 26), Reduce (8, [NS 9, TS 19, NS 9])), ((74, 27), Reduce (8, [NS 9, TS 19, NS 9]))
            , ((75, 2), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 5), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 7), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 13), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 14), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 15), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 16), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 17), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 18), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 19), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 20), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 21), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 22), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 23), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 24), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 25), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 26), Reduce (9, [NS 10, TS 23, NS 9])), ((75, 27), Reduce (9, [NS 10, TS 23, NS 9]))
            , ((76, 2), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 5), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 7), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 13), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 14), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 15), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 16), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 17), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 18), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 19), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 20), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 21), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 22), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 23), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 24), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 25), Reduce (10, [NS 10, TS 25, NS 11])), ((76, 26), Shift 52), ((76, 27), Shift 51)
            , ((77, 2), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 5), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 7), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 13), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 14), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 15), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 16), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 17), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 18), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 19), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 20), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 21), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 22), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 23), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 24), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 25), Reduce (10, [NS 10, TS 24, NS 11])), ((77, 26), Shift 52), ((77, 27), Shift 51)
            , ((78, 2), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 5), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 7), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 13), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 14), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 15), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 16), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 17), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 18), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 19), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 20), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 21), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 22), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 23), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 24), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 25), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 26), Reduce (11, [NS 11, TS 27, NS 12])), ((78, 27), Reduce (11, [NS 11, TS 27, NS 12]))
            , ((79, 2), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 5), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 7), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 13), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 14), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 15), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 16), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 17), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 18), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 19), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 20), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 21), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 22), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 23), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 24), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 25), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 26), Reduce (11, [NS 11, TS 26, NS 12])), ((79, 27), Reduce (11, [NS 11, TS 26, NS 12]))
            , ((80, 1), Shift 35), ((80, 4), Shift 26), ((80, 6), Shift 25), ((80, 9), Shift 28), ((80, 10), Shift 30), ((80, 11), Shift 32), ((80, 28), Shift 20), ((80, 29), Shift 33), ((80, 30), Shift 22), ((80, 31), Shift 21), ((80, 34), Shift 23), ((80, 35), Shift 27), ((80, 36), Shift 19), ((80, 37), Shift 31)
            , ((81, 2), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 5), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 7), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 13), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 14), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 15), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 16), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 17), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 18), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 19), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 20), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 21), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 22), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 23), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 24), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 25), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 26), Reduce (3, [TS 34, TS 12, NS 3])), ((81, 27), Reduce (3, [TS 34, TS 12, NS 3]))
            , ((82, 2), Shift 96)
            , ((83, 2), Reduce (20, [NS 21])), ((83, 3), Shift 97), ((83, 5), Reduce (20, [NS 21]))
            , ((84, 4), Shift 84), ((84, 33), Shift 85)
            , ((85, 2), Reduce (21, [TS 33])), ((85, 3), Reduce (21, [TS 33])), ((85, 5), Reduce (21, [TS 33]))
            , ((86, 1), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 2), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 4), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 5), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 6), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 7), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 13), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 14), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 15), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 16), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 17), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 18), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 19), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 20), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 21), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 22), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 23), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 24), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 25), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 26), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 27), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 28), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 29), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 30), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 31), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 34), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 35), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 36), Reduce (16, [TS 6, NS 17, TS 7])), ((86, 37), Reduce (16, [TS 6, NS 17, TS 7]))
            , ((87, 1), Shift 35), ((87, 4), Shift 26), ((87, 6), Shift 25), ((87, 9), Shift 28), ((87, 10), Shift 30), ((87, 11), Shift 32), ((87, 28), Shift 20), ((87, 29), Shift 33), ((87, 30), Shift 22), ((87, 31), Shift 21), ((87, 34), Shift 60), ((87, 35), Shift 27), ((87, 36), Shift 19), ((87, 37), Shift 31)
            , ((88, 1), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 2), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 4), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 5), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 6), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 7), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 13), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 14), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 15), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 16), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 17), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 18), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 19), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 20), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 21), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 22), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 23), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 24), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 25), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 26), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 27), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 28), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 29), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 30), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 31), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 34), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 35), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 36), Reduce (16, [TS 4, NS 3, TS 5])), ((88, 37), Reduce (16, [TS 4, NS 3, TS 5]))
            , ((89, 0), Reduce (2, [TS 8, NS 3, TS 2]))
            , ((90, 2), Shift 100)
            , ((91, 2), Reduce (22, [NS 23])), ((91, 3), Shift 102), ((91, 4), Shift 94), ((91, 5), Reduce (22, [NS 23])), ((91, 34), Shift 93)
            , ((92, 2), Reduce (23, [NS 24])), ((92, 3), Reduce (23, [NS 24])), ((92, 4), Reduce (23, [NS 24])), ((92, 5), Reduce (23, [NS 24])), ((92, 34), Reduce (23, [NS 24]))
            , ((93, 2), Reduce (24, [TS 34])), ((93, 3), Reduce (24, [TS 34])), ((93, 4), Reduce (24, [TS 34])), ((93, 5), Reduce (24, [TS 34])), ((93, 34), Reduce (24, [TS 34]))
            , ((94, 4), Shift 94), ((94, 34), Shift 93)
            , ((95, 2), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 5), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 7), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 13), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 14), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 15), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 16), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 17), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 18), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 19), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 20), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 21), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 22), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 23), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 24), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 25), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 26), Reduce (14, [NS 15, TS 34, TS 12, NS 3])), ((95, 27), Reduce (14, [NS 15, TS 34, TS 12, NS 3]))
            , ((96, 0), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 1), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 4), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 6), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 9), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 10), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 11), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 28), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 29), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 30), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 31), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 32), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 33), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 34), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 35), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 36), Reduce (19, [TS 32, TS 34, NS 20, TS 2])), ((96, 37), Reduce (19, [TS 32, TS 34, NS 20, TS 2]))
            , ((97, 4), Shift 84), ((97, 33), Shift 85)
            , ((98, 5), Shift 105)
            , ((99, 7), Reduce (17, [NS 9, TS 16, NS 17]))
            , ((100, 0), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 1), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 4), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 6), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 9), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 10), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 11), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 28), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 29), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 30), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 31), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 32), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 33), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 34), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 35), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 36), Reduce (19, [TS 33, TS 34, NS 22, TS 2])), ((100, 37), Reduce (19, [TS 33, TS 34, NS 22, TS 2]))
            , ((101, 2), Reduce (23, [NS 23, NS 24])), ((101, 3), Reduce (23, [NS 23, NS 24])), ((101, 4), Reduce (23, [NS 23, NS 24])), ((101, 5), Reduce (23, [NS 23, NS 24])), ((101, 34), Reduce (23, [NS 23, NS 24]))
            , ((102, 4), Shift 94), ((102, 34), Shift 93)
            , ((103, 5), Shift 107)
            , ((104, 2), Reduce (20, [NS 21, TS 3, NS 20])), ((104, 5), Reduce (20, [NS 21, TS 3, NS 20]))
            , ((105, 2), Reduce (21, [TS 4, NS 20, TS 5])), ((105, 3), Reduce (21, [TS 4, NS 20, TS 5])), ((105, 5), Reduce (21, [TS 4, NS 20, TS 5]))
            , ((106, 2), Reduce (22, [NS 23, TS 3, NS 22])), ((106, 5), Reduce (22, [NS 23, TS 3, NS 22]))
            , ((107, 2), Reduce (24, [TS 4, NS 22, TS 5])), ((107, 3), Reduce (24, [TS 4, NS 22, TS 5])), ((107, 4), Reduce (24, [TS 4, NS 22, TS 5])), ((107, 5), Reduce (24, [TS 4, NS 22, TS 5])), ((107, 34), Reduce (24, [TS 4, NS 22, TS 5]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 18), ((0, 2), 2), ((0, 3), 3), ((0, 4), 4), ((0, 5), 5), ((0, 6), 6), ((0, 7), 7), ((0, 8), 8), ((0, 9), 9), ((0, 10), 10), ((0, 11), 11), ((0, 12), 12), ((0, 13), 13), ((0, 14), 14), ((0, 15), 15), ((0, 16), 16), ((0, 18), 17), ((0, 19), 1)
            , ((1, 3), 3), ((1, 4), 4), ((1, 5), 5), ((1, 6), 6), ((1, 7), 7), ((1, 8), 8), ((1, 9), 9), ((1, 10), 10), ((1, 11), 11), ((1, 12), 12), ((1, 13), 13), ((1, 14), 14), ((1, 15), 15), ((1, 16), 16), ((1, 18), 36), ((1, 19), 1)
            , ((15, 16), 53)
            , ((25, 9), 59), ((25, 10), 10), ((25, 11), 11), ((25, 12), 12), ((25, 13), 13), ((25, 14), 14), ((25, 15), 15), ((25, 16), 16), ((25, 17), 58)
            , ((26, 3), 62), ((26, 4), 4), ((26, 5), 5), ((26, 6), 6), ((26, 7), 7), ((26, 8), 8), ((26, 9), 9), ((26, 10), 10), ((26, 11), 11), ((26, 12), 12), ((26, 13), 13), ((26, 14), 14), ((26, 15), 15), ((26, 16), 16)
            , ((29, 3), 63), ((29, 4), 4), ((29, 5), 5), ((29, 6), 6), ((29, 7), 7), ((29, 8), 8), ((29, 9), 9), ((29, 10), 10), ((29, 11), 11), ((29, 12), 12), ((29, 13), 13), ((29, 14), 14), ((29, 15), 15), ((29, 16), 16)
            , ((38, 5), 65), ((38, 6), 6), ((38, 7), 7), ((38, 8), 8), ((38, 9), 9), ((38, 10), 10), ((38, 11), 11), ((38, 12), 12), ((38, 13), 13), ((38, 14), 14), ((38, 15), 15), ((38, 16), 16)
            , ((39, 6), 66), ((39, 7), 7), ((39, 8), 8), ((39, 9), 9), ((39, 10), 10), ((39, 11), 11), ((39, 12), 12), ((39, 13), 13), ((39, 14), 14), ((39, 15), 15), ((39, 16), 16)
            , ((40, 8), 67), ((40, 9), 9), ((40, 10), 10), ((40, 11), 11), ((40, 12), 12), ((40, 13), 13), ((40, 14), 14), ((40, 15), 15), ((40, 16), 16)
            , ((41, 6), 68), ((41, 7), 7), ((41, 8), 8), ((41, 9), 9), ((41, 10), 10), ((41, 11), 11), ((41, 12), 12), ((41, 13), 13), ((41, 14), 14), ((41, 15), 15), ((41, 16), 16)
            , ((42, 9), 69), ((42, 10), 10), ((42, 11), 11), ((42, 12), 12), ((42, 13), 13), ((42, 14), 14), ((42, 15), 15), ((42, 16), 16)
            , ((43, 9), 70), ((43, 10), 10), ((43, 11), 11), ((43, 12), 12), ((43, 13), 13), ((43, 14), 14), ((43, 15), 15), ((43, 16), 16)
            , ((44, 9), 71), ((44, 10), 10), ((44, 11), 11), ((44, 12), 12), ((44, 13), 13), ((44, 14), 14), ((44, 15), 15), ((44, 16), 16)
            , ((45, 9), 72), ((45, 10), 10), ((45, 11), 11), ((45, 12), 12), ((45, 13), 13), ((45, 14), 14), ((45, 15), 15), ((45, 16), 16)
            , ((46, 9), 73), ((46, 10), 10), ((46, 11), 11), ((46, 12), 12), ((46, 13), 13), ((46, 14), 14), ((46, 15), 15), ((46, 16), 16)
            , ((47, 9), 74), ((47, 10), 10), ((47, 11), 11), ((47, 12), 12), ((47, 13), 13), ((47, 14), 14), ((47, 15), 15), ((47, 16), 16)
            , ((48, 9), 75), ((48, 10), 10), ((48, 11), 11), ((48, 12), 12), ((48, 13), 13), ((48, 14), 14), ((48, 15), 15), ((48, 16), 16)
            , ((49, 11), 76), ((49, 12), 12), ((49, 13), 13), ((49, 14), 14), ((49, 15), 15), ((49, 16), 16)
            , ((50, 11), 77), ((50, 12), 12), ((50, 13), 13), ((50, 14), 14), ((50, 15), 15), ((50, 16), 16)
            , ((51, 12), 78), ((51, 13), 13), ((51, 14), 14), ((51, 15), 15), ((51, 16), 16)
            , ((52, 12), 79), ((52, 13), 13), ((52, 14), 14), ((52, 15), 15), ((52, 16), 16)
            , ((56, 3), 81), ((56, 4), 4), ((56, 5), 5), ((56, 6), 6), ((56, 7), 7), ((56, 8), 8), ((56, 9), 9), ((56, 10), 10), ((56, 11), 11), ((56, 12), 12), ((56, 13), 13), ((56, 14), 14), ((56, 15), 15), ((56, 16), 16)
            , ((57, 20), 82), ((57, 21), 83)
            , ((64, 22), 90), ((64, 23), 91), ((64, 24), 92)
            , ((80, 3), 95), ((80, 4), 4), ((80, 5), 5), ((80, 6), 6), ((80, 7), 7), ((80, 8), 8), ((80, 9), 9), ((80, 10), 10), ((80, 11), 11), ((80, 12), 12), ((80, 13), 13), ((80, 14), 14), ((80, 15), 15), ((80, 16), 16)
            , ((84, 20), 98), ((84, 21), 83)
            , ((87, 9), 59), ((87, 10), 10), ((87, 11), 11), ((87, 12), 12), ((87, 13), 13), ((87, 14), 14), ((87, 15), 15), ((87, 16), 16), ((87, 17), 99)
            , ((91, 24), 101)
            , ((94, 22), 103), ((94, 23), 91), ((94, 24), 92)
            , ((97, 20), 104), ((97, 21), 83)
            , ((102, 22), 106), ((102, 23), 91), ((102, 24), 92)
            ]
        }
