module Hol.BETA2.PlanHolParser where

import Hol.BETA2.Header
import Hol.BETA2.PlanHolLexer
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

-- the following codes are generated by PGS.

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()

runHolParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runHolParser = fmap (getEither getQuery (getSequence getDecl)) . runLALR1 theLALR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] = (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[20]] = RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[22]] = RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_infixl loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixL (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infixr loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixR (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infix loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixN (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_prefix loc_1), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | otherwise = RFixityDecl ((loc_1) <> (loc_4)) FF_Prefix (contents_2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infixl loc_1), _2@(PTBranch guard2 _), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | [guard2] `elem` [[25]] = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixL (getSymOp _2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infixr loc_1), _2@(PTBranch guard2 _), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | [guard2] `elem` [[25]] = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixR (getSymOp _2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_infix loc_1), _2@(PTBranch guard2 _), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | [guard2] `elem` [[25]] = RFixityDecl ((loc_1) <> (loc_4)) FF_InfixN (getSymOp _2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_prefix loc_1), _2@(PTBranch guard2 _), PTLeaf (T_nat_lit loc_3 contents_3), PTLeaf (T_dot loc_4)])
        | [guard2] `elem` [[25]] = RFixityDecl ((loc_1) <> (loc_4)) FF_Prefix (getSymOp _2) (contents_3)
    getDecl (PTBranch _ [PTLeaf (T_abbrev loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_assign loc_4), _5@(PTBranch guard5 _), PTLeaf (T_dot loc_6)])
        | [guard3, guard5] `elem` [[26, 22]] = RAbbrevDecl ((loc_1) <> (loc_6)) (contents_2) (getSequence getIdElem _3) (getTypeRep0 _5)
    getDecl (PTBranch _ [PTLeaf (T_notation loc_1), PTLeaf (T_id loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_assign loc_4), _5@(PTBranch guard5 _), PTLeaf (T_dot loc_6)])
        | [guard3, guard5] `elem` [[26, 3]] = RNotationDecl ((loc_1) <> (loc_6)) (contents_2) (getSequence getIdElem _3) (getTermRep0 _5)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] = RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getIdElem :: ParsingTree -> (LargeId)
    getIdElem (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = (contents_1)
    getSymOp :: ParsingTree -> (SmallId)
    getSymOp (PTBranch _ [PTLeaf (T_plus loc_1)])
        | otherwise = "+"
    getSymOp (PTBranch _ [PTLeaf (T_minus loc_1)])
        | otherwise = "-"
    getSymOp (PTBranch _ [PTLeaf (T_star loc_1)])
        | otherwise = "*"
    getSymOp (PTBranch _ [PTLeaf (T_slash loc_1)])
        | otherwise = "/"
    getSymOp (PTBranch _ [PTLeaf (T_eq loc_1)])
        | otherwise = "="
    getSymOp (PTBranch _ [PTLeaf (T_le loc_1)])
        | otherwise = "=<"
    getSymOp (PTBranch _ [PTLeaf (T_lt loc_1)])
        | otherwise = "<"
    getSymOp (PTBranch _ [PTLeaf (T_ge loc_1)])
        | otherwise = ">="
    getSymOp (PTBranch _ [PTLeaf (T_gt loc_1)])
        | otherwise = ">"
    getSymOp (PTBranch _ [PTLeaf (T_cons loc_1)])
        | otherwise = "::"
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[21, 20]] = RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[21]] = (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise = RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[20]] = RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[23, 22]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[23]] = (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[23, 24]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[24]] = (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = if head (contents_1) `elem` ['A' .. 'Z'] then RTyVar (loc_1) (contents_1) else RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[22]] = RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_id loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] = RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] = (getTermRep1L0 _1)
    getTermRep1L0 :: ParsingTree -> (TermRep)
    getTermRep1L0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[5, 5]] = RApp (getSLoc (getTermRep1L1 _1) <> getSLoc (getTermRep1L1 _3)) (RApp (getSLoc (getTermRep1L1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1L1 _1)) (getTermRep1L1 _3)
    getTermRep1L0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] = (getTermRep1L1 _1)
    getTermRep1L1 :: ParsingTree -> (TermRep)
    getTermRep1L1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[5, 6]] = RApp (getSLoc (getTermRep1L1 _1) <> getSLoc (getTermRep1L2 _3)) (RApp (getSLoc (getTermRep1L1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1L1 _1)) (getTermRep1L2 _3)
    getTermRep1L1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] = (getTermRep1L2 _1)
    getTermRep1L2 :: ParsingTree -> (TermRep)
    getTermRep1L2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[7, 6]] = RApp (getSLoc (getTermRep1L3 _1) <> getSLoc (getTermRep1L2 _3)) (RApp (getSLoc (getTermRep1L3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep1L3 _1)) (getTermRep1L2 _3)
    getTermRep1L2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] = (getTermRep1L3 _1)
    getTermRep1L3 :: ParsingTree -> (TermRep)
    getTermRep1L3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[7, 8]] = RApp (getSLoc (getTermRep1L3 _1) <> getSLoc (getTermRep1L4 _3)) (RApp (getSLoc (getTermRep1L3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep1L3 _1)) (getTermRep1L4 _3)
    getTermRep1L3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = (getTermRep1L4 _1)
    getTermRep1L4 :: ParsingTree -> (TermRep)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_is loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_is)) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_eq) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_le loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_le) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_lt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_lt) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_ge loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_ge) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_gt loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_gt) (getTermRep1L5 _1)) (getTermRep1L5 _3)
    getTermRep1L4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = (getTermRep1L5 _1)
    getTermRep1L5 :: ParsingTree -> (TermRep)
    getTermRep1L5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 9]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L5 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep1L6 _1)) (getTermRep1L5 _3)
    getTermRep1L5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] = (getTermRep1L6 _1)
    getTermRep1L6 :: ParsingTree -> (TermRep)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_plus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L7 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_plus) (getTermRep1L6 _1)) (getTermRep1L7 _3)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_minus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getTermRep1L6 _1) <> getSLoc (getTermRep1L7 _3)) (RApp (getSLoc (getTermRep1L6 _1) <> (loc_2)) (RCon (loc_2) DC_minus) (getTermRep1L6 _1)) (getTermRep1L7 _3)
    getTermRep1L6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[11]] = (getTermRep1L7 _1)
    getTermRep1L7 :: ParsingTree -> (TermRep)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_star loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[11, 12]] = RApp (getSLoc (getTermRep1L7 _1) <> getSLoc (getTermRep1L8 _3)) (RApp (getSLoc (getTermRep1L7 _1) <> (loc_2)) (RCon (loc_2) DC_mul) (getTermRep1L7 _1)) (getTermRep1L8 _3)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_slash loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[11, 12]] = RApp (getSLoc (getTermRep1L7 _1) <> getSLoc (getTermRep1L8 _3)) (RApp (getSLoc (getTermRep1L7 _1) <> (loc_2)) (RCon (loc_2) DC_div) (getTermRep1L7 _1)) (getTermRep1L8 _3)
    getTermRep1L7 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] = (getTermRep1L8 _1)
    getTermRep1L8 :: ParsingTree -> (TermRep)
    getTermRep1L8 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[13]] = (getTermRep1L9 _1)
    getTermRep1L9 :: ParsingTree -> (TermRep)
    getTermRep1L9 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[14]] = (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_id loc_2 contents_2), PTLeaf (T_bslash loc_3), _4@(PTBranch guard4 _)])
        | [guard1, guard4] `elem` [[15, 3]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep0 _4)) (getTermRep3 _1) (RAbs ((loc_2) <> getSLoc (getTermRep0 _4)) (contents_2) (getTermRep0 _4))
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[15]] = (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[15, 16]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _2)) (getTermRep3 _1) (getTermRep4 _2)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[16]] = (getTermRep4 _1)
    getTermRep3 (PTBranch _ [PTLeaf (T_pi loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_pi)
    getTermRep3 (PTBranch _ [PTLeaf (T_sigma loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_sigma)
    getTermRep3 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise = RCon (loc_1) DC_Succ
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] = RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep4 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_cut)
    getTermRep4 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_true)
    getTermRep4 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_fail)
    getTermRep4 (PTBranch _ [PTLeaf (T_debug loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_debug)
    getTermRep4 (PTBranch _ [PTLeaf (T_wildcard loc_1)])
        | otherwise = R_wc (loc_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_id loc_1 contents_1)])
        | otherwise = if head (contents_1) `elem` ['A' .. 'Z'] then RVar (loc_1) (contents_1) else RCon (loc_1) (DC_Named (contents_1))
    getTermRep4 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise = mkNatLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise = mkStrLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise = mkChrLit (loc_1) (contents_1)
    getTermRep4 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise = RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep4 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[17]] = RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = RApp (getSLoc (getTermRep1L5 _1)) (RApp (getSLoc (getTermRep1L5 _1)) (RCon (getSLoc (getTermRep1L5 _1)) DC_Cons) (getTermRep1L5 _1)) (RCon (getSLoc (getTermRep1L5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 17]] = RApp (getSLoc (getTermRep1L5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep1L5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep1L5 _1)) (getListBody _3)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise = []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[19, 18], [27, 26]] = (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] = Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[18]] = Right (getRight _1)
    toTerminal :: (Token) -> TSym
    toTerminal (T_wildcard loc) = 1
    toTerminal (T_dot loc) = 2
    toTerminal (T_arrow loc) = 3
    toTerminal (T_lparen loc) = 4
    toTerminal (T_rparen loc) = 5
    toTerminal (T_lbracket loc) = 6
    toTerminal (T_rbracket loc) = 7
    toTerminal (T_quest loc) = 8
    toTerminal (T_pi loc) = 9
    toTerminal (T_sigma loc) = 10
    toTerminal (T_succ loc) = 11
    toTerminal (T_bslash loc) = 12
    toTerminal (T_if loc) = 13
    toTerminal (T_semicolon loc) = 14
    toTerminal (T_fatarrow loc) = 15
    toTerminal (T_comma loc) = 16
    toTerminal (T_eq loc) = 17
    toTerminal (T_le loc) = 18
    toTerminal (T_lt loc) = 19
    toTerminal (T_ge loc) = 20
    toTerminal (T_gt loc) = 21
    toTerminal (T_is loc) = 22
    toTerminal (T_cons loc) = 23
    toTerminal (T_plus loc) = 24
    toTerminal (T_minus loc) = 25
    toTerminal (T_star loc) = 26
    toTerminal (T_slash loc) = 27
    toTerminal (T_cut loc) = 28
    toTerminal (T_true loc) = 29
    toTerminal (T_fail loc) = 30
    toTerminal (T_debug loc) = 31
    toTerminal (T_kind loc) = 32
    toTerminal (T_type loc) = 33
    toTerminal (T_infixl loc) = 34
    toTerminal (T_infixr loc) = 35
    toTerminal (T_infix loc) = 36
    toTerminal (T_prefix loc) = 37
    toTerminal (T_abbrev loc) = 38
    toTerminal (T_notation loc) = 39
    toTerminal (T_assign loc) = 40
    toTerminal (T_id loc contents) = 41
    toTerminal (T_nat_lit loc contents) = 42
    toTerminal (T_chr_lit loc contents) = 43
    toTerminal (T_str_lit loc contents) = 44
    runLALR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLALR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLALR1Parser :: LR1Parser
    theLALR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (18, [])), ((0, 1), Shift 41), ((0, 4), Shift 30), ((0, 6), Shift 29), ((0, 8), Shift 35), ((0, 9), Shift 33), ((0, 10), Shift 36), ((0, 11), Shift 38), ((0, 28), Shift 21), ((0, 29), Shift 39), ((0, 30), Shift 23), ((0, 31), Shift 22), ((0, 32), Shift 28), ((0, 33), Shift 40), ((0, 34), Shift 26), ((0, 35), Shift 27), ((0, 36), Shift 25), ((0, 37), Shift 34), ((0, 38), Shift 19), ((0, 39), Shift 32), ((0, 41), Shift 24), ((0, 42), Shift 31), ((0, 43), Shift 20), ((0, 44), Shift 37)
            , ((1, 0), Reduce (18, [])), ((1, 1), Shift 41), ((1, 4), Shift 30), ((1, 6), Shift 29), ((1, 9), Shift 33), ((1, 10), Shift 36), ((1, 11), Shift 38), ((1, 28), Shift 21), ((1, 29), Shift 39), ((1, 30), Shift 23), ((1, 31), Shift 22), ((1, 32), Shift 28), ((1, 33), Shift 40), ((1, 34), Shift 26), ((1, 35), Shift 27), ((1, 36), Shift 25), ((1, 37), Shift 34), ((1, 38), Shift 19), ((1, 39), Shift 32), ((1, 41), Shift 24), ((1, 42), Shift 31), ((1, 43), Shift 20), ((1, 44), Shift 37)
            , ((2, 0), Reduce (1, [NS 2]))
            , ((3, 2), Shift 43)
            , ((4, 2), Reduce (3, [NS 4])), ((4, 5), Reduce (3, [NS 4])), ((4, 7), Reduce (3, [NS 4])), ((4, 13), Reduce (3, [NS 4])), ((4, 14), Reduce (3, [NS 4])), ((4, 15), Reduce (3, [NS 4])), ((4, 16), Reduce (3, [NS 4])), ((4, 17), Reduce (3, [NS 4])), ((4, 18), Reduce (3, [NS 4])), ((4, 19), Reduce (3, [NS 4])), ((4, 20), Reduce (3, [NS 4])), ((4, 21), Reduce (3, [NS 4])), ((4, 22), Reduce (3, [NS 4])), ((4, 23), Reduce (3, [NS 4])), ((4, 24), Reduce (3, [NS 4])), ((4, 25), Reduce (3, [NS 4])), ((4, 26), Reduce (3, [NS 4])), ((4, 27), Reduce (3, [NS 4]))
            , ((5, 2), Reduce (4, [NS 5])), ((5, 5), Reduce (4, [NS 5])), ((5, 7), Reduce (4, [NS 5])), ((5, 13), Shift 44), ((5, 14), Shift 45), ((5, 15), Reduce (4, [NS 5])), ((5, 16), Reduce (4, [NS 5])), ((5, 17), Reduce (4, [NS 5])), ((5, 18), Reduce (4, [NS 5])), ((5, 19), Reduce (4, [NS 5])), ((5, 20), Reduce (4, [NS 5])), ((5, 21), Reduce (4, [NS 5])), ((5, 22), Reduce (4, [NS 5])), ((5, 23), Reduce (4, [NS 5])), ((5, 24), Reduce (4, [NS 5])), ((5, 25), Reduce (4, [NS 5])), ((5, 26), Reduce (4, [NS 5])), ((5, 27), Reduce (4, [NS 5]))
            , ((6, 2), Reduce (5, [NS 6])), ((6, 5), Reduce (5, [NS 6])), ((6, 7), Reduce (5, [NS 6])), ((6, 13), Reduce (5, [NS 6])), ((6, 14), Reduce (5, [NS 6])), ((6, 15), Reduce (5, [NS 6])), ((6, 16), Reduce (5, [NS 6])), ((6, 17), Reduce (5, [NS 6])), ((6, 18), Reduce (5, [NS 6])), ((6, 19), Reduce (5, [NS 6])), ((6, 20), Reduce (5, [NS 6])), ((6, 21), Reduce (5, [NS 6])), ((6, 22), Reduce (5, [NS 6])), ((6, 23), Reduce (5, [NS 6])), ((6, 24), Reduce (5, [NS 6])), ((6, 25), Reduce (5, [NS 6])), ((6, 26), Reduce (5, [NS 6])), ((6, 27), Reduce (5, [NS 6]))
            , ((7, 2), Reduce (6, [NS 7])), ((7, 5), Reduce (6, [NS 7])), ((7, 7), Reduce (6, [NS 7])), ((7, 13), Reduce (6, [NS 7])), ((7, 14), Reduce (6, [NS 7])), ((7, 15), Shift 47), ((7, 16), Shift 46), ((7, 17), Reduce (6, [NS 7])), ((7, 18), Reduce (6, [NS 7])), ((7, 19), Reduce (6, [NS 7])), ((7, 20), Reduce (6, [NS 7])), ((7, 21), Reduce (6, [NS 7])), ((7, 22), Reduce (6, [NS 7])), ((7, 23), Reduce (6, [NS 7])), ((7, 24), Reduce (6, [NS 7])), ((7, 25), Reduce (6, [NS 7])), ((7, 26), Reduce (6, [NS 7])), ((7, 27), Reduce (6, [NS 7]))
            , ((8, 2), Reduce (7, [NS 8])), ((8, 5), Reduce (7, [NS 8])), ((8, 7), Reduce (7, [NS 8])), ((8, 13), Reduce (7, [NS 8])), ((8, 14), Reduce (7, [NS 8])), ((8, 15), Reduce (7, [NS 8])), ((8, 16), Reduce (7, [NS 8])), ((8, 17), Reduce (7, [NS 8])), ((8, 18), Reduce (7, [NS 8])), ((8, 19), Reduce (7, [NS 8])), ((8, 20), Reduce (7, [NS 8])), ((8, 21), Reduce (7, [NS 8])), ((8, 22), Reduce (7, [NS 8])), ((8, 23), Reduce (7, [NS 8])), ((8, 24), Reduce (7, [NS 8])), ((8, 25), Reduce (7, [NS 8])), ((8, 26), Reduce (7, [NS 8])), ((8, 27), Reduce (7, [NS 8]))
            , ((9, 2), Reduce (8, [NS 9])), ((9, 5), Reduce (8, [NS 9])), ((9, 7), Reduce (8, [NS 9])), ((9, 13), Reduce (8, [NS 9])), ((9, 14), Reduce (8, [NS 9])), ((9, 15), Reduce (8, [NS 9])), ((9, 16), Reduce (8, [NS 9])), ((9, 17), Shift 48), ((9, 18), Shift 52), ((9, 19), Shift 53), ((9, 20), Shift 49), ((9, 21), Shift 50), ((9, 22), Shift 51), ((9, 23), Reduce (8, [NS 9])), ((9, 24), Reduce (8, [NS 9])), ((9, 25), Reduce (8, [NS 9])), ((9, 26), Reduce (8, [NS 9])), ((9, 27), Reduce (8, [NS 9]))
            , ((10, 2), Reduce (9, [NS 10])), ((10, 5), Reduce (9, [NS 10])), ((10, 7), Reduce (9, [NS 10])), ((10, 13), Reduce (9, [NS 10])), ((10, 14), Reduce (9, [NS 10])), ((10, 15), Reduce (9, [NS 10])), ((10, 16), Reduce (9, [NS 10])), ((10, 17), Reduce (9, [NS 10])), ((10, 18), Reduce (9, [NS 10])), ((10, 19), Reduce (9, [NS 10])), ((10, 20), Reduce (9, [NS 10])), ((10, 21), Reduce (9, [NS 10])), ((10, 22), Reduce (9, [NS 10])), ((10, 23), Shift 54), ((10, 24), Shift 56), ((10, 25), Shift 55), ((10, 26), Reduce (9, [NS 10])), ((10, 27), Reduce (9, [NS 10]))
            , ((11, 2), Reduce (10, [NS 11])), ((11, 5), Reduce (10, [NS 11])), ((11, 7), Reduce (10, [NS 11])), ((11, 13), Reduce (10, [NS 11])), ((11, 14), Reduce (10, [NS 11])), ((11, 15), Reduce (10, [NS 11])), ((11, 16), Reduce (10, [NS 11])), ((11, 17), Reduce (10, [NS 11])), ((11, 18), Reduce (10, [NS 11])), ((11, 19), Reduce (10, [NS 11])), ((11, 20), Reduce (10, [NS 11])), ((11, 21), Reduce (10, [NS 11])), ((11, 22), Reduce (10, [NS 11])), ((11, 23), Reduce (10, [NS 11])), ((11, 24), Reduce (10, [NS 11])), ((11, 25), Reduce (10, [NS 11])), ((11, 26), Shift 58), ((11, 27), Shift 57)
            , ((12, 2), Reduce (11, [NS 12])), ((12, 5), Reduce (11, [NS 12])), ((12, 7), Reduce (11, [NS 12])), ((12, 13), Reduce (11, [NS 12])), ((12, 14), Reduce (11, [NS 12])), ((12, 15), Reduce (11, [NS 12])), ((12, 16), Reduce (11, [NS 12])), ((12, 17), Reduce (11, [NS 12])), ((12, 18), Reduce (11, [NS 12])), ((12, 19), Reduce (11, [NS 12])), ((12, 20), Reduce (11, [NS 12])), ((12, 21), Reduce (11, [NS 12])), ((12, 22), Reduce (11, [NS 12])), ((12, 23), Reduce (11, [NS 12])), ((12, 24), Reduce (11, [NS 12])), ((12, 25), Reduce (11, [NS 12])), ((12, 26), Reduce (11, [NS 12])), ((12, 27), Reduce (11, [NS 12]))
            , ((13, 2), Reduce (12, [NS 13])), ((13, 5), Reduce (12, [NS 13])), ((13, 7), Reduce (12, [NS 13])), ((13, 13), Reduce (12, [NS 13])), ((13, 14), Reduce (12, [NS 13])), ((13, 15), Reduce (12, [NS 13])), ((13, 16), Reduce (12, [NS 13])), ((13, 17), Reduce (12, [NS 13])), ((13, 18), Reduce (12, [NS 13])), ((13, 19), Reduce (12, [NS 13])), ((13, 20), Reduce (12, [NS 13])), ((13, 21), Reduce (12, [NS 13])), ((13, 22), Reduce (12, [NS 13])), ((13, 23), Reduce (12, [NS 13])), ((13, 24), Reduce (12, [NS 13])), ((13, 25), Reduce (12, [NS 13])), ((13, 26), Reduce (12, [NS 13])), ((13, 27), Reduce (12, [NS 13]))
            , ((14, 2), Reduce (13, [NS 14])), ((14, 5), Reduce (13, [NS 14])), ((14, 7), Reduce (13, [NS 14])), ((14, 13), Reduce (13, [NS 14])), ((14, 14), Reduce (13, [NS 14])), ((14, 15), Reduce (13, [NS 14])), ((14, 16), Reduce (13, [NS 14])), ((14, 17), Reduce (13, [NS 14])), ((14, 18), Reduce (13, [NS 14])), ((14, 19), Reduce (13, [NS 14])), ((14, 20), Reduce (13, [NS 14])), ((14, 21), Reduce (13, [NS 14])), ((14, 22), Reduce (13, [NS 14])), ((14, 23), Reduce (13, [NS 14])), ((14, 24), Reduce (13, [NS 14])), ((14, 25), Reduce (13, [NS 14])), ((14, 26), Reduce (13, [NS 14])), ((14, 27), Reduce (13, [NS 14]))
            , ((15, 1), Shift 41), ((15, 2), Reduce (14, [NS 15])), ((15, 4), Shift 30), ((15, 5), Reduce (14, [NS 15])), ((15, 6), Shift 29), ((15, 7), Reduce (14, [NS 15])), ((15, 13), Reduce (14, [NS 15])), ((15, 14), Reduce (14, [NS 15])), ((15, 15), Reduce (14, [NS 15])), ((15, 16), Reduce (14, [NS 15])), ((15, 17), Reduce (14, [NS 15])), ((15, 18), Reduce (14, [NS 15])), ((15, 19), Reduce (14, [NS 15])), ((15, 20), Reduce (14, [NS 15])), ((15, 21), Reduce (14, [NS 15])), ((15, 22), Reduce (14, [NS 15])), ((15, 23), Reduce (14, [NS 15])), ((15, 24), Reduce (14, [NS 15])), ((15, 25), Reduce (14, [NS 15])), ((15, 26), Reduce (14, [NS 15])), ((15, 27), Reduce (14, [NS 15])), ((15, 28), Shift 21), ((15, 29), Shift 39), ((15, 30), Shift 23), ((15, 31), Shift 22), ((15, 41), Shift 60), ((15, 42), Shift 31), ((15, 43), Shift 20), ((15, 44), Shift 37)
            , ((16, 1), Reduce (15, [NS 16])), ((16, 2), Reduce (15, [NS 16])), ((16, 4), Reduce (15, [NS 16])), ((16, 5), Reduce (15, [NS 16])), ((16, 6), Reduce (15, [NS 16])), ((16, 7), Reduce (15, [NS 16])), ((16, 13), Reduce (15, [NS 16])), ((16, 14), Reduce (15, [NS 16])), ((16, 15), Reduce (15, [NS 16])), ((16, 16), Reduce (15, [NS 16])), ((16, 17), Reduce (15, [NS 16])), ((16, 18), Reduce (15, [NS 16])), ((16, 19), Reduce (15, [NS 16])), ((16, 20), Reduce (15, [NS 16])), ((16, 21), Reduce (15, [NS 16])), ((16, 22), Reduce (15, [NS 16])), ((16, 23), Reduce (15, [NS 16])), ((16, 24), Reduce (15, [NS 16])), ((16, 25), Reduce (15, [NS 16])), ((16, 26), Reduce (15, [NS 16])), ((16, 27), Reduce (15, [NS 16])), ((16, 28), Reduce (15, [NS 16])), ((16, 29), Reduce (15, [NS 16])), ((16, 30), Reduce (15, [NS 16])), ((16, 31), Reduce (15, [NS 16])), ((16, 41), Reduce (15, [NS 16])), ((16, 42), Reduce (15, [NS 16])), ((16, 43), Reduce (15, [NS 16])), ((16, 44), Reduce (15, [NS 16]))
            , ((17, 0), Reduce (1, [NS 18]))
            , ((18, 0), Accept)
            , ((19, 41), Shift 62)
            , ((20, 1), Reduce (16, [TS 43])), ((20, 2), Reduce (16, [TS 43])), ((20, 4), Reduce (16, [TS 43])), ((20, 5), Reduce (16, [TS 43])), ((20, 6), Reduce (16, [TS 43])), ((20, 7), Reduce (16, [TS 43])), ((20, 13), Reduce (16, [TS 43])), ((20, 14), Reduce (16, [TS 43])), ((20, 15), Reduce (16, [TS 43])), ((20, 16), Reduce (16, [TS 43])), ((20, 17), Reduce (16, [TS 43])), ((20, 18), Reduce (16, [TS 43])), ((20, 19), Reduce (16, [TS 43])), ((20, 20), Reduce (16, [TS 43])), ((20, 21), Reduce (16, [TS 43])), ((20, 22), Reduce (16, [TS 43])), ((20, 23), Reduce (16, [TS 43])), ((20, 24), Reduce (16, [TS 43])), ((20, 25), Reduce (16, [TS 43])), ((20, 26), Reduce (16, [TS 43])), ((20, 27), Reduce (16, [TS 43])), ((20, 28), Reduce (16, [TS 43])), ((20, 29), Reduce (16, [TS 43])), ((20, 30), Reduce (16, [TS 43])), ((20, 31), Reduce (16, [TS 43])), ((20, 41), Reduce (16, [TS 43])), ((20, 42), Reduce (16, [TS 43])), ((20, 43), Reduce (16, [TS 43])), ((20, 44), Reduce (16, [TS 43]))
            , ((21, 1), Reduce (16, [TS 28])), ((21, 2), Reduce (16, [TS 28])), ((21, 4), Reduce (16, [TS 28])), ((21, 5), Reduce (16, [TS 28])), ((21, 6), Reduce (16, [TS 28])), ((21, 7), Reduce (16, [TS 28])), ((21, 13), Reduce (16, [TS 28])), ((21, 14), Reduce (16, [TS 28])), ((21, 15), Reduce (16, [TS 28])), ((21, 16), Reduce (16, [TS 28])), ((21, 17), Reduce (16, [TS 28])), ((21, 18), Reduce (16, [TS 28])), ((21, 19), Reduce (16, [TS 28])), ((21, 20), Reduce (16, [TS 28])), ((21, 21), Reduce (16, [TS 28])), ((21, 22), Reduce (16, [TS 28])), ((21, 23), Reduce (16, [TS 28])), ((21, 24), Reduce (16, [TS 28])), ((21, 25), Reduce (16, [TS 28])), ((21, 26), Reduce (16, [TS 28])), ((21, 27), Reduce (16, [TS 28])), ((21, 28), Reduce (16, [TS 28])), ((21, 29), Reduce (16, [TS 28])), ((21, 30), Reduce (16, [TS 28])), ((21, 31), Reduce (16, [TS 28])), ((21, 41), Reduce (16, [TS 28])), ((21, 42), Reduce (16, [TS 28])), ((21, 43), Reduce (16, [TS 28])), ((21, 44), Reduce (16, [TS 28]))
            , ((22, 1), Reduce (16, [TS 31])), ((22, 2), Reduce (16, [TS 31])), ((22, 4), Reduce (16, [TS 31])), ((22, 5), Reduce (16, [TS 31])), ((22, 6), Reduce (16, [TS 31])), ((22, 7), Reduce (16, [TS 31])), ((22, 13), Reduce (16, [TS 31])), ((22, 14), Reduce (16, [TS 31])), ((22, 15), Reduce (16, [TS 31])), ((22, 16), Reduce (16, [TS 31])), ((22, 17), Reduce (16, [TS 31])), ((22, 18), Reduce (16, [TS 31])), ((22, 19), Reduce (16, [TS 31])), ((22, 20), Reduce (16, [TS 31])), ((22, 21), Reduce (16, [TS 31])), ((22, 22), Reduce (16, [TS 31])), ((22, 23), Reduce (16, [TS 31])), ((22, 24), Reduce (16, [TS 31])), ((22, 25), Reduce (16, [TS 31])), ((22, 26), Reduce (16, [TS 31])), ((22, 27), Reduce (16, [TS 31])), ((22, 28), Reduce (16, [TS 31])), ((22, 29), Reduce (16, [TS 31])), ((22, 30), Reduce (16, [TS 31])), ((22, 31), Reduce (16, [TS 31])), ((22, 41), Reduce (16, [TS 31])), ((22, 42), Reduce (16, [TS 31])), ((22, 43), Reduce (16, [TS 31])), ((22, 44), Reduce (16, [TS 31]))
            , ((23, 1), Reduce (16, [TS 30])), ((23, 2), Reduce (16, [TS 30])), ((23, 4), Reduce (16, [TS 30])), ((23, 5), Reduce (16, [TS 30])), ((23, 6), Reduce (16, [TS 30])), ((23, 7), Reduce (16, [TS 30])), ((23, 13), Reduce (16, [TS 30])), ((23, 14), Reduce (16, [TS 30])), ((23, 15), Reduce (16, [TS 30])), ((23, 16), Reduce (16, [TS 30])), ((23, 17), Reduce (16, [TS 30])), ((23, 18), Reduce (16, [TS 30])), ((23, 19), Reduce (16, [TS 30])), ((23, 20), Reduce (16, [TS 30])), ((23, 21), Reduce (16, [TS 30])), ((23, 22), Reduce (16, [TS 30])), ((23, 23), Reduce (16, [TS 30])), ((23, 24), Reduce (16, [TS 30])), ((23, 25), Reduce (16, [TS 30])), ((23, 26), Reduce (16, [TS 30])), ((23, 27), Reduce (16, [TS 30])), ((23, 28), Reduce (16, [TS 30])), ((23, 29), Reduce (16, [TS 30])), ((23, 30), Reduce (16, [TS 30])), ((23, 31), Reduce (16, [TS 30])), ((23, 41), Reduce (16, [TS 30])), ((23, 42), Reduce (16, [TS 30])), ((23, 43), Reduce (16, [TS 30])), ((23, 44), Reduce (16, [TS 30]))
            , ((24, 1), Reduce (16, [TS 41])), ((24, 2), Reduce (16, [TS 41])), ((24, 4), Reduce (16, [TS 41])), ((24, 5), Reduce (16, [TS 41])), ((24, 6), Reduce (16, [TS 41])), ((24, 7), Reduce (16, [TS 41])), ((24, 12), Shift 63), ((24, 13), Reduce (16, [TS 41])), ((24, 14), Reduce (16, [TS 41])), ((24, 15), Reduce (16, [TS 41])), ((24, 16), Reduce (16, [TS 41])), ((24, 17), Reduce (16, [TS 41])), ((24, 18), Reduce (16, [TS 41])), ((24, 19), Reduce (16, [TS 41])), ((24, 20), Reduce (16, [TS 41])), ((24, 21), Reduce (16, [TS 41])), ((24, 22), Reduce (16, [TS 41])), ((24, 23), Reduce (16, [TS 41])), ((24, 24), Reduce (16, [TS 41])), ((24, 25), Reduce (16, [TS 41])), ((24, 26), Reduce (16, [TS 41])), ((24, 27), Reduce (16, [TS 41])), ((24, 28), Reduce (16, [TS 41])), ((24, 29), Reduce (16, [TS 41])), ((24, 30), Reduce (16, [TS 41])), ((24, 31), Reduce (16, [TS 41])), ((24, 41), Reduce (16, [TS 41])), ((24, 42), Reduce (16, [TS 41])), ((24, 43), Reduce (16, [TS 41])), ((24, 44), Reduce (16, [TS 41]))
            , ((25, 17), Shift 66), ((25, 18), Shift 70), ((25, 19), Shift 71), ((25, 20), Shift 67), ((25, 21), Shift 68), ((25, 23), Shift 65), ((25, 24), Shift 73), ((25, 25), Shift 72), ((25, 26), Shift 75), ((25, 27), Shift 74), ((25, 41), Shift 69)
            , ((26, 17), Shift 66), ((26, 18), Shift 70), ((26, 19), Shift 71), ((26, 20), Shift 67), ((26, 21), Shift 68), ((26, 23), Shift 65), ((26, 24), Shift 73), ((26, 25), Shift 72), ((26, 26), Shift 75), ((26, 27), Shift 74), ((26, 41), Shift 77)
            , ((27, 17), Shift 66), ((27, 18), Shift 70), ((27, 19), Shift 71), ((27, 20), Shift 67), ((27, 21), Shift 68), ((27, 23), Shift 65), ((27, 24), Shift 73), ((27, 25), Shift 72), ((27, 26), Shift 75), ((27, 27), Shift 74), ((27, 41), Shift 79)
            , ((28, 41), Shift 80)
            , ((29, 1), Shift 41), ((29, 4), Shift 30), ((29, 6), Shift 29), ((29, 7), Shift 84), ((29, 9), Shift 33), ((29, 10), Shift 36), ((29, 11), Shift 38), ((29, 28), Shift 21), ((29, 29), Shift 39), ((29, 30), Shift 23), ((29, 31), Shift 22), ((29, 41), Shift 83), ((29, 42), Shift 31), ((29, 43), Shift 20), ((29, 44), Shift 37)
            , ((30, 1), Shift 41), ((30, 4), Shift 30), ((30, 6), Shift 29), ((30, 9), Shift 33), ((30, 10), Shift 36), ((30, 11), Shift 38), ((30, 28), Shift 21), ((30, 29), Shift 39), ((30, 30), Shift 23), ((30, 31), Shift 22), ((30, 41), Shift 24), ((30, 42), Shift 31), ((30, 43), Shift 20), ((30, 44), Shift 37)
            , ((31, 1), Reduce (16, [TS 42])), ((31, 2), Reduce (16, [TS 42])), ((31, 4), Reduce (16, [TS 42])), ((31, 5), Reduce (16, [TS 42])), ((31, 6), Reduce (16, [TS 42])), ((31, 7), Reduce (16, [TS 42])), ((31, 13), Reduce (16, [TS 42])), ((31, 14), Reduce (16, [TS 42])), ((31, 15), Reduce (16, [TS 42])), ((31, 16), Reduce (16, [TS 42])), ((31, 17), Reduce (16, [TS 42])), ((31, 18), Reduce (16, [TS 42])), ((31, 19), Reduce (16, [TS 42])), ((31, 20), Reduce (16, [TS 42])), ((31, 21), Reduce (16, [TS 42])), ((31, 22), Reduce (16, [TS 42])), ((31, 23), Reduce (16, [TS 42])), ((31, 24), Reduce (16, [TS 42])), ((31, 25), Reduce (16, [TS 42])), ((31, 26), Reduce (16, [TS 42])), ((31, 27), Reduce (16, [TS 42])), ((31, 28), Reduce (16, [TS 42])), ((31, 29), Reduce (16, [TS 42])), ((31, 30), Reduce (16, [TS 42])), ((31, 31), Reduce (16, [TS 42])), ((31, 41), Reduce (16, [TS 42])), ((31, 42), Reduce (16, [TS 42])), ((31, 43), Reduce (16, [TS 42])), ((31, 44), Reduce (16, [TS 42]))
            , ((32, 41), Shift 86)
            , ((33, 1), Reduce (15, [TS 9])), ((33, 2), Reduce (15, [TS 9])), ((33, 4), Reduce (15, [TS 9])), ((33, 5), Reduce (15, [TS 9])), ((33, 6), Reduce (15, [TS 9])), ((33, 7), Reduce (15, [TS 9])), ((33, 13), Reduce (15, [TS 9])), ((33, 14), Reduce (15, [TS 9])), ((33, 15), Reduce (15, [TS 9])), ((33, 16), Reduce (15, [TS 9])), ((33, 17), Reduce (15, [TS 9])), ((33, 18), Reduce (15, [TS 9])), ((33, 19), Reduce (15, [TS 9])), ((33, 20), Reduce (15, [TS 9])), ((33, 21), Reduce (15, [TS 9])), ((33, 22), Reduce (15, [TS 9])), ((33, 23), Reduce (15, [TS 9])), ((33, 24), Reduce (15, [TS 9])), ((33, 25), Reduce (15, [TS 9])), ((33, 26), Reduce (15, [TS 9])), ((33, 27), Reduce (15, [TS 9])), ((33, 28), Reduce (15, [TS 9])), ((33, 29), Reduce (15, [TS 9])), ((33, 30), Reduce (15, [TS 9])), ((33, 31), Reduce (15, [TS 9])), ((33, 41), Reduce (15, [TS 9])), ((33, 42), Reduce (15, [TS 9])), ((33, 43), Reduce (15, [TS 9])), ((33, 44), Reduce (15, [TS 9]))
            , ((34, 17), Shift 66), ((34, 18), Shift 70), ((34, 19), Shift 71), ((34, 20), Shift 67), ((34, 21), Shift 68), ((34, 23), Shift 65), ((34, 24), Shift 73), ((34, 25), Shift 72), ((34, 26), Shift 75), ((34, 27), Shift 74), ((34, 41), Shift 88)
            , ((35, 1), Shift 41), ((35, 4), Shift 30), ((35, 6), Shift 29), ((35, 9), Shift 33), ((35, 10), Shift 36), ((35, 11), Shift 38), ((35, 28), Shift 21), ((35, 29), Shift 39), ((35, 30), Shift 23), ((35, 31), Shift 22), ((35, 41), Shift 24), ((35, 42), Shift 31), ((35, 43), Shift 20), ((35, 44), Shift 37)
            , ((36, 1), Reduce (15, [TS 10])), ((36, 2), Reduce (15, [TS 10])), ((36, 4), Reduce (15, [TS 10])), ((36, 5), Reduce (15, [TS 10])), ((36, 6), Reduce (15, [TS 10])), ((36, 7), Reduce (15, [TS 10])), ((36, 13), Reduce (15, [TS 10])), ((36, 14), Reduce (15, [TS 10])), ((36, 15), Reduce (15, [TS 10])), ((36, 16), Reduce (15, [TS 10])), ((36, 17), Reduce (15, [TS 10])), ((36, 18), Reduce (15, [TS 10])), ((36, 19), Reduce (15, [TS 10])), ((36, 20), Reduce (15, [TS 10])), ((36, 21), Reduce (15, [TS 10])), ((36, 22), Reduce (15, [TS 10])), ((36, 23), Reduce (15, [TS 10])), ((36, 24), Reduce (15, [TS 10])), ((36, 25), Reduce (15, [TS 10])), ((36, 26), Reduce (15, [TS 10])), ((36, 27), Reduce (15, [TS 10])), ((36, 28), Reduce (15, [TS 10])), ((36, 29), Reduce (15, [TS 10])), ((36, 30), Reduce (15, [TS 10])), ((36, 31), Reduce (15, [TS 10])), ((36, 41), Reduce (15, [TS 10])), ((36, 42), Reduce (15, [TS 10])), ((36, 43), Reduce (15, [TS 10])), ((36, 44), Reduce (15, [TS 10]))
            , ((37, 1), Reduce (16, [TS 44])), ((37, 2), Reduce (16, [TS 44])), ((37, 4), Reduce (16, [TS 44])), ((37, 5), Reduce (16, [TS 44])), ((37, 6), Reduce (16, [TS 44])), ((37, 7), Reduce (16, [TS 44])), ((37, 13), Reduce (16, [TS 44])), ((37, 14), Reduce (16, [TS 44])), ((37, 15), Reduce (16, [TS 44])), ((37, 16), Reduce (16, [TS 44])), ((37, 17), Reduce (16, [TS 44])), ((37, 18), Reduce (16, [TS 44])), ((37, 19), Reduce (16, [TS 44])), ((37, 20), Reduce (16, [TS 44])), ((37, 21), Reduce (16, [TS 44])), ((37, 22), Reduce (16, [TS 44])), ((37, 23), Reduce (16, [TS 44])), ((37, 24), Reduce (16, [TS 44])), ((37, 25), Reduce (16, [TS 44])), ((37, 26), Reduce (16, [TS 44])), ((37, 27), Reduce (16, [TS 44])), ((37, 28), Reduce (16, [TS 44])), ((37, 29), Reduce (16, [TS 44])), ((37, 30), Reduce (16, [TS 44])), ((37, 31), Reduce (16, [TS 44])), ((37, 41), Reduce (16, [TS 44])), ((37, 42), Reduce (16, [TS 44])), ((37, 43), Reduce (16, [TS 44])), ((37, 44), Reduce (16, [TS 44]))
            , ((38, 1), Reduce (15, [TS 11])), ((38, 2), Reduce (15, [TS 11])), ((38, 4), Reduce (15, [TS 11])), ((38, 5), Reduce (15, [TS 11])), ((38, 6), Reduce (15, [TS 11])), ((38, 7), Reduce (15, [TS 11])), ((38, 13), Reduce (15, [TS 11])), ((38, 14), Reduce (15, [TS 11])), ((38, 15), Reduce (15, [TS 11])), ((38, 16), Reduce (15, [TS 11])), ((38, 17), Reduce (15, [TS 11])), ((38, 18), Reduce (15, [TS 11])), ((38, 19), Reduce (15, [TS 11])), ((38, 20), Reduce (15, [TS 11])), ((38, 21), Reduce (15, [TS 11])), ((38, 22), Reduce (15, [TS 11])), ((38, 23), Reduce (15, [TS 11])), ((38, 24), Reduce (15, [TS 11])), ((38, 25), Reduce (15, [TS 11])), ((38, 26), Reduce (15, [TS 11])), ((38, 27), Reduce (15, [TS 11])), ((38, 28), Reduce (15, [TS 11])), ((38, 29), Reduce (15, [TS 11])), ((38, 30), Reduce (15, [TS 11])), ((38, 31), Reduce (15, [TS 11])), ((38, 41), Reduce (15, [TS 11])), ((38, 42), Reduce (15, [TS 11])), ((38, 43), Reduce (15, [TS 11])), ((38, 44), Reduce (15, [TS 11]))
            , ((39, 1), Reduce (16, [TS 29])), ((39, 2), Reduce (16, [TS 29])), ((39, 4), Reduce (16, [TS 29])), ((39, 5), Reduce (16, [TS 29])), ((39, 6), Reduce (16, [TS 29])), ((39, 7), Reduce (16, [TS 29])), ((39, 13), Reduce (16, [TS 29])), ((39, 14), Reduce (16, [TS 29])), ((39, 15), Reduce (16, [TS 29])), ((39, 16), Reduce (16, [TS 29])), ((39, 17), Reduce (16, [TS 29])), ((39, 18), Reduce (16, [TS 29])), ((39, 19), Reduce (16, [TS 29])), ((39, 20), Reduce (16, [TS 29])), ((39, 21), Reduce (16, [TS 29])), ((39, 22), Reduce (16, [TS 29])), ((39, 23), Reduce (16, [TS 29])), ((39, 24), Reduce (16, [TS 29])), ((39, 25), Reduce (16, [TS 29])), ((39, 26), Reduce (16, [TS 29])), ((39, 27), Reduce (16, [TS 29])), ((39, 28), Reduce (16, [TS 29])), ((39, 29), Reduce (16, [TS 29])), ((39, 30), Reduce (16, [TS 29])), ((39, 31), Reduce (16, [TS 29])), ((39, 41), Reduce (16, [TS 29])), ((39, 42), Reduce (16, [TS 29])), ((39, 43), Reduce (16, [TS 29])), ((39, 44), Reduce (16, [TS 29]))
            , ((40, 41), Shift 90)
            , ((41, 1), Reduce (16, [TS 1])), ((41, 2), Reduce (16, [TS 1])), ((41, 4), Reduce (16, [TS 1])), ((41, 5), Reduce (16, [TS 1])), ((41, 6), Reduce (16, [TS 1])), ((41, 7), Reduce (16, [TS 1])), ((41, 13), Reduce (16, [TS 1])), ((41, 14), Reduce (16, [TS 1])), ((41, 15), Reduce (16, [TS 1])), ((41, 16), Reduce (16, [TS 1])), ((41, 17), Reduce (16, [TS 1])), ((41, 18), Reduce (16, [TS 1])), ((41, 19), Reduce (16, [TS 1])), ((41, 20), Reduce (16, [TS 1])), ((41, 21), Reduce (16, [TS 1])), ((41, 22), Reduce (16, [TS 1])), ((41, 23), Reduce (16, [TS 1])), ((41, 24), Reduce (16, [TS 1])), ((41, 25), Reduce (16, [TS 1])), ((41, 26), Reduce (16, [TS 1])), ((41, 27), Reduce (16, [TS 1])), ((41, 28), Reduce (16, [TS 1])), ((41, 29), Reduce (16, [TS 1])), ((41, 30), Reduce (16, [TS 1])), ((41, 31), Reduce (16, [TS 1])), ((41, 41), Reduce (16, [TS 1])), ((41, 42), Reduce (16, [TS 1])), ((41, 43), Reduce (16, [TS 1])), ((41, 44), Reduce (16, [TS 1]))
            , ((42, 0), Reduce (18, [NS 19, NS 18]))
            , ((43, 0), Reduce (19, [NS 3, TS 2])), ((43, 1), Reduce (19, [NS 3, TS 2])), ((43, 4), Reduce (19, [NS 3, TS 2])), ((43, 6), Reduce (19, [NS 3, TS 2])), ((43, 9), Reduce (19, [NS 3, TS 2])), ((43, 10), Reduce (19, [NS 3, TS 2])), ((43, 11), Reduce (19, [NS 3, TS 2])), ((43, 28), Reduce (19, [NS 3, TS 2])), ((43, 29), Reduce (19, [NS 3, TS 2])), ((43, 30), Reduce (19, [NS 3, TS 2])), ((43, 31), Reduce (19, [NS 3, TS 2])), ((43, 32), Reduce (19, [NS 3, TS 2])), ((43, 33), Reduce (19, [NS 3, TS 2])), ((43, 34), Reduce (19, [NS 3, TS 2])), ((43, 35), Reduce (19, [NS 3, TS 2])), ((43, 36), Reduce (19, [NS 3, TS 2])), ((43, 37), Reduce (19, [NS 3, TS 2])), ((43, 38), Reduce (19, [NS 3, TS 2])), ((43, 39), Reduce (19, [NS 3, TS 2])), ((43, 41), Reduce (19, [NS 3, TS 2])), ((43, 42), Reduce (19, [NS 3, TS 2])), ((43, 43), Reduce (19, [NS 3, TS 2])), ((43, 44), Reduce (19, [NS 3, TS 2]))
            , ((44, 1), Shift 41), ((44, 4), Shift 30), ((44, 6), Shift 29), ((44, 9), Shift 33), ((44, 10), Shift 36), ((44, 11), Shift 38), ((44, 28), Shift 21), ((44, 29), Shift 39), ((44, 30), Shift 23), ((44, 31), Shift 22), ((44, 41), Shift 83), ((44, 42), Shift 31), ((44, 43), Shift 20), ((44, 44), Shift 37)
            , ((45, 1), Shift 41), ((45, 4), Shift 30), ((45, 6), Shift 29), ((45, 9), Shift 33), ((45, 10), Shift 36), ((45, 11), Shift 38), ((45, 28), Shift 21), ((45, 29), Shift 39), ((45, 30), Shift 23), ((45, 31), Shift 22), ((45, 41), Shift 83), ((45, 42), Shift 31), ((45, 43), Shift 20), ((45, 44), Shift 37)
            , ((46, 1), Shift 41), ((46, 4), Shift 30), ((46, 6), Shift 29), ((46, 9), Shift 33), ((46, 10), Shift 36), ((46, 11), Shift 38), ((46, 28), Shift 21), ((46, 29), Shift 39), ((46, 30), Shift 23), ((46, 31), Shift 22), ((46, 41), Shift 83), ((46, 42), Shift 31), ((46, 43), Shift 20), ((46, 44), Shift 37)
            , ((47, 1), Shift 41), ((47, 4), Shift 30), ((47, 6), Shift 29), ((47, 9), Shift 33), ((47, 10), Shift 36), ((47, 11), Shift 38), ((47, 28), Shift 21), ((47, 29), Shift 39), ((47, 30), Shift 23), ((47, 31), Shift 22), ((47, 41), Shift 83), ((47, 42), Shift 31), ((47, 43), Shift 20), ((47, 44), Shift 37)
            , ((48, 1), Shift 41), ((48, 4), Shift 30), ((48, 6), Shift 29), ((48, 9), Shift 33), ((48, 10), Shift 36), ((48, 11), Shift 38), ((48, 28), Shift 21), ((48, 29), Shift 39), ((48, 30), Shift 23), ((48, 31), Shift 22), ((48, 41), Shift 83), ((48, 42), Shift 31), ((48, 43), Shift 20), ((48, 44), Shift 37)
            , ((49, 1), Shift 41), ((49, 4), Shift 30), ((49, 6), Shift 29), ((49, 9), Shift 33), ((49, 10), Shift 36), ((49, 11), Shift 38), ((49, 28), Shift 21), ((49, 29), Shift 39), ((49, 30), Shift 23), ((49, 31), Shift 22), ((49, 41), Shift 83), ((49, 42), Shift 31), ((49, 43), Shift 20), ((49, 44), Shift 37)
            , ((50, 1), Shift 41), ((50, 4), Shift 30), ((50, 6), Shift 29), ((50, 9), Shift 33), ((50, 10), Shift 36), ((50, 11), Shift 38), ((50, 28), Shift 21), ((50, 29), Shift 39), ((50, 30), Shift 23), ((50, 31), Shift 22), ((50, 41), Shift 83), ((50, 42), Shift 31), ((50, 43), Shift 20), ((50, 44), Shift 37)
            , ((51, 1), Shift 41), ((51, 4), Shift 30), ((51, 6), Shift 29), ((51, 9), Shift 33), ((51, 10), Shift 36), ((51, 11), Shift 38), ((51, 28), Shift 21), ((51, 29), Shift 39), ((51, 30), Shift 23), ((51, 31), Shift 22), ((51, 41), Shift 83), ((51, 42), Shift 31), ((51, 43), Shift 20), ((51, 44), Shift 37)
            , ((52, 1), Shift 41), ((52, 4), Shift 30), ((52, 6), Shift 29), ((52, 9), Shift 33), ((52, 10), Shift 36), ((52, 11), Shift 38), ((52, 28), Shift 21), ((52, 29), Shift 39), ((52, 30), Shift 23), ((52, 31), Shift 22), ((52, 41), Shift 83), ((52, 42), Shift 31), ((52, 43), Shift 20), ((52, 44), Shift 37)
            , ((53, 1), Shift 41), ((53, 4), Shift 30), ((53, 6), Shift 29), ((53, 9), Shift 33), ((53, 10), Shift 36), ((53, 11), Shift 38), ((53, 28), Shift 21), ((53, 29), Shift 39), ((53, 30), Shift 23), ((53, 31), Shift 22), ((53, 41), Shift 83), ((53, 42), Shift 31), ((53, 43), Shift 20), ((53, 44), Shift 37)
            , ((54, 1), Shift 41), ((54, 4), Shift 30), ((54, 6), Shift 29), ((54, 9), Shift 33), ((54, 10), Shift 36), ((54, 11), Shift 38), ((54, 28), Shift 21), ((54, 29), Shift 39), ((54, 30), Shift 23), ((54, 31), Shift 22), ((54, 41), Shift 83), ((54, 42), Shift 31), ((54, 43), Shift 20), ((54, 44), Shift 37)
            , ((55, 1), Shift 41), ((55, 4), Shift 30), ((55, 6), Shift 29), ((55, 9), Shift 33), ((55, 10), Shift 36), ((55, 11), Shift 38), ((55, 28), Shift 21), ((55, 29), Shift 39), ((55, 30), Shift 23), ((55, 31), Shift 22), ((55, 41), Shift 83), ((55, 42), Shift 31), ((55, 43), Shift 20), ((55, 44), Shift 37)
            , ((56, 1), Shift 41), ((56, 4), Shift 30), ((56, 6), Shift 29), ((56, 9), Shift 33), ((56, 10), Shift 36), ((56, 11), Shift 38), ((56, 28), Shift 21), ((56, 29), Shift 39), ((56, 30), Shift 23), ((56, 31), Shift 22), ((56, 41), Shift 83), ((56, 42), Shift 31), ((56, 43), Shift 20), ((56, 44), Shift 37)
            , ((57, 1), Shift 41), ((57, 4), Shift 30), ((57, 6), Shift 29), ((57, 9), Shift 33), ((57, 10), Shift 36), ((57, 11), Shift 38), ((57, 28), Shift 21), ((57, 29), Shift 39), ((57, 30), Shift 23), ((57, 31), Shift 22), ((57, 41), Shift 83), ((57, 42), Shift 31), ((57, 43), Shift 20), ((57, 44), Shift 37)
            , ((58, 1), Shift 41), ((58, 4), Shift 30), ((58, 6), Shift 29), ((58, 9), Shift 33), ((58, 10), Shift 36), ((58, 11), Shift 38), ((58, 28), Shift 21), ((58, 29), Shift 39), ((58, 30), Shift 23), ((58, 31), Shift 22), ((58, 41), Shift 83), ((58, 42), Shift 31), ((58, 43), Shift 20), ((58, 44), Shift 37)
            , ((59, 1), Reduce (15, [NS 15, NS 16])), ((59, 2), Reduce (15, [NS 15, NS 16])), ((59, 4), Reduce (15, [NS 15, NS 16])), ((59, 5), Reduce (15, [NS 15, NS 16])), ((59, 6), Reduce (15, [NS 15, NS 16])), ((59, 7), Reduce (15, [NS 15, NS 16])), ((59, 13), Reduce (15, [NS 15, NS 16])), ((59, 14), Reduce (15, [NS 15, NS 16])), ((59, 15), Reduce (15, [NS 15, NS 16])), ((59, 16), Reduce (15, [NS 15, NS 16])), ((59, 17), Reduce (15, [NS 15, NS 16])), ((59, 18), Reduce (15, [NS 15, NS 16])), ((59, 19), Reduce (15, [NS 15, NS 16])), ((59, 20), Reduce (15, [NS 15, NS 16])), ((59, 21), Reduce (15, [NS 15, NS 16])), ((59, 22), Reduce (15, [NS 15, NS 16])), ((59, 23), Reduce (15, [NS 15, NS 16])), ((59, 24), Reduce (15, [NS 15, NS 16])), ((59, 25), Reduce (15, [NS 15, NS 16])), ((59, 26), Reduce (15, [NS 15, NS 16])), ((59, 27), Reduce (15, [NS 15, NS 16])), ((59, 28), Reduce (15, [NS 15, NS 16])), ((59, 29), Reduce (15, [NS 15, NS 16])), ((59, 30), Reduce (15, [NS 15, NS 16])), ((59, 31), Reduce (15, [NS 15, NS 16])), ((59, 41), Reduce (15, [NS 15, NS 16])), ((59, 42), Reduce (15, [NS 15, NS 16])), ((59, 43), Reduce (15, [NS 15, NS 16])), ((59, 44), Reduce (15, [NS 15, NS 16]))
            , ((60, 1), Reduce (16, [TS 41])), ((60, 2), Reduce (16, [TS 41])), ((60, 4), Reduce (16, [TS 41])), ((60, 5), Reduce (16, [TS 41])), ((60, 6), Reduce (16, [TS 41])), ((60, 7), Reduce (16, [TS 41])), ((60, 12), Shift 106), ((60, 13), Reduce (16, [TS 41])), ((60, 14), Reduce (16, [TS 41])), ((60, 15), Reduce (16, [TS 41])), ((60, 16), Reduce (16, [TS 41])), ((60, 17), Reduce (16, [TS 41])), ((60, 18), Reduce (16, [TS 41])), ((60, 19), Reduce (16, [TS 41])), ((60, 20), Reduce (16, [TS 41])), ((60, 21), Reduce (16, [TS 41])), ((60, 22), Reduce (16, [TS 41])), ((60, 23), Reduce (16, [TS 41])), ((60, 24), Reduce (16, [TS 41])), ((60, 25), Reduce (16, [TS 41])), ((60, 26), Reduce (16, [TS 41])), ((60, 27), Reduce (16, [TS 41])), ((60, 28), Reduce (16, [TS 41])), ((60, 29), Reduce (16, [TS 41])), ((60, 30), Reduce (16, [TS 41])), ((60, 31), Reduce (16, [TS 41])), ((60, 41), Reduce (16, [TS 41])), ((60, 42), Reduce (16, [TS 41])), ((60, 43), Reduce (16, [TS 41])), ((60, 44), Reduce (16, [TS 41]))
            , ((62, 40), Reduce (26, [])), ((62, 41), Shift 109)
            , ((63, 1), Shift 41), ((63, 4), Shift 30), ((63, 6), Shift 29), ((63, 9), Shift 33), ((63, 10), Shift 36), ((63, 11), Shift 38), ((63, 28), Shift 21), ((63, 29), Shift 39), ((63, 30), Shift 23), ((63, 31), Shift 22), ((63, 41), Shift 24), ((63, 42), Shift 31), ((63, 43), Shift 20), ((63, 44), Shift 37)
            , ((64, 42), Shift 111)
            , ((65, 42), Reduce (25, [TS 23]))
            , ((66, 42), Reduce (25, [TS 17]))
            , ((67, 42), Reduce (25, [TS 20]))
            , ((68, 42), Reduce (25, [TS 21]))
            , ((69, 42), Shift 112)
            , ((70, 42), Reduce (25, [TS 18]))
            , ((71, 42), Reduce (25, [TS 19]))
            , ((72, 42), Reduce (25, [TS 25]))
            , ((73, 42), Reduce (25, [TS 24]))
            , ((74, 42), Reduce (25, [TS 27]))
            , ((75, 42), Reduce (25, [TS 26]))
            , ((76, 42), Shift 113)
            , ((77, 42), Shift 114)
            , ((78, 42), Shift 115)
            , ((79, 42), Shift 116)
            , ((80, 4), Shift 119), ((80, 33), Shift 120)
            , ((81, 7), Shift 121)
            , ((82, 7), Reduce (17, [NS 9])), ((82, 16), Shift 122)
            , ((83, 1), Reduce (16, [TS 41])), ((83, 2), Reduce (16, [TS 41])), ((83, 4), Reduce (16, [TS 41])), ((83, 5), Reduce (16, [TS 41])), ((83, 6), Reduce (16, [TS 41])), ((83, 7), Reduce (16, [TS 41])), ((83, 13), Reduce (16, [TS 41])), ((83, 14), Reduce (16, [TS 41])), ((83, 15), Reduce (16, [TS 41])), ((83, 16), Reduce (16, [TS 41])), ((83, 17), Reduce (16, [TS 41])), ((83, 18), Reduce (16, [TS 41])), ((83, 19), Reduce (16, [TS 41])), ((83, 20), Reduce (16, [TS 41])), ((83, 21), Reduce (16, [TS 41])), ((83, 22), Reduce (16, [TS 41])), ((83, 23), Reduce (16, [TS 41])), ((83, 24), Reduce (16, [TS 41])), ((83, 25), Reduce (16, [TS 41])), ((83, 26), Reduce (16, [TS 41])), ((83, 27), Reduce (16, [TS 41])), ((83, 28), Reduce (16, [TS 41])), ((83, 29), Reduce (16, [TS 41])), ((83, 30), Reduce (16, [TS 41])), ((83, 31), Reduce (16, [TS 41])), ((83, 41), Reduce (16, [TS 41])), ((83, 42), Reduce (16, [TS 41])), ((83, 43), Reduce (16, [TS 41])), ((83, 44), Reduce (16, [TS 41]))
            , ((84, 1), Reduce (16, [TS 6, TS 7])), ((84, 2), Reduce (16, [TS 6, TS 7])), ((84, 4), Reduce (16, [TS 6, TS 7])), ((84, 5), Reduce (16, [TS 6, TS 7])), ((84, 6), Reduce (16, [TS 6, TS 7])), ((84, 7), Reduce (16, [TS 6, TS 7])), ((84, 13), Reduce (16, [TS 6, TS 7])), ((84, 14), Reduce (16, [TS 6, TS 7])), ((84, 15), Reduce (16, [TS 6, TS 7])), ((84, 16), Reduce (16, [TS 6, TS 7])), ((84, 17), Reduce (16, [TS 6, TS 7])), ((84, 18), Reduce (16, [TS 6, TS 7])), ((84, 19), Reduce (16, [TS 6, TS 7])), ((84, 20), Reduce (16, [TS 6, TS 7])), ((84, 21), Reduce (16, [TS 6, TS 7])), ((84, 22), Reduce (16, [TS 6, TS 7])), ((84, 23), Reduce (16, [TS 6, TS 7])), ((84, 24), Reduce (16, [TS 6, TS 7])), ((84, 25), Reduce (16, [TS 6, TS 7])), ((84, 26), Reduce (16, [TS 6, TS 7])), ((84, 27), Reduce (16, [TS 6, TS 7])), ((84, 28), Reduce (16, [TS 6, TS 7])), ((84, 29), Reduce (16, [TS 6, TS 7])), ((84, 30), Reduce (16, [TS 6, TS 7])), ((84, 31), Reduce (16, [TS 6, TS 7])), ((84, 41), Reduce (16, [TS 6, TS 7])), ((84, 42), Reduce (16, [TS 6, TS 7])), ((84, 43), Reduce (16, [TS 6, TS 7])), ((84, 44), Reduce (16, [TS 6, TS 7]))
            , ((85, 5), Shift 123)
            , ((86, 40), Reduce (26, [])), ((86, 41), Shift 109)
            , ((87, 42), Shift 125)
            , ((88, 42), Shift 126)
            , ((89, 2), Shift 127)
            , ((90, 4), Shift 132), ((90, 41), Shift 131)
            , ((91, 2), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 5), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 7), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 13), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 14), Shift 45), ((91, 15), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 16), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 17), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 18), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 19), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 20), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 21), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 22), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 23), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 24), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 25), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 26), Reduce (4, [NS 5, TS 13, NS 5])), ((91, 27), Reduce (4, [NS 5, TS 13, NS 5]))
            , ((92, 2), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 5), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 7), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 13), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 14), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 15), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 16), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 17), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 18), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 19), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 20), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 21), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 22), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 23), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 24), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 25), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 26), Reduce (5, [NS 5, TS 14, NS 6])), ((92, 27), Reduce (5, [NS 5, TS 14, NS 6]))
            , ((93, 2), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 5), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 7), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 13), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 14), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 15), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 16), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 17), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 18), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 19), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 20), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 21), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 22), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 23), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 24), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 25), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 26), Reduce (7, [NS 7, TS 16, NS 8])), ((93, 27), Reduce (7, [NS 7, TS 16, NS 8]))
            , ((94, 2), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 5), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 7), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 13), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 14), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 15), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 16), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 17), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 18), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 19), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 20), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 21), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 22), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 23), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 24), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 25), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 26), Reduce (6, [NS 7, TS 15, NS 6])), ((94, 27), Reduce (6, [NS 7, TS 15, NS 6]))
            , ((95, 2), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 5), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 7), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 13), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 14), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 15), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 16), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 17), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 18), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 19), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 20), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 21), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 22), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 23), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 24), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 25), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 26), Reduce (8, [NS 9, TS 17, NS 9])), ((95, 27), Reduce (8, [NS 9, TS 17, NS 9]))
            , ((96, 2), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 5), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 7), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 13), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 14), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 15), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 16), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 17), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 18), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 19), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 20), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 21), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 22), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 23), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 24), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 25), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 26), Reduce (8, [NS 9, TS 20, NS 9])), ((96, 27), Reduce (8, [NS 9, TS 20, NS 9]))
            , ((97, 2), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 5), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 7), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 13), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 14), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 15), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 16), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 17), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 18), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 19), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 20), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 21), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 22), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 23), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 24), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 25), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 26), Reduce (8, [NS 9, TS 21, NS 9])), ((97, 27), Reduce (8, [NS 9, TS 21, NS 9]))
            , ((98, 2), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 5), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 7), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 13), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 14), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 15), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 16), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 17), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 18), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 19), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 20), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 21), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 22), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 23), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 24), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 25), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 26), Reduce (8, [NS 9, TS 22, NS 9])), ((98, 27), Reduce (8, [NS 9, TS 22, NS 9]))
            , ((99, 2), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 5), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 7), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 13), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 14), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 15), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 16), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 17), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 18), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 19), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 20), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 21), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 22), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 23), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 24), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 25), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 26), Reduce (8, [NS 9, TS 18, NS 9])), ((99, 27), Reduce (8, [NS 9, TS 18, NS 9]))
            , ((100, 2), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 5), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 7), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 13), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 14), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 15), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 16), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 17), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 18), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 19), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 20), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 21), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 22), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 23), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 24), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 25), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 26), Reduce (8, [NS 9, TS 19, NS 9])), ((100, 27), Reduce (8, [NS 9, TS 19, NS 9]))
            , ((101, 2), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 5), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 7), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 13), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 14), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 15), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 16), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 17), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 18), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 19), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 20), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 21), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 22), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 23), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 24), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 25), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 26), Reduce (9, [NS 10, TS 23, NS 9])), ((101, 27), Reduce (9, [NS 10, TS 23, NS 9]))
            , ((102, 2), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 5), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 7), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 13), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 14), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 15), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 16), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 17), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 18), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 19), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 20), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 21), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 22), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 23), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 24), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 25), Reduce (10, [NS 10, TS 25, NS 11])), ((102, 26), Shift 58), ((102, 27), Shift 57)
            , ((103, 2), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 5), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 7), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 13), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 14), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 15), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 16), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 17), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 18), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 19), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 20), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 21), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 22), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 23), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 24), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 25), Reduce (10, [NS 10, TS 24, NS 11])), ((103, 26), Shift 58), ((103, 27), Shift 57)
            , ((104, 2), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 5), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 7), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 13), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 14), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 15), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 16), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 17), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 18), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 19), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 20), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 21), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 22), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 23), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 24), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 25), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 26), Reduce (11, [NS 11, TS 27, NS 12])), ((104, 27), Reduce (11, [NS 11, TS 27, NS 12]))
            , ((105, 2), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 5), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 7), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 13), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 14), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 15), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 16), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 17), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 18), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 19), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 20), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 21), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 22), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 23), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 24), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 25), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 26), Reduce (11, [NS 11, TS 26, NS 12])), ((105, 27), Reduce (11, [NS 11, TS 26, NS 12]))
            , ((106, 1), Shift 41), ((106, 4), Shift 30), ((106, 6), Shift 29), ((106, 9), Shift 33), ((106, 10), Shift 36), ((106, 11), Shift 38), ((106, 28), Shift 21), ((106, 29), Shift 39), ((106, 30), Shift 23), ((106, 31), Shift 22), ((106, 41), Shift 24), ((106, 42), Shift 31), ((106, 43), Shift 20), ((106, 44), Shift 37)
            , ((107, 40), Reduce (26, [])), ((107, 41), Shift 109)
            , ((108, 40), Shift 135)
            , ((109, 40), Reduce (27, [TS 41])), ((109, 41), Reduce (27, [TS 41]))
            , ((110, 2), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 5), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 7), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 13), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 14), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 15), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 16), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 17), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 18), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 19), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 20), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 21), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 22), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 23), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 24), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 25), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 26), Reduce (3, [TS 41, TS 12, NS 3])), ((110, 27), Reduce (3, [TS 41, TS 12, NS 3]))
            , ((111, 2), Shift 136)
            , ((112, 2), Shift 137)
            , ((113, 2), Shift 138)
            , ((114, 2), Shift 139)
            , ((115, 2), Shift 140)
            , ((116, 2), Shift 141)
            , ((117, 2), Shift 142)
            , ((118, 2), Reduce (20, [NS 21])), ((118, 3), Shift 143), ((118, 5), Reduce (20, [NS 21]))
            , ((119, 4), Shift 119), ((119, 33), Shift 120)
            , ((120, 2), Reduce (21, [TS 33])), ((120, 3), Reduce (21, [TS 33])), ((120, 5), Reduce (21, [TS 33]))
            , ((121, 1), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 2), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 4), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 5), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 6), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 7), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 13), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 14), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 15), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 16), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 17), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 18), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 19), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 20), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 21), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 22), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 23), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 24), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 25), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 26), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 27), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 28), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 29), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 30), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 31), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 41), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 42), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 43), Reduce (16, [TS 6, NS 17, TS 7])), ((121, 44), Reduce (16, [TS 6, NS 17, TS 7]))
            , ((122, 1), Shift 41), ((122, 4), Shift 30), ((122, 6), Shift 29), ((122, 9), Shift 33), ((122, 10), Shift 36), ((122, 11), Shift 38), ((122, 28), Shift 21), ((122, 29), Shift 39), ((122, 30), Shift 23), ((122, 31), Shift 22), ((122, 41), Shift 83), ((122, 42), Shift 31), ((122, 43), Shift 20), ((122, 44), Shift 37)
            , ((123, 1), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 2), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 4), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 5), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 6), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 7), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 13), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 14), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 15), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 16), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 17), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 18), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 19), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 20), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 21), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 22), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 23), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 24), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 25), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 26), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 27), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 28), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 29), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 30), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 31), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 41), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 42), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 43), Reduce (16, [TS 4, NS 3, TS 5])), ((123, 44), Reduce (16, [TS 4, NS 3, TS 5]))
            , ((124, 40), Shift 146)
            , ((125, 2), Shift 147)
            , ((126, 2), Shift 148)
            , ((127, 0), Reduce (2, [TS 8, NS 3, TS 2]))
            , ((128, 2), Shift 149)
            , ((129, 2), Reduce (22, [NS 23])), ((129, 3), Shift 151), ((129, 4), Shift 132), ((129, 5), Reduce (22, [NS 23])), ((129, 41), Shift 131)
            , ((130, 2), Reduce (23, [NS 24])), ((130, 3), Reduce (23, [NS 24])), ((130, 4), Reduce (23, [NS 24])), ((130, 5), Reduce (23, [NS 24])), ((130, 41), Reduce (23, [NS 24]))
            , ((131, 2), Reduce (24, [TS 41])), ((131, 3), Reduce (24, [TS 41])), ((131, 4), Reduce (24, [TS 41])), ((131, 5), Reduce (24, [TS 41])), ((131, 41), Reduce (24, [TS 41]))
            , ((132, 4), Shift 132), ((132, 41), Shift 131)
            , ((133, 2), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 5), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 7), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 13), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 14), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 15), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 16), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 17), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 18), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 19), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 20), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 21), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 22), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 23), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 24), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 25), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 26), Reduce (14, [NS 15, TS 41, TS 12, NS 3])), ((133, 27), Reduce (14, [NS 15, TS 41, TS 12, NS 3]))
            , ((134, 40), Reduce (26, [NS 27, NS 26]))
            , ((135, 4), Shift 132), ((135, 41), Shift 131)
            , ((136, 0), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 1), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 4), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 6), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 9), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 10), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 11), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 28), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 29), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 30), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 31), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 32), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 33), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 34), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 35), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 36), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 37), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 38), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 39), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 41), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 42), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 43), Reduce (19, [TS 36, NS 25, TS 42, TS 2])), ((136, 44), Reduce (19, [TS 36, NS 25, TS 42, TS 2]))
            , ((137, 0), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 1), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 4), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 6), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 9), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 10), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 11), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 28), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 29), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 30), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 31), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 32), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 33), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 34), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 35), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 36), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 37), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 38), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 39), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 41), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 42), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 43), Reduce (19, [TS 36, TS 41, TS 42, TS 2])), ((137, 44), Reduce (19, [TS 36, TS 41, TS 42, TS 2]))
            , ((138, 0), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 1), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 4), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 6), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 9), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 10), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 11), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 28), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 29), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 30), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 31), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 32), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 33), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 34), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 35), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 36), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 37), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 38), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 39), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 41), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 42), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 43), Reduce (19, [TS 34, NS 25, TS 42, TS 2])), ((138, 44), Reduce (19, [TS 34, NS 25, TS 42, TS 2]))
            , ((139, 0), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 1), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 4), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 6), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 9), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 10), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 11), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 28), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 29), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 30), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 31), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 32), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 33), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 34), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 35), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 36), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 37), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 38), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 39), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 41), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 42), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 43), Reduce (19, [TS 34, TS 41, TS 42, TS 2])), ((139, 44), Reduce (19, [TS 34, TS 41, TS 42, TS 2]))
            , ((140, 0), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 1), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 4), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 6), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 9), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 10), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 11), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 28), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 29), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 30), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 31), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 32), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 33), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 34), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 35), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 36), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 37), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 38), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 39), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 41), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 42), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 43), Reduce (19, [TS 35, NS 25, TS 42, TS 2])), ((140, 44), Reduce (19, [TS 35, NS 25, TS 42, TS 2]))
            , ((141, 0), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 1), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 4), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 6), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 9), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 10), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 11), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 28), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 29), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 30), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 31), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 32), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 33), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 34), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 35), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 36), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 37), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 38), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 39), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 41), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 42), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 43), Reduce (19, [TS 35, TS 41, TS 42, TS 2])), ((141, 44), Reduce (19, [TS 35, TS 41, TS 42, TS 2]))
            , ((142, 0), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 1), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 4), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 6), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 9), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 10), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 11), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 28), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 29), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 30), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 31), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 32), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 33), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 34), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 35), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 36), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 37), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 38), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 39), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 41), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 42), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 43), Reduce (19, [TS 32, TS 41, NS 20, TS 2])), ((142, 44), Reduce (19, [TS 32, TS 41, NS 20, TS 2]))
            , ((143, 4), Shift 119), ((143, 33), Shift 120)
            , ((144, 5), Shift 155)
            , ((145, 7), Reduce (17, [NS 9, TS 16, NS 17]))
            , ((146, 1), Shift 41), ((146, 4), Shift 30), ((146, 6), Shift 29), ((146, 9), Shift 33), ((146, 10), Shift 36), ((146, 11), Shift 38), ((146, 28), Shift 21), ((146, 29), Shift 39), ((146, 30), Shift 23), ((146, 31), Shift 22), ((146, 41), Shift 24), ((146, 42), Shift 31), ((146, 43), Shift 20), ((146, 44), Shift 37)
            , ((147, 0), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 1), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 4), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 6), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 9), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 10), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 11), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 28), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 29), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 30), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 31), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 32), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 33), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 34), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 35), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 36), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 37), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 38), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 39), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 41), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 42), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 43), Reduce (19, [TS 37, NS 25, TS 42, TS 2])), ((147, 44), Reduce (19, [TS 37, NS 25, TS 42, TS 2]))
            , ((148, 0), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 1), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 4), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 6), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 9), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 10), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 11), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 28), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 29), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 30), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 31), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 32), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 33), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 34), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 35), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 36), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 37), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 38), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 39), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 41), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 42), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 43), Reduce (19, [TS 37, TS 41, TS 42, TS 2])), ((148, 44), Reduce (19, [TS 37, TS 41, TS 42, TS 2]))
            , ((149, 0), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 1), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 4), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 6), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 9), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 10), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 11), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 28), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 29), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 30), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 31), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 32), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 33), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 34), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 35), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 36), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 37), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 38), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 39), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 41), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 42), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 43), Reduce (19, [TS 33, TS 41, NS 22, TS 2])), ((149, 44), Reduce (19, [TS 33, TS 41, NS 22, TS 2]))
            , ((150, 2), Reduce (23, [NS 23, NS 24])), ((150, 3), Reduce (23, [NS 23, NS 24])), ((150, 4), Reduce (23, [NS 23, NS 24])), ((150, 5), Reduce (23, [NS 23, NS 24])), ((150, 41), Reduce (23, [NS 23, NS 24]))
            , ((151, 4), Shift 132), ((151, 41), Shift 131)
            , ((152, 5), Shift 158)
            , ((153, 2), Shift 159)
            , ((154, 2), Reduce (20, [NS 21, TS 3, NS 20])), ((154, 5), Reduce (20, [NS 21, TS 3, NS 20]))
            , ((155, 2), Reduce (21, [TS 4, NS 20, TS 5])), ((155, 3), Reduce (21, [TS 4, NS 20, TS 5])), ((155, 5), Reduce (21, [TS 4, NS 20, TS 5]))
            , ((156, 2), Shift 160)
            , ((157, 2), Reduce (22, [NS 23, TS 3, NS 22])), ((157, 5), Reduce (22, [NS 23, TS 3, NS 22]))
            , ((158, 2), Reduce (24, [TS 4, NS 22, TS 5])), ((158, 3), Reduce (24, [TS 4, NS 22, TS 5])), ((158, 4), Reduce (24, [TS 4, NS 22, TS 5])), ((158, 5), Reduce (24, [TS 4, NS 22, TS 5])), ((158, 41), Reduce (24, [TS 4, NS 22, TS 5]))
            , ((159, 0), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 1), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 4), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 6), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 9), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 10), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 11), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 28), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 29), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 30), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 31), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 32), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 33), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 34), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 35), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 36), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 37), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 38), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 39), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 41), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 42), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 43), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2])), ((159, 44), Reduce (19, [TS 38, TS 41, NS 26, TS 40, NS 22, TS 2]))
            , ((160, 0), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 1), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 4), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 6), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 9), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 10), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 11), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 28), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 29), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 30), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 31), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 32), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 33), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 34), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 35), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 36), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 37), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 38), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 39), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 41), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 42), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 43), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2])), ((160, 44), Reduce (19, [TS 39, TS 41, NS 26, TS 40, NS 3, TS 2]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 18), ((0, 2), 2), ((0, 3), 3), ((0, 4), 4), ((0, 5), 5), ((0, 6), 6), ((0, 7), 7), ((0, 8), 8), ((0, 9), 9), ((0, 10), 10), ((0, 11), 11), ((0, 12), 12), ((0, 13), 13), ((0, 14), 14), ((0, 15), 15), ((0, 16), 16), ((0, 18), 17), ((0, 19), 1)
            , ((1, 3), 3), ((1, 4), 4), ((1, 5), 5), ((1, 6), 6), ((1, 7), 7), ((1, 8), 8), ((1, 9), 9), ((1, 10), 10), ((1, 11), 11), ((1, 12), 12), ((1, 13), 13), ((1, 14), 14), ((1, 15), 15), ((1, 16), 16), ((1, 18), 42), ((1, 19), 1)
            , ((15, 16), 59)
            , ((25, 25), 64)
            , ((26, 25), 76)
            , ((27, 25), 78)
            , ((29, 9), 82), ((29, 10), 10), ((29, 11), 11), ((29, 12), 12), ((29, 13), 13), ((29, 14), 14), ((29, 15), 15), ((29, 16), 16), ((29, 17), 81)
            , ((30, 3), 85), ((30, 4), 4), ((30, 5), 5), ((30, 6), 6), ((30, 7), 7), ((30, 8), 8), ((30, 9), 9), ((30, 10), 10), ((30, 11), 11), ((30, 12), 12), ((30, 13), 13), ((30, 14), 14), ((30, 15), 15), ((30, 16), 16)
            , ((34, 25), 87)
            , ((35, 3), 89), ((35, 4), 4), ((35, 5), 5), ((35, 6), 6), ((35, 7), 7), ((35, 8), 8), ((35, 9), 9), ((35, 10), 10), ((35, 11), 11), ((35, 12), 12), ((35, 13), 13), ((35, 14), 14), ((35, 15), 15), ((35, 16), 16)
            , ((44, 5), 91), ((44, 6), 6), ((44, 7), 7), ((44, 8), 8), ((44, 9), 9), ((44, 10), 10), ((44, 11), 11), ((44, 12), 12), ((44, 13), 13), ((44, 14), 14), ((44, 15), 15), ((44, 16), 16)
            , ((45, 6), 92), ((45, 7), 7), ((45, 8), 8), ((45, 9), 9), ((45, 10), 10), ((45, 11), 11), ((45, 12), 12), ((45, 13), 13), ((45, 14), 14), ((45, 15), 15), ((45, 16), 16)
            , ((46, 8), 93), ((46, 9), 9), ((46, 10), 10), ((46, 11), 11), ((46, 12), 12), ((46, 13), 13), ((46, 14), 14), ((46, 15), 15), ((46, 16), 16)
            , ((47, 6), 94), ((47, 7), 7), ((47, 8), 8), ((47, 9), 9), ((47, 10), 10), ((47, 11), 11), ((47, 12), 12), ((47, 13), 13), ((47, 14), 14), ((47, 15), 15), ((47, 16), 16)
            , ((48, 9), 95), ((48, 10), 10), ((48, 11), 11), ((48, 12), 12), ((48, 13), 13), ((48, 14), 14), ((48, 15), 15), ((48, 16), 16)
            , ((49, 9), 96), ((49, 10), 10), ((49, 11), 11), ((49, 12), 12), ((49, 13), 13), ((49, 14), 14), ((49, 15), 15), ((49, 16), 16)
            , ((50, 9), 97), ((50, 10), 10), ((50, 11), 11), ((50, 12), 12), ((50, 13), 13), ((50, 14), 14), ((50, 15), 15), ((50, 16), 16)
            , ((51, 9), 98), ((51, 10), 10), ((51, 11), 11), ((51, 12), 12), ((51, 13), 13), ((51, 14), 14), ((51, 15), 15), ((51, 16), 16)
            , ((52, 9), 99), ((52, 10), 10), ((52, 11), 11), ((52, 12), 12), ((52, 13), 13), ((52, 14), 14), ((52, 15), 15), ((52, 16), 16)
            , ((53, 9), 100), ((53, 10), 10), ((53, 11), 11), ((53, 12), 12), ((53, 13), 13), ((53, 14), 14), ((53, 15), 15), ((53, 16), 16)
            , ((54, 9), 101), ((54, 10), 10), ((54, 11), 11), ((54, 12), 12), ((54, 13), 13), ((54, 14), 14), ((54, 15), 15), ((54, 16), 16)
            , ((55, 11), 102), ((55, 12), 12), ((55, 13), 13), ((55, 14), 14), ((55, 15), 15), ((55, 16), 16)
            , ((56, 11), 103), ((56, 12), 12), ((56, 13), 13), ((56, 14), 14), ((56, 15), 15), ((56, 16), 16)
            , ((57, 12), 104), ((57, 13), 13), ((57, 14), 14), ((57, 15), 15), ((57, 16), 16)
            , ((58, 12), 105), ((58, 13), 13), ((58, 14), 14), ((58, 15), 15), ((58, 16), 16)
            , ((62, 26), 108), ((62, 27), 107)
            , ((63, 3), 110), ((63, 4), 4), ((63, 5), 5), ((63, 6), 6), ((63, 7), 7), ((63, 8), 8), ((63, 9), 9), ((63, 10), 10), ((63, 11), 11), ((63, 12), 12), ((63, 13), 13), ((63, 14), 14), ((63, 15), 15), ((63, 16), 16)
            , ((80, 20), 117), ((80, 21), 118)
            , ((86, 26), 124), ((86, 27), 107)
            , ((90, 22), 128), ((90, 23), 129), ((90, 24), 130)
            , ((106, 3), 133), ((106, 4), 4), ((106, 5), 5), ((106, 6), 6), ((106, 7), 7), ((106, 8), 8), ((106, 9), 9), ((106, 10), 10), ((106, 11), 11), ((106, 12), 12), ((106, 13), 13), ((106, 14), 14), ((106, 15), 15), ((106, 16), 16)
            , ((107, 26), 134), ((107, 27), 107)
            , ((119, 20), 144), ((119, 21), 118)
            , ((122, 9), 82), ((122, 10), 10), ((122, 11), 11), ((122, 12), 12), ((122, 13), 13), ((122, 14), 14), ((122, 15), 15), ((122, 16), 16), ((122, 17), 145)
            , ((129, 24), 150)
            , ((132, 22), 152), ((132, 23), 129), ((132, 24), 130)
            , ((135, 22), 153), ((135, 23), 129), ((135, 24), 130)
            , ((143, 20), 154), ((143, 21), 118)
            , ((146, 3), 156), ((146, 4), 4), ((146, 5), 5), ((146, 6), 6), ((146, 7), 7), ((146, 8), 8), ((146, 9), 9), ((146, 10), 10), ((146, 11), 11), ((146, 12), 12), ((146, 13), 13), ((146, 14), 14), ((146, 15), 15), ((146, 16), 16)
            , ((151, 22), 157), ((151, 23), 129), ((151, 24), 130)
            ]
        }
