module Hol.ALPHA1.Front.Analyzer.Parser where

import Hol.ALPHA1.Front.Analyzer.Grammar
import Hol.ALPHA1.Front.Header
import qualified Control.Monad.Trans.Class as Y
import qualified Control.Monad.Trans.Except as Y
import qualified Control.Monad.Trans.State.Strict as Y
import qualified Data.Map.Strict as YMap
import qualified Data.Set as YSet

-- the following codes are generated by PGS.

type ParserS = Int

type NSym = Int

type TSym = Int

data Sym
    = NS NSym
    | TS TSym
    deriving (Eq, Ord)

data Action
    = Shift ParserS
    | Reduce (NSym, [Sym])
    | Accept
    deriving (Eq)

data LR1Parser
    = LR1Parser
        { getInitialS :: ParserS
        , getActionTable :: YMap.Map (ParserS, TSym) Action
        , getReduceTable :: YMap.Map (ParserS, NSym) ParserS
        }
    deriving ()

data ParsingTree
    = PTLeaf (Token)
    | PTBranch NSym [ParsingTree]
    deriving ()

runAladdinParser :: [Token] -> Either (Maybe (Token)) (Either TermRep [DeclRep])
runAladdinParser = fmap (getEither getQuery (getSequence getDecl)) . runLALR1 theLALR1Parser where
    getQuery :: ParsingTree -> (TermRep)
    getQuery (PTBranch _ [PTLeaf (T_quest loc_1), _2@(PTBranch guard2 _), PTLeaf (T_dot loc_3)])
        | [guard2] `elem` [[3]] = (getTermRep0 _2)
    getDecl :: ParsingTree -> (DeclRep)
    getDecl (PTBranch _ [PTLeaf (T_kind loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[17]] = RKindDecl ((loc_1) <> (loc_4)) (TC_Named (contents_2)) (getKindRep0 _3)
    getDecl (PTBranch _ [PTLeaf (T_type loc_1), PTLeaf (T_smallid loc_2 contents_2), _3@(PTBranch guard3 _), PTLeaf (T_dot loc_4)])
        | [guard3] `elem` [[19]] = RTypeDecl ((loc_1) <> (loc_4)) (DC_Named (contents_2)) (getTypeRep0 _3)
    getDecl (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_dot loc_2)])
        | [guard1] `elem` [[3]] = RFactDecl (getSLoc (getTermRep0 _1) <> (loc_2)) (getTermRep0 _1)
    getKindRep0 :: ParsingTree -> (KindRep)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[18, 17]] = RKArr (getSLoc (getKindRep1 _1) <> getSLoc (getKindRep0 _3)) (getKindRep1 _1) (getKindRep0 _3)
    getKindRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[18]] = (getKindRep1 _1)
    getKindRep1 :: ParsingTree -> (KindRep)
    getKindRep1 (PTBranch _ [PTLeaf (T_type loc_1)])
        | otherwise = RStar (loc_1)
    getKindRep1 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[17]] = RKPrn ((loc_1) <> (loc_3)) (getKindRep0 _2)
    getTypeRep0 :: ParsingTree -> (TypeRep)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[20, 19]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep0 _3)) (RTyApp (getSLoc (getTypeRep1 _1) <> (loc_2)) (RTyCon (loc_2) TC_Arrow) (getTypeRep1 _1)) (getTypeRep0 _3)
    getTypeRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[20]] = (getTypeRep1 _1)
    getTypeRep1 :: ParsingTree -> (TypeRep)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[20, 21]] = RTyApp (getSLoc (getTypeRep1 _1) <> getSLoc (getTypeRep2 _2)) (getTypeRep1 _1) (getTypeRep2 _2)
    getTypeRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[21]] = (getTypeRep2 _1)
    getTypeRep2 :: ParsingTree -> (TypeRep)
    getTypeRep2 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise = RTyVar (loc_1) (contents_1)
    getTypeRep2 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise = RTyCon (loc_1) (TC_Named (contents_1))
    getTypeRep2 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[19]] = RTyPrn ((loc_1) <> (loc_3)) (getTypeRep0 _2)
    getTermRep0 :: ParsingTree -> (TermRep)
    getTermRep0 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1), PTLeaf (T_bslash loc_2), _3@(PTBranch guard3 _)])
        | [guard3] `elem` [[3]] = RAbs ((loc_1) <> getSLoc (getTermRep0 _3)) (contents_1) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_if loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 3]] = RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep0 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_if)) (getTermRep1 _1)) (getTermRep0 _3)
    getTermRep0 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[4]] = (getTermRep1 _1)
    getTermRep1 :: ParsingTree -> (TermRep)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_semicolon loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[4, 5]] = RApp (getSLoc (getTermRep1 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep1 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_or)) (getTermRep1 _1)) (getTermRep2 _3)
    getTermRep1 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[5]] = (getTermRep2 _1)
    getTermRep2 :: ParsingTree -> (TermRep)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_fatarrow loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 5]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep2 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_imply)) (getTermRep3 _1)) (getTermRep2 _3)
    getTermRep2 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[6]] = (getTermRep3 _1)
    getTermRep3 :: ParsingTree -> (TermRep)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[6, 7]] = RApp (getSLoc (getTermRep3 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep3 _1) <> (loc_2)) (RCon (loc_2) (DC_LO LO_and)) (getTermRep3 _1)) (getTermRep4 _3)
    getTermRep3 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[7]] = (getTermRep4 _1)
    getTermRep4 :: ParsingTree -> (TermRep)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_cons loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 7]] = RApp (getSLoc (getTermRep5 _1) <> getSLoc (getTermRep4 _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getTermRep4 _3)
    getTermRep4 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = (getTermRep5 _1)
    getTermRep5 :: ParsingTree -> (TermRep)
    getTermRep5 (PTBranch _ [PTLeaf (T_pi loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] = RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_pi)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [PTLeaf (T_sigma loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[8]] = RApp ((loc_1) <> getSLoc (getTermRep5 _2)) (RCon (loc_1) (DC_LO LO_sigma)) (getTermRep5 _2)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_Eq loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getAdditiveTerm _1) <> getSLoc (getAdditiveTerm _3)) (RApp (getSLoc (getAdditiveTerm _1) <> (loc_2)) (RCon (loc_2) DC_Eq) (getAdditiveTerm _1)) (getAdditiveTerm _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_arithmetic_predicate loc_2 predicate_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 9]] = RApp (getSLoc (getAdditiveTerm _1) <> getSLoc (getAdditiveTerm _3)) (RApp (getSLoc (getAdditiveTerm _1) <> (loc_2)) (RCon (loc_2) (DC_LO (LO_Arith (predicate_2)))) (getAdditiveTerm _1)) (getAdditiveTerm _3)
    getTermRep5 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[9]] = (getAdditiveTerm _1)
    getAdditiveTerm :: ParsingTree -> (TermRep)
    getAdditiveTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_plus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 10]] = RApp (getSLoc (getAdditiveTerm _1) <> getSLoc (getMultiplicativeTerm _3)) (RApp (getSLoc (getAdditiveTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Add)) (getAdditiveTerm _1)) (getMultiplicativeTerm _3)
    getAdditiveTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_minus loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[9, 10]] = RApp (getSLoc (getAdditiveTerm _1) <> getSLoc (getMultiplicativeTerm _3)) (RApp (getSLoc (getAdditiveTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Subtract)) (getAdditiveTerm _1)) (getMultiplicativeTerm _3)
    getAdditiveTerm (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[10]] = (getMultiplicativeTerm _1)
    getMultiplicativeTerm :: ParsingTree -> (TermRep)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_star loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getMultiplicativeTerm _1) <> getSLoc (getUnaryTerm _3)) (RApp (getSLoc (getMultiplicativeTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Multiply)) (getMultiplicativeTerm _1)) (getUnaryTerm _3)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_slash loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getMultiplicativeTerm _1) <> getSLoc (getUnaryTerm _3)) (RApp (getSLoc (getMultiplicativeTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Divide)) (getMultiplicativeTerm _1)) (getUnaryTerm _3)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_quotient loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getMultiplicativeTerm _1) <> getSLoc (getUnaryTerm _3)) (RApp (getSLoc (getMultiplicativeTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Quotient)) (getMultiplicativeTerm _1)) (getUnaryTerm _3)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_div loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getMultiplicativeTerm _1) <> getSLoc (getUnaryTerm _3)) (RApp (getSLoc (getMultiplicativeTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Div)) (getMultiplicativeTerm _1)) (getUnaryTerm _3)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_mod loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getMultiplicativeTerm _1) <> getSLoc (getUnaryTerm _3)) (RApp (getSLoc (getMultiplicativeTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Mod)) (getMultiplicativeTerm _1)) (getUnaryTerm _3)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_rem loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[10, 11]] = RApp (getSLoc (getMultiplicativeTerm _1) <> getSLoc (getUnaryTerm _3)) (RApp (getSLoc (getMultiplicativeTerm _1) <> (loc_2)) (RCon (loc_2) (DC_Arith AO_Rem)) (getMultiplicativeTerm _1)) (getUnaryTerm _3)
    getMultiplicativeTerm (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[11]] = (getUnaryTerm _1)
    getUnaryTerm :: ParsingTree -> (TermRep)
    getUnaryTerm (PTBranch _ [PTLeaf (T_plus loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[11]] = RApp ((loc_1) <> getSLoc (getUnaryTerm _2)) (RCon (loc_1) (DC_Arith AO_Positive)) (getUnaryTerm _2)
    getUnaryTerm (PTBranch _ [PTLeaf (T_minus loc_1), _2@(PTBranch guard2 _)])
        | [guard2] `elem` [[11]] = RApp ((loc_1) <> getSLoc (getUnaryTerm _2)) (RCon (loc_1) (DC_Arith AO_Negate)) (getUnaryTerm _2)
    getUnaryTerm (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[12]] = (getTermRep6 _1)
    getTermRep6 :: ParsingTree -> (TermRep)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[12, 13]] = RApp (getSLoc (getTermRep6 _1) <> getSLoc (getTermRep7 _2)) (getTermRep6 _1) (getTermRep7 _2)
    getTermRep6 (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[13]] = (getTermRep7 _1)
    getTermRep6 (PTBranch _ [PTLeaf (T_succ loc_1)])
        | otherwise = RCon (loc_1) DC_Succ
    getTermRep7 :: ParsingTree -> (TermRep)
    getTermRep7 (PTBranch _ [PTLeaf (T_lparen loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rparen loc_3)])
        | [guard2] `elem` [[3]] = RPrn ((loc_1) <> (loc_3)) (getTermRep0 _2)
    getTermRep7 (PTBranch _ [PTLeaf (T_cut loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_cut)
    getTermRep7 (PTBranch _ [PTLeaf (T_true loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_true)
    getTermRep7 (PTBranch _ [PTLeaf (T_fail loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_fail)
    getTermRep7 (PTBranch _ [PTLeaf (T_debug loc_1)])
        | otherwise = RCon (loc_1) (DC_LO LO_debug)
    getTermRep7 (PTBranch _ [PTLeaf (T_smallid loc_1 contents_1)])
        | otherwise = RCon (loc_1) (DC_Named (contents_1))
    getTermRep7 (PTBranch _ [PTLeaf (T_largeid loc_1 contents_1)])
        | otherwise = RVar (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_nat_lit loc_1 contents_1)])
        | otherwise = mkNatLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_str_lit loc_1 contents_1)])
        | otherwise = mkStrLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_chr_lit loc_1 contents_1)])
        | otherwise = mkChrLit (loc_1) (contents_1)
    getTermRep7 (PTBranch _ [PTLeaf (T_lbracket loc_1), PTLeaf (T_rbracket loc_2)])
        | otherwise = RCon ((loc_1) <> (loc_2)) DC_Nil
    getTermRep7 (PTBranch _ [PTLeaf (T_lbracket loc_1), _2@(PTBranch guard2 _), PTLeaf (T_rbracket loc_3)])
        | [guard2] `elem` [[14]] = RPrn ((loc_1) <> (loc_3)) (getListBody _2)
    getSequence :: (ParsingTree -> (a)) -> ParsingTree -> ([a])
    getSequence getElem (PTBranch _ [])
        | otherwise = []
    getSequence getElem (PTBranch _ [_1@(PTBranch guard1 _), _2@(PTBranch guard2 _)])
        | [guard1, guard2] `elem` [[16, 15]] = (getElem _1) : (getSequence getElem _2)
    getEither :: (ParsingTree -> (a)) -> (ParsingTree -> (b)) -> ParsingTree -> (Either a b)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[2]] = Left (getLeft _1)
    getEither getLeft getRight (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[15]] = Right (getRight _1)
    getListBody :: ParsingTree -> (TermRep)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _)])
        | [guard1] `elem` [[8]] = RApp (getSLoc (getTermRep5 _1)) (RApp (getSLoc (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Cons) (getTermRep5 _1)) (RCon (getSLoc (getTermRep5 _1)) DC_Nil)
    getListBody (PTBranch _ [_1@(PTBranch guard1 _), PTLeaf (T_comma loc_2), _3@(PTBranch guard3 _)])
        | [guard1, guard3] `elem` [[8, 14]] = RApp (getSLoc (getTermRep5 _1) <> getSLoc (getListBody _3)) (RApp (getSLoc (getTermRep5 _1) <> (loc_2)) (RCon (loc_2) DC_Cons) (getTermRep5 _1)) (getListBody _3)
    toTerminal :: (Token) -> TSym
    toTerminal (T_dot loc) = 1
    toTerminal (T_arrow loc) = 2
    toTerminal (T_lparen loc) = 3
    toTerminal (T_rparen loc) = 4
    toTerminal (T_lbracket loc) = 5
    toTerminal (T_rbracket loc) = 6
    toTerminal (T_quest loc) = 7
    toTerminal (T_if loc) = 8
    toTerminal (T_comma loc) = 9
    toTerminal (T_semicolon loc) = 10
    toTerminal (T_fatarrow loc) = 11
    toTerminal (T_pi loc) = 12
    toTerminal (T_sigma loc) = 13
    toTerminal (T_succ loc) = 14
    toTerminal (T_Eq loc) = 15
    toTerminal (T_arithmetic_predicate loc predicate) = 16
    toTerminal (T_plus loc) = 17
    toTerminal (T_minus loc) = 18
    toTerminal (T_star loc) = 19
    toTerminal (T_slash loc) = 20
    toTerminal (T_quotient loc) = 21
    toTerminal (T_div loc) = 22
    toTerminal (T_mod loc) = 23
    toTerminal (T_rem loc) = 24
    toTerminal (T_cut loc) = 25
    toTerminal (T_true loc) = 26
    toTerminal (T_fail loc) = 27
    toTerminal (T_debug loc) = 28
    toTerminal (T_bslash loc) = 29
    toTerminal (T_cons loc) = 30
    toTerminal (T_kind loc) = 31
    toTerminal (T_type loc) = 32
    toTerminal (T_smallid loc contents) = 33
    toTerminal (T_largeid loc contents) = 34
    toTerminal (T_nat_lit loc contents) = 35
    toTerminal (T_chr_lit loc contents) = 36
    toTerminal (T_str_lit loc contents) = 37
    toTerminal _ = -1
    runLALR1 :: LR1Parser -> [Token] -> Either (Maybe (Token)) ParsingTree
    runLALR1 (LR1Parser getInitS getActionT getReduceT) = go where
        loop inputs = do
            let cur = if null inputs then 0 else toTerminal (head inputs)
                exception = Y.lift (if null inputs then Left Nothing else Left (Just (head inputs)))
            (stack, trees) <- Y.get
            case YMap.lookup (head stack, cur) getActionT of
                Nothing -> exception
                Just Accept -> return ()
                Just (Shift top') -> do
                    Y.put (top' : stack, PTLeaf (head inputs) : trees)
                    loop (tail inputs)
                Just (Reduce (lhs, rhs)) -> do
                    let n = length rhs
                    case YMap.lookup (stack !! n, lhs) getReduceT of
                        Nothing -> exception
                        Just top' -> do
                            Y.put (top' : drop n stack, PTBranch lhs (reverse (take n trees)) : drop n trees)
                            loop inputs
        go tokens = do
            (_, (_, result)) <- Y.runStateT (loop tokens) ([getInitS], [])
            case result of
                [output] -> return output
    theLALR1Parser :: LR1Parser
    theLALR1Parser = LR1Parser
        { getInitialS = 0
        , getActionTable = YMap.fromAscList 
            [ ((0, 0), Reduce (15, [])), ((0, 3), Shift 23), ((0, 5), Shift 22), ((0, 7), Shift 28), ((0, 12), Shift 26), ((0, 13), Shift 29), ((0, 14), Shift 32), ((0, 17), Shift 27), ((0, 18), Shift 24), ((0, 25), Shift 17), ((0, 26), Shift 33), ((0, 27), Shift 19), ((0, 28), Shift 18), ((0, 31), Shift 20), ((0, 32), Shift 34), ((0, 33), Shift 30), ((0, 34), Shift 21), ((0, 35), Shift 25), ((0, 36), Shift 16), ((0, 37), Shift 31)
            , ((1, 1), Reduce (8, [NS 9])), ((1, 4), Reduce (8, [NS 9])), ((1, 6), Reduce (8, [NS 9])), ((1, 8), Reduce (8, [NS 9])), ((1, 9), Reduce (8, [NS 9])), ((1, 10), Reduce (8, [NS 9])), ((1, 11), Reduce (8, [NS 9])), ((1, 15), Shift 36), ((1, 16), Shift 35), ((1, 17), Shift 38), ((1, 18), Shift 37), ((1, 30), Reduce (8, [NS 9]))
            , ((2, 0), Reduce (15, [])), ((2, 3), Shift 23), ((2, 5), Shift 22), ((2, 12), Shift 26), ((2, 13), Shift 29), ((2, 14), Shift 32), ((2, 17), Shift 27), ((2, 18), Shift 24), ((2, 25), Shift 17), ((2, 26), Shift 33), ((2, 27), Shift 19), ((2, 28), Shift 18), ((2, 31), Shift 20), ((2, 32), Shift 34), ((2, 33), Shift 30), ((2, 34), Shift 21), ((2, 35), Shift 25), ((2, 36), Shift 16), ((2, 37), Shift 31)
            , ((3, 1), Reduce (9, [NS 10])), ((3, 4), Reduce (9, [NS 10])), ((3, 6), Reduce (9, [NS 10])), ((3, 8), Reduce (9, [NS 10])), ((3, 9), Reduce (9, [NS 10])), ((3, 10), Reduce (9, [NS 10])), ((3, 11), Reduce (9, [NS 10])), ((3, 15), Reduce (9, [NS 10])), ((3, 16), Reduce (9, [NS 10])), ((3, 17), Reduce (9, [NS 10])), ((3, 18), Reduce (9, [NS 10])), ((3, 19), Shift 45), ((3, 20), Shift 44), ((3, 21), Shift 42), ((3, 22), Shift 40), ((3, 23), Shift 41), ((3, 24), Shift 43), ((3, 30), Reduce (9, [NS 10]))
            , ((4, 0), Reduce (1, [NS 2]))
            , ((5, 1), Shift 46)
            , ((6, 1), Reduce (3, [NS 4])), ((6, 4), Reduce (3, [NS 4])), ((6, 8), Shift 47), ((6, 10), Shift 48)
            , ((7, 1), Reduce (4, [NS 5])), ((7, 4), Reduce (4, [NS 5])), ((7, 8), Reduce (4, [NS 5])), ((7, 10), Reduce (4, [NS 5]))
            , ((8, 1), Reduce (5, [NS 6])), ((8, 4), Reduce (5, [NS 6])), ((8, 8), Reduce (5, [NS 6])), ((8, 9), Shift 49), ((8, 10), Reduce (5, [NS 6])), ((8, 11), Shift 50)
            , ((9, 1), Reduce (6, [NS 7])), ((9, 4), Reduce (6, [NS 7])), ((9, 8), Reduce (6, [NS 7])), ((9, 9), Reduce (6, [NS 7])), ((9, 10), Reduce (6, [NS 7])), ((9, 11), Reduce (6, [NS 7]))
            , ((10, 1), Reduce (7, [NS 8])), ((10, 4), Reduce (7, [NS 8])), ((10, 8), Reduce (7, [NS 8])), ((10, 9), Reduce (7, [NS 8])), ((10, 10), Reduce (7, [NS 8])), ((10, 11), Reduce (7, [NS 8])), ((10, 30), Shift 51)
            , ((11, 1), Reduce (11, [NS 12])), ((11, 3), Shift 23), ((11, 4), Reduce (11, [NS 12])), ((11, 5), Shift 22), ((11, 6), Reduce (11, [NS 12])), ((11, 8), Reduce (11, [NS 12])), ((11, 9), Reduce (11, [NS 12])), ((11, 10), Reduce (11, [NS 12])), ((11, 11), Reduce (11, [NS 12])), ((11, 15), Reduce (11, [NS 12])), ((11, 16), Reduce (11, [NS 12])), ((11, 17), Reduce (11, [NS 12])), ((11, 18), Reduce (11, [NS 12])), ((11, 19), Reduce (11, [NS 12])), ((11, 20), Reduce (11, [NS 12])), ((11, 21), Reduce (11, [NS 12])), ((11, 22), Reduce (11, [NS 12])), ((11, 23), Reduce (11, [NS 12])), ((11, 24), Reduce (11, [NS 12])), ((11, 25), Shift 17), ((11, 26), Shift 33), ((11, 27), Shift 19), ((11, 28), Shift 18), ((11, 30), Reduce (11, [NS 12])), ((11, 33), Shift 30), ((11, 34), Shift 53), ((11, 35), Shift 25), ((11, 36), Shift 16), ((11, 37), Shift 31)
            , ((12, 1), Reduce (12, [NS 13])), ((12, 3), Reduce (12, [NS 13])), ((12, 4), Reduce (12, [NS 13])), ((12, 5), Reduce (12, [NS 13])), ((12, 6), Reduce (12, [NS 13])), ((12, 8), Reduce (12, [NS 13])), ((12, 9), Reduce (12, [NS 13])), ((12, 10), Reduce (12, [NS 13])), ((12, 11), Reduce (12, [NS 13])), ((12, 15), Reduce (12, [NS 13])), ((12, 16), Reduce (12, [NS 13])), ((12, 17), Reduce (12, [NS 13])), ((12, 18), Reduce (12, [NS 13])), ((12, 19), Reduce (12, [NS 13])), ((12, 20), Reduce (12, [NS 13])), ((12, 21), Reduce (12, [NS 13])), ((12, 22), Reduce (12, [NS 13])), ((12, 23), Reduce (12, [NS 13])), ((12, 24), Reduce (12, [NS 13])), ((12, 25), Reduce (12, [NS 13])), ((12, 26), Reduce (12, [NS 13])), ((12, 27), Reduce (12, [NS 13])), ((12, 28), Reduce (12, [NS 13])), ((12, 30), Reduce (12, [NS 13])), ((12, 33), Reduce (12, [NS 13])), ((12, 34), Reduce (12, [NS 13])), ((12, 35), Reduce (12, [NS 13])), ((12, 36), Reduce (12, [NS 13])), ((12, 37), Reduce (12, [NS 13]))
            , ((13, 1), Reduce (10, [NS 11])), ((13, 4), Reduce (10, [NS 11])), ((13, 6), Reduce (10, [NS 11])), ((13, 8), Reduce (10, [NS 11])), ((13, 9), Reduce (10, [NS 11])), ((13, 10), Reduce (10, [NS 11])), ((13, 11), Reduce (10, [NS 11])), ((13, 15), Reduce (10, [NS 11])), ((13, 16), Reduce (10, [NS 11])), ((13, 17), Reduce (10, [NS 11])), ((13, 18), Reduce (10, [NS 11])), ((13, 19), Reduce (10, [NS 11])), ((13, 20), Reduce (10, [NS 11])), ((13, 21), Reduce (10, [NS 11])), ((13, 22), Reduce (10, [NS 11])), ((13, 23), Reduce (10, [NS 11])), ((13, 24), Reduce (10, [NS 11])), ((13, 30), Reduce (10, [NS 11]))
            , ((14, 0), Reduce (1, [NS 15]))
            , ((15, 0), Accept)
            , ((16, 1), Reduce (13, [TS 36])), ((16, 3), Reduce (13, [TS 36])), ((16, 4), Reduce (13, [TS 36])), ((16, 5), Reduce (13, [TS 36])), ((16, 6), Reduce (13, [TS 36])), ((16, 8), Reduce (13, [TS 36])), ((16, 9), Reduce (13, [TS 36])), ((16, 10), Reduce (13, [TS 36])), ((16, 11), Reduce (13, [TS 36])), ((16, 15), Reduce (13, [TS 36])), ((16, 16), Reduce (13, [TS 36])), ((16, 17), Reduce (13, [TS 36])), ((16, 18), Reduce (13, [TS 36])), ((16, 19), Reduce (13, [TS 36])), ((16, 20), Reduce (13, [TS 36])), ((16, 21), Reduce (13, [TS 36])), ((16, 22), Reduce (13, [TS 36])), ((16, 23), Reduce (13, [TS 36])), ((16, 24), Reduce (13, [TS 36])), ((16, 25), Reduce (13, [TS 36])), ((16, 26), Reduce (13, [TS 36])), ((16, 27), Reduce (13, [TS 36])), ((16, 28), Reduce (13, [TS 36])), ((16, 30), Reduce (13, [TS 36])), ((16, 33), Reduce (13, [TS 36])), ((16, 34), Reduce (13, [TS 36])), ((16, 35), Reduce (13, [TS 36])), ((16, 36), Reduce (13, [TS 36])), ((16, 37), Reduce (13, [TS 36]))
            , ((17, 1), Reduce (13, [TS 25])), ((17, 3), Reduce (13, [TS 25])), ((17, 4), Reduce (13, [TS 25])), ((17, 5), Reduce (13, [TS 25])), ((17, 6), Reduce (13, [TS 25])), ((17, 8), Reduce (13, [TS 25])), ((17, 9), Reduce (13, [TS 25])), ((17, 10), Reduce (13, [TS 25])), ((17, 11), Reduce (13, [TS 25])), ((17, 15), Reduce (13, [TS 25])), ((17, 16), Reduce (13, [TS 25])), ((17, 17), Reduce (13, [TS 25])), ((17, 18), Reduce (13, [TS 25])), ((17, 19), Reduce (13, [TS 25])), ((17, 20), Reduce (13, [TS 25])), ((17, 21), Reduce (13, [TS 25])), ((17, 22), Reduce (13, [TS 25])), ((17, 23), Reduce (13, [TS 25])), ((17, 24), Reduce (13, [TS 25])), ((17, 25), Reduce (13, [TS 25])), ((17, 26), Reduce (13, [TS 25])), ((17, 27), Reduce (13, [TS 25])), ((17, 28), Reduce (13, [TS 25])), ((17, 30), Reduce (13, [TS 25])), ((17, 33), Reduce (13, [TS 25])), ((17, 34), Reduce (13, [TS 25])), ((17, 35), Reduce (13, [TS 25])), ((17, 36), Reduce (13, [TS 25])), ((17, 37), Reduce (13, [TS 25]))
            , ((18, 1), Reduce (13, [TS 28])), ((18, 3), Reduce (13, [TS 28])), ((18, 4), Reduce (13, [TS 28])), ((18, 5), Reduce (13, [TS 28])), ((18, 6), Reduce (13, [TS 28])), ((18, 8), Reduce (13, [TS 28])), ((18, 9), Reduce (13, [TS 28])), ((18, 10), Reduce (13, [TS 28])), ((18, 11), Reduce (13, [TS 28])), ((18, 15), Reduce (13, [TS 28])), ((18, 16), Reduce (13, [TS 28])), ((18, 17), Reduce (13, [TS 28])), ((18, 18), Reduce (13, [TS 28])), ((18, 19), Reduce (13, [TS 28])), ((18, 20), Reduce (13, [TS 28])), ((18, 21), Reduce (13, [TS 28])), ((18, 22), Reduce (13, [TS 28])), ((18, 23), Reduce (13, [TS 28])), ((18, 24), Reduce (13, [TS 28])), ((18, 25), Reduce (13, [TS 28])), ((18, 26), Reduce (13, [TS 28])), ((18, 27), Reduce (13, [TS 28])), ((18, 28), Reduce (13, [TS 28])), ((18, 30), Reduce (13, [TS 28])), ((18, 33), Reduce (13, [TS 28])), ((18, 34), Reduce (13, [TS 28])), ((18, 35), Reduce (13, [TS 28])), ((18, 36), Reduce (13, [TS 28])), ((18, 37), Reduce (13, [TS 28]))
            , ((19, 1), Reduce (13, [TS 27])), ((19, 3), Reduce (13, [TS 27])), ((19, 4), Reduce (13, [TS 27])), ((19, 5), Reduce (13, [TS 27])), ((19, 6), Reduce (13, [TS 27])), ((19, 8), Reduce (13, [TS 27])), ((19, 9), Reduce (13, [TS 27])), ((19, 10), Reduce (13, [TS 27])), ((19, 11), Reduce (13, [TS 27])), ((19, 15), Reduce (13, [TS 27])), ((19, 16), Reduce (13, [TS 27])), ((19, 17), Reduce (13, [TS 27])), ((19, 18), Reduce (13, [TS 27])), ((19, 19), Reduce (13, [TS 27])), ((19, 20), Reduce (13, [TS 27])), ((19, 21), Reduce (13, [TS 27])), ((19, 22), Reduce (13, [TS 27])), ((19, 23), Reduce (13, [TS 27])), ((19, 24), Reduce (13, [TS 27])), ((19, 25), Reduce (13, [TS 27])), ((19, 26), Reduce (13, [TS 27])), ((19, 27), Reduce (13, [TS 27])), ((19, 28), Reduce (13, [TS 27])), ((19, 30), Reduce (13, [TS 27])), ((19, 33), Reduce (13, [TS 27])), ((19, 34), Reduce (13, [TS 27])), ((19, 35), Reduce (13, [TS 27])), ((19, 36), Reduce (13, [TS 27])), ((19, 37), Reduce (13, [TS 27]))
            , ((20, 33), Shift 55)
            , ((21, 1), Reduce (13, [TS 34])), ((21, 3), Reduce (13, [TS 34])), ((21, 4), Reduce (13, [TS 34])), ((21, 5), Reduce (13, [TS 34])), ((21, 8), Reduce (13, [TS 34])), ((21, 9), Reduce (13, [TS 34])), ((21, 10), Reduce (13, [TS 34])), ((21, 11), Reduce (13, [TS 34])), ((21, 15), Reduce (13, [TS 34])), ((21, 16), Reduce (13, [TS 34])), ((21, 17), Reduce (13, [TS 34])), ((21, 18), Reduce (13, [TS 34])), ((21, 19), Reduce (13, [TS 34])), ((21, 20), Reduce (13, [TS 34])), ((21, 21), Reduce (13, [TS 34])), ((21, 22), Reduce (13, [TS 34])), ((21, 23), Reduce (13, [TS 34])), ((21, 24), Reduce (13, [TS 34])), ((21, 25), Reduce (13, [TS 34])), ((21, 26), Reduce (13, [TS 34])), ((21, 27), Reduce (13, [TS 34])), ((21, 28), Reduce (13, [TS 34])), ((21, 29), Shift 56), ((21, 30), Reduce (13, [TS 34])), ((21, 33), Reduce (13, [TS 34])), ((21, 34), Reduce (13, [TS 34])), ((21, 35), Reduce (13, [TS 34])), ((21, 36), Reduce (13, [TS 34])), ((21, 37), Reduce (13, [TS 34]))
            , ((22, 3), Shift 23), ((22, 5), Shift 22), ((22, 6), Shift 59), ((22, 12), Shift 26), ((22, 13), Shift 29), ((22, 14), Shift 32), ((22, 17), Shift 27), ((22, 18), Shift 24), ((22, 25), Shift 17), ((22, 26), Shift 33), ((22, 27), Shift 19), ((22, 28), Shift 18), ((22, 33), Shift 30), ((22, 34), Shift 53), ((22, 35), Shift 25), ((22, 36), Shift 16), ((22, 37), Shift 31)
            , ((23, 3), Shift 23), ((23, 5), Shift 22), ((23, 12), Shift 26), ((23, 13), Shift 29), ((23, 14), Shift 32), ((23, 17), Shift 27), ((23, 18), Shift 24), ((23, 25), Shift 17), ((23, 26), Shift 33), ((23, 27), Shift 19), ((23, 28), Shift 18), ((23, 33), Shift 30), ((23, 34), Shift 21), ((23, 35), Shift 25), ((23, 36), Shift 16), ((23, 37), Shift 31)
            , ((24, 3), Shift 23), ((24, 5), Shift 22), ((24, 14), Shift 32), ((24, 17), Shift 27), ((24, 18), Shift 24), ((24, 25), Shift 17), ((24, 26), Shift 33), ((24, 27), Shift 19), ((24, 28), Shift 18), ((24, 33), Shift 30), ((24, 34), Shift 53), ((24, 35), Shift 25), ((24, 36), Shift 16), ((24, 37), Shift 31)
            , ((25, 1), Reduce (13, [TS 35])), ((25, 3), Reduce (13, [TS 35])), ((25, 4), Reduce (13, [TS 35])), ((25, 5), Reduce (13, [TS 35])), ((25, 6), Reduce (13, [TS 35])), ((25, 8), Reduce (13, [TS 35])), ((25, 9), Reduce (13, [TS 35])), ((25, 10), Reduce (13, [TS 35])), ((25, 11), Reduce (13, [TS 35])), ((25, 15), Reduce (13, [TS 35])), ((25, 16), Reduce (13, [TS 35])), ((25, 17), Reduce (13, [TS 35])), ((25, 18), Reduce (13, [TS 35])), ((25, 19), Reduce (13, [TS 35])), ((25, 20), Reduce (13, [TS 35])), ((25, 21), Reduce (13, [TS 35])), ((25, 22), Reduce (13, [TS 35])), ((25, 23), Reduce (13, [TS 35])), ((25, 24), Reduce (13, [TS 35])), ((25, 25), Reduce (13, [TS 35])), ((25, 26), Reduce (13, [TS 35])), ((25, 27), Reduce (13, [TS 35])), ((25, 28), Reduce (13, [TS 35])), ((25, 30), Reduce (13, [TS 35])), ((25, 33), Reduce (13, [TS 35])), ((25, 34), Reduce (13, [TS 35])), ((25, 35), Reduce (13, [TS 35])), ((25, 36), Reduce (13, [TS 35])), ((25, 37), Reduce (13, [TS 35]))
            , ((26, 3), Shift 23), ((26, 5), Shift 22), ((26, 12), Shift 26), ((26, 13), Shift 29), ((26, 14), Shift 32), ((26, 17), Shift 27), ((26, 18), Shift 24), ((26, 25), Shift 17), ((26, 26), Shift 33), ((26, 27), Shift 19), ((26, 28), Shift 18), ((26, 33), Shift 30), ((26, 34), Shift 53), ((26, 35), Shift 25), ((26, 36), Shift 16), ((26, 37), Shift 31)
            , ((27, 3), Shift 23), ((27, 5), Shift 22), ((27, 14), Shift 32), ((27, 17), Shift 27), ((27, 18), Shift 24), ((27, 25), Shift 17), ((27, 26), Shift 33), ((27, 27), Shift 19), ((27, 28), Shift 18), ((27, 33), Shift 30), ((27, 34), Shift 53), ((27, 35), Shift 25), ((27, 36), Shift 16), ((27, 37), Shift 31)
            , ((28, 3), Shift 23), ((28, 5), Shift 22), ((28, 12), Shift 26), ((28, 13), Shift 29), ((28, 14), Shift 32), ((28, 17), Shift 27), ((28, 18), Shift 24), ((28, 25), Shift 17), ((28, 26), Shift 33), ((28, 27), Shift 19), ((28, 28), Shift 18), ((28, 33), Shift 30), ((28, 34), Shift 21), ((28, 35), Shift 25), ((28, 36), Shift 16), ((28, 37), Shift 31)
            , ((29, 3), Shift 23), ((29, 5), Shift 22), ((29, 12), Shift 26), ((29, 13), Shift 29), ((29, 14), Shift 32), ((29, 17), Shift 27), ((29, 18), Shift 24), ((29, 25), Shift 17), ((29, 26), Shift 33), ((29, 27), Shift 19), ((29, 28), Shift 18), ((29, 33), Shift 30), ((29, 34), Shift 53), ((29, 35), Shift 25), ((29, 36), Shift 16), ((29, 37), Shift 31)
            , ((30, 1), Reduce (13, [TS 33])), ((30, 3), Reduce (13, [TS 33])), ((30, 4), Reduce (13, [TS 33])), ((30, 5), Reduce (13, [TS 33])), ((30, 6), Reduce (13, [TS 33])), ((30, 8), Reduce (13, [TS 33])), ((30, 9), Reduce (13, [TS 33])), ((30, 10), Reduce (13, [TS 33])), ((30, 11), Reduce (13, [TS 33])), ((30, 15), Reduce (13, [TS 33])), ((30, 16), Reduce (13, [TS 33])), ((30, 17), Reduce (13, [TS 33])), ((30, 18), Reduce (13, [TS 33])), ((30, 19), Reduce (13, [TS 33])), ((30, 20), Reduce (13, [TS 33])), ((30, 21), Reduce (13, [TS 33])), ((30, 22), Reduce (13, [TS 33])), ((30, 23), Reduce (13, [TS 33])), ((30, 24), Reduce (13, [TS 33])), ((30, 25), Reduce (13, [TS 33])), ((30, 26), Reduce (13, [TS 33])), ((30, 27), Reduce (13, [TS 33])), ((30, 28), Reduce (13, [TS 33])), ((30, 30), Reduce (13, [TS 33])), ((30, 33), Reduce (13, [TS 33])), ((30, 34), Reduce (13, [TS 33])), ((30, 35), Reduce (13, [TS 33])), ((30, 36), Reduce (13, [TS 33])), ((30, 37), Reduce (13, [TS 33]))
            , ((31, 1), Reduce (13, [TS 37])), ((31, 3), Reduce (13, [TS 37])), ((31, 4), Reduce (13, [TS 37])), ((31, 5), Reduce (13, [TS 37])), ((31, 6), Reduce (13, [TS 37])), ((31, 8), Reduce (13, [TS 37])), ((31, 9), Reduce (13, [TS 37])), ((31, 10), Reduce (13, [TS 37])), ((31, 11), Reduce (13, [TS 37])), ((31, 15), Reduce (13, [TS 37])), ((31, 16), Reduce (13, [TS 37])), ((31, 17), Reduce (13, [TS 37])), ((31, 18), Reduce (13, [TS 37])), ((31, 19), Reduce (13, [TS 37])), ((31, 20), Reduce (13, [TS 37])), ((31, 21), Reduce (13, [TS 37])), ((31, 22), Reduce (13, [TS 37])), ((31, 23), Reduce (13, [TS 37])), ((31, 24), Reduce (13, [TS 37])), ((31, 25), Reduce (13, [TS 37])), ((31, 26), Reduce (13, [TS 37])), ((31, 27), Reduce (13, [TS 37])), ((31, 28), Reduce (13, [TS 37])), ((31, 30), Reduce (13, [TS 37])), ((31, 33), Reduce (13, [TS 37])), ((31, 34), Reduce (13, [TS 37])), ((31, 35), Reduce (13, [TS 37])), ((31, 36), Reduce (13, [TS 37])), ((31, 37), Reduce (13, [TS 37]))
            , ((32, 1), Reduce (12, [TS 14])), ((32, 3), Reduce (12, [TS 14])), ((32, 4), Reduce (12, [TS 14])), ((32, 5), Reduce (12, [TS 14])), ((32, 6), Reduce (12, [TS 14])), ((32, 8), Reduce (12, [TS 14])), ((32, 9), Reduce (12, [TS 14])), ((32, 10), Reduce (12, [TS 14])), ((32, 11), Reduce (12, [TS 14])), ((32, 15), Reduce (12, [TS 14])), ((32, 16), Reduce (12, [TS 14])), ((32, 17), Reduce (12, [TS 14])), ((32, 18), Reduce (12, [TS 14])), ((32, 19), Reduce (12, [TS 14])), ((32, 20), Reduce (12, [TS 14])), ((32, 21), Reduce (12, [TS 14])), ((32, 22), Reduce (12, [TS 14])), ((32, 23), Reduce (12, [TS 14])), ((32, 24), Reduce (12, [TS 14])), ((32, 25), Reduce (12, [TS 14])), ((32, 26), Reduce (12, [TS 14])), ((32, 27), Reduce (12, [TS 14])), ((32, 28), Reduce (12, [TS 14])), ((32, 30), Reduce (12, [TS 14])), ((32, 33), Reduce (12, [TS 14])), ((32, 34), Reduce (12, [TS 14])), ((32, 35), Reduce (12, [TS 14])), ((32, 36), Reduce (12, [TS 14])), ((32, 37), Reduce (12, [TS 14]))
            , ((33, 1), Reduce (13, [TS 26])), ((33, 3), Reduce (13, [TS 26])), ((33, 4), Reduce (13, [TS 26])), ((33, 5), Reduce (13, [TS 26])), ((33, 6), Reduce (13, [TS 26])), ((33, 8), Reduce (13, [TS 26])), ((33, 9), Reduce (13, [TS 26])), ((33, 10), Reduce (13, [TS 26])), ((33, 11), Reduce (13, [TS 26])), ((33, 15), Reduce (13, [TS 26])), ((33, 16), Reduce (13, [TS 26])), ((33, 17), Reduce (13, [TS 26])), ((33, 18), Reduce (13, [TS 26])), ((33, 19), Reduce (13, [TS 26])), ((33, 20), Reduce (13, [TS 26])), ((33, 21), Reduce (13, [TS 26])), ((33, 22), Reduce (13, [TS 26])), ((33, 23), Reduce (13, [TS 26])), ((33, 24), Reduce (13, [TS 26])), ((33, 25), Reduce (13, [TS 26])), ((33, 26), Reduce (13, [TS 26])), ((33, 27), Reduce (13, [TS 26])), ((33, 28), Reduce (13, [TS 26])), ((33, 30), Reduce (13, [TS 26])), ((33, 33), Reduce (13, [TS 26])), ((33, 34), Reduce (13, [TS 26])), ((33, 35), Reduce (13, [TS 26])), ((33, 36), Reduce (13, [TS 26])), ((33, 37), Reduce (13, [TS 26]))
            , ((34, 33), Shift 66)
            , ((35, 3), Shift 23), ((35, 5), Shift 22), ((35, 14), Shift 32), ((35, 17), Shift 27), ((35, 18), Shift 24), ((35, 25), Shift 17), ((35, 26), Shift 33), ((35, 27), Shift 19), ((35, 28), Shift 18), ((35, 33), Shift 30), ((35, 34), Shift 53), ((35, 35), Shift 25), ((35, 36), Shift 16), ((35, 37), Shift 31)
            , ((36, 3), Shift 23), ((36, 5), Shift 22), ((36, 14), Shift 32), ((36, 17), Shift 27), ((36, 18), Shift 24), ((36, 25), Shift 17), ((36, 26), Shift 33), ((36, 27), Shift 19), ((36, 28), Shift 18), ((36, 33), Shift 30), ((36, 34), Shift 53), ((36, 35), Shift 25), ((36, 36), Shift 16), ((36, 37), Shift 31)
            , ((37, 3), Shift 23), ((37, 5), Shift 22), ((37, 14), Shift 32), ((37, 17), Shift 27), ((37, 18), Shift 24), ((37, 25), Shift 17), ((37, 26), Shift 33), ((37, 27), Shift 19), ((37, 28), Shift 18), ((37, 33), Shift 30), ((37, 34), Shift 53), ((37, 35), Shift 25), ((37, 36), Shift 16), ((37, 37), Shift 31)
            , ((38, 3), Shift 23), ((38, 5), Shift 22), ((38, 14), Shift 32), ((38, 17), Shift 27), ((38, 18), Shift 24), ((38, 25), Shift 17), ((38, 26), Shift 33), ((38, 27), Shift 19), ((38, 28), Shift 18), ((38, 33), Shift 30), ((38, 34), Shift 53), ((38, 35), Shift 25), ((38, 36), Shift 16), ((38, 37), Shift 31)
            , ((39, 0), Reduce (15, [NS 16, NS 15]))
            , ((40, 3), Shift 23), ((40, 5), Shift 22), ((40, 14), Shift 32), ((40, 17), Shift 27), ((40, 18), Shift 24), ((40, 25), Shift 17), ((40, 26), Shift 33), ((40, 27), Shift 19), ((40, 28), Shift 18), ((40, 33), Shift 30), ((40, 34), Shift 53), ((40, 35), Shift 25), ((40, 36), Shift 16), ((40, 37), Shift 31)
            , ((41, 3), Shift 23), ((41, 5), Shift 22), ((41, 14), Shift 32), ((41, 17), Shift 27), ((41, 18), Shift 24), ((41, 25), Shift 17), ((41, 26), Shift 33), ((41, 27), Shift 19), ((41, 28), Shift 18), ((41, 33), Shift 30), ((41, 34), Shift 53), ((41, 35), Shift 25), ((41, 36), Shift 16), ((41, 37), Shift 31)
            , ((42, 3), Shift 23), ((42, 5), Shift 22), ((42, 14), Shift 32), ((42, 17), Shift 27), ((42, 18), Shift 24), ((42, 25), Shift 17), ((42, 26), Shift 33), ((42, 27), Shift 19), ((42, 28), Shift 18), ((42, 33), Shift 30), ((42, 34), Shift 53), ((42, 35), Shift 25), ((42, 36), Shift 16), ((42, 37), Shift 31)
            , ((43, 3), Shift 23), ((43, 5), Shift 22), ((43, 14), Shift 32), ((43, 17), Shift 27), ((43, 18), Shift 24), ((43, 25), Shift 17), ((43, 26), Shift 33), ((43, 27), Shift 19), ((43, 28), Shift 18), ((43, 33), Shift 30), ((43, 34), Shift 53), ((43, 35), Shift 25), ((43, 36), Shift 16), ((43, 37), Shift 31)
            , ((44, 3), Shift 23), ((44, 5), Shift 22), ((44, 14), Shift 32), ((44, 17), Shift 27), ((44, 18), Shift 24), ((44, 25), Shift 17), ((44, 26), Shift 33), ((44, 27), Shift 19), ((44, 28), Shift 18), ((44, 33), Shift 30), ((44, 34), Shift 53), ((44, 35), Shift 25), ((44, 36), Shift 16), ((44, 37), Shift 31)
            , ((45, 3), Shift 23), ((45, 5), Shift 22), ((45, 14), Shift 32), ((45, 17), Shift 27), ((45, 18), Shift 24), ((45, 25), Shift 17), ((45, 26), Shift 33), ((45, 27), Shift 19), ((45, 28), Shift 18), ((45, 33), Shift 30), ((45, 34), Shift 53), ((45, 35), Shift 25), ((45, 36), Shift 16), ((45, 37), Shift 31)
            , ((46, 0), Reduce (16, [NS 3, TS 1])), ((46, 3), Reduce (16, [NS 3, TS 1])), ((46, 5), Reduce (16, [NS 3, TS 1])), ((46, 12), Reduce (16, [NS 3, TS 1])), ((46, 13), Reduce (16, [NS 3, TS 1])), ((46, 14), Reduce (16, [NS 3, TS 1])), ((46, 17), Reduce (16, [NS 3, TS 1])), ((46, 18), Reduce (16, [NS 3, TS 1])), ((46, 25), Reduce (16, [NS 3, TS 1])), ((46, 26), Reduce (16, [NS 3, TS 1])), ((46, 27), Reduce (16, [NS 3, TS 1])), ((46, 28), Reduce (16, [NS 3, TS 1])), ((46, 31), Reduce (16, [NS 3, TS 1])), ((46, 32), Reduce (16, [NS 3, TS 1])), ((46, 33), Reduce (16, [NS 3, TS 1])), ((46, 34), Reduce (16, [NS 3, TS 1])), ((46, 35), Reduce (16, [NS 3, TS 1])), ((46, 36), Reduce (16, [NS 3, TS 1])), ((46, 37), Reduce (16, [NS 3, TS 1]))
            , ((47, 3), Shift 23), ((47, 5), Shift 22), ((47, 12), Shift 26), ((47, 13), Shift 29), ((47, 14), Shift 32), ((47, 17), Shift 27), ((47, 18), Shift 24), ((47, 25), Shift 17), ((47, 26), Shift 33), ((47, 27), Shift 19), ((47, 28), Shift 18), ((47, 33), Shift 30), ((47, 34), Shift 21), ((47, 35), Shift 25), ((47, 36), Shift 16), ((47, 37), Shift 31)
            , ((48, 3), Shift 23), ((48, 5), Shift 22), ((48, 12), Shift 26), ((48, 13), Shift 29), ((48, 14), Shift 32), ((48, 17), Shift 27), ((48, 18), Shift 24), ((48, 25), Shift 17), ((48, 26), Shift 33), ((48, 27), Shift 19), ((48, 28), Shift 18), ((48, 33), Shift 30), ((48, 34), Shift 53), ((48, 35), Shift 25), ((48, 36), Shift 16), ((48, 37), Shift 31)
            , ((49, 3), Shift 23), ((49, 5), Shift 22), ((49, 12), Shift 26), ((49, 13), Shift 29), ((49, 14), Shift 32), ((49, 17), Shift 27), ((49, 18), Shift 24), ((49, 25), Shift 17), ((49, 26), Shift 33), ((49, 27), Shift 19), ((49, 28), Shift 18), ((49, 33), Shift 30), ((49, 34), Shift 53), ((49, 35), Shift 25), ((49, 36), Shift 16), ((49, 37), Shift 31)
            , ((50, 3), Shift 23), ((50, 5), Shift 22), ((50, 12), Shift 26), ((50, 13), Shift 29), ((50, 14), Shift 32), ((50, 17), Shift 27), ((50, 18), Shift 24), ((50, 25), Shift 17), ((50, 26), Shift 33), ((50, 27), Shift 19), ((50, 28), Shift 18), ((50, 33), Shift 30), ((50, 34), Shift 53), ((50, 35), Shift 25), ((50, 36), Shift 16), ((50, 37), Shift 31)
            , ((51, 3), Shift 23), ((51, 5), Shift 22), ((51, 12), Shift 26), ((51, 13), Shift 29), ((51, 14), Shift 32), ((51, 17), Shift 27), ((51, 18), Shift 24), ((51, 25), Shift 17), ((51, 26), Shift 33), ((51, 27), Shift 19), ((51, 28), Shift 18), ((51, 33), Shift 30), ((51, 34), Shift 53), ((51, 35), Shift 25), ((51, 36), Shift 16), ((51, 37), Shift 31)
            , ((52, 1), Reduce (12, [NS 12, NS 13])), ((52, 3), Reduce (12, [NS 12, NS 13])), ((52, 4), Reduce (12, [NS 12, NS 13])), ((52, 5), Reduce (12, [NS 12, NS 13])), ((52, 6), Reduce (12, [NS 12, NS 13])), ((52, 8), Reduce (12, [NS 12, NS 13])), ((52, 9), Reduce (12, [NS 12, NS 13])), ((52, 10), Reduce (12, [NS 12, NS 13])), ((52, 11), Reduce (12, [NS 12, NS 13])), ((52, 15), Reduce (12, [NS 12, NS 13])), ((52, 16), Reduce (12, [NS 12, NS 13])), ((52, 17), Reduce (12, [NS 12, NS 13])), ((52, 18), Reduce (12, [NS 12, NS 13])), ((52, 19), Reduce (12, [NS 12, NS 13])), ((52, 20), Reduce (12, [NS 12, NS 13])), ((52, 21), Reduce (12, [NS 12, NS 13])), ((52, 22), Reduce (12, [NS 12, NS 13])), ((52, 23), Reduce (12, [NS 12, NS 13])), ((52, 24), Reduce (12, [NS 12, NS 13])), ((52, 25), Reduce (12, [NS 12, NS 13])), ((52, 26), Reduce (12, [NS 12, NS 13])), ((52, 27), Reduce (12, [NS 12, NS 13])), ((52, 28), Reduce (12, [NS 12, NS 13])), ((52, 30), Reduce (12, [NS 12, NS 13])), ((52, 33), Reduce (12, [NS 12, NS 13])), ((52, 34), Reduce (12, [NS 12, NS 13])), ((52, 35), Reduce (12, [NS 12, NS 13])), ((52, 36), Reduce (12, [NS 12, NS 13])), ((52, 37), Reduce (12, [NS 12, NS 13]))
            , ((53, 1), Reduce (13, [TS 34])), ((53, 3), Reduce (13, [TS 34])), ((53, 4), Reduce (13, [TS 34])), ((53, 5), Reduce (13, [TS 34])), ((53, 6), Reduce (13, [TS 34])), ((53, 8), Reduce (13, [TS 34])), ((53, 9), Reduce (13, [TS 34])), ((53, 10), Reduce (13, [TS 34])), ((53, 11), Reduce (13, [TS 34])), ((53, 15), Reduce (13, [TS 34])), ((53, 16), Reduce (13, [TS 34])), ((53, 17), Reduce (13, [TS 34])), ((53, 18), Reduce (13, [TS 34])), ((53, 19), Reduce (13, [TS 34])), ((53, 20), Reduce (13, [TS 34])), ((53, 21), Reduce (13, [TS 34])), ((53, 22), Reduce (13, [TS 34])), ((53, 23), Reduce (13, [TS 34])), ((53, 24), Reduce (13, [TS 34])), ((53, 25), Reduce (13, [TS 34])), ((53, 26), Reduce (13, [TS 34])), ((53, 27), Reduce (13, [TS 34])), ((53, 28), Reduce (13, [TS 34])), ((53, 30), Reduce (13, [TS 34])), ((53, 33), Reduce (13, [TS 34])), ((53, 34), Reduce (13, [TS 34])), ((53, 35), Reduce (13, [TS 34])), ((53, 36), Reduce (13, [TS 34])), ((53, 37), Reduce (13, [TS 34]))
            , ((55, 3), Shift 84), ((55, 32), Shift 85)
            , ((56, 3), Shift 23), ((56, 5), Shift 22), ((56, 12), Shift 26), ((56, 13), Shift 29), ((56, 14), Shift 32), ((56, 17), Shift 27), ((56, 18), Shift 24), ((56, 25), Shift 17), ((56, 26), Shift 33), ((56, 27), Shift 19), ((56, 28), Shift 18), ((56, 33), Shift 30), ((56, 34), Shift 21), ((56, 35), Shift 25), ((56, 36), Shift 16), ((56, 37), Shift 31)
            , ((57, 6), Shift 87)
            , ((58, 6), Reduce (14, [NS 8])), ((58, 9), Shift 88)
            , ((59, 1), Reduce (13, [TS 5, TS 6])), ((59, 3), Reduce (13, [TS 5, TS 6])), ((59, 4), Reduce (13, [TS 5, TS 6])), ((59, 5), Reduce (13, [TS 5, TS 6])), ((59, 6), Reduce (13, [TS 5, TS 6])), ((59, 8), Reduce (13, [TS 5, TS 6])), ((59, 9), Reduce (13, [TS 5, TS 6])), ((59, 10), Reduce (13, [TS 5, TS 6])), ((59, 11), Reduce (13, [TS 5, TS 6])), ((59, 15), Reduce (13, [TS 5, TS 6])), ((59, 16), Reduce (13, [TS 5, TS 6])), ((59, 17), Reduce (13, [TS 5, TS 6])), ((59, 18), Reduce (13, [TS 5, TS 6])), ((59, 19), Reduce (13, [TS 5, TS 6])), ((59, 20), Reduce (13, [TS 5, TS 6])), ((59, 21), Reduce (13, [TS 5, TS 6])), ((59, 22), Reduce (13, [TS 5, TS 6])), ((59, 23), Reduce (13, [TS 5, TS 6])), ((59, 24), Reduce (13, [TS 5, TS 6])), ((59, 25), Reduce (13, [TS 5, TS 6])), ((59, 26), Reduce (13, [TS 5, TS 6])), ((59, 27), Reduce (13, [TS 5, TS 6])), ((59, 28), Reduce (13, [TS 5, TS 6])), ((59, 30), Reduce (13, [TS 5, TS 6])), ((59, 33), Reduce (13, [TS 5, TS 6])), ((59, 34), Reduce (13, [TS 5, TS 6])), ((59, 35), Reduce (13, [TS 5, TS 6])), ((59, 36), Reduce (13, [TS 5, TS 6])), ((59, 37), Reduce (13, [TS 5, TS 6]))
            , ((60, 4), Shift 89)
            , ((61, 1), Reduce (11, [TS 18, NS 11])), ((61, 4), Reduce (11, [TS 18, NS 11])), ((61, 6), Reduce (11, [TS 18, NS 11])), ((61, 8), Reduce (11, [TS 18, NS 11])), ((61, 9), Reduce (11, [TS 18, NS 11])), ((61, 10), Reduce (11, [TS 18, NS 11])), ((61, 11), Reduce (11, [TS 18, NS 11])), ((61, 15), Reduce (11, [TS 18, NS 11])), ((61, 16), Reduce (11, [TS 18, NS 11])), ((61, 17), Reduce (11, [TS 18, NS 11])), ((61, 18), Reduce (11, [TS 18, NS 11])), ((61, 19), Reduce (11, [TS 18, NS 11])), ((61, 20), Reduce (11, [TS 18, NS 11])), ((61, 21), Reduce (11, [TS 18, NS 11])), ((61, 22), Reduce (11, [TS 18, NS 11])), ((61, 23), Reduce (11, [TS 18, NS 11])), ((61, 24), Reduce (11, [TS 18, NS 11])), ((61, 30), Reduce (11, [TS 18, NS 11]))
            , ((62, 1), Reduce (8, [TS 12, NS 8])), ((62, 4), Reduce (8, [TS 12, NS 8])), ((62, 6), Reduce (8, [TS 12, NS 8])), ((62, 8), Reduce (8, [TS 12, NS 8])), ((62, 9), Reduce (8, [TS 12, NS 8])), ((62, 10), Reduce (8, [TS 12, NS 8])), ((62, 11), Reduce (8, [TS 12, NS 8])), ((62, 30), Reduce (8, [TS 12, NS 8]))
            , ((63, 1), Reduce (11, [TS 17, NS 11])), ((63, 4), Reduce (11, [TS 17, NS 11])), ((63, 6), Reduce (11, [TS 17, NS 11])), ((63, 8), Reduce (11, [TS 17, NS 11])), ((63, 9), Reduce (11, [TS 17, NS 11])), ((63, 10), Reduce (11, [TS 17, NS 11])), ((63, 11), Reduce (11, [TS 17, NS 11])), ((63, 15), Reduce (11, [TS 17, NS 11])), ((63, 16), Reduce (11, [TS 17, NS 11])), ((63, 17), Reduce (11, [TS 17, NS 11])), ((63, 18), Reduce (11, [TS 17, NS 11])), ((63, 19), Reduce (11, [TS 17, NS 11])), ((63, 20), Reduce (11, [TS 17, NS 11])), ((63, 21), Reduce (11, [TS 17, NS 11])), ((63, 22), Reduce (11, [TS 17, NS 11])), ((63, 23), Reduce (11, [TS 17, NS 11])), ((63, 24), Reduce (11, [TS 17, NS 11])), ((63, 30), Reduce (11, [TS 17, NS 11]))
            , ((64, 1), Shift 90)
            , ((65, 1), Reduce (8, [TS 13, NS 8])), ((65, 4), Reduce (8, [TS 13, NS 8])), ((65, 6), Reduce (8, [TS 13, NS 8])), ((65, 8), Reduce (8, [TS 13, NS 8])), ((65, 9), Reduce (8, [TS 13, NS 8])), ((65, 10), Reduce (8, [TS 13, NS 8])), ((65, 11), Reduce (8, [TS 13, NS 8])), ((65, 30), Reduce (8, [TS 13, NS 8]))
            , ((66, 3), Shift 95), ((66, 33), Shift 96), ((66, 34), Shift 94)
            , ((67, 1), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 4), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 6), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 8), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 9), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 10), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 11), Reduce (8, [NS 9, TS 16, NS 9])), ((67, 17), Shift 38), ((67, 18), Shift 37), ((67, 30), Reduce (8, [NS 9, TS 16, NS 9]))
            , ((68, 1), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 4), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 6), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 8), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 9), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 10), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 11), Reduce (8, [NS 9, TS 15, NS 9])), ((68, 17), Shift 38), ((68, 18), Shift 37), ((68, 30), Reduce (8, [NS 9, TS 15, NS 9]))
            , ((69, 1), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 4), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 6), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 8), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 9), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 10), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 11), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 15), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 16), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 17), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 18), Reduce (9, [NS 9, TS 18, NS 10])), ((69, 19), Shift 45), ((69, 20), Shift 44), ((69, 21), Shift 42), ((69, 22), Shift 40), ((69, 23), Shift 41), ((69, 24), Shift 43), ((69, 30), Reduce (9, [NS 9, TS 18, NS 10]))
            , ((70, 1), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 4), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 6), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 8), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 9), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 10), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 11), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 15), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 16), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 17), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 18), Reduce (9, [NS 9, TS 17, NS 10])), ((70, 19), Shift 45), ((70, 20), Shift 44), ((70, 21), Shift 42), ((70, 22), Shift 40), ((70, 23), Shift 41), ((70, 24), Shift 43), ((70, 30), Reduce (9, [NS 9, TS 17, NS 10]))
            , ((71, 1), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 4), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 6), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 8), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 9), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 10), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 11), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 15), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 16), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 17), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 18), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 19), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 20), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 21), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 22), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 23), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 24), Reduce (10, [NS 10, TS 22, NS 11])), ((71, 30), Reduce (10, [NS 10, TS 22, NS 11]))
            , ((72, 1), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 4), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 6), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 8), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 9), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 10), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 11), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 15), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 16), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 17), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 18), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 19), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 20), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 21), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 22), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 23), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 24), Reduce (10, [NS 10, TS 23, NS 11])), ((72, 30), Reduce (10, [NS 10, TS 23, NS 11]))
            , ((73, 1), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 4), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 6), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 8), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 9), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 10), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 11), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 15), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 16), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 17), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 18), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 19), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 20), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 21), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 22), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 23), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 24), Reduce (10, [NS 10, TS 21, NS 11])), ((73, 30), Reduce (10, [NS 10, TS 21, NS 11]))
            , ((74, 1), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 4), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 6), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 8), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 9), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 10), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 11), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 15), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 16), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 17), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 18), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 19), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 20), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 21), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 22), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 23), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 24), Reduce (10, [NS 10, TS 24, NS 11])), ((74, 30), Reduce (10, [NS 10, TS 24, NS 11]))
            , ((75, 1), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 4), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 6), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 8), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 9), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 10), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 11), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 15), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 16), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 17), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 18), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 19), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 20), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 21), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 22), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 23), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 24), Reduce (10, [NS 10, TS 20, NS 11])), ((75, 30), Reduce (10, [NS 10, TS 20, NS 11]))
            , ((76, 1), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 4), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 6), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 8), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 9), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 10), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 11), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 15), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 16), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 17), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 18), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 19), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 20), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 21), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 22), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 23), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 24), Reduce (10, [NS 10, TS 19, NS 11])), ((76, 30), Reduce (10, [NS 10, TS 19, NS 11]))
            , ((77, 1), Reduce (3, [NS 4, TS 8, NS 3])), ((77, 4), Reduce (3, [NS 4, TS 8, NS 3]))
            , ((78, 1), Reduce (4, [NS 4, TS 10, NS 5])), ((78, 4), Reduce (4, [NS 4, TS 10, NS 5])), ((78, 8), Reduce (4, [NS 4, TS 10, NS 5])), ((78, 10), Reduce (4, [NS 4, TS 10, NS 5]))
            , ((79, 1), Reduce (6, [NS 6, TS 9, NS 7])), ((79, 4), Reduce (6, [NS 6, TS 9, NS 7])), ((79, 8), Reduce (6, [NS 6, TS 9, NS 7])), ((79, 9), Reduce (6, [NS 6, TS 9, NS 7])), ((79, 10), Reduce (6, [NS 6, TS 9, NS 7])), ((79, 11), Reduce (6, [NS 6, TS 9, NS 7]))
            , ((80, 1), Reduce (5, [NS 6, TS 11, NS 5])), ((80, 4), Reduce (5, [NS 6, TS 11, NS 5])), ((80, 8), Reduce (5, [NS 6, TS 11, NS 5])), ((80, 10), Reduce (5, [NS 6, TS 11, NS 5]))
            , ((81, 1), Reduce (7, [NS 8, TS 30, NS 7])), ((81, 4), Reduce (7, [NS 8, TS 30, NS 7])), ((81, 8), Reduce (7, [NS 8, TS 30, NS 7])), ((81, 9), Reduce (7, [NS 8, TS 30, NS 7])), ((81, 10), Reduce (7, [NS 8, TS 30, NS 7])), ((81, 11), Reduce (7, [NS 8, TS 30, NS 7]))
            , ((82, 1), Shift 97)
            , ((83, 1), Reduce (17, [NS 18])), ((83, 2), Shift 98), ((83, 4), Reduce (17, [NS 18]))
            , ((84, 3), Shift 84), ((84, 32), Shift 85)
            , ((85, 1), Reduce (18, [TS 32])), ((85, 2), Reduce (18, [TS 32])), ((85, 4), Reduce (18, [TS 32]))
            , ((86, 1), Reduce (3, [TS 34, TS 29, NS 3])), ((86, 4), Reduce (3, [TS 34, TS 29, NS 3]))
            , ((87, 1), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 3), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 4), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 5), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 6), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 8), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 9), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 10), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 11), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 15), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 16), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 17), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 18), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 19), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 20), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 21), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 22), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 23), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 24), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 25), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 26), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 27), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 28), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 30), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 33), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 34), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 35), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 36), Reduce (13, [TS 5, NS 14, TS 6])), ((87, 37), Reduce (13, [TS 5, NS 14, TS 6]))
            , ((88, 3), Shift 23), ((88, 5), Shift 22), ((88, 12), Shift 26), ((88, 13), Shift 29), ((88, 14), Shift 32), ((88, 17), Shift 27), ((88, 18), Shift 24), ((88, 25), Shift 17), ((88, 26), Shift 33), ((88, 27), Shift 19), ((88, 28), Shift 18), ((88, 33), Shift 30), ((88, 34), Shift 53), ((88, 35), Shift 25), ((88, 36), Shift 16), ((88, 37), Shift 31)
            , ((89, 1), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 3), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 4), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 5), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 6), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 8), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 9), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 10), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 11), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 15), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 16), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 17), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 18), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 19), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 20), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 21), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 22), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 23), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 24), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 25), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 26), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 27), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 28), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 30), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 33), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 34), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 35), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 36), Reduce (13, [TS 3, NS 3, TS 4])), ((89, 37), Reduce (13, [TS 3, NS 3, TS 4]))
            , ((90, 0), Reduce (2, [TS 7, NS 3, TS 1]))
            , ((91, 1), Shift 101)
            , ((92, 1), Reduce (19, [NS 20])), ((92, 2), Shift 103), ((92, 3), Shift 95), ((92, 4), Reduce (19, [NS 20])), ((92, 33), Shift 96), ((92, 34), Shift 94)
            , ((93, 1), Reduce (20, [NS 21])), ((93, 2), Reduce (20, [NS 21])), ((93, 3), Reduce (20, [NS 21])), ((93, 4), Reduce (20, [NS 21])), ((93, 33), Reduce (20, [NS 21])), ((93, 34), Reduce (20, [NS 21]))
            , ((94, 1), Reduce (21, [TS 34])), ((94, 2), Reduce (21, [TS 34])), ((94, 3), Reduce (21, [TS 34])), ((94, 4), Reduce (21, [TS 34])), ((94, 33), Reduce (21, [TS 34])), ((94, 34), Reduce (21, [TS 34]))
            , ((95, 3), Shift 95), ((95, 33), Shift 96), ((95, 34), Shift 94)
            , ((96, 1), Reduce (21, [TS 33])), ((96, 2), Reduce (21, [TS 33])), ((96, 3), Reduce (21, [TS 33])), ((96, 4), Reduce (21, [TS 33])), ((96, 33), Reduce (21, [TS 33])), ((96, 34), Reduce (21, [TS 33]))
            , ((97, 0), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 3), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 5), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 12), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 13), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 14), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 17), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 18), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 25), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 26), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 27), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 28), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 31), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 32), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 33), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 34), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 35), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 36), Reduce (16, [TS 31, TS 33, NS 17, TS 1])), ((97, 37), Reduce (16, [TS 31, TS 33, NS 17, TS 1]))
            , ((98, 3), Shift 84), ((98, 32), Shift 85)
            , ((99, 4), Shift 106)
            , ((100, 6), Reduce (14, [NS 8, TS 9, NS 14]))
            , ((101, 0), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 3), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 5), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 12), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 13), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 14), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 17), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 18), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 25), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 26), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 27), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 28), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 31), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 32), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 33), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 34), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 35), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 36), Reduce (16, [TS 32, TS 33, NS 19, TS 1])), ((101, 37), Reduce (16, [TS 32, TS 33, NS 19, TS 1]))
            , ((102, 1), Reduce (20, [NS 20, NS 21])), ((102, 2), Reduce (20, [NS 20, NS 21])), ((102, 3), Reduce (20, [NS 20, NS 21])), ((102, 4), Reduce (20, [NS 20, NS 21])), ((102, 33), Reduce (20, [NS 20, NS 21])), ((102, 34), Reduce (20, [NS 20, NS 21]))
            , ((103, 3), Shift 95), ((103, 33), Shift 96), ((103, 34), Shift 94)
            , ((104, 4), Shift 108)
            , ((105, 1), Reduce (17, [NS 18, TS 2, NS 17])), ((105, 4), Reduce (17, [NS 18, TS 2, NS 17]))
            , ((106, 1), Reduce (18, [TS 3, NS 17, TS 4])), ((106, 2), Reduce (18, [TS 3, NS 17, TS 4])), ((106, 4), Reduce (18, [TS 3, NS 17, TS 4]))
            , ((107, 1), Reduce (19, [NS 20, TS 2, NS 19])), ((107, 4), Reduce (19, [NS 20, TS 2, NS 19]))
            , ((108, 1), Reduce (21, [TS 3, NS 19, TS 4])), ((108, 2), Reduce (21, [TS 3, NS 19, TS 4])), ((108, 3), Reduce (21, [TS 3, NS 19, TS 4])), ((108, 4), Reduce (21, [TS 3, NS 19, TS 4])), ((108, 33), Reduce (21, [TS 3, NS 19, TS 4])), ((108, 34), Reduce (21, [TS 3, NS 19, TS 4]))
            ]
        , getReduceTable = YMap.fromAscList 
            [ ((0, 1), 15), ((0, 2), 4), ((0, 3), 5), ((0, 4), 6), ((0, 5), 7), ((0, 6), 8), ((0, 7), 9), ((0, 8), 10), ((0, 9), 1), ((0, 10), 3), ((0, 11), 13), ((0, 12), 11), ((0, 13), 12), ((0, 15), 14), ((0, 16), 2)
            , ((2, 3), 5), ((2, 4), 6), ((2, 5), 7), ((2, 6), 8), ((2, 7), 9), ((2, 8), 10), ((2, 9), 1), ((2, 10), 3), ((2, 11), 13), ((2, 12), 11), ((2, 13), 12), ((2, 15), 39), ((2, 16), 2)
            , ((11, 13), 52)
            , ((22, 8), 58), ((22, 9), 1), ((22, 10), 3), ((22, 11), 13), ((22, 12), 11), ((22, 13), 12), ((22, 14), 57)
            , ((23, 3), 60), ((23, 4), 6), ((23, 5), 7), ((23, 6), 8), ((23, 7), 9), ((23, 8), 10), ((23, 9), 1), ((23, 10), 3), ((23, 11), 13), ((23, 12), 11), ((23, 13), 12)
            , ((24, 11), 61), ((24, 12), 11), ((24, 13), 12)
            , ((26, 8), 62), ((26, 9), 1), ((26, 10), 3), ((26, 11), 13), ((26, 12), 11), ((26, 13), 12)
            , ((27, 11), 63), ((27, 12), 11), ((27, 13), 12)
            , ((28, 3), 64), ((28, 4), 6), ((28, 5), 7), ((28, 6), 8), ((28, 7), 9), ((28, 8), 10), ((28, 9), 1), ((28, 10), 3), ((28, 11), 13), ((28, 12), 11), ((28, 13), 12)
            , ((29, 8), 65), ((29, 9), 1), ((29, 10), 3), ((29, 11), 13), ((29, 12), 11), ((29, 13), 12)
            , ((35, 9), 67), ((35, 10), 3), ((35, 11), 13), ((35, 12), 11), ((35, 13), 12)
            , ((36, 9), 68), ((36, 10), 3), ((36, 11), 13), ((36, 12), 11), ((36, 13), 12)
            , ((37, 10), 69), ((37, 11), 13), ((37, 12), 11), ((37, 13), 12)
            , ((38, 10), 70), ((38, 11), 13), ((38, 12), 11), ((38, 13), 12)
            , ((40, 11), 71), ((40, 12), 11), ((40, 13), 12)
            , ((41, 11), 72), ((41, 12), 11), ((41, 13), 12)
            , ((42, 11), 73), ((42, 12), 11), ((42, 13), 12)
            , ((43, 11), 74), ((43, 12), 11), ((43, 13), 12)
            , ((44, 11), 75), ((44, 12), 11), ((44, 13), 12)
            , ((45, 11), 76), ((45, 12), 11), ((45, 13), 12)
            , ((47, 3), 77), ((47, 4), 6), ((47, 5), 7), ((47, 6), 8), ((47, 7), 9), ((47, 8), 10), ((47, 9), 1), ((47, 10), 3), ((47, 11), 13), ((47, 12), 11), ((47, 13), 12)
            , ((48, 5), 78), ((48, 6), 8), ((48, 7), 9), ((48, 8), 10), ((48, 9), 1), ((48, 10), 3), ((48, 11), 13), ((48, 12), 11), ((48, 13), 12)
            , ((49, 7), 79), ((49, 8), 10), ((49, 9), 1), ((49, 10), 3), ((49, 11), 13), ((49, 12), 11), ((49, 13), 12)
            , ((50, 5), 80), ((50, 6), 8), ((50, 7), 9), ((50, 8), 10), ((50, 9), 1), ((50, 10), 3), ((50, 11), 13), ((50, 12), 11), ((50, 13), 12)
            , ((51, 7), 81), ((51, 8), 10), ((51, 9), 1), ((51, 10), 3), ((51, 11), 13), ((51, 12), 11), ((51, 13), 12)
            , ((55, 17), 82), ((55, 18), 83)
            , ((56, 3), 86), ((56, 4), 6), ((56, 5), 7), ((56, 6), 8), ((56, 7), 9), ((56, 8), 10), ((56, 9), 1), ((56, 10), 3), ((56, 11), 13), ((56, 12), 11), ((56, 13), 12)
            , ((66, 19), 91), ((66, 20), 92), ((66, 21), 93)
            , ((84, 17), 99), ((84, 18), 83)
            , ((88, 8), 58), ((88, 9), 1), ((88, 10), 3), ((88, 11), 13), ((88, 12), 11), ((88, 13), 12), ((88, 14), 100)
            , ((92, 21), 102)
            , ((95, 19), 104), ((95, 20), 92), ((95, 21), 93)
            , ((98, 17), 105), ((98, 18), 83)
            , ((103, 19), 107), ((103, 20), 92), ((103, 21), 93)
            ]
        }
